UPDATE VOL_Feedback SET
 ACCESSIBILITY=CASE WHEN ACCESSIBILITY IS NOT NULL AND ACCESSIBILITY NOT LIKE '<%' THEN (SELECT [NOTE]=ACCESSIBILITY FOR XML PATH('ACCESSIBILITY')) ELSE ACCESSIBILITY END,
 COMMITMENT_LENGTH=CASE WHEN COMMITMENT_LENGTH IS NOT NULL AND COMMITMENT_LENGTH NOT LIKE '<%' THEN (SELECT [NOTE]=COMMITMENT_LENGTH FOR XML PATH('COMMITMENT_LENGTH')) ELSE COMMITMENT_LENGTH END,
 INTERACTION_LEVEL=CASE WHEN INTERACTION_LEVEL IS NOT NULL AND INTERACTION_LEVEL NOT LIKE '<%' THEN (SELECT [NOTE]=INTERACTION_LEVEL FOR XML PATH('INTERACTION_LEVEL')) ELSE INTERACTION_LEVEL END,
 SEASONS=CASE WHEN SEASONS IS NOT NULL AND SEASONS NOT LIKE '<%' THEN (SELECT [NOTE]=SEASONS FOR XML PATH('SEASONS')) ELSE SEASONS END,
 SKILLS=CASE WHEN SKILLS IS NOT NULL AND SKILLS NOT LIKE '<%' THEN (SELECT [NOTE]=SKILLS FOR XML PATH('SKILLS')) ELSE SKILLS END,
 SUITABILITY=CASE WHEN SUITABILITY IS NOT NULL AND SUITABILITY NOT LIKE '<%' THEN (SELECT [NOTE]=SUITABILITY FOR XML PATH('SUITABILITY')) ELSE SUITABILITY END,
 TRAINING=CASE WHEN TRAINING IS NOT NULL AND TRAINING NOT LIKE '<%' THEN (SELECT [NOTE]=TRAINING FOR XML PATH('TRAINING')) ELSE TRAINING END,
 TRANSPORTATION=CASE WHEN TRANSPORTATION IS NOT NULL AND TRANSPORTATION NOT LIKE '<%' THEN (SELECT [NOTE]=TRANSPORTATION FOR XML PATH('TRANSPORTATION')) ELSE TRANSPORTATION END

 WHERE ACCESSIBILITY IS NOT NULL OR COMMITMENT_LENGTH IS NOT NULL OR INTERACTION_LEVEL IS NOT NULL 
 OR SEASONS IS NOT NULL OR SKILLS IS NOT NULL OR SUITABILITY IS NOT NULL OR TRAINING IS NOT NULL OR TRANSPORTATION IS NOT NULL
