DECLARE @STATFIRSTID int, @STATLASTID int, @STATCURRENTID int, @INCREMENT int

SELECT @STATFIRSTID = MIN(BTD_ID), @STATLASTID = MAX(BTD_ID) FROM GBL_BaseTable_Description 
PRINT N'GETTING ROWS FROM ' + CAST(@STATFIRSTID AS nvarchar) + N' TO ' + CAST(@STATLASTID AS nvarchar)

SET @STATCURRENTID = @STATFIRSTID
SET @INCREMENT = 1000

WHILE @STATCURRENTID <= @STATLASTID BEGIN
	PRINT N'SELECT FROM ' + CAST(@STATCURRENTID AS nvarchar) + N' TO ' + CAST(@STATCURRENTID + @INCREMENT AS nvarchar)

UPDATE btd
	SET CMP_DescriptionShort = CASE WHEN DESCRIPTION IS NULL AND (ORG_DESCRIPTION IS NOT NULL OR LOCATION_DESCRIPTION IS NOT NULL) THEN LTRIM(LEFT(
			REPLACE(REPLACE(REPLACE(
					REPLACE(REPLACE(REPLACE(cioc_shared.dbo.RegexReplace(REPLACE(REPLACE(COALESCE(btd.DESCRIPTION, btd.ORG_DESCRIPTION, btd.LOCATION_DESCRIPTION), '<li>', ' * '),'<LI>', ' * '),'<[^>]+>',' '), CHAR(10), ' '), CHAR(9), ' '), CHAR(13), ' '),
				'  ', ' ' + CHAR(1)), CHAR(1) + ' ', ''), CHAR(1), '')
		,200)) + CASE WHEN LEN(COALESCE(btd.DESCRIPTION, btd.ORG_DESCRIPTION, btd.LOCATION_DESCRIPTION)) > 200 THEN ' ...' ELSE '' END ELSE CMP_DescriptionShort END,
		CMP_OrgDescriptionShort = LTRIM(LEFT(
			REPLACE(REPLACE(REPLACE(
					REPLACE(REPLACE(REPLACE(cioc_shared.dbo.RegexReplace(REPLACE(REPLACE(btd.ORG_DESCRIPTION, '<li>', ' * '),'<LI>', ' * '),'<[^>]+>',' '), CHAR(10), ' '), CHAR(9), ' '), CHAR(13), ' '),
				'  ', ' ' + CHAR(1)), CHAR(1) + ' ', ''), CHAR(1), '')
		,200)) + CASE WHEN LEN(btd.ORG_DESCRIPTION) > 200 THEN ' ...' ELSE '' END
	FROM GBL_BaseTable_Description btd
	WHERE (ORG_DESCRIPTION IS NOT NULL OR (DESCRIPTION IS NULL AND LOCATION_DESCRIPTION IS NOT NULL)) AND BTD_ID >= @STATCURRENTID AND BTD_ID < (@STATCURRENTID + @INCREMENT)

	SET @STATCURRENTID = @STATCURRENTID + @INCREMENT
END