UPDATE GBL_Template_Layout SET SystemLayoutCode='CSSINGLE' WHERE SystemLayout=1 AND LayoutCSSURL='cicsearch_singleform.css' AND UseFullCIOCBootstrap=0 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='cicsearch_singleform.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='CSSINGLEBS' WHERE SystemLayout=1 AND LayoutCSSURL='cicsearch_singleform_bstrap.scss' AND UseFullCIOCBootstrap=1 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='cicsearch_singleform_bstrap.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='CSTABBED' WHERE SystemLayout=1 AND LayoutCSSURL='cicsearch_tabbed.css' AND UseFullCIOCBootstrap=0 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='cicsearch_tabbed.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='FTLARGE' WHERE SystemLayout=1 AND LayoutCSSURL='footer_large.scss' AND UseFullCIOCBootstrap=1 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='footer_large.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='FTLARGEALT' WHERE SystemLayout=1 AND LayoutCSSURL='footer_large.scss' AND UseFullCIOCBootstrap=1 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='footer_large_alternate.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='FTSLIM' WHERE SystemLayout=1 AND LayoutCSSURL='footer_slim.css' AND UseFullCIOCBootstrap=0 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='footer_slim.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='HDCOMPACT' WHERE SystemLayout=1 AND LayoutCSSURL='header_compact.css' AND UseFullCIOCBootstrap=0 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='header_compact.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='HDDUALBSCRUMB' WHERE SystemLayout=1 AND LayoutCSSURL='header_dualbcrumb.scss' AND UseFullCIOCBootstrap=1 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='header_dualbcrumb.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='HDTABBED' WHERE SystemLayout=1 AND LayoutCSSURL='header_tabbed.css' AND UseFullCIOCBootstrap=0 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='header_tabbed.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='HDTABBEDALT' WHERE SystemLayout=1 AND LayoutCSSURL='header_tabbed_alternate.css' AND UseFullCIOCBootstrap=0 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='header_tabbed_alternate.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='VSDUALPANEL' WHERE SystemLayout=1 AND LayoutCSSURL='volsearch_dualpanel.scss' AND UseFullCIOCBootstrap=1 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='volsearch_dualpanel.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='VSMULTIPANEL' WHERE SystemLayout=1 AND LayoutCSSURL='volsearch_multipanel.scss' AND UseFullCIOCBootstrap=1 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='volsearch_multipanel.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='VSSINGLE' WHERE SystemLayout=1 AND LayoutCSSURL='volsearch_singleform.css' AND UseFullCIOCBootstrap=0 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='volsearch_singleform.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='VSTABBED' WHERE SystemLayout=1 AND LayoutCSSURL='volsearch_tabbed.css' AND UseFullCIOCBootstrap=0 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='volsearch_tabbed.en_CA.html'
UPDATE GBL_Template_Layout SET SystemLayoutCode='VSTABBEDBRSALT' WHERE SystemLayout=1 AND LayoutCSSURL='volsearch_tabbed_browsealternate.css' AND UseFullCIOCBootstrap=0 AND (SELECT LayoutHTMLURL FROM GBL_Template_Layout_Description WHERE LangID=0 AND LayoutID=GBL_Template_Layout.LayoutID)='volsearch_tabbed_browsealternate.en_CA.html'

UPDATE ld SET SystemLayoutCode=l.SystemLayoutCode
FROM GBL_Template_Layout_Description ld
INNER JOIN GBL_Template_Layout l
	ON l.LayoutID = ld.LayoutID AND l.SystemLayout=1 AND l.SystemLayoutCode IS NOT NULL