CREATE FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST]
AUTHORIZATION [dbo];
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 0;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 1028;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 1031;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 1033;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 1036;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 1040;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 1041;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 1043;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 1049;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 1053;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 1054;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 2052;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 2057;
GO
ALTER FULLTEXT STOPLIST [CIOC_DEFAULT_STOPLIST] ADD N'$' LANGUAGE 3082;
GO
