SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_CIC_iCarolImport_Incremental]
	@service BIT,
	@Data [XML]
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

DECLARE	@Error		INT
SET @Error = 0

DECLARE @source TABLE(
	[ResourceAgencyNum] [NVARCHAR](50) COLLATE Latin1_General_100_CI_AI NOT NULL PRIMARY KEY,
	[ImportDate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ImportStatus] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Refresh] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PublicName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AlternateName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OfficialName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TaxonomyLevelName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ParentAgency] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ParentAgencyNum] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[RecordOwner] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[UniqueIDPriorSystem] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingAttentionName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingAddress1] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingAddress2] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingCity] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingStateProvince] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingPostalCode] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingCountry] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingAddressIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalAddress1] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalAddress2] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalCity] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalCounty] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalStateProvince] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalPostalCode] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalCountry] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalAddressIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherAddress1] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherAddress2] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherCity] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherCounty] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherStateProvince] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherPostalCode] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherCountry] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Latitude] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Longitude] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[HoursOfOperation] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone1Number] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone1Name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone1Description] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone1IsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone1Type] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone2Number] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone2Name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone2Description] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone2IsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone2Type] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone3Number] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone3Name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone3Description] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone3IsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone3Type] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone4Number] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone4Name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone4Description] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone4IsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone4Type] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone5Number] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone5name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone5Description] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone5IsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone5Type] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneFax] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneFaxDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneFaxIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTTY] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTTYDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTTYIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTollFree] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTollFreeDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTollFreeIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberHotline] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberHotlineDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberHotlineIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberBusinessLine] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberBusinessLineDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberBusinessLineIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberOutOfArea] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberOutOfAreaDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberOutOfAreaIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberAfterHours] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberAfterHoursDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberAfterHoursIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EmailAddressMain] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[WebsiteAddress] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AgencyStatus] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AgencyClassification] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AgencyDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SearchHints] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[CoverageArea] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[CoverageAreaText] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Eligibility] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityAdult] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityChild] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityFamily] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityFemale] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityMale] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityTeen] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SeniorWorkerName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SeniorWorkerTitle] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SeniorWorkerEmailAddress] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SeniorWorkerPhoneNumber] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SeniorWorkerIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactTitle] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactEmailAddress] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactPhoneNumber] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactType] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LicenseAccreditation] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[IRSStatus] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[FEIN] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[YearIncorporated] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AnnualBudgetTotal] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LegalStatus] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SourceOfFunds] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ExcludeFromWebsite] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ExcludeFromDirectory] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[DisabilitiesAccess] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalLocationDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[BusServiceAccess] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PublicAccessTransportation] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PaymentMethods] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[FeeStructureSource] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ApplicationProcess] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ResourceInfo] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[DocumentsRequired] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LanguagesOffered] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LanguagesOfferedList] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailabilityNumberOfTimes] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailabilityFrequency] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailabilityPeriod] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ServiceNotAlwaysAvailability] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[CapacityType] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ServiceCapacity] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[NormalWaitTime] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TemporaryMessage] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TemporaryMessageAppears] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TemporaryMessageExpires] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EnteredOn] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[UpdatedOn] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MadeInactiveOn] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[InternalNotes] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[InternalNotesForEditorsAndViewers] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[HighlightedResource] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerifiedOn] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerifiedByName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerifiedByTitle] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerifiedByPhoneNumber] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerifiedByEmailAddress] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerificationApprovedBy] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailableForDirectory] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailableForReferral] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailableForResearch] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PreferredProvider] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ConnectsToSiteNum] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ConnectsToProgramNum] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LanguageOfRecord] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[CurrentWorkflowStepCode] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[VolunteerOpportunities] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[VolunteerDuties] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[IsLinkOnly] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ProgramAgencyNamePublic] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SiteAgencyNamePublic] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Categories] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TaxonomyTerm] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TaxonomyTerms] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TaxonomyTermsNotDeactivated] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TaxonomyCodes] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Coverage] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Hours] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_A1) Does your organization consent to participate in the] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Public Comments] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_A2) What is the likelihood that within the next 2-5 year] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_S1) Does your organization own/rent/sublease the space] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_S2) If your organization rents the space please state fr] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_S3) What type of facilities do you have at the space (Ch] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_S4) What is the approximate square footage of the space] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_S5) In what type of building is the space located] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_S6) If your organization plans to move from the space in] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_211 Record] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Former Names] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Headings] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Legal Name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Pub Codes] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Record Owner (211 Central)] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Record Owner (controlled)] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_SINV] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_iCarol-managed record] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Facebook] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Instagram] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_LinkedIn] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Twitter] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_YouTube] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL
)

INSERT INTO @source 
SELECT 

	N.value('(field[@name="ResourceAgencyNum"]/text())[1]', 'nvarchar(max)') AS [ResourceAgencyNum],
	N.value('(field[@name="ImportDate"]/text())[1]', 'nvarchar(max)') AS [ImportDate],
	N.value('(field[@name="ImportStatus"]/text())[1]', 'nvarchar(max)') AS [ImportStatus],
	N.value('(field[@name="Refresh"]/text())[1]', 'nvarchar(max)') AS [Refresh],
	N.value('(field[@name="PublicName"]/text())[1]', 'nvarchar(max)') AS [PublicName],
	N.value('(field[@name="AlternateName"]/text())[1]', 'nvarchar(max)') AS [AlternateName],
	N.value('(field[@name="OfficialName"]/text())[1]', 'nvarchar(max)') AS [OfficialName],
	N.value('(field[@name="TaxonomyLevelName"]/text())[1]', 'nvarchar(max)') AS [TaxonomyLevelName],
	N.value('(field[@name="ParentAgency"]/text())[1]', 'nvarchar(max)') AS [ParentAgency],
	N.value('(field[@name="ParentAgencyNum"]/text())[1]', 'nvarchar(max)') AS [ParentAgencyNum],
	N.value('(field[@name="RecordOwner"]/text())[1]', 'nvarchar(max)') AS [RecordOwner],
	N.value('(field[@name="UniqueIDPriorSystem"]/text())[1]', 'nvarchar(max)') AS [UniqueIDPriorSystem],
	N.value('(field[@name="MailingAttentionName"]/text())[1]', 'nvarchar(max)') AS [MailingAttentionName],
	N.value('(field[@name="MailingAddress1"]/text())[1]', 'nvarchar(max)') AS [MailingAddress1],
	N.value('(field[@name="MailingAddress2"]/text())[1]', 'nvarchar(max)') AS [MailingAddress2],
	N.value('(field[@name="MailingCity"]/text())[1]', 'nvarchar(max)') AS [MailingCity],
	N.value('(field[@name="MailingStateProvince"]/text())[1]', 'nvarchar(max)') AS [MailingStateProvince],
	N.value('(field[@name="MailingPostalCode"]/text())[1]', 'nvarchar(max)') AS [MailingPostalCode],
	N.value('(field[@name="MailingCountry"]/text())[1]', 'nvarchar(max)') AS [MailingCountry],
	N.value('(field[@name="MailingAddressIsPrivate"]/text())[1]', 'nvarchar(max)') AS [MailingAddressIsPrivate],
	N.value('(field[@name="PhysicalAddress1"]/text())[1]', 'nvarchar(max)') AS [PhysicalAddress1],
	N.value('(field[@name="PhysicalAddress2"]/text())[1]', 'nvarchar(max)') AS [PhysicalAddress2],
	N.value('(field[@name="PhysicalCity"]/text())[1]', 'nvarchar(max)') AS [PhysicalCity],
	N.value('(field[@name="PhysicalCounty"]/text())[1]', 'nvarchar(max)') AS [PhysicalCounty],
	N.value('(field[@name="PhysicalStateProvince"]/text())[1]', 'nvarchar(max)') AS [PhysicalStateProvince],
	N.value('(field[@name="PhysicalPostalCode"]/text())[1]', 'nvarchar(max)') AS [PhysicalPostalCode],
	N.value('(field[@name="PhysicalCountry"]/text())[1]', 'nvarchar(max)') AS [PhysicalCountry],
	N.value('(field[@name="PhysicalAddressIsPrivate"]/text())[1]', 'nvarchar(max)') AS [PhysicalAddressIsPrivate],
	N.value('(field[@name="OtherAddress1"]/text())[1]', 'nvarchar(max)') AS [OtherAddress1],
	N.value('(field[@name="OtherAddress2"]/text())[1]', 'nvarchar(max)') AS [OtherAddress2],
	N.value('(field[@name="OtherCity"]/text())[1]', 'nvarchar(max)') AS [OtherCity],
	N.value('(field[@name="OtherCounty"]/text())[1]', 'nvarchar(max)') AS [OtherCounty],
	N.value('(field[@name="OtherStateProvince"]/text())[1]', 'nvarchar(max)') AS [OtherStateProvince],
	N.value('(field[@name="OtherPostalCode"]/text())[1]', 'nvarchar(max)') AS [OtherPostalCode],
	N.value('(field[@name="OtherCountry"]/text())[1]', 'nvarchar(max)') AS [OtherCountry],
	N.value('(field[@name="Latitude"]/text())[1]', 'nvarchar(max)') AS [Latitude],
	N.value('(field[@name="Longitude"]/text())[1]', 'nvarchar(max)') AS [Longitude],
	N.value('(field[@name="HoursOfOperation"]/text())[1]', 'nvarchar(max)') AS [HoursOfOperation],
	N.value('(field[@name="Phone1Number"]/text())[1]', 'nvarchar(max)') AS [Phone1Number],
	N.value('(field[@name="Phone1Name"]/text())[1]', 'nvarchar(max)') AS [Phone1Name],
	N.value('(field[@name="Phone1Description"]/text())[1]', 'nvarchar(max)') AS [Phone1Description],
	N.value('(field[@name="Phone1IsPrivate"]/text())[1]', 'nvarchar(max)') AS [Phone1IsPrivate],
	N.value('(field[@name="Phone1Type"]/text())[1]', 'nvarchar(max)') AS [Phone1Type],
	N.value('(field[@name="Phone2Number"]/text())[1]', 'nvarchar(max)') AS [Phone2Number],
	N.value('(field[@name="Phone2Name"]/text())[1]', 'nvarchar(max)') AS [Phone2Name],
	N.value('(field[@name="Phone2Description"]/text())[1]', 'nvarchar(max)') AS [Phone2Description],
	N.value('(field[@name="Phone2IsPrivate"]/text())[1]', 'nvarchar(max)') AS [Phone2IsPrivate],
	N.value('(field[@name="Phone2Type"]/text())[1]', 'nvarchar(max)') AS [Phone2Type],
	N.value('(field[@name="Phone3Number"]/text())[1]', 'nvarchar(max)') AS [Phone3Number],
	N.value('(field[@name="Phone3Name"]/text())[1]', 'nvarchar(max)') AS [Phone3Name],
	N.value('(field[@name="Phone3Description"]/text())[1]', 'nvarchar(max)') AS [Phone3Description],
	N.value('(field[@name="Phone3IsPrivate"]/text())[1]', 'nvarchar(max)') AS [Phone3IsPrivate],
	N.value('(field[@name="Phone3Type"]/text())[1]', 'nvarchar(max)') AS [Phone3Type],
	N.value('(field[@name="Phone4Number"]/text())[1]', 'nvarchar(max)') AS [Phone4Number],
	N.value('(field[@name="Phone4Name"]/text())[1]', 'nvarchar(max)') AS [Phone4Name],
	N.value('(field[@name="Phone4Description"]/text())[1]', 'nvarchar(max)') AS [Phone4Description],
	N.value('(field[@name="Phone4IsPrivate"]/text())[1]', 'nvarchar(max)') AS [Phone4IsPrivate],
	N.value('(field[@name="Phone4Type"]/text())[1]', 'nvarchar(max)') AS [Phone4Type],
	N.value('(field[@name="Phone5Number"]/text())[1]', 'nvarchar(max)') AS [Phone5Number],
	N.value('(field[@name="Phone5name"]/text())[1]', 'nvarchar(max)') AS [Phone5name],
	N.value('(field[@name="Phone5Description"]/text())[1]', 'nvarchar(max)') AS [Phone5Description],
	N.value('(field[@name="Phone5IsPrivate"]/text())[1]', 'nvarchar(max)') AS [Phone5IsPrivate],
	N.value('(field[@name="Phone5Type"]/text())[1]', 'nvarchar(max)') AS [Phone5Type],
	N.value('(field[@name="PhoneFax"]/text())[1]', 'nvarchar(max)') AS [PhoneFax],
	N.value('(field[@name="PhoneFaxDescription"]/text())[1]', 'nvarchar(max)') AS [PhoneFaxDescription],
	N.value('(field[@name="PhoneFaxIsPrivate"]/text())[1]', 'nvarchar(max)') AS [PhoneFaxIsPrivate],
	N.value('(field[@name="PhoneTTY"]/text())[1]', 'nvarchar(max)') AS [PhoneTTY],
	N.value('(field[@name="PhoneTTYDescription"]/text())[1]', 'nvarchar(max)') AS [PhoneTTYDescription],
	N.value('(field[@name="PhoneTTYIsPrivate"]/text())[1]', 'nvarchar(max)') AS [PhoneTTYIsPrivate],
	N.value('(field[@name="PhoneTollFree"]/text())[1]', 'nvarchar(max)') AS [PhoneTollFree],
	N.value('(field[@name="PhoneTollFreeDescription"]/text())[1]', 'nvarchar(max)') AS [PhoneTollFreeDescription],
	N.value('(field[@name="PhoneTollFreeIsPrivate"]/text())[1]', 'nvarchar(max)') AS [PhoneTollFreeIsPrivate],
	N.value('(field[@name="PhoneNumberHotline"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberHotline],
	N.value('(field[@name="PhoneNumberHotlineDescription"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberHotlineDescription],
	N.value('(field[@name="PhoneNumberHotlineIsPrivate"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberHotlineIsPrivate],
	N.value('(field[@name="PhoneNumberBusinessLine"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberBusinessLine],
	N.value('(field[@name="PhoneNumberBusinessLineDescription"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberBusinessLineDescription],
	N.value('(field[@name="PhoneNumberBusinessLineIsPrivate"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberBusinessLineIsPrivate],
	N.value('(field[@name="PhoneNumberOutOfArea"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberOutOfArea],
	N.value('(field[@name="PhoneNumberOutOfAreaDescription"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberOutOfAreaDescription],
	N.value('(field[@name="PhoneNumberOutOfAreaIsPrivate"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberOutOfAreaIsPrivate],
	N.value('(field[@name="PhoneNumberAfterHours"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberAfterHours],
	N.value('(field[@name="PhoneNumberAfterHoursDescription"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberAfterHoursDescription],
	N.value('(field[@name="PhoneNumberAfterHoursIsPrivate"]/text())[1]', 'nvarchar(max)') AS [PhoneNumberAfterHoursIsPrivate],
	N.value('(field[@name="EmailAddressMain"]/text())[1]', 'nvarchar(max)') AS [EmailAddressMain],
	N.value('(field[@name="WebsiteAddress"]/text())[1]', 'nvarchar(max)') AS [WebsiteAddress],
	N.value('(field[@name="AgencyStatus"]/text())[1]', 'nvarchar(max)') AS [AgencyStatus],
	N.value('(field[@name="AgencyClassification"]/text())[1]', 'nvarchar(max)') AS [AgencyClassification],
	N.value('(field[@name="AgencyDescription"]/text())[1]', 'nvarchar(max)') AS [AgencyDescription],
	N.value('(field[@name="SearchHints"]/text())[1]', 'nvarchar(max)') AS [SearchHints],
	N.value('(field[@name="CoverageArea"]/text())[1]', 'nvarchar(max)') AS [CoverageArea],
	N.value('(field[@name="CoverageAreaText"]/text())[1]', 'nvarchar(max)') AS [CoverageAreaText],
	N.value('(field[@name="Eligibility"]/text())[1]', 'nvarchar(max)') AS [Eligibility],
	N.value('(field[@name="EligibilityAdult"]/text())[1]', 'nvarchar(max)') AS [EligibilityAdult],
	N.value('(field[@name="EligibilityChild"]/text())[1]', 'nvarchar(max)') AS [EligibilityChild],
	N.value('(field[@name="EligibilityFamily"]/text())[1]', 'nvarchar(max)') AS [EligibilityFamily],
	N.value('(field[@name="EligibilityFemale"]/text())[1]', 'nvarchar(max)') AS [EligibilityFemale],
	N.value('(field[@name="EligibilityMale"]/text())[1]', 'nvarchar(max)') AS [EligibilityMale],
	N.value('(field[@name="EligibilityTeen"]/text())[1]', 'nvarchar(max)') AS [EligibilityTeen],
	N.value('(field[@name="SeniorWorkerName"]/text())[1]', 'nvarchar(max)') AS [SeniorWorkerName],
	N.value('(field[@name="SeniorWorkerTitle"]/text())[1]', 'nvarchar(max)') AS [SeniorWorkerTitle],
	N.value('(field[@name="SeniorWorkerEmailAddress"]/text())[1]', 'nvarchar(max)') AS [SeniorWorkerEmailAddress],
	N.value('(field[@name="SeniorWorkerPhoneNumber"]/text())[1]', 'nvarchar(max)') AS [SeniorWorkerPhoneNumber],
	N.value('(field[@name="SeniorWorkerIsPrivate"]/text())[1]', 'nvarchar(max)') AS [SeniorWorkerIsPrivate],
	N.value('(field[@name="MainContactName"]/text())[1]', 'nvarchar(max)') AS [MainContactName],
	N.value('(field[@name="MainContactTitle"]/text())[1]', 'nvarchar(max)') AS [MainContactTitle],
	N.value('(field[@name="MainContactEmailAddress"]/text())[1]', 'nvarchar(max)') AS [MainContactEmailAddress],
	N.value('(field[@name="MainContactPhoneNumber"]/text())[1]', 'nvarchar(max)') AS [MainContactPhoneNumber],
	N.value('(field[@name="MainContactType"]/text())[1]', 'nvarchar(max)') AS [MainContactType],
	N.value('(field[@name="MainContactIsPrivate"]/text())[1]', 'nvarchar(max)') AS [MainContactIsPrivate],
	N.value('(field[@name="LicenseAccreditation"]/text())[1]', 'nvarchar(max)') AS [LicenseAccreditation],
	N.value('(field[@name="IRSStatus"]/text())[1]', 'nvarchar(max)') AS [IRSStatus],
	N.value('(field[@name="FEIN"]/text())[1]', 'nvarchar(max)') AS [FEIN],
	N.value('(field[@name="YearIncorporated"]/text())[1]', 'nvarchar(max)') AS [YearIncorporated],
	N.value('(field[@name="AnnualBudgetTotal"]/text())[1]', 'nvarchar(max)') AS [AnnualBudgetTotal],
	N.value('(field[@name="LegalStatus"]/text())[1]', 'nvarchar(max)') AS [LegalStatus],
	N.value('(field[@name="SourceOfFunds"]/text())[1]', 'nvarchar(max)') AS [SourceOfFunds],
	N.value('(field[@name="ExcludeFromWebsite"]/text())[1]', 'nvarchar(max)') AS [ExcludeFromWebsite],
	N.value('(field[@name="ExcludeFromDirectory"]/text())[1]', 'nvarchar(max)') AS [ExcludeFromDirectory],
	N.value('(field[@name="DisabilitiesAccess"]/text())[1]', 'nvarchar(max)') AS [DisabilitiesAccess],
	N.value('(field[@name="PhysicalLocationDescription"]/text())[1]', 'nvarchar(max)') AS [PhysicalLocationDescription],
	N.value('(field[@name="BusServiceAccess"]/text())[1]', 'nvarchar(max)') AS [BusServiceAccess],
	N.value('(field[@name="PublicAccessTransportation"]/text())[1]', 'nvarchar(max)') AS [PublicAccessTransportation],
	N.value('(field[@name="PaymentMethods"]/text())[1]', 'nvarchar(max)') AS [PaymentMethods],
	N.value('(field[@name="FeeStructureSource"]/text())[1]', 'nvarchar(max)') AS [FeeStructureSource],
	N.value('(field[@name="ApplicationProcess"]/text())[1]', 'nvarchar(max)') AS [ApplicationProcess],
	N.value('(field[@name="ResourceInfo"]/text())[1]', 'nvarchar(max)') AS [ResourceInfo],
	N.value('(field[@name="DocumentsRequired"]/text())[1]', 'nvarchar(max)') AS [DocumentsRequired],
	N.value('(field[@name="LanguagesOffered"]/text())[1]', 'nvarchar(max)') AS [LanguagesOffered],
	N.value('(field[@name="LanguagesOfferedList"]/text())[1]', 'nvarchar(max)') AS [LanguagesOfferedList],
	N.value('(field[@name="AvailabilityNumberOfTimes"]/text())[1]', 'nvarchar(max)') AS [AvailabilityNumberOfTimes],
	N.value('(field[@name="AvailabilityFrequency"]/text())[1]', 'nvarchar(max)') AS [AvailabilityFrequency],
	N.value('(field[@name="AvailabilityPeriod"]/text())[1]', 'nvarchar(max)') AS [AvailabilityPeriod],
	N.value('(field[@name="ServiceNotAlwaysAvailability"]/text())[1]', 'nvarchar(max)') AS [ServiceNotAlwaysAvailability],
	N.value('(field[@name="CapacityType"]/text())[1]', 'nvarchar(max)') AS [CapacityType],
	N.value('(field[@name="ServiceCapacity"]/text())[1]', 'nvarchar(max)') AS [ServiceCapacity],
	N.value('(field[@name="NormalWaitTime"]/text())[1]', 'nvarchar(max)') AS [NormalWaitTime],
	N.value('(field[@name="TemporaryMessage"]/text())[1]', 'nvarchar(max)') AS [TemporaryMessage],
	N.value('(field[@name="TemporaryMessageAppears"]/text())[1]', 'nvarchar(max)') AS [TemporaryMessageAppears],
	N.value('(field[@name="TemporaryMessageExpires"]/text())[1]', 'nvarchar(max)') AS [TemporaryMessageExpires],
	N.value('(field[@name="EnteredOn"]/text())[1]', 'nvarchar(max)') AS [EnteredOn],
	N.value('(field[@name="UpdatedOn"]/text())[1]', 'nvarchar(max)') AS [UpdatedOn],
	N.value('(field[@name="MadeInactiveOn"]/text())[1]', 'nvarchar(max)') AS [MadeInactiveOn],
	N.value('(field[@name="InternalNotes"]/text())[1]', 'nvarchar(max)') AS [InternalNotes],
	N.value('(field[@name="InternalNotesForEditorsAndViewers"]/text())[1]', 'nvarchar(max)') AS [InternalNotesForEditorsAndViewers],
	N.value('(field[@name="HighlightedResource"]/text())[1]', 'nvarchar(max)') AS [HighlightedResource],
	N.value('(field[@name="LastVerifiedOn"]/text())[1]', 'nvarchar(max)') AS [LastVerifiedOn],
	N.value('(field[@name="LastVerifiedByName"]/text())[1]', 'nvarchar(max)') AS [LastVerifiedByName],
	N.value('(field[@name="LastVerifiedByTitle"]/text())[1]', 'nvarchar(max)') AS [LastVerifiedByTitle],
	N.value('(field[@name="LastVerifiedByPhoneNumber"]/text())[1]', 'nvarchar(max)') AS [LastVerifiedByPhoneNumber],
	N.value('(field[@name="LastVerifiedByEmailAddress"]/text())[1]', 'nvarchar(max)') AS [LastVerifiedByEmailAddress],
	N.value('(field[@name="LastVerificationApprovedBy"]/text())[1]', 'nvarchar(max)') AS [LastVerificationApprovedBy],
	N.value('(field[@name="AvailableForDirectory"]/text())[1]', 'nvarchar(max)') AS [AvailableForDirectory],
	N.value('(field[@name="AvailableForReferral"]/text())[1]', 'nvarchar(max)') AS [AvailableForReferral],
	N.value('(field[@name="AvailableForResearch"]/text())[1]', 'nvarchar(max)') AS [AvailableForResearch],
	N.value('(field[@name="PreferredProvider"]/text())[1]', 'nvarchar(max)') AS [PreferredProvider],
	N.value('(field[@name="ConnectsToSiteNum"]/text())[1]', 'nvarchar(max)') AS [ConnectsToSiteNum],
	N.value('(field[@name="ConnectsToProgramNum"]/text())[1]', 'nvarchar(max)') AS [ConnectsToProgramNum],
	N.value('(field[@name="LanguageOfRecord"]/text())[1]', 'nvarchar(max)') AS [LanguageOfRecord],
	N.value('(field[@name="CurrentWorkflowStepCode"]/text())[1]', 'nvarchar(max)') AS [CurrentWorkflowStepCode],
	N.value('(field[@name="VolunteerOpportunities"]/text())[1]', 'nvarchar(max)') AS [VolunteerOpportunities],
	N.value('(field[@name="VolunteerDuties"]/text())[1]', 'nvarchar(max)') AS [VolunteerDuties],
	N.value('(field[@name="IsLinkOnly"]/text())[1]', 'nvarchar(max)') AS [IsLinkOnly],
	N.value('(field[@name="ProgramAgencyNamePublic"]/text())[1]', 'nvarchar(max)') AS [ProgramAgencyNamePublic],
	N.value('(field[@name="SiteAgencyNamePublic"]/text())[1]', 'nvarchar(max)') AS [SiteAgencyNamePublic],
	N.value('(field[@name="Categories"]/text())[1]', 'nvarchar(max)') AS [Categories],
	N.value('(field[@name="TaxonomyTerm"]/text())[1]', 'nvarchar(max)') AS [TaxonomyTerm],
	N.value('(field[@name="TaxonomyTerms"]/text())[1]', 'nvarchar(max)') AS [TaxonomyTerms],
	N.value('(field[@name="TaxonomyTermsNotDeactivated"]/text())[1]', 'nvarchar(max)') AS [TaxonomyTermsNotDeactivated],
	N.value('(field[@name="TaxonomyCodes"]/text())[1]', 'nvarchar(max)') AS [TaxonomyCodes],
	N.value('(field[@name="Coverage"]/text())[1]', 'nvarchar(max)') AS [Coverage],
	N.value('(field[@name="Hours"]/text())[1]', 'nvarchar(max)') AS [Hours],
	N.value('(field[@name="Custom_A1) Does your organization consent to participate in the"]/text())[1]', 'nvarchar(max)') AS [Custom_A1) Does your organization consent to participate in the],
	N.value('(field[@name="Custom_Public Comments"]/text())[1]', 'nvarchar(max)') AS [Custom_Public Comments],
	N.value('(field[@name="Custom_A2) What is the likelihood that within the next 2-5 year"]/text())[1]', 'nvarchar(max)') AS [Custom_A2) What is the likelihood that within the next 2-5 year],
	N.value('(field[@name="Custom_S1) Does your organization own/rent/sublease the space"]/text())[1]', 'nvarchar(max)') AS [Custom_S1) Does your organization own/rent/sublease the space],
	N.value('(field[@name="Custom_S2) If your organization rents the space please state fr"]/text())[1]', 'nvarchar(max)') AS [Custom_S2) If your organization rents the space please state fr],
	N.value('(field[@name="Custom_S3) What type of facilities do you have at the space (Ch"]/text())[1]', 'nvarchar(max)') AS [Custom_S3) What type of facilities do you have at the space (Ch],
	N.value('(field[@name="Custom_S4) What is the approximate square footage of the space"]/text())[1]', 'nvarchar(max)') AS [Custom_S4) What is the approximate square footage of the space],
	N.value('(field[@name="Custom_S5) In what type of building is the space located"]/text())[1]', 'nvarchar(max)') AS [Custom_S5) In what type of building is the space located],
	N.value('(field[@name="Custom_S6) If your organization plans to move from the space in"]/text())[1]', 'nvarchar(max)') AS [Custom_S6) If your organization plans to move from the space in],
	N.value('(field[@name="Custom_211 Record"]/text())[1]', 'nvarchar(max)') AS [Custom_211 Record],
	N.value('(field[@name="Custom_Former Names"]/text())[1]', 'nvarchar(max)') AS [Custom_Former Names],
	N.value('(field[@name="Custom_Headings"]/text())[1]', 'nvarchar(max)') AS [Custom_Headings],
	N.value('(field[@name="Custom_Legal Name"]/text())[1]', 'nvarchar(max)') AS [Custom_Legal Name],
	N.value('(field[@name="Custom_Pub Codes"]/text())[1]', 'nvarchar(max)') AS [Custom_Pub Codes],
	N.value('(field[@name="Custom_Record Owner (211 Central)"]/text())[1]', 'nvarchar(max)') AS [Custom_Record Owner (211 Central)],
	N.value('(field[@name="Custom_Record Owner (controlled)"]/text())[1]', 'nvarchar(max)') AS [Custom_Record Owner (controlled)],
	N.value('(field[@name="Custom_SINV"]/text())[1]', 'nvarchar(max)') AS [Custom_SINV],
	N.value('(field[@name="Custom_iCarol-managed record"]/text())[1]', 'nvarchar(max)') AS [Custom_iCarol-managed record],
	N.value('(field[@name="Custom_Facebook"]/text())[1]', 'nvarchar(max)') AS [Custom_Facebook],
	N.value('(field[@name="Custom_Instagram"]/text())[1]', 'nvarchar(max)') AS [Custom_Instagram],
	N.value('(field[@name="Custom_LinkedIn"]/text())[1]', 'nvarchar(max)') AS [Custom_LinkedIn],
	N.value('(field[@name="Custom_Twitter"]/text())[1]', 'nvarchar(max)') AS [Custom_Twitter],
N.value('(field[@name="Custom_YouTube"]/text())[1]', 'nvarchar(max)') AS [Custom_YouTube]

FROM @Data.nodes('//item') AS T(N)

MERGE INTO dbo.CIC_iCarolImport dst
USING @source AS src
ON dst.ResourceAgencyNum=src.ResourceAgencyNum AND dst.LangID=@@LANGID AND dst.[service] = @service
WHEN MATCHED THEN
	UPDATE SET 
		[ImportDate]=src.[ImportDate],
		[ImportStatus]=src.[ImportStatus],
		[Refresh]=src.[Refresh],
		[PublicName]=src.[PublicName],
		[AlternateName]=src.[AlternateName],
		[OfficialName]=src.[OfficialName],
		[TaxonomyLevelName]=src.[TaxonomyLevelName],
		[ParentAgency]=src.[ParentAgency],
		[ParentAgencyNum]=src.[ParentAgencyNum],
		[RecordOwner]=src.[RecordOwner],
		[UniqueIDPriorSystem]=src.[UniqueIDPriorSystem],
		[MailingAttentionName]=src.[MailingAttentionName],
		[MailingAddress1]=src.[MailingAddress1],
		[MailingAddress2]=src.[MailingAddress2],
		[MailingCity]=src.[MailingCity],
		[MailingStateProvince]=src.[MailingStateProvince],
		[MailingPostalCode]=src.[MailingPostalCode],
		[MailingCountry]=src.[MailingCountry],
		[MailingAddressIsPrivate]=src.[MailingAddressIsPrivate],
		[PhysicalAddress1]=src.[PhysicalAddress1],
		[PhysicalAddress2]=src.[PhysicalAddress2],
		[PhysicalCity]=src.[PhysicalCity],
		[PhysicalCounty]=src.[PhysicalCounty],
		[PhysicalStateProvince]=src.[PhysicalStateProvince],
		[PhysicalPostalCode]=src.[PhysicalPostalCode],
		[PhysicalCountry]=src.[PhysicalCountry],
		[PhysicalAddressIsPrivate]=src.[PhysicalAddressIsPrivate],
		[OtherAddress1]=src.[OtherAddress1],
		[OtherAddress2]=src.[OtherAddress2],
		[OtherCity]=src.[OtherCity],
		[OtherCounty]=src.[OtherCounty],
		[OtherStateProvince]=src.[OtherStateProvince],
		[OtherPostalCode]=src.[OtherPostalCode],
		[OtherCountry]=src.[OtherCountry],
		[Latitude]=src.[Latitude],
		[Longitude]=src.[Longitude],
		[HoursOfOperation]=src.[HoursOfOperation],
		[Phone1Number]=src.[Phone1Number],
		[Phone1Name]=src.[Phone1Name],
		[Phone1Description]=src.[Phone1Description],
		[Phone1IsPrivate]=src.[Phone1IsPrivate],
		[Phone1Type]=src.[Phone1Type],
		[Phone2Number]=src.[Phone2Number],
		[Phone2Name]=src.[Phone2Name],
		[Phone2Description]=src.[Phone2Description],
		[Phone2IsPrivate]=src.[Phone2IsPrivate],
		[Phone2Type]=src.[Phone2Type],
		[Phone3Number]=src.[Phone3Number],
		[Phone3Name]=src.[Phone3Name],
		[Phone3Description]=src.[Phone3Description],
		[Phone3IsPrivate]=src.[Phone3IsPrivate],
		[Phone3Type]=src.[Phone3Type],
		[Phone4Number]=src.[Phone4Number],
		[Phone4Name]=src.[Phone4Name],
		[Phone4Description]=src.[Phone4Description],
		[Phone4IsPrivate]=src.[Phone4IsPrivate],
		[Phone4Type]=src.[Phone4Type],
		[Phone5Number]=src.[Phone5Number],
		[Phone5name]=src.[Phone5name],
		[Phone5Description]=src.[Phone5Description],
		[Phone5IsPrivate]=src.[Phone5IsPrivate],
		[Phone5Type]=src.[Phone5Type],
		[PhoneFax]=src.[PhoneFax],
		[PhoneFaxDescription]=src.[PhoneFaxDescription],
		[PhoneFaxIsPrivate]=src.[PhoneFaxIsPrivate],
		[PhoneTTY]=src.[PhoneTTY],
		[PhoneTTYDescription]=src.[PhoneTTYDescription],
		[PhoneTTYIsPrivate]=src.[PhoneTTYIsPrivate],
		[PhoneTollFree]=src.[PhoneTollFree],
		[PhoneTollFreeDescription]=src.[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate]=src.[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline]=src.[PhoneNumberHotline],
		[PhoneNumberHotlineDescription]=src.[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate]=src.[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine]=src.[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription]=src.[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate]=src.[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea]=src.[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription]=src.[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate]=src.[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours]=src.[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription]=src.[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate]=src.[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain]=src.[EmailAddressMain],
		[WebsiteAddress]=src.[WebsiteAddress],
		[AgencyStatus]=src.[AgencyStatus],
		[AgencyClassification]=src.[AgencyClassification],
		[AgencyDescription]=src.[AgencyDescription],
		[SearchHints]=src.[SearchHints],
		[CoverageArea]=src.[CoverageArea],
		[CoverageAreaText]=src.[CoverageAreaText],
		[Eligibility]=src.[Eligibility],
		[EligibilityAdult]=src.[EligibilityAdult],
		[EligibilityChild]=src.[EligibilityChild],
		[EligibilityFamily]=src.[EligibilityFamily],
		[EligibilityFemale]=src.[EligibilityFemale],
		[EligibilityMale]=src.[EligibilityMale],
		[EligibilityTeen]=src.[EligibilityTeen],
		[SeniorWorkerName]=src.[SeniorWorkerName],
		[SeniorWorkerTitle]=src.[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress]=src.[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber]=src.[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate]=src.[SeniorWorkerIsPrivate],
		[MainContactName]=src.[MainContactName],
		[MainContactTitle]=src.[MainContactTitle],
		[MainContactEmailAddress]=src.[MainContactEmailAddress],
		[MainContactPhoneNumber]=src.[MainContactPhoneNumber],
		[MainContactType]=src.[MainContactType],
		[MainContactIsPrivate]=src.[MainContactIsPrivate],
		[LicenseAccreditation]=src.[LicenseAccreditation],
		[IRSStatus]=src.[IRSStatus],
		[FEIN]=src.[FEIN],
		[YearIncorporated]=src.[YearIncorporated],
		[AnnualBudgetTotal]=src.[AnnualBudgetTotal],
		[LegalStatus]=src.[LegalStatus],
		[SourceOfFunds]=src.[SourceOfFunds],
		[ExcludeFromWebsite]=src.[ExcludeFromWebsite],
		[ExcludeFromDirectory]=src.[ExcludeFromDirectory],
		[DisabilitiesAccess]=src.[DisabilitiesAccess],
		[PhysicalLocationDescription]=src.[PhysicalLocationDescription],
		[BusServiceAccess]=src.[BusServiceAccess],
		[PublicAccessTransportation]=src.[PublicAccessTransportation],
		[PaymentMethods]=src.[PaymentMethods],
		[FeeStructureSource]=src.[FeeStructureSource],
		[ApplicationProcess]=src.[ApplicationProcess],
		[ResourceInfo]=src.[ResourceInfo],
		[DocumentsRequired]=src.[DocumentsRequired],
		[LanguagesOffered]=src.[LanguagesOffered],
		[LanguagesOfferedList]=src.[LanguagesOfferedList],
		[AvailabilityNumberOfTimes]=src.[AvailabilityNumberOfTimes],
		[AvailabilityFrequency]=src.[AvailabilityFrequency],
		[AvailabilityPeriod]=src.[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability]=src.[ServiceNotAlwaysAvailability],
		[CapacityType]=src.[CapacityType],
		[ServiceCapacity]=src.[ServiceCapacity],
		[NormalWaitTime]=src.[NormalWaitTime],
		[TemporaryMessage]=src.[TemporaryMessage],
		[TemporaryMessageAppears]=src.[TemporaryMessageAppears],
		[TemporaryMessageExpires]=src.[TemporaryMessageExpires],
		[EnteredOn]=src.[EnteredOn],
		[UpdatedOn]=src.[UpdatedOn],
		[MadeInactiveOn]=src.[MadeInactiveOn],
		[InternalNotes]=src.[InternalNotes],
		[InternalNotesForEditorsAndViewers]=src.[InternalNotesForEditorsAndViewers],
		[HighlightedResource]=src.[HighlightedResource],
		[LastVerifiedOn]=src.[LastVerifiedOn],
		[LastVerifiedByName]=src.[LastVerifiedByName],
		[LastVerifiedByTitle]=src.[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber]=src.[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress]=src.[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy]=src.[LastVerificationApprovedBy],
		[AvailableForDirectory]=src.[AvailableForDirectory],
		[AvailableForReferral]=src.[AvailableForReferral],
		[AvailableForResearch]=src.[AvailableForResearch],
		[PreferredProvider]=src.[PreferredProvider],
		[ConnectsToSiteNum]=src.[ConnectsToSiteNum],
		[ConnectsToProgramNum]=src.[ConnectsToProgramNum],
		[LanguageOfRecord]=src.[LanguageOfRecord],
		[CurrentWorkflowStepCode]=src.[CurrentWorkflowStepCode],
		[VolunteerOpportunities]=src.[VolunteerOpportunities],
		[VolunteerDuties]=src.[VolunteerDuties],
		[IsLinkOnly]=src.[IsLinkOnly],
		[ProgramAgencyNamePublic]=src.[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic]=src.[SiteAgencyNamePublic],
		[Categories]=src.[Categories],
		[TaxonomyTerm]=src.[TaxonomyTerm],
		[TaxonomyTerms]=src.[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated]=src.[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes]=src.[TaxonomyCodes],
		[Coverage]=src.[Coverage],
		[Hours]=src.[Hours],
		[Custom_A1) Does your organization consent to participate in the]=src.[Custom_A1) Does your organization consent to participate in the],
		[Custom_Public Comments]=src.[Custom_Public Comments],
		[Custom_A2) What is the likelihood that within the next 2-5 year]=src.[Custom_A2) What is the likelihood that within the next 2-5 year],
		[Custom_S1) Does your organization own/rent/sublease the space]=src.[Custom_S1) Does your organization own/rent/sublease the space],
		[Custom_S2) If your organization rents the space please state fr]=src.[Custom_S2) If your organization rents the space please state fr],
		[Custom_S3) What type of facilities do you have at the space (Ch]=src.[Custom_S3) What type of facilities do you have at the space (Ch],
		[Custom_S4) What is the approximate square footage of the space]=src.[Custom_S4) What is the approximate square footage of the space],
		[Custom_S5) In what type of building is the space located]=src.[Custom_S5) In what type of building is the space located],
		[Custom_S6) If your organization plans to move from the space in]=src.[Custom_S6) If your organization plans to move from the space in],
		[Custom_211 Record]=src.[Custom_211 Record],
		[Custom_Former Names]=src.[Custom_Former Names],
		[Custom_Headings]=src.[Custom_Headings],
		[Custom_Legal Name]=src.[Custom_Legal Name],
		[Custom_Pub Codes]=src.[Custom_Pub Codes],
		[Custom_Record Owner (211 Central)]=src.[Custom_Record Owner (211 Central)],
		[Custom_Record Owner (controlled)]=src.[Custom_Record Owner (controlled)],
		[Custom_SINV]=src.[Custom_SINV],
		[Custom_iCarol-managed record]=src.[Custom_iCarol-managed record],
		[Custom_Facebook]=src.[Custom_Facebook],
		[Custom_Instagram]=src.[Custom_Instagram],
		[Custom_LinkedIn]=src.[Custom_LinkedIn],
		[Custom_Twitter]=src.[Custom_Twitter],
		[Custom_YouTube]=src.[Custom_YouTube]

WHEN NOT MATCHED BY TARGET THEN
	INSERT (
		[ResourceAgencyNum],
		[LangID],
		[service],
		[ImportDate],
		[ImportStatus],
		[Refresh],
		[PublicName],
		[AlternateName],
		[OfficialName],
		[TaxonomyLevelName],
		[ParentAgency],
		[ParentAgencyNum],
		[RecordOwner],
		[UniqueIDPriorSystem],
		[MailingAttentionName],
		[MailingAddress1],
		[MailingAddress2],
		[MailingCity],
		[MailingStateProvince],
		[MailingPostalCode],
		[MailingCountry],
		[MailingAddressIsPrivate],
		[PhysicalAddress1],
		[PhysicalAddress2],
		[PhysicalCity],
		[PhysicalCounty],
		[PhysicalStateProvince],
		[PhysicalPostalCode],
		[PhysicalCountry],
		[PhysicalAddressIsPrivate],
		[OtherAddress1],
		[OtherAddress2],
		[OtherCity],
		[OtherCounty],
		[OtherStateProvince],
		[OtherPostalCode],
		[OtherCountry],
		[Latitude],
		[Longitude],
		[HoursOfOperation],
		[Phone1Number],
		[Phone1Name],
		[Phone1Description],
		[Phone1IsPrivate],
		[Phone1Type],
		[Phone2Number],
		[Phone2Name],
		[Phone2Description],
		[Phone2IsPrivate],
		[Phone2Type],
		[Phone3Number],
		[Phone3Name],
		[Phone3Description],
		[Phone3IsPrivate],
		[Phone3Type],
		[Phone4Number],
		[Phone4Name],
		[Phone4Description],
		[Phone4IsPrivate],
		[Phone4Type],
		[Phone5Number],
		[Phone5name],
		[Phone5Description],
		[Phone5IsPrivate],
		[Phone5Type],
		[PhoneFax],
		[PhoneFaxDescription],
		[PhoneFaxIsPrivate],
		[PhoneTTY],
		[PhoneTTYDescription],
		[PhoneTTYIsPrivate],
		[PhoneTollFree],
		[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline],
		[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain],
		[WebsiteAddress],
		[AgencyStatus],
		[AgencyClassification],
		[AgencyDescription],
		[SearchHints],
		[CoverageArea],
		[CoverageAreaText],
		[Eligibility],
		[EligibilityAdult],
		[EligibilityChild],
		[EligibilityFamily],
		[EligibilityFemale],
		[EligibilityMale],
		[EligibilityTeen],
		[SeniorWorkerName],
		[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate],
		[MainContactName],
		[MainContactTitle],
		[MainContactEmailAddress],
		[MainContactPhoneNumber],
		[MainContactType],
		[MainContactIsPrivate],
		[LicenseAccreditation],
		[IRSStatus],
		[FEIN],
		[YearIncorporated],
		[AnnualBudgetTotal],
		[LegalStatus],
		[SourceOfFunds],
		[ExcludeFromWebsite],
		[ExcludeFromDirectory],
		[DisabilitiesAccess],
		[PhysicalLocationDescription],
		[BusServiceAccess],
		[PublicAccessTransportation],
		[PaymentMethods],
		[FeeStructureSource],
		[ApplicationProcess],
		[ResourceInfo],
		[DocumentsRequired],
		[LanguagesOffered],
		[LanguagesOfferedList],
		[AvailabilityNumberOfTimes],
		[AvailabilityFrequency],
		[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability],
		[CapacityType],
		[ServiceCapacity],
		[NormalWaitTime],
		[TemporaryMessage],
		[TemporaryMessageAppears],
		[TemporaryMessageExpires],
		[EnteredOn],
		[UpdatedOn],
		[MadeInactiveOn],
		[InternalNotes],
		[InternalNotesForEditorsAndViewers],
		[HighlightedResource],
		[LastVerifiedOn],
		[LastVerifiedByName],
		[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy],
		[AvailableForDirectory],
		[AvailableForReferral],
		[AvailableForResearch],
		[PreferredProvider],
		[ConnectsToSiteNum],
		[ConnectsToProgramNum],
		[LanguageOfRecord],
		[CurrentWorkflowStepCode],
		[VolunteerOpportunities],
		[VolunteerDuties],
		[IsLinkOnly],
		[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic],
		[Categories],
		[TaxonomyTerm],
		[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes],
		[Coverage],
		[Hours],
		[Custom_A1) Does your organization consent to participate in the],
		[Custom_Public Comments],
		[Custom_A2) What is the likelihood that within the next 2-5 year],
		[Custom_S1) Does your organization own/rent/sublease the space],
		[Custom_S2) If your organization rents the space please state fr],
		[Custom_S3) What type of facilities do you have at the space (Ch],
		[Custom_S4) What is the approximate square footage of the space],
		[Custom_S5) In what type of building is the space located],
		[Custom_S6) If your organization plans to move from the space in],
		[Custom_211 Record],
		[Custom_Former Names],
		[Custom_Headings],
		[Custom_Legal Name],
		[Custom_Pub Codes],
		[Custom_Record Owner (211 Central)],
		[Custom_Record Owner (controlled)],
		[Custom_SINV],
		[Custom_iCarol-managed record],
		[Custom_Facebook],
		[Custom_Instagram],
		[Custom_LinkedIn],
		[Custom_Twitter],
		[Custom_YouTube]
	) VALUES (
		src.[ResourceAgencyNum],
		@@LANGID,
		@service,
		src.[ImportDate],
		src.[ImportStatus],
		src.[Refresh],
		src.[PublicName],
		src.[AlternateName],
		src.[OfficialName],
		src.[TaxonomyLevelName],
		src.[ParentAgency],
		src.[ParentAgencyNum],
		src.[RecordOwner],
		src.[UniqueIDPriorSystem],
		src.[MailingAttentionName],
		src.[MailingAddress1],
		src.[MailingAddress2],
		src.[MailingCity],
		src.[MailingStateProvince],
		src.[MailingPostalCode],
		src.[MailingCountry],
		src.[MailingAddressIsPrivate],
		src.[PhysicalAddress1],
		src.[PhysicalAddress2],
		src.[PhysicalCity],
		src.[PhysicalCounty],
		src.[PhysicalStateProvince],
		src.[PhysicalPostalCode],
		src.[PhysicalCountry],
		src.[PhysicalAddressIsPrivate],
		src.[OtherAddress1],
		src.[OtherAddress2],
		src.[OtherCity],
		src.[OtherCounty],
		src.[OtherStateProvince],
		src.[OtherPostalCode],
		src.[OtherCountry],
		src.[Latitude],
		src.[Longitude],
		src.[HoursOfOperation],
		src.[Phone1Number],
		src.[Phone1Name],
		src.[Phone1Description],
		src.[Phone1IsPrivate],
		src.[Phone1Type],
		src.[Phone2Number],
		src.[Phone2Name],
		src.[Phone2Description],
		src.[Phone2IsPrivate],
		src.[Phone2Type],
		src.[Phone3Number],
		src.[Phone3Name],
		src.[Phone3Description],
		src.[Phone3IsPrivate],
		src.[Phone3Type],
		src.[Phone4Number],
		src.[Phone4Name],
		src.[Phone4Description],
		src.[Phone4IsPrivate],
		src.[Phone4Type],
		src.[Phone5Number],
		src.[Phone5name],
		src.[Phone5Description],
		src.[Phone5IsPrivate],
		src.[Phone5Type],
		src.[PhoneFax],
		src.[PhoneFaxDescription],
		src.[PhoneFaxIsPrivate],
		src.[PhoneTTY],
		src.[PhoneTTYDescription],
		src.[PhoneTTYIsPrivate],
		src.[PhoneTollFree],
		src.[PhoneTollFreeDescription],
		src.[PhoneTollFreeIsPrivate],
		src.[PhoneNumberHotline],
		src.[PhoneNumberHotlineDescription],
		src.[PhoneNumberHotlineIsPrivate],
		src.[PhoneNumberBusinessLine],
		src.[PhoneNumberBusinessLineDescription],
		src.[PhoneNumberBusinessLineIsPrivate],
		src.[PhoneNumberOutOfArea],
		src.[PhoneNumberOutOfAreaDescription],
		src.[PhoneNumberOutOfAreaIsPrivate],
		src.[PhoneNumberAfterHours],
		src.[PhoneNumberAfterHoursDescription],
		src.[PhoneNumberAfterHoursIsPrivate],
		src.[EmailAddressMain],
		src.[WebsiteAddress],
		src.[AgencyStatus],
		src.[AgencyClassification],
		src.[AgencyDescription],
		src.[SearchHints],
		src.[CoverageArea],
		src.[CoverageAreaText],
		src.[Eligibility],
		src.[EligibilityAdult],
		src.[EligibilityChild],
		src.[EligibilityFamily],
		src.[EligibilityFemale],
		src.[EligibilityMale],
		src.[EligibilityTeen],
		src.[SeniorWorkerName],
		src.[SeniorWorkerTitle],
		src.[SeniorWorkerEmailAddress],
		src.[SeniorWorkerPhoneNumber],
		src.[SeniorWorkerIsPrivate],
		src.[MainContactName],
		src.[MainContactTitle],
		src.[MainContactEmailAddress],
		src.[MainContactPhoneNumber],
		src.[MainContactType],
		src.[MainContactIsPrivate],
		src.[LicenseAccreditation],
		src.[IRSStatus],
		src.[FEIN],
		src.[YearIncorporated],
		src.[AnnualBudgetTotal],
		src.[LegalStatus],
		src.[SourceOfFunds],
		src.[ExcludeFromWebsite],
		src.[ExcludeFromDirectory],
		src.[DisabilitiesAccess],
		src.[PhysicalLocationDescription],
		src.[BusServiceAccess],
		src.[PublicAccessTransportation],
		src.[PaymentMethods],
		src.[FeeStructureSource],
		src.[ApplicationProcess],
		src.[ResourceInfo],
		src.[DocumentsRequired],
		src.[LanguagesOffered],
		src.[LanguagesOfferedList],
		src.[AvailabilityNumberOfTimes],
		src.[AvailabilityFrequency],
		src.[AvailabilityPeriod],
		src.[ServiceNotAlwaysAvailability],
		src.[CapacityType],
		src.[ServiceCapacity],
		src.[NormalWaitTime],
		src.[TemporaryMessage],
		src.[TemporaryMessageAppears],
		src.[TemporaryMessageExpires],
		src.[EnteredOn],
		src.[UpdatedOn],
		src.[MadeInactiveOn],
		src.[InternalNotes],
		src.[InternalNotesForEditorsAndViewers],
		src.[HighlightedResource],
		src.[LastVerifiedOn],
		src.[LastVerifiedByName],
		src.[LastVerifiedByTitle],
		src.[LastVerifiedByPhoneNumber],
		src.[LastVerifiedByEmailAddress],
		src.[LastVerificationApprovedBy],
		src.[AvailableForDirectory],
		src.[AvailableForReferral],
		src.[AvailableForResearch],
		src.[PreferredProvider],
		src.[ConnectsToSiteNum],
		src.[ConnectsToProgramNum],
		src.[LanguageOfRecord],
		src.[CurrentWorkflowStepCode],
		src.[VolunteerOpportunities],
		src.[VolunteerDuties],
		src.[IsLinkOnly],
		src.[ProgramAgencyNamePublic],
		src.[SiteAgencyNamePublic],
		src.[Categories],
		src.[TaxonomyTerm],
		src.[TaxonomyTerms],
		src.[TaxonomyTermsNotDeactivated],
		src.[TaxonomyCodes],
		src.[Coverage],
		src.[Hours],
		src.[Custom_A1) Does your organization consent to participate in the],
		src.[Custom_Public Comments],
		src.[Custom_A2) What is the likelihood that within the next 2-5 year],
		src.[Custom_S1) Does your organization own/rent/sublease the space],
		src.[Custom_S2) If your organization rents the space please state fr],
		src.[Custom_S3) What type of facilities do you have at the space (Ch],
		src.[Custom_S4) What is the approximate square footage of the space],
		src.[Custom_S5) In what type of building is the space located],
		src.[Custom_S6) If your organization plans to move from the space in],
		src.[Custom_211 Record],
		src.[Custom_Former Names],
		src.[Custom_Headings],
		src.[Custom_Legal Name],
		src.[Custom_Pub Codes],
		src.[Custom_Record Owner (211 Central)],
		src.[Custom_Record Owner (controlled)],
		src.[Custom_SINV],
		src.[Custom_iCarol-managed record],
		src.[Custom_Facebook],
		src.[Custom_Instagram],
		src.[Custom_LinkedIn],
		src.[Custom_Twitter],
		src.[Custom_YouTube]
	)

	;

RETURN @Error

SET NOCOUNT OFF

GO
GRANT EXECUTE ON  [dbo].[sp_CIC_iCarolImport_Incremental] TO [cioc_login_role]
GO
