SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_VOL_VNUMSetCLIDs_u]
	@VNUM varchar(10),
	@IdList varchar(max)
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.6
	Checked by: CL
	Checked on: 27-Sep-2014
	Action: TESTING REQUIRED
*/

DECLARE @tmpCLIDs TABLE(CL_ID int)

INSERT INTO @tmpCLIDs SELECT DISTINCT tm.*
	FROM dbo.fn_GBL_ParseIntIDList(@IdList,',') tm
	INNER JOIN VOL_CommitmentLength cl
		ON tm.ItemID=cl.CL_ID

DELETE pr
	FROM VOL_OP_CL pr
	LEFT JOIN @tmpCLIDs tm
		ON pr.CL_ID = tm.CL_ID
WHERE tm.CL_ID IS NULL AND VNUM=@VNUM

INSERT INTO VOL_OP_CL (VNUM, CL_ID) SELECT VNUM=@VNUM, tm.CL_ID
	FROM @tmpCLIDs tm
WHERE NOT EXISTS(SELECT * FROM VOL_OP_CL pr WHERE VNUM=@VNUM AND pr.CL_ID=tm.CL_ID)

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_VOL_VNUMSetCLIDs_u] TO [cioc_login_role]
GO
