SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_VOL_VNUMSetILIDs_u]
	@VNUM varchar(10),
	@IdList varchar(max)
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.6
	Checked by: CL
	Checked on: 27-Sep-2014
	Action: TESTING REQUIRED
*/

DECLARE @tmpILIDs TABLE(IL_ID int)

INSERT INTO @tmpILIDs SELECT DISTINCT tm.*
	FROM dbo.fn_GBL_ParseIntIDList(@IdList,',') tm
	INNER JOIN VOL_InteractionLevel il
		ON tm.ItemID=il.IL_ID

DELETE pr
	FROM VOL_OP_IL pr
	LEFT JOIN @tmpILIDs tm
		ON pr.IL_ID = tm.IL_ID
WHERE tm.IL_ID IS NULL AND VNUM=@VNUM

INSERT INTO VOL_OP_IL (VNUM, IL_ID) SELECT VNUM=@VNUM, tm.IL_ID
	FROM @tmpILIDs tm
WHERE NOT EXISTS(SELECT * FROM VOL_OP_IL pr WHERE VNUM=@VNUM AND pr.IL_ID=tm.IL_ID)

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_VOL_VNUMSetILIDs_u] TO [cioc_login_role]
GO
