SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[sp_GBL_AIRS_Export_ICarolSource] 
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON


DECLARE 	@Error	int
SET @Error = 0

SELECT NUM AS RECORD_NUM FROM dbo.GBL_BaseTable bt
	WHERE bt.SOURCE_FROM_ICAROL=1 OR EXISTS(SELECT * FROM dbo.GBL_BT_OLS olsed WHERE olsed.EXTERNAL_ID IS NOT NULL AND olsed.NUM=bt.NUM)

RETURN @Error

SET NOCOUNT OFF
GO
GRANT EXECUTE ON  [dbo].[sp_GBL_AIRS_Export_ICarolSource] TO [cioc_cic_search_role]
GO
GRANT EXECUTE ON  [dbo].[sp_GBL_AIRS_Export_ICarolSource] TO [cioc_login_role]
GO
