SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_VOL_VNUMSetSSNIDs_u]
	@VNUM varchar(10),
	@IdList varchar(max)
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.6
	Checked by: CL
	Checked on: 27-Sep-2014
	Action: TESTING REQUIRED
*/

DECLARE @tmpSSNIDs TABLE(SSN_ID int)

INSERT INTO @tmpSSNIDs SELECT DISTINCT tm.*
	FROM dbo.fn_GBL_ParseIntIDList(@IdList,',') tm
	INNER JOIN VOL_Seasons SSN
		ON tm.ItemID=SSN.SSN_ID

DELETE pr
	FROM VOL_OP_SSN pr
	LEFT JOIN @tmpSSNIDs tm
		ON pr.SSN_ID = tm.SSN_ID
WHERE tm.SSN_ID IS NULL AND VNUM=@VNUM

INSERT INTO VOL_OP_SSN (VNUM, SSN_ID) SELECT VNUM=@VNUM, tm.SSN_ID
	FROM @tmpSSNIDs tm
WHERE NOT EXISTS(SELECT * FROM VOL_OP_SSN pr WHERE VNUM=@VNUM AND pr.SSN_ID=tm.SSN_ID)

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_VOL_VNUMSetSSNIDs_u] TO [cioc_login_role]
GO
