SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_VOL_VNUMSetACIDs_u]
	@VNUM varchar(10),
	@IdList varchar(max)
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.6
	Checked by: CL
	Checked on: 27-Sep-2014
	Action: TESTING REQUIRED
*/

DECLARE @tmpACIDs TABLE(AC_ID int)

INSERT INTO @tmpACIDs SELECT DISTINCT tm.*
	FROM dbo.fn_GBL_ParseIntIDList(@IdList,',') tm
	INNER JOIN GBL_Accessibility ac
		ON tm.ItemID=ac.AC_ID

DELETE pr
	FROM VOL_OP_AC pr
	LEFT JOIN @tmpACIDs tm
		ON pr.AC_ID = tm.AC_ID
WHERE tm.AC_ID IS NULL AND VNUM=@VNUM

INSERT INTO VOL_OP_AC (VNUM, AC_ID) SELECT VNUM=@VNUM, tm.AC_ID
	FROM @tmpACIDs tm
WHERE NOT EXISTS(SELECT * FROM VOL_OP_AC pr WHERE VNUM=@VNUM AND pr.AC_ID=tm.AC_ID)

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_VOL_VNUMSetACIDs_u] TO [cioc_login_role]
GO
