SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_CIC_iCarolImport_Rollup]
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

DECLARE	@Error		INT
SET @Error = 0

MERGE INTO dbo.CIC_iCarolImportRollup dst
USING dbo.CIC_iCarolImport AS src
ON src.ResourceAgencyNum=dst.ResourceAgencyNum AND src.LangID=dst.LangID AND src.TaxonomyLevelName = 'Agency'
WHEN MATCHED AND (src.SYNC_DATE > dst.DATE_MODIFIED)  THEN 
	UPDATE SET 
		[PublicName]=src.[PublicName],
		[AlternateName]=src.[AlternateName],
		[OfficialName]=src.[OfficialName],
		[TaxonomyLevelName]=src.[TaxonomyLevelName],
		[ParentAgency]=src.[ParentAgency],
		[ParentAgencyNum]=src.[ParentAgencyNum],
		[RECORD_OWNER]=LEFT(src.[Custom_Record Owner (controlled)], 3),
		[UniqueIDPriorSystem]=LEFT(src.[UniqueIDPriorSystem], 8),
		[MailingAttentionName]=src.[MailingAttentionName],
		[MailingAddress1]=src.[MailingAddress1],
		[MailingAddress2]=src.[MailingAddress2],
		[MailingCity]=src.[MailingCity],
		[MailingStateProvince]=src.[MailingStateProvince],
		[MailingPostalCode]=src.[MailingPostalCode],
		[MailingCountry]=NULLIF(src.[MailingCountry],'-1'),
		[MailingAddressIsPrivate]=src.[MailingAddressIsPrivate],
		[PhysicalAddress1]=src.[PhysicalAddress1],
		[PhysicalAddress2]=src.[PhysicalAddress2],
		[PhysicalCity]=src.[PhysicalCity],
		[PhysicalCounty]=src.[PhysicalCounty],
		[PhysicalStateProvince]=src.[PhysicalStateProvince],
		[PhysicalPostalCode]=src.[PhysicalPostalCode],
		[PhysicalCountry]=NULLIF(src.[PhysicalCountry], '-1'),
		[PhysicalAddressIsPrivate]=src.[PhysicalAddressIsPrivate],
		[OtherAddress1]=src.[OtherAddress1],
		[OtherAddress2]=src.[OtherAddress2],
		[OtherCity]=src.[OtherCity],
		[OtherCounty]=src.[OtherCounty],
		[OtherStateProvince]=src.[OtherStateProvince],
		[OtherPostalCode]=src.[OtherPostalCode],
		[OtherCountry]=src.[OtherCountry],
		[Latitude]=NULLIF(NULLIF(src.[Latitude],'0'), '0.00000000000000'),
		[Longitude]=NULLIF(NULLIF(src.[Longitude], '0'), '0.00000000000000'),
		[HoursOfOperation]=src.[HoursOfOperation],
		[Phone1Number]=src.[Phone1Number],
		[Phone1Name]=src.[Phone1Name],
		[Phone1Description]=src.[Phone1Description],
		[Phone1IsPrivate]=src.[Phone1IsPrivate],
		[Phone1Type]=src.[Phone1Type],
		[Phone2Number]=src.[Phone2Number],
		[Phone2Name]=src.[Phone2Name],
		[Phone2Description]=src.[Phone2Description],
		[Phone2IsPrivate]=src.[Phone2IsPrivate],
		[Phone2Type]=src.[Phone2Type],
		[Phone3Number]=src.[Phone3Number],
		[Phone3Name]=src.[Phone3Name],
		[Phone3Description]=src.[Phone3Description],
		[Phone3IsPrivate]=src.[Phone3IsPrivate],
		[Phone3Type]=src.[Phone3Type],
		[Phone4Number]=src.[Phone4Number],
		[Phone4Name]=src.[Phone4Name],
		[Phone4Description]=src.[Phone4Description],
		[Phone4IsPrivate]=src.[Phone4IsPrivate],
		[Phone4Type]=src.[Phone4Type],
		[Phone5Number]=src.[Phone5Number],
		[Phone5name]=src.[Phone5name],
		[Phone5Description]=src.[Phone5Description],
		[Phone5IsPrivate]=src.[Phone5IsPrivate],
		[Phone5Type]=src.[Phone5Type],
		[PhoneFax]=src.[PhoneFax],
		[PhoneFaxDescription]=src.[PhoneFaxDescription],
		[PhoneFaxIsPrivate]=src.[PhoneFaxIsPrivate],
		[PhoneTTY]=src.[PhoneTTY],
		[PhoneTTYDescription]=src.[PhoneTTYDescription],
		[PhoneTTYIsPrivate]=src.[PhoneTTYIsPrivate],
		[PhoneTollFree]=src.[PhoneTollFree],
		[PhoneTollFreeDescription]=src.[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate]=src.[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline]=src.[PhoneNumberHotline],
		[PhoneNumberHotlineDescription]=src.[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate]=src.[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine]=src.[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription]=src.[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate]=src.[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea]=src.[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription]=src.[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate]=src.[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours]=src.[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription]=src.[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate]=src.[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain]=src.[EmailAddressMain],
		[WebsiteAddress]=src.[WebsiteAddress],
		[AgencyStatus]=src.[AgencyStatus],
		[AgencyClassification]=src.[AgencyClassification],
		[CoverageArea]=src.[CoverageArea],
		[CoverageAreaText]=src.[CoverageAreaText],
		[Eligibility]=src.[Eligibility],
		[EligibilityAdult]=src.[EligibilityAdult],
		[EligibilityChild]=src.[EligibilityChild],
		[EligibilityFamily]=src.[EligibilityFamily],
		[EligibilityFemale]=src.[EligibilityFemale],
		[EligibilityMale]=src.[EligibilityMale],
		[EligibilityTeen]=src.[EligibilityTeen],
		[SeniorWorkerName]=src.[SeniorWorkerName],
		[SeniorWorkerTitle]=src.[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress]=src.[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber]=src.[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate]=src.[SeniorWorkerIsPrivate],
		[MainContactName]=src.[MainContactName],
		[MainContactTitle]=src.[MainContactTitle],
		[MainContactEmailAddress]=src.[MainContactEmailAddress],
		[MainContactPhoneNumber]=src.[MainContactPhoneNumber],
		[MainContactType]=src.[MainContactType],
		[MainContactIsPrivate]=src.[MainContactIsPrivate],
		[LicenseAccreditation]=src.[LicenseAccreditation],
		[YearIncorporated]=src.[YearIncorporated],
		[AnnualBudgetTotal]=src.[AnnualBudgetTotal],
		[LegalStatus]=src.[LegalStatus],
		[SourceOfFunds]=src.[SourceOfFunds],
		[ExcludeFromWebsite]=src.[ExcludeFromWebsite],
		[ExcludeFromDirectory]=src.[ExcludeFromDirectory],
		[DisabilitiesAccess]=src.[DisabilitiesAccess],
		[PhysicalLocationDescription]=src.[PhysicalLocationDescription],
		[BusServiceAccess]=src.[BusServiceAccess],
		[PublicAccessTransportation]=src.[PublicAccessTransportation],
		[PaymentMethods]=src.[PaymentMethods],
		[FeeStructureSource]=src.[FeeStructureSource],
		[ApplicationProcess]=src.[ApplicationProcess],
		[ResourceInfo]=src.[ResourceInfo],
		[DocumentsRequired]=src.[DocumentsRequired],
		[LanguagesOffered]=src.[LanguagesOffered],
		[LanguagesOfferedList]=src.[LanguagesOfferedList],
		[AvailabilityNumberOfTimes]=src.[AvailabilityNumberOfTimes],
		[AvailabilityFrequency]=src.[AvailabilityFrequency],
		[AvailabilityPeriod]=src.[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability]=src.[ServiceNotAlwaysAvailability],
		[CapacityType]=src.[CapacityType],
		[ServiceCapacity]=src.[ServiceCapacity],
		[NormalWaitTime]=src.[NormalWaitTime],
		[TemporaryMessage]=src.[TemporaryMessage],
		[TemporaryMessageAppears]=src.[TemporaryMessageAppears],
		[TemporaryMessageExpires]=src.[TemporaryMessageExpires],
		[EnteredOn]=src.[EnteredOn],
		[UpdatedOn]=src.[UpdatedOn],
		[MadeInactiveOn]=src.[MadeInactiveOn],
		[InternalNotes]=src.[InternalNotes],
		[InternalNotesForEditorsAndViewers]=src.[InternalNotesForEditorsAndViewers],
		[HighlightedResource]=src.[HighlightedResource],
		[LastVerifiedOn]=src.[LastVerifiedOn],
		[LastVerifiedByName]=src.[LastVerifiedByName],
		[LastVerifiedByTitle]=src.[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber]=src.[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress]=src.[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy]=src.[LastVerificationApprovedBy],
		[AvailableForDirectory]=src.[AvailableForDirectory],
		[AvailableForReferral]=src.[AvailableForReferral],
		[AvailableForResearch]=src.[AvailableForResearch],
		[PreferredProvider]=src.[PreferredProvider],
		[ConnectsToSiteNum]=src.[ConnectsToSiteNum],
		[ConnectsToProgramNum]=src.[ConnectsToProgramNum],
		[LanguageOfRecord]=src.[LanguageOfRecord],
		[CurrentWorkflowStepCode]=src.[CurrentWorkflowStepCode],
		[VolunteerOpportunities]=src.[VolunteerOpportunities],
		[VolunteerDuties]=src.[VolunteerDuties],
		[IsLinkOnly]=src.[IsLinkOnly],
		[ProgramAgencyNamePublic]=src.[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic]=src.[SiteAgencyNamePublic],
		[Categories]=src.[Categories],
		[TaxonomyTerm]=src.[TaxonomyTerm],
		[TaxonomyTerms]=src.[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated]=src.[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes]=src.[TaxonomyCodes],
		[Coverage]=src.[Coverage],
		[Hours]=src.[Hours],
		[Custom_Public Comments]=src.[Custom_Public Comments],
		[Custom_Former Names]=src.[Custom_Former Names],
		[Custom_Legal Name]=src.[Custom_Legal Name],
		[Custom_Facebook]=src.[Custom_Facebook],
		[Custom_Instagram]=src.[Custom_Instagram],
		[Custom_LinkedIn]=src.[Custom_LinkedIn],
		[Custom_Twitter]=src.[Custom_Twitter],
		[Custom_YouTube]=src.[Custom_YouTube],
		[Custom_Minimum Age]=src.[Custom_Minimum Age],
		[Custom_Maximum Age]=src.[Custom_Maximum Age],
		[dst].[DATE_MODIFIED]=GETDATE(),
		ORG_LEVEL_1=src.PublicName,
		dst.ORG_DESCRIPTION=src.AgencyDescription,
		dst.ORG_LOCATION_SERVICE='AGENCY',
		dst.DELETION_DATE=src.DELETION_DATE,
		dst.SOFT_DELETION_DATE=CASE WHEN src.[Custom_Deleted Record] = 'yes' THEN COALESCE(dst.SOFT_DELETION_DATE, GETDATE()) ELSE NULL END,
		dst.[Custom_Deleted Record]=src.[Custom_Deleted Record],
		[MailingCommunity]=src.[MailingCommunity],
		[OtherCommunity]=src.[OtherCommunity],
		[PhysicalCommunity]=src.[PhysicalCommunity]		
WHEN NOT MATCHED BY TARGET AND src.TaxonomyLevelName='Agency' THEN
	INSERT (
		[ResourceAgencyNum],
		[LangID],
		[PublicName],
		[AlternateName],
		[OfficialName],
		[TaxonomyLevelName],
		[ParentAgency],
		[ParentAgencyNum],
		[RECORD_OWNER],
		[UniqueIDPriorSystem],
		[MailingAttentionName],
		[MailingAddress1],
		[MailingAddress2],
		[MailingCity],
		[MailingStateProvince],
		[MailingPostalCode],
		[MailingCountry],
		[MailingAddressIsPrivate],
		[PhysicalAddress1],
		[PhysicalAddress2],
		[PhysicalCity],
		[PhysicalCounty],
		[PhysicalStateProvince],
		[PhysicalPostalCode],
		[PhysicalCountry],
		[PhysicalAddressIsPrivate],
		[OtherAddress1],
		[OtherAddress2],
		[OtherCity],
		[OtherCounty],
		[OtherStateProvince],
		[OtherPostalCode],
		[OtherCountry],
		[Latitude],
		[Longitude],
		[HoursOfOperation],
		[Phone1Number],
		[Phone1Name],
		[Phone1Description],
		[Phone1IsPrivate],
		[Phone1Type],
		[Phone2Number],
		[Phone2Name],
		[Phone2Description],
		[Phone2IsPrivate],
		[Phone2Type],
		[Phone3Number],
		[Phone3Name],
		[Phone3Description],
		[Phone3IsPrivate],
		[Phone3Type],
		[Phone4Number],
		[Phone4Name],
		[Phone4Description],
		[Phone4IsPrivate],
		[Phone4Type],
		[Phone5Number],
		[Phone5name],
		[Phone5Description],
		[Phone5IsPrivate],
		[Phone5Type],
		[PhoneFax],
		[PhoneFaxDescription],
		[PhoneFaxIsPrivate],
		[PhoneTTY],
		[PhoneTTYDescription],
		[PhoneTTYIsPrivate],
		[PhoneTollFree],
		[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline],
		[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain],
		[WebsiteAddress],
		[AgencyStatus],
		[AgencyClassification],
		[CoverageArea],
		[CoverageAreaText],
		[Eligibility],
		[EligibilityAdult],
		[EligibilityChild],
		[EligibilityFamily],
		[EligibilityFemale],
		[EligibilityMale],
		[EligibilityTeen],
		[SeniorWorkerName],
		[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate],
		[MainContactName],
		[MainContactTitle],
		[MainContactEmailAddress],
		[MainContactPhoneNumber],
		[MainContactType],
		[MainContactIsPrivate],
		[LicenseAccreditation],
		[YearIncorporated],
		[AnnualBudgetTotal],
		[LegalStatus],
		[SourceOfFunds],
		[ExcludeFromWebsite],
		[ExcludeFromDirectory],
		[DisabilitiesAccess],
		[PhysicalLocationDescription],
		[BusServiceAccess],
		[PublicAccessTransportation],
		[PaymentMethods],
		[FeeStructureSource],
		[ApplicationProcess],
		[ResourceInfo],
		[DocumentsRequired],
		[LanguagesOffered],
		[LanguagesOfferedList],
		[AvailabilityNumberOfTimes],
		[AvailabilityFrequency],
		[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability],
		[CapacityType],
		[ServiceCapacity],
		[NormalWaitTime],
		[TemporaryMessage],
		[TemporaryMessageAppears],
		[TemporaryMessageExpires],
		[EnteredOn],
		[UpdatedOn],
		[MadeInactiveOn],
		[InternalNotes],
		[InternalNotesForEditorsAndViewers],
		[HighlightedResource],
		[LastVerifiedOn],
		[LastVerifiedByName],
		[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy],
		[AvailableForDirectory],
		[AvailableForReferral],
		[AvailableForResearch],
		[PreferredProvider],
		[ConnectsToSiteNum],
		[ConnectsToProgramNum],
		[LanguageOfRecord],
		[CurrentWorkflowStepCode],
		[VolunteerOpportunities],
		[VolunteerDuties],
		[IsLinkOnly],
		[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic],
		[Categories],
		[TaxonomyTerm],
		[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes],
		[Coverage],
		[Hours],
		[Custom_Public Comments],
		[Custom_Former Names],
		[Custom_Legal Name],
		[Custom_Facebook],
		[Custom_Instagram],
		[Custom_LinkedIn],
		[Custom_Twitter],
		[Custom_YouTube],
		[Custom_Minimum Age],
		[Custom_Maximum Age],
		[DATE_MODIFIED],
		ORG_LEVEL_1,
		ORG_DESCRIPTION,
		ORG_LOCATION_SERVICE,
		DELETION_DATE,
		SOFT_DELETION_DATE,
		[Custom_Deleted Record],
		[MailingCommunity],
		[OtherCommunity],
		[PhysicalCommunity]
	) VALUES (
		src.[ResourceAgencyNum],
		src.LangID,
		src.[PublicName],
		src.[AlternateName],
		src.[OfficialName],
		src.[TaxonomyLevelName],
		src.[ParentAgency],
		src.[ParentAgencyNum],
		LEFT(src.[Custom_Record Owner (controlled)], 3),
		LEFT(src.[UniqueIDPriorSystem],8),
		src.[MailingAttentionName],
		src.[MailingAddress1],
		src.[MailingAddress2],
		src.[MailingCity],
		src.[MailingStateProvince],
		src.[MailingPostalCode],
		NULLIF(src.[MailingCountry], '-1'),
		src.[MailingAddressIsPrivate],
		src.[PhysicalAddress1],
		src.[PhysicalAddress2],
		src.[PhysicalCity],
		src.[PhysicalCounty],
		src.[PhysicalStateProvince],
		src.[PhysicalPostalCode],
		NULLIF(src.[PhysicalCountry], '-1'),
		src.[PhysicalAddressIsPrivate],
		src.[OtherAddress1],
		src.[OtherAddress2],
		src.[OtherCity],
		src.[OtherCounty],
		src.[OtherStateProvince],
		src.[OtherPostalCode],
		NULLIF(src.[OtherCountry], '-1'),
		NULLIF(src.[Latitude],'0'),
		NULLIF(src.[Longitude],'0'),
		src.[HoursOfOperation],
		src.[Phone1Number],
		src.[Phone1Name],
		src.[Phone1Description],
		src.[Phone1IsPrivate],
		src.[Phone1Type],
		src.[Phone2Number],
		src.[Phone2Name],
		src.[Phone2Description],
		src.[Phone2IsPrivate],
		src.[Phone2Type],
		src.[Phone3Number],
		src.[Phone3Name],
		src.[Phone3Description],
		src.[Phone3IsPrivate],
		src.[Phone3Type],
		src.[Phone4Number],
		src.[Phone4Name],
		src.[Phone4Description],
		src.[Phone4IsPrivate],
		src.[Phone4Type],
		src.[Phone5Number],
		src.[Phone5name],
		src.[Phone5Description],
		src.[Phone5IsPrivate],
		src.[Phone5Type],
		src.[PhoneFax],
		src.[PhoneFaxDescription],
		src.[PhoneFaxIsPrivate],
		src.[PhoneTTY],
		src.[PhoneTTYDescription],
		src.[PhoneTTYIsPrivate],
		src.[PhoneTollFree],
		src.[PhoneTollFreeDescription],
		src.[PhoneTollFreeIsPrivate],
		src.[PhoneNumberHotline],
		src.[PhoneNumberHotlineDescription],
		src.[PhoneNumberHotlineIsPrivate],
		src.[PhoneNumberBusinessLine],
		src.[PhoneNumberBusinessLineDescription],
		src.[PhoneNumberBusinessLineIsPrivate],
		src.[PhoneNumberOutOfArea],
		src.[PhoneNumberOutOfAreaDescription],
		src.[PhoneNumberOutOfAreaIsPrivate],
		src.[PhoneNumberAfterHours],
		src.[PhoneNumberAfterHoursDescription],
		src.[PhoneNumberAfterHoursIsPrivate],
		src.[EmailAddressMain],
		src.[WebsiteAddress],
		src.[AgencyStatus],
		src.[AgencyClassification],
		src.[CoverageArea],
		src.[CoverageAreaText],
		src.[Eligibility],
		src.[EligibilityAdult],
		src.[EligibilityChild],
		src.[EligibilityFamily],
		src.[EligibilityFemale],
		src.[EligibilityMale],
		src.[EligibilityTeen],
		src.[SeniorWorkerName],
		src.[SeniorWorkerTitle],
		src.[SeniorWorkerEmailAddress],
		src.[SeniorWorkerPhoneNumber],
		src.[SeniorWorkerIsPrivate],
		src.[MainContactName],
		src.[MainContactTitle],
		src.[MainContactEmailAddress],
		src.[MainContactPhoneNumber],
		src.[MainContactType],
		src.[MainContactIsPrivate],
		src.[LicenseAccreditation],
		src.[YearIncorporated],
		src.[AnnualBudgetTotal],
		src.[LegalStatus],
		src.[SourceOfFunds],
		src.[ExcludeFromWebsite],
		src.[ExcludeFromDirectory],
		src.[DisabilitiesAccess],
		src.[PhysicalLocationDescription],
		src.[BusServiceAccess],
		src.[PublicAccessTransportation],
		src.[PaymentMethods],
		src.[FeeStructureSource],
		src.[ApplicationProcess],
		src.[ResourceInfo],
		src.[DocumentsRequired],
		src.[LanguagesOffered],
		src.[LanguagesOfferedList],
		src.[AvailabilityNumberOfTimes],
		src.[AvailabilityFrequency],
		src.[AvailabilityPeriod],
		src.[ServiceNotAlwaysAvailability],
		src.[CapacityType],
		src.[ServiceCapacity],
		src.[NormalWaitTime],
		src.[TemporaryMessage],
		src.[TemporaryMessageAppears],
		src.[TemporaryMessageExpires],
		src.[EnteredOn],
		src.[UpdatedOn],
		src.[MadeInactiveOn],
		src.[InternalNotes],
		src.[InternalNotesForEditorsAndViewers],
		src.[HighlightedResource],
		src.[LastVerifiedOn],
		src.[LastVerifiedByName],
		src.[LastVerifiedByTitle],
		src.[LastVerifiedByPhoneNumber],
		src.[LastVerifiedByEmailAddress],
		src.[LastVerificationApprovedBy],
		src.[AvailableForDirectory],
		src.[AvailableForReferral],
		src.[AvailableForResearch],
		src.[PreferredProvider],
		src.[ConnectsToSiteNum],
		src.[ConnectsToProgramNum],
		src.[LanguageOfRecord],
		src.[CurrentWorkflowStepCode],
		src.[VolunteerOpportunities],
		src.[VolunteerDuties],
		src.[IsLinkOnly],
		src.[ProgramAgencyNamePublic],
		src.[SiteAgencyNamePublic],
		src.[Categories],
		src.[TaxonomyTerm],
		src.[TaxonomyTerms],
		src.[TaxonomyTermsNotDeactivated],
		src.[TaxonomyCodes],
		src.[Coverage],
		src.[Hours],
		src.[Custom_Public Comments],
		src.[Custom_Former Names],
		src.[Custom_Legal Name],
		src.[Custom_Facebook],
		src.[Custom_Instagram],
		src.[Custom_LinkedIn],
		src.[Custom_Twitter],
		src.[Custom_YouTube],
		src.[Custom_Minimum Age],
		src.[Custom_Maximum Age],
		GETDATE(),
		src.PublicName,
		src.AgencyDescription,
		'AGENCY',
		src.DELETION_DATE,
		CASE WHEN src.[Custom_Deleted Record] = 'yes' THEN GETDATE() ELSE NULL END,
		src.[Custom_Deleted Record],
		src.[MailingCommunity],
		src.[OtherCommunity],
		src.[PhysicalCommunity]	
	)
OPTION (ROBUST PLAN)
	;


MERGE INTO dbo.CIC_iCarolImportRollup dst
USING (
SELECT 
		(SELECT MAX(SYNC_DATE) FROM (VALUES (pas.SYNC_DATE), (p.SYNC_DATE), (s.SYNC_DATE), (a.SYNC_DATE)) AS i(SYNC_DATE)) AS SYNC_DATE,
		COALESCE(pas.[ResourceAgencyNum], p.[ResourceAgencyNum], s.[ResourceAgencyNum], a.[ResourceAgencyNum]) AS [ResourceAgencyNum],
		COALESCE(pas.[LangID], p.[LangID], s.[LangID], a.[LangID]) AS [LangID],
		COALESCE(pas.[PublicName], p.[PublicName], s.[PublicName], a.[PublicName]) AS [PublicName],
		COALESCE(pas.[AlternateName], p.[AlternateName], s.[AlternateName], a.[AlternateName]) AS [AlternateName],
		COALESCE(pas.[OfficialName], p.[OfficialName], s.[OfficialName], a.[OfficialName]) AS [OfficialName],
		COALESCE(pas.[TaxonomyLevelName], p.[TaxonomyLevelName], s.[TaxonomyLevelName], a.[TaxonomyLevelName]) AS [TaxonomyLevelName],
		COALESCE(pas.[ParentAgency], p.[ParentAgency], s.[ParentAgency], a.[ParentAgency]) AS [ParentAgency],
		COALESCE(pas.[ParentAgencyNum], p.[ParentAgencyNum], s.[ParentAgencyNum], a.[ParentAgencyNum]) AS [ParentAgencyNum],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_Record Owner (controlled)] END, p.[Custom_Record Owner (controlled)]) AS [RECORD_OWNER],
		LEFT(COALESCE(pas.[UniqueIDPriorSystem], p.[UniqueIDPriorSystem], s.[UniqueIDPriorSystem], a.[UniqueIDPriorSystem]), 8) AS [UniqueIDPriorSystem],
		CASE WHEN pas.HasMailingAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MailingAttentionName] WHEN p.HasMailingAddress=1 THEN p.[MailingAttentionName] WHEN s.HasMailingAddress=1 THEN s.[MailingAttentionName] END AS [MailingAttentionName],
		CASE WHEN pas.HasMailingAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MailingAddress1] WHEN p.HasMailingAddress=1 THEN p.[MailingAddress1] WHEN s.HasMailingAddress=1 THEN s.[MailingAddress1] END AS [MailingAddress1],
		CASE WHEN pas.HasMailingAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MailingAddress2] WHEN p.HasMailingAddress=1 THEN p.[MailingAddress2] WHEN s.HasMailingAddress=1 THEN s.[MailingAddress2] END AS [MailingAddress2],
		CASE WHEN pas.HasMailingAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MailingCity] WHEN p.HasMailingAddress=1 THEN p.[MailingCity] WHEN s.HasMailingAddress=1 THEN s.[MailingCity] END AS [MailingCity],
		CASE WHEN pas.HasMailingAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MailingCommunity] WHEN p.HasMailingAddress=1 THEN p.[MailingCommunity] WHEN s.HasMailingAddress=1 THEN s.[MailingCommunity] END AS [MailingCommunity],
		CASE WHEN pas.HasMailingAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MailingStateProvince] WHEN p.HasMailingAddress=1 THEN p.[MailingStateProvince] WHEN s.HasMailingAddress=1 THEN s.[MailingStateProvince] END AS [MailingStateProvince],
		CASE WHEN pas.HasMailingAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MailingPostalCode] WHEN p.HasMailingAddress=1 THEN p.[MailingPostalCode] WHEN s.HasMailingAddress=1 THEN s.[MailingPostalCode] END AS [MailingPostalCode],
		CASE WHEN pas.HasMailingAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MailingCountry] WHEN p.HasMailingAddress=1 THEN p.[MailingCountry] WHEN s.HasMailingAddress=1 THEN s.[MailingCountry] END AS [MailingCountry],
		CASE WHEN pas.HasMailingAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MailingAddressIsPrivate] WHEN p.HasMailingAddress=1 THEN p.[MailingAddressIsPrivate] WHEN s.HasMailingAddress=1 THEN s.[MailingAddressIsPrivate] END AS [MailingAddressIsPrivate],
		CASE WHEN pas.HasPhysicalAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhysicalAddress1] WHEN p.HasPhysicalAddress=1 THEN p.[PhysicalAddress1] WHEN s.HasPhysicalAddress=1 THEN s.[PhysicalAddress1] END AS [PhysicalAddress1],
		CASE WHEN pas.HasPhysicalAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhysicalAddress2] WHEN p.HasPhysicalAddress=1 THEN p.[PhysicalAddress2] WHEN s.HasPhysicalAddress=1 THEN s.[PhysicalAddress2] END AS [PhysicalAddress2],
		CASE WHEN pas.HasPhysicalAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhysicalCity] WHEN p.HasPhysicalAddress=1 THEN p.[PhysicalCity] WHEN s.HasPhysicalAddress=1 THEN s.[PhysicalCity] END AS [PhysicalCity],
		CASE WHEN pas.HasPhysicalAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhysicalCounty] WHEN p.HasPhysicalAddress=1 THEN p.[PhysicalCounty] WHEN s.HasPhysicalAddress=1 THEN s.[PhysicalCounty] END AS [PhysicalCounty],
		CASE WHEN pas.HasPhysicalAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhysicalCommunity] WHEN p.HasPhysicalAddress=1 THEN p.[PhysicalCommunity] WHEN s.HasPhysicalAddress=1 THEN s.[PhysicalCommunity] END AS [PhysicalCommunity],
		CASE WHEN pas.HasPhysicalAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhysicalStateProvince] WHEN p.HasPhysicalAddress=1 THEN p.[PhysicalStateProvince] WHEN s.HasPhysicalAddress=1 THEN s.[PhysicalStateProvince] END AS [PhysicalStateProvince],
		CASE WHEN pas.HasPhysicalAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhysicalPostalCode] WHEN p.HasPhysicalAddress=1 THEN p.[PhysicalPostalCode] WHEN s.HasPhysicalAddress=1 THEN s.[PhysicalPostalCode] END AS [PhysicalPostalCode],
		CASE WHEN pas.HasPhysicalAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhysicalCountry] WHEN p.HasPhysicalAddress=1 THEN p.[PhysicalCountry] WHEN s.HasPhysicalAddress=1 THEN s.[PhysicalCountry] END AS [PhysicalCountry],
		CASE WHEN pas.HasPhysicalAddress=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhysicalAddressIsPrivate] WHEN p.HasPhysicalAddress=1 THEN p.[PhysicalAddressIsPrivate] WHEN s.HasPhysicalAddress=1 THEN s.[PhysicalAddressIsPrivate] END AS [PhysicalAddressIsPrivate],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[OtherAddress1] END, p.[OtherAddress1], s.[OtherAddress1]) AS [OtherAddress1],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[OtherAddress2] END, p.[OtherAddress2], s.[OtherAddress2]) AS [OtherAddress2],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[OtherCity] END, p.[OtherCity], s.[OtherCity]) AS [OtherCity],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[OtherCounty] END, p.[OtherCounty], s.[OtherCounty]) AS [OtherCounty],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[OtherCommunity] END, p.[OtherCommunity], s.[OtherCommunity]) AS [OtherCommunity],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[OtherStateProvince] END, p.[OtherStateProvince], s.[OtherStateProvince]) AS [OtherStateProvince],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[OtherPostalCode] END, p.[OtherPostalCode], s.[OtherPostalCode]) AS [OtherPostalCode],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN NULLIF(pas.[OtherCountry], '-1') END, NULLIF(p.[OtherCountry], '-1'), NULLIF(s.[OtherCountry], '-1')) AS [OtherCountry],
		-- TODO Update Lat/Lng with HasPhysical
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN NULLIF(NULLIF(pas.[Latitude],'0'), '0.00000000000000') END, CASE WHEN p.PhysicalAddressIsPrivate = 'Yes' THEN NULL ELSE NULLIF(NULLIF(p.[Latitude],'0'), '0.00000000000000') END, CASE WHEN s.PhysicalAddressIsPrivate = 'Yes' THEN NULL ELSE NULLIF(NULLIF(s.[Latitude],'0'), '0.00000000000000') END) AS [Latitude],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN NULLIF(NULLIF(pas.[Longitude], '0'), '0.00000000000000') END, CASE WHEN p.PhysicalAddressIsPrivate = 'Yes' THEN NULL ELSE NULLIF(NULLIF(p.[Longitude],'0'), '0.00000000000000') END, CASE WHEN s.PhysicalAddressIsPrivate = 'Yes' THEN NULL ELSE NULLIF(NULLIF(s.[Longitude],'0'), '0.00000000000000') END) AS [Longitude],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[HoursOfOperation] END, p.[HoursOfOperation], s.[HoursOfOperation]) AS [HoursOfOperation],
		CASE WHEN pas.HasPhone1=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone1Number] WHEN p.HasPhone1=1 THEN p.[Phone1Number] WHEN s.HasPhone1=1 THEN s.[Phone1Number] END AS [Phone1Number],
		CASE WHEN pas.HasPhone1=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone1Name] WHEN p.HasPhone1=1 THEN p.[Phone1Name] WHEN s.HasPhone1=1 THEN s.[Phone1Name] END AS [Phone1Name],
		CASE WHEN pas.HasPhone1=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone1Description] WHEN p.HasPhone1=1 THEN p.[Phone1Description] WHEN s.HasPhone1=1 THEN s.[Phone1Description] END AS [Phone1Description],
		CASE WHEN pas.HasPhone1=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone1IsPrivate] WHEN p.HasPhone1=1 THEN p.[Phone1IsPrivate] WHEN s.HasPhone1=1 THEN s.[Phone1IsPrivate] END AS [Phone1IsPrivate],
		CASE WHEN pas.HasPhone1=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone1Type] WHEN p.HasPhone1=1 THEN p.[Phone1Type] WHEN s.HasPhone1=1 THEN s.[Phone1Type] END AS [Phone1Type],
		CASE WHEN pas.HasPhone2=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone2Number] WHEN p.HasPhone2=1 THEN p.[Phone2Number] WHEN s.HasPhone2=1 THEN s.[Phone2Number] END AS [Phone2Number],
		CASE WHEN pas.HasPhone2=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone2Name] WHEN p.HasPhone2=1 THEN p.[Phone2Name] WHEN s.HasPhone2=1 THEN s.[Phone2Name] END AS [Phone2Name],
		CASE WHEN pas.HasPhone2=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone2Description] WHEN p.HasPhone2=1 THEN p.[Phone2Description] WHEN s.HasPhone2=1 THEN s.[Phone2Description] END AS [Phone2Description],
		CASE WHEN pas.HasPhone2=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone2IsPrivate] WHEN p.HasPhone2=1 THEN p.[Phone2IsPrivate] WHEN s.HasPhone2=1 THEN s.[Phone2IsPrivate] END AS [Phone2IsPrivate],
		CASE WHEN pas.HasPhone2=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone2Type] WHEN p.HasPhone2=1 THEN p.[Phone2Type] WHEN s.HasPhone2=1 THEN s.[Phone2Type] END AS [Phone2Type],
		CASE WHEN pas.HasPhone3=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone3Number] WHEN p.HasPhone3=1 THEN p.[Phone3Number] WHEN s.HasPhone3=1 THEN s.[Phone3Number] END AS [Phone3Number],
		CASE WHEN pas.HasPhone3=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone3Name] WHEN p.HasPhone3=1 THEN p.[Phone3Name] WHEN s.HasPhone3=1 THEN s.[Phone3Name] END AS [Phone3Name],
		CASE WHEN pas.HasPhone3=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone3Description] WHEN p.HasPhone3=1 THEN p.[Phone3Description] WHEN s.HasPhone3=1 THEN s.[Phone3Description] END AS [Phone3Description],
		CASE WHEN pas.HasPhone3=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone3IsPrivate] WHEN p.HasPhone3=1 THEN p.[Phone3IsPrivate] WHEN s.HasPhone3=1 THEN s.[Phone3IsPrivate] END AS [Phone3IsPrivate],
		CASE WHEN pas.HasPhone3=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone3Type] WHEN p.HasPhone3=1 THEN p.[Phone3Type] WHEN s.HasPhone3=1 THEN s.[Phone3Type] END AS [Phone3Type],
		CASE WHEN pas.HasPhone4=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone4Number] WHEN p.HasPhone4=1 THEN p.[Phone4Number] WHEN s.HasPhone4=1 THEN s.[Phone4Number] END AS [Phone4Number],
		CASE WHEN pas.HasPhone4=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone4Name] WHEN p.HasPhone4=1 THEN p.[Phone4Name] WHEN s.HasPhone4=1 THEN s.[Phone4Name] END AS [Phone4Name],
		CASE WHEN pas.HasPhone4=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone4Description] WHEN p.HasPhone4=1 THEN p.[Phone4Description] WHEN s.HasPhone4=1 THEN s.[Phone4Description] END AS [Phone4Description],
		CASE WHEN pas.HasPhone4=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone4IsPrivate] WHEN p.HasPhone4=1 THEN p.[Phone4IsPrivate] WHEN s.HasPhone4=1 THEN s.[Phone4IsPrivate] END AS [Phone4IsPrivate],
		CASE WHEN pas.HasPhone4=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone4Type] WHEN p.HasPhone4=1 THEN p.[Phone4Type] WHEN s.HasPhone4=1 THEN s.[Phone4Type] END AS [Phone4Type],
		CASE WHEN pas.HasPhone5=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone5Number] WHEN p.HasPhone5=1 THEN p.[Phone5Number] WHEN s.HasPhone5=1 THEN s.[Phone5Number] END AS [Phone5Number],
		CASE WHEN pas.HasPhone5=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone5name] WHEN p.HasPhone5=1 THEN p.[Phone5name] WHEN s.HasPhone5=1 THEN s.[Phone5name] END AS [Phone5name],
		CASE WHEN pas.HasPhone5=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone5Description] WHEN p.HasPhone5=1 THEN p.[Phone5Description] WHEN s.HasPhone5=1 THEN s.[Phone5Description] END AS [Phone5Description],
		CASE WHEN pas.HasPhone5=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone5IsPrivate] WHEN p.HasPhone5=1 THEN p.[Phone5IsPrivate] WHEN s.HasPhone5=1 THEN s.[Phone5IsPrivate] END AS [Phone5IsPrivate],
		CASE WHEN pas.HasPhone5=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[Phone5Type] WHEN p.HasPhone5=1 THEN p.[Phone5Type] WHEN s.HasPhone5=1 THEN s.[Phone5Type] END AS [Phone5Type],
		CASE WHEN pas.HasPhoneFax=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneFax] WHEN p.HasPhoneFax=1 THEN p.[PhoneFax] WHEN s.HasPhoneFax=1 THEN s.[PhoneFax] END AS [PhoneFax],
		CASE WHEN pas.HasPhoneFax=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneFaxDescription] WHEN p.HasPhoneFax=1 THEN p.[PhoneFaxDescription] WHEN s.HasPhoneFax=1 THEN s.[PhoneFaxDescription] END AS [PhoneFaxDescription],
		CASE WHEN pas.HasPhoneFax=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneFaxIsPrivate] WHEN p.HasPhoneFax=1 THEN p.[PhoneFaxIsPrivate] WHEN s.HasPhoneFax=1 THEN s.[PhoneFaxIsPrivate] END AS [PhoneFaxIsPrivate],
		CASE WHEN pas.HasPhoneTTY=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneTTY] WHEN p.HasPhoneTTY=1 THEN p.[PhoneTTY] WHEN s.HasPhoneTTY=1 THEN s.[PhoneTTY] END AS [PhoneTTY],
		CASE WHEN pas.HasPhoneTTY=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneTTYDescription] WHEN p.HasPhoneTTY=1 THEN p.[PhoneTTYDescription] WHEN s.HasPhoneTTY=1 THEN s.[PhoneTTYDescription] END AS [PhoneTTYDescription],
		CASE WHEN pas.HasPhoneTTY=1 AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneTTYIsPrivate] WHEN p.HasPhoneTTY=1 THEN p.[PhoneTTYIsPrivate] WHEN s.HasPhoneTTY=1 THEN s.[PhoneTTYIsPrivate] END AS [PhoneTTYIsPrivate],
		CASE WHEN pas.HasPhoneTollFree=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneTollFree] WHEN p.HasPhoneTollFree=1 THEN p.[PhoneTollFree] WHEN s.HasPhoneTollFree=1 THEN s.[PhoneTollFree] END AS [PhoneTollFree],
		CASE WHEN pas.HasPhoneTollFree=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneTollFreeDescription] WHEN p.HasPhoneTollFree=1 THEN p.[PhoneTollFreeDescription] WHEN s.HasPhoneTollFree=1 THEN s.[PhoneTollFreeDescription] END AS [PhoneTollFreeDescription],
		CASE WHEN pas.HasPhoneTollFree=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneTollFreeIsPrivate] WHEN p.HasPhoneTollFree=1 THEN p.[PhoneTollFreeIsPrivate] WHEN s.HasPhoneTollFree=1 THEN s.[PhoneTollFreeIsPrivate] END AS [PhoneTollFreeIsPrivate],
		CASE WHEN pas.HasPhoneNumberHotline=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberHotline] WHEN p.HasPhoneNumberHotline=1 THEN p.[PhoneNumberHotline] WHEN s.HasPhoneNumberHotline=1 THEN s.[PhoneNumberHotline] END AS [PhoneNumberHotline],
		CASE WHEN pas.HasPhoneNumberHotline=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberHotlineDescription] WHEN p.HasPhoneNumberHotline=1 THEN p.[PhoneNumberHotlineDescription] WHEN s.HasPhoneNumberHotline=1 THEN s.[PhoneNumberHotlineDescription] END AS [PhoneNumberHotlineDescription],
		CASE WHEN pas.HasPhoneNumberHotline=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberHotlineIsPrivate] WHEN p.HasPhoneNumberHotline=1 THEN p.[PhoneNumberHotlineIsPrivate] WHEN s.HasPhoneNumberHotline=1 THEN s.[PhoneNumberHotlineIsPrivate] END AS [PhoneNumberHotlineIsPrivate],
		CASE WHEN pas.HasPhoneNumberBusinessLine=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberBusinessLine] WHEN p.HasPhoneNumberBusinessLine=1 THEN p.[PhoneNumberBusinessLine] WHEN s.HasPhoneNumberBusinessLine=1 THEN s.[PhoneNumberBusinessLine] END AS [PhoneNumberBusinessLine],
		CASE WHEN pas.HasPhoneNumberBusinessLine=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberBusinessLineDescription] WHEN p.HasPhoneNumberBusinessLine=1 THEN p.[PhoneNumberBusinessLineDescription] WHEN s.HasPhoneNumberBusinessLine=1 THEN s.[PhoneNumberBusinessLineDescription] END AS [PhoneNumberBusinessLineDescription],
		CASE WHEN pas.HasPhoneNumberBusinessLine=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberBusinessLineIsPrivate] WHEN p.HasPhoneNumberBusinessLine=1 THEN p.[PhoneNumberBusinessLineIsPrivate] WHEN s.HasPhoneNumberBusinessLine=1 THEN s.[PhoneNumberBusinessLineIsPrivate] END AS [PhoneNumberBusinessLineIsPrivate],
		CASE WHEN pas.HasPhoneNumberOutOfArea=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberOutOfArea] WHEN p.HasPhoneNumberOutOfArea=1 THEN p.[PhoneNumberOutOfArea] WHEN s.HasPhoneNumberOutOfArea=1 THEN s.[PhoneNumberOutOfArea] END AS [PhoneNumberOutOfArea],
		CASE WHEN pas.HasPhoneNumberOutOfArea=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberOutOfAreaDescription] WHEN p.HasPhoneNumberOutOfArea=1 THEN p.[PhoneNumberOutOfAreaDescription] WHEN s.HasPhoneNumberOutOfArea=1 THEN s.[PhoneNumberOutOfAreaDescription] END AS [PhoneNumberOutOfAreaDescription],
		CASE WHEN pas.HasPhoneNumberOutOfArea=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberOutOfAreaIsPrivate] WHEN p.HasPhoneNumberOutOfArea=1 THEN p.[PhoneNumberOutOfAreaIsPrivate] WHEN s.HasPhoneNumberOutOfArea=1 THEN s.[PhoneNumberOutOfAreaIsPrivate] END AS [PhoneNumberOutOfAreaIsPrivate],
		CASE WHEN pas.HasPhoneNumberAfterHours=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberAfterHours] WHEN p.HasPhoneNumberAfterHours=1 THEN p.[PhoneNumberAfterHours] WHEN s.HasPhoneNumberAfterHours=1 THEN s.[PhoneNumberAfterHours] END AS [PhoneNumberAfterHours],
		CASE WHEN pas.HasPhoneNumberAfterHours=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberAfterHoursDescription] WHEN p.HasPhoneNumberAfterHours=1 THEN p.[PhoneNumberAfterHoursDescription] WHEN s.HasPhoneNumberAfterHours=1 THEN s.[PhoneNumberAfterHoursDescription] END AS [PhoneNumberAfterHoursDescription],
		CASE WHEN pas.HasPhoneNumberAfterHours=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[PhoneNumberAfterHoursIsPrivate] WHEN p.HasPhoneNumberAfterHours=1 THEN p.[PhoneNumberAfterHoursIsPrivate] WHEN s.HasPhoneNumberAfterHours=1 THEN s.[PhoneNumberAfterHoursIsPrivate] END AS [PhoneNumberAfterHoursIsPrivate],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[EmailAddressMain] END, p.[EmailAddressMain], s.[EmailAddressMain]) AS [EmailAddressMain],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[WebsiteAddress] END, p.[WebsiteAddress], s.[WebsiteAddress]) AS [WebsiteAddress],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[AgencyStatus] END, p.[AgencyStatus], s.[AgencyStatus]) AS [AgencyStatus],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[AgencyClassification] END, p.[AgencyClassification], s.[AgencyClassification]) AS [AgencyClassification],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[CoverageArea] END, p.[CoverageArea], s.[CoverageArea]) AS [CoverageArea],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[CoverageAreaText] END, p.[CoverageAreaText], s.[CoverageAreaText]) AS [CoverageAreaText],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Eligibility] END, p.[Eligibility], s.[Eligibility]) AS [Eligibility],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[EligibilityAdult] END, p.[EligibilityAdult], s.[EligibilityAdult]) AS [EligibilityAdult],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[EligibilityChild] END, p.[EligibilityChild], s.[EligibilityChild]) AS [EligibilityChild],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[EligibilityFamily] END, p.[EligibilityFamily], s.[EligibilityFamily]) AS [EligibilityFamily],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[EligibilityFemale] END, p.[EligibilityFemale], s.[EligibilityFemale]) AS [EligibilityFemale],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[EligibilityMale] END, p.[EligibilityMale], s.[EligibilityMale]) AS [EligibilityMale],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[EligibilityTeen] END, p.[EligibilityTeen], s.[EligibilityTeen]) AS [EligibilityTeen],
		CASE WHEN pas.HasSeniorWorker=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[SeniorWorkerName] ELSE p.[SeniorWorkerName] END AS [SeniorWorkerName],
		CASE WHEN pas.HasSeniorWorker=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[SeniorWorkerTitle] ELSE p.[SeniorWorkerTitle] END AS [SeniorWorkerTitle],
		CASE WHEN pas.HasSeniorWorker=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[SeniorWorkerEmailAddress] ELSE p.[SeniorWorkerEmailAddress] END AS [SeniorWorkerEmailAddress],
		CASE WHEN pas.HasSeniorWorker=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[SeniorWorkerPhoneNumber] ELSE p.[SeniorWorkerPhoneNumber] END AS [SeniorWorkerPhoneNumber],
		CASE WHEN pas.HasSeniorWorker=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[SeniorWorkerIsPrivate] ELSE p.[SeniorWorkerIsPrivate] END AS [SeniorWorkerIsPrivate],
		CASE WHEN pas.HasMainContact=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MainContactName] ELSE p.[MainContactName] END AS [MainContactName], 
        CASE WHEN pas.HasMainContact=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MainContactTitle] ELSE p.[MainContactTitle] END AS [MainContactTitle],
		CASE WHEN pas.HasMainContact=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MainContactEmailAddress] ELSE p.[MainContactEmailAddress] END AS [MainContactEmailAddress],
		CASE WHEN pas.HasMainContact=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MainContactPhoneNumber] ELSE p.[MainContactPhoneNumber] END AS [MainContactPhoneNumber],
		CASE WHEN pas.HasMainContact=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MainContactType] ELSE p.[MainContactType] END AS [MainContactType],
		CASE WHEN pas.HasMainContact=1  AND ISNULL(pas.IsLinkOnly, 'False')='False' THEN pas.[MainContactIsPrivate] ELSE p.[MainContactIsPrivate] END AS [MainContactIsPrivate],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LicenseAccreditation] END, p.[LicenseAccreditation], s.[LicenseAccreditation]) AS [LicenseAccreditation],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[YearIncorporated] END, p.[YearIncorporated], s.[YearIncorporated]) AS [YearIncorporated],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[AnnualBudgetTotal] END, p.[AnnualBudgetTotal], s.[AnnualBudgetTotal]) AS [AnnualBudgetTotal],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LegalStatus] END, p.[LegalStatus], s.[LegalStatus]) AS [LegalStatus],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[SourceOfFunds] END, p.[SourceOfFunds], s.[SourceOfFunds]) AS [SourceOfFunds],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[ExcludeFromWebsite] END, p.[ExcludeFromWebsite], s.[ExcludeFromWebsite]) AS [ExcludeFromWebsite],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[ExcludeFromDirectory] END, p.[ExcludeFromDirectory], s.[ExcludeFromDirectory]) AS [ExcludeFromDirectory],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[DisabilitiesAccess] END, p.[DisabilitiesAccess], s.[DisabilitiesAccess]) AS [DisabilitiesAccess],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[PhysicalLocationDescription] END, p.[PhysicalLocationDescription], s.[PhysicalLocationDescription]) AS [PhysicalLocationDescription],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[BusServiceAccess] END, p.[BusServiceAccess], s.[BusServiceAccess]) AS [BusServiceAccess],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[PublicAccessTransportation] END, p.[PublicAccessTransportation], s.[PublicAccessTransportation]) AS [PublicAccessTransportation],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[PaymentMethods] END, p.[PaymentMethods], s.[PaymentMethods]) AS [PaymentMethods],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[FeeStructureSource] END, p.[FeeStructureSource], s.[FeeStructureSource]) AS [FeeStructureSource],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[ApplicationProcess] END, p.[ApplicationProcess], s.[ApplicationProcess]) AS [ApplicationProcess],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[ResourceInfo] END, p.[ResourceInfo], s.[ResourceInfo]) AS [ResourceInfo],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[DocumentsRequired] END, p.[DocumentsRequired], s.[DocumentsRequired]) AS [DocumentsRequired],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LanguagesOffered] END, p.[LanguagesOffered], s.[LanguagesOffered]) AS [LanguagesOffered],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LanguagesOfferedList] END, p.[LanguagesOfferedList], s.[LanguagesOfferedList]) AS [LanguagesOfferedList],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[AvailabilityNumberOfTimes] END, p.[AvailabilityNumberOfTimes], s.[AvailabilityNumberOfTimes]) AS [AvailabilityNumberOfTimes],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[AvailabilityFrequency] END, p.[AvailabilityFrequency], s.[AvailabilityFrequency]) AS [AvailabilityFrequency],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[AvailabilityPeriod] END, p.[AvailabilityPeriod], s.[AvailabilityPeriod]) AS [AvailabilityPeriod],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[ServiceNotAlwaysAvailability] END, p.[ServiceNotAlwaysAvailability], s.[ServiceNotAlwaysAvailability]) AS [ServiceNotAlwaysAvailability],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[CapacityType] END, p.[CapacityType], s.[CapacityType]) AS [CapacityType],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[ServiceCapacity] END, p.[ServiceCapacity], s.[ServiceCapacity]) AS [ServiceCapacity],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[NormalWaitTime] END, p.[NormalWaitTime], s.[NormalWaitTime]) AS [NormalWaitTime],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[TemporaryMessage] END, p.[TemporaryMessage], s.[TemporaryMessage]) AS [TemporaryMessage],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[TemporaryMessageAppears] END, p.[TemporaryMessageAppears], s.[TemporaryMessageAppears]) AS [TemporaryMessageAppears],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[TemporaryMessageExpires] END, p.[TemporaryMessageExpires], s.[TemporaryMessageExpires]) AS [TemporaryMessageExpires],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[EnteredOn] END, p.[EnteredOn], s.[EnteredOn]) AS [EnteredOn],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[UpdatedOn] END, p.[UpdatedOn], s.[UpdatedOn]) AS [UpdatedOn],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[MadeInactiveOn] END, p.[MadeInactiveOn], s.[MadeInactiveOn]) AS [MadeInactiveOn],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[InternalNotes] END, p.[InternalNotes]) AS [InternalNotes],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[InternalNotesForEditorsAndViewers] END, p.[InternalNotesForEditorsAndViewers]) AS [InternalNotesForEditorsAndViewers],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[HighlightedResource] END, p.[HighlightedResource], s.[HighlightedResource], a.[HighlightedResource]) AS [HighlightedResource],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LastVerifiedOn] END, p.[LastVerifiedOn]) AS [LastVerifiedOn],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LastVerifiedByName] END, p.[LastVerifiedByName]) AS [LastVerifiedByName],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LastVerifiedByTitle] END, p.[LastVerifiedByTitle]) AS [LastVerifiedByTitle],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LastVerifiedByPhoneNumber] END, p.[LastVerifiedByPhoneNumber]) AS [LastVerifiedByPhoneNumber],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LastVerifiedByEmailAddress] END, p.[LastVerifiedByEmailAddress]) AS [LastVerifiedByEmailAddress],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LastVerificationApprovedBy] END, p.[LastVerificationApprovedBy]) AS [LastVerificationApprovedBy],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[AvailableForDirectory] END, p.[AvailableForDirectory], s.[AvailableForDirectory]) AS [AvailableForDirectory],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[AvailableForReferral] END, p.[AvailableForReferral], s.[AvailableForReferral]) AS [AvailableForReferral],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[AvailableForResearch] END, p.[AvailableForResearch], s.[AvailableForResearch]) AS [AvailableForResearch],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[PreferredProvider] END, p.[PreferredProvider], s.[PreferredProvider]) AS [PreferredProvider],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[ConnectsToSiteNum] END, p.[ConnectsToSiteNum], s.[ConnectsToSiteNum]) AS [ConnectsToSiteNum],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[ConnectsToProgramNum] END, p.[ConnectsToProgramNum], s.[ConnectsToProgramNum]) AS [ConnectsToProgramNum],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[LanguageOfRecord] END, p.[LanguageOfRecord], s.[LanguageOfRecord]) AS [LanguageOfRecord],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[CurrentWorkflowStepCode] END, p.[CurrentWorkflowStepCode], s.[CurrentWorkflowStepCode]) AS [CurrentWorkflowStepCode],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[VolunteerOpportunities] END, p.[VolunteerOpportunities], s.[VolunteerOpportunities]) AS [VolunteerOpportunities],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[VolunteerDuties] END, p.[VolunteerDuties], s.[VolunteerDuties]) AS [VolunteerDuties],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[IsLinkOnly] END, p.[IsLinkOnly], s.[IsLinkOnly]) AS [IsLinkOnly],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[ProgramAgencyNamePublic] END, p.[ProgramAgencyNamePublic], s.[ProgramAgencyNamePublic]) AS [ProgramAgencyNamePublic],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[SiteAgencyNamePublic] END, p.[SiteAgencyNamePublic], s.[SiteAgencyNamePublic]) AS [SiteAgencyNamePublic],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Categories] END, p.[Categories], s.[Categories]) AS [Categories],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[TaxonomyTerm] END, p.[TaxonomyTerm], s.[TaxonomyTerm]) AS [TaxonomyTerm],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[TaxonomyTerms] END, p.[TaxonomyTerms], s.[TaxonomyTerms]) AS [TaxonomyTerms],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[TaxonomyTermsNotDeactivated] END, p.[TaxonomyTermsNotDeactivated], s.[TaxonomyTermsNotDeactivated]) AS [TaxonomyTermsNotDeactivated],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[TaxonomyCodes] END, p.[TaxonomyCodes], s.[TaxonomyCodes]) AS [TaxonomyCodes],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Coverage] END, p.[Coverage], s.[Coverage]) AS [Coverage],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Hours] END, p.[Hours], s.[Hours]) AS [Hours],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_Public Comments] END, p.[Custom_Public Comments]) AS [Custom_Public Comments],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_Former Names] END, p.[Custom_Former Names], s.[Custom_Former Names]) AS [Custom_Former Names],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_Legal Name] END, p.[Custom_Legal Name], s.[Custom_Legal Name]) AS [Custom_Legal Name],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_Facebook] END, p.[Custom_Facebook], s.[Custom_Facebook]) AS [Custom_Facebook],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_Instagram] END, p.[Custom_Instagram], s.[Custom_Instagram]) AS [Custom_Instagram],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_LinkedIn] END, p.[Custom_LinkedIn], s.[Custom_LinkedIn]) AS [Custom_LinkedIn],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_Twitter] END, p.[Custom_Twitter], s.[Custom_Twitter]) AS [Custom_Twitter],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_YouTube] END, p.[Custom_YouTube], s.[Custom_YouTube]) AS [Custom_YouTube],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_Minimum Age] END, p.[Custom_Minimum Age], s.[Custom_Minimum Age]) AS [Custom_Minimum Age],
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.[Custom_Maximum Age] END, p.[Custom_Maximum Age], s.[Custom_Maximum Age]) AS [Custom_Maximum Age],
		a.PublicName AS ORG_LEVEL_1,
		NULL AS ORG_DESCRIPTION,
		s.PublicName AS LOCATION_NAME,
		s.AgencyDescription AS LOCATION_DESCRIPTION,
		COALESCE(p.PublicName, pas.PublicName) AS SERVICE_NAME_LEVEL_1,
		s.PublicName AS SERVICE_NAME_LEVEL_2,
		COALESCE(CASE WHEN ISNULL(pas.ISLinkOnly, 'False')='False' THEN pas.AgencyDescription END, p.AgencyDescription) AS DESCRIPTION,
		pas.DELETION_DATE,
		CASE WHEN p.ResourceAgencyNum IS NULL OR s.ResourceAgencyNum IS NULL OR a.ResourceAgencyNum IS NULL OR 'yes' IN (pas.[Custom_Deleted Record], p.[Custom_Deleted Record], s.[Custom_Deleted Record], a.[Custom_Deleted Record]) THEN 'yes' ELSE 'no' END AS [Custom_Deleted Record]
	FROM dbo.CIC_iCarolImport pas
	LEFT JOIN dbo.CIC_iCarolImport p
		ON p.ResourceAgencyNum=pas.ConnectsToProgramNum AND p.TaxonomyLevelName='Program' AND p.LangID=pas.LangID
	LEFT JOIN dbo.CIC_iCarolImport s
		ON s.ResourceAgencyNum=pas.ConnectsToSiteNum AND s.TaxonomyLevelName='Site' AND s.langid=pas.LangID
	LEFT JOIN dbo.CIC_iCarolImport a
		ON pas.ParentAgencyNum=a.ResourceAgencyNum AND a.TaxonomyLevelName='Agency' AND a.LangID=pas.LangID
	WHERE pas.TaxonomyLevelName='ProgramAtSite'
) AS src
ON src.ResourceAgencyNum=dst.ResourceAgencyNum AND src.LangID=dst.LangID AND src.TaxonomyLevelName = 'ProgramAtSite'
WHEN MATCHED AND src.SYNC_DATE > dst.DATE_MODIFIED THEN 
	UPDATE SET 
		[PublicName]=src.[PublicName],
		[AlternateName]=src.[AlternateName],
		[OfficialName]=src.[OfficialName],
		[TaxonomyLevelName]=src.[TaxonomyLevelName],
		[ParentAgency]=src.[ParentAgency],
		[ParentAgencyNum]=src.[ParentAgencyNum],
		[RECORD_OWNER]=LEFT(src.[RECORD_OWNER], 3),
		[UniqueIDPriorSystem]=src.[UniqueIDPriorSystem],
		[MailingAttentionName]=src.[MailingAttentionName],
		[MailingAddress1]=src.[MailingAddress1],
		[MailingAddress2]=src.[MailingAddress2],
		[MailingCity]=src.[MailingCity],
		[MailingCommunity]=src.[MailingCommunity],
		[MailingStateProvince]=src.[MailingStateProvince],
		[MailingPostalCode]=src.[MailingPostalCode],
		[MailingCountry]=src.[MailingCountry],
		[MailingAddressIsPrivate]=src.[MailingAddressIsPrivate],
		[PhysicalAddress1]=src.[PhysicalAddress1],
		[PhysicalAddress2]=src.[PhysicalAddress2],
		[PhysicalCity]=src.[PhysicalCity],
		[PhysicalCounty]=src.[PhysicalCounty],
		[PhysicalCommunity]=src.[PhysicalCommunity],
		[PhysicalStateProvince]=src.[PhysicalStateProvince],
		[PhysicalPostalCode]=src.[PhysicalPostalCode],
		[PhysicalCountry]=src.[PhysicalCountry],
		[PhysicalAddressIsPrivate]=src.[PhysicalAddressIsPrivate],
		[OtherAddress1]=src.[OtherAddress1],
		[OtherAddress2]=src.[OtherAddress2],
		[OtherCity]=src.[OtherCity],
		[OtherCounty]=src.[OtherCounty],
		[OtherCommunity]=src.[OtherCommunity],
		[OtherStateProvince]=src.[OtherStateProvince],
		[OtherPostalCode]=src.[OtherPostalCode],
		[OtherCountry]=src.[OtherCountry],
		[Latitude]=src.[Latitude],
		[Longitude]=src.[Longitude],
		[HoursOfOperation]=src.[HoursOfOperation],
		[Phone1Number]=src.[Phone1Number],
		[Phone1Name]=src.[Phone1Name],
		[Phone1Description]=src.[Phone1Description],
		[Phone1IsPrivate]=src.[Phone1IsPrivate],
		[Phone1Type]=src.[Phone1Type],
		[Phone2Number]=src.[Phone2Number],
		[Phone2Name]=src.[Phone2Name],
		[Phone2Description]=src.[Phone2Description],
		[Phone2IsPrivate]=src.[Phone2IsPrivate],
		[Phone2Type]=src.[Phone2Type],
		[Phone3Number]=src.[Phone3Number],
		[Phone3Name]=src.[Phone3Name],
		[Phone3Description]=src.[Phone3Description],
		[Phone3IsPrivate]=src.[Phone3IsPrivate],
		[Phone3Type]=src.[Phone3Type],
		[Phone4Number]=src.[Phone4Number],
		[Phone4Name]=src.[Phone4Name],
		[Phone4Description]=src.[Phone4Description],
		[Phone4IsPrivate]=src.[Phone4IsPrivate],
		[Phone4Type]=src.[Phone4Type],
		[Phone5Number]=src.[Phone5Number],
		[Phone5name]=src.[Phone5name],
		[Phone5Description]=src.[Phone5Description],
		[Phone5IsPrivate]=src.[Phone5IsPrivate],
		[Phone5Type]=src.[Phone5Type],
		[PhoneFax]=src.[PhoneFax],
		[PhoneFaxDescription]=src.[PhoneFaxDescription],
		[PhoneFaxIsPrivate]=src.[PhoneFaxIsPrivate],
		[PhoneTTY]=src.[PhoneTTY],
		[PhoneTTYDescription]=src.[PhoneTTYDescription],
		[PhoneTTYIsPrivate]=src.[PhoneTTYIsPrivate],
		[PhoneTollFree]=src.[PhoneTollFree],
		[PhoneTollFreeDescription]=src.[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate]=src.[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline]=src.[PhoneNumberHotline],
		[PhoneNumberHotlineDescription]=src.[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate]=src.[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine]=src.[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription]=src.[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate]=src.[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea]=src.[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription]=src.[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate]=src.[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours]=src.[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription]=src.[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate]=src.[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain]=src.[EmailAddressMain],
		[WebsiteAddress]=src.[WebsiteAddress],
		[AgencyStatus]=src.[AgencyStatus],
		[AgencyClassification]=src.[AgencyClassification],
		[CoverageArea]=src.[CoverageArea],
		[CoverageAreaText]=src.[CoverageAreaText],
		[Eligibility]=src.[Eligibility],
		[EligibilityAdult]=src.[EligibilityAdult],
		[EligibilityChild]=src.[EligibilityChild],
		[EligibilityFamily]=src.[EligibilityFamily],
		[EligibilityFemale]=src.[EligibilityFemale],
		[EligibilityMale]=src.[EligibilityMale],
		[EligibilityTeen]=src.[EligibilityTeen],
		[SeniorWorkerName]=src.[SeniorWorkerName],
		[SeniorWorkerTitle]=src.[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress]=src.[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber]=src.[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate]=src.[SeniorWorkerIsPrivate],
		[MainContactName]=src.[MainContactName],
		[MainContactTitle]=src.[MainContactTitle],
		[MainContactEmailAddress]=src.[MainContactEmailAddress],
		[MainContactPhoneNumber]=src.[MainContactPhoneNumber],
		[MainContactType]=src.[MainContactType],
		[MainContactIsPrivate]=src.[MainContactIsPrivate],
		[LicenseAccreditation]=src.[LicenseAccreditation],
		[YearIncorporated]=src.[YearIncorporated],
		[AnnualBudgetTotal]=src.[AnnualBudgetTotal],
		[LegalStatus]=src.[LegalStatus],
		[SourceOfFunds]=src.[SourceOfFunds],
		[ExcludeFromWebsite]=src.[ExcludeFromWebsite],
		[ExcludeFromDirectory]=src.[ExcludeFromDirectory],
		[DisabilitiesAccess]=src.[DisabilitiesAccess],
		[PhysicalLocationDescription]=src.[PhysicalLocationDescription],
		[BusServiceAccess]=src.[BusServiceAccess],
		[PublicAccessTransportation]=src.[PublicAccessTransportation],
		[PaymentMethods]=src.[PaymentMethods],
		[FeeStructureSource]=src.[FeeStructureSource],
		[ApplicationProcess]=src.[ApplicationProcess],
		[ResourceInfo]=src.[ResourceInfo],
		[DocumentsRequired]=src.[DocumentsRequired],
		[LanguagesOffered]=src.[LanguagesOffered],
		[LanguagesOfferedList]=src.[LanguagesOfferedList],
		[AvailabilityNumberOfTimes]=src.[AvailabilityNumberOfTimes],
		[AvailabilityFrequency]=src.[AvailabilityFrequency],
		[AvailabilityPeriod]=src.[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability]=src.[ServiceNotAlwaysAvailability],
		[CapacityType]=src.[CapacityType],
		[ServiceCapacity]=src.[ServiceCapacity],
		[NormalWaitTime]=src.[NormalWaitTime],
		[TemporaryMessage]=src.[TemporaryMessage],
		[TemporaryMessageAppears]=src.[TemporaryMessageAppears],
		[TemporaryMessageExpires]=src.[TemporaryMessageExpires],
		[EnteredOn]=src.[EnteredOn],
		[UpdatedOn]=src.[UpdatedOn],
		[MadeInactiveOn]=src.[MadeInactiveOn],
		[InternalNotes]=src.[InternalNotes],
		[InternalNotesForEditorsAndViewers]=src.[InternalNotesForEditorsAndViewers],
		[HighlightedResource]=src.[HighlightedResource],
		[LastVerifiedOn]=src.[LastVerifiedOn],
		[LastVerifiedByName]=src.[LastVerifiedByName],
		[LastVerifiedByTitle]=src.[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber]=src.[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress]=src.[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy]=src.[LastVerificationApprovedBy],
		[AvailableForDirectory]=src.[AvailableForDirectory],
		[AvailableForReferral]=src.[AvailableForReferral],
		[AvailableForResearch]=src.[AvailableForResearch],
		[PreferredProvider]=src.[PreferredProvider],
		[ConnectsToSiteNum]=src.[ConnectsToSiteNum],
		[ConnectsToProgramNum]=src.[ConnectsToProgramNum],
		[LanguageOfRecord]=src.[LanguageOfRecord],
		[CurrentWorkflowStepCode]=src.[CurrentWorkflowStepCode],
		[VolunteerOpportunities]=src.[VolunteerOpportunities],
		[VolunteerDuties]=src.[VolunteerDuties],
		[IsLinkOnly]=src.[IsLinkOnly],
		[ProgramAgencyNamePublic]=src.[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic]=src.[SiteAgencyNamePublic],
		[Categories]=src.[Categories],
		[TaxonomyTerm]=src.[TaxonomyTerm],
		[TaxonomyTerms]=src.[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated]=src.[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes]=src.[TaxonomyCodes],
		[Coverage]=src.[Coverage],
		[Hours]=src.[Hours],
		[Custom_Public Comments]=src.[Custom_Public Comments],
		[Custom_Former Names]=src.[Custom_Former Names],
		[Custom_Legal Name]=src.[Custom_Legal Name],
		[Custom_Facebook]=src.[Custom_Facebook],
		[Custom_Instagram]=src.[Custom_Instagram],
		[Custom_LinkedIn]=src.[Custom_LinkedIn],
		[Custom_Twitter]=src.[Custom_Twitter],
		[Custom_YouTube]=src.[Custom_YouTube],
		[Custom_Minimum Age]=src.[Custom_Minimum Age],
		[Custom_Maximum Age]=src.[Custom_Maximum Age],
		[dst].[DATE_MODIFIED]=GETDATE(),
		ORG_LEVEL_1=src.ORG_LEVEL_1,
		ORG_DESCRIPTION=src.ORG_DESCRIPTION,
		LOCATION_NAME=src.LOCATION_NAME,
		LOCATION_DESCRIPTION=src.LOCATION_DESCRIPTION,
		SERVICE_NAME_LEVEL_1=src.SERVICE_NAME_LEVEL_1,
		SERVICE_NAME_LEVEL_2=src.SERVICE_NAME_LEVEL_2,
		DESCRIPTION=src.DESCRIPTION,
		dst.ORG_LOCATION_SERVICE='SERVICE',
		dst.DELETION_DATE=src.DELETION_DATE,
		dst.SOFT_DELETION_DATE=CASE WHEN src.[Custom_Deleted Record] = 'yes' THEN COALESCE(dst.SOFT_DELETION_DATE,GETDATE()) ELSE NULL END,
		dst.[Custom_Deleted Record]=src.[Custom_Deleted Record]
WHEN NOT MATCHED BY TARGET AND src.TaxonomyLevelName='ProgramAtSite' THEN
	INSERT (
		[ResourceAgencyNum],
		[LangID],
		[PublicName],
		[AlternateName],
		[OfficialName],
		[TaxonomyLevelName],
		[ParentAgency],
		[ParentAgencyNum],
		[RECORD_OWNER],
		[UniqueIDPriorSystem],
		[MailingAttentionName],
		[MailingAddress1],
		[MailingAddress2],
		[MailingCity],
		[MailingCommunity],
		[MailingStateProvince],
		[MailingPostalCode],
		[MailingCountry],
		[MailingAddressIsPrivate],
		[PhysicalAddress1],
		[PhysicalAddress2],
		[PhysicalCity],
		[PhysicalCounty],
		[PhysicalCommunity],
		[PhysicalStateProvince],
		[PhysicalPostalCode],
		[PhysicalCountry],
		[PhysicalAddressIsPrivate],
		[OtherAddress1],
		[OtherAddress2],
		[OtherCity],
		[OtherCounty],
		[OtherCommunity],
		[OtherStateProvince],
		[OtherPostalCode],
		[OtherCountry],
		[Latitude],
		[Longitude],
		[HoursOfOperation],
		[Phone1Number],
		[Phone1Name],
		[Phone1Description],
		[Phone1IsPrivate],
		[Phone1Type],
		[Phone2Number],
		[Phone2Name],
		[Phone2Description],
		[Phone2IsPrivate],
		[Phone2Type],
		[Phone3Number],
		[Phone3Name],
		[Phone3Description],
		[Phone3IsPrivate],
		[Phone3Type],
		[Phone4Number],
		[Phone4Name],
		[Phone4Description],
		[Phone4IsPrivate],
		[Phone4Type],
		[Phone5Number],
		[Phone5name],
		[Phone5Description],
		[Phone5IsPrivate],
		[Phone5Type],
		[PhoneFax],
		[PhoneFaxDescription],
		[PhoneFaxIsPrivate],
		[PhoneTTY],
		[PhoneTTYDescription],
		[PhoneTTYIsPrivate],
		[PhoneTollFree],
		[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline],
		[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain],
		[WebsiteAddress],
		[AgencyStatus],
		[AgencyClassification],
		[CoverageArea],
		[CoverageAreaText],
		[Eligibility],
		[EligibilityAdult],
		[EligibilityChild],
		[EligibilityFamily],
		[EligibilityFemale],
		[EligibilityMale],
		[EligibilityTeen],
		[SeniorWorkerName],
		[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate],
		[MainContactName],
		[MainContactTitle],
		[MainContactEmailAddress],
		[MainContactPhoneNumber],
		[MainContactType],
		[MainContactIsPrivate],
		[LicenseAccreditation],
		[YearIncorporated],
		[AnnualBudgetTotal],
		[LegalStatus],
		[SourceOfFunds],
		[ExcludeFromWebsite],
		[ExcludeFromDirectory],
		[DisabilitiesAccess],
		[PhysicalLocationDescription],
		[BusServiceAccess],
		[PublicAccessTransportation],
		[PaymentMethods],
		[FeeStructureSource],
		[ApplicationProcess],
		[ResourceInfo],
		[DocumentsRequired],
		[LanguagesOffered],
		[LanguagesOfferedList],
		[AvailabilityNumberOfTimes],
		[AvailabilityFrequency],
		[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability],
		[CapacityType],
		[ServiceCapacity],
		[NormalWaitTime],
		[TemporaryMessage],
		[TemporaryMessageAppears],
		[TemporaryMessageExpires],
		[EnteredOn],
		[UpdatedOn],
		[MadeInactiveOn],
		[InternalNotes],
		[InternalNotesForEditorsAndViewers],
		[HighlightedResource],
		[LastVerifiedOn],
		[LastVerifiedByName],
		[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy],
		[AvailableForDirectory],
		[AvailableForReferral],
		[AvailableForResearch],
		[PreferredProvider],
		[ConnectsToSiteNum],
		[ConnectsToProgramNum],
		[LanguageOfRecord],
		[CurrentWorkflowStepCode],
		[VolunteerOpportunities],
		[VolunteerDuties],
		[IsLinkOnly],
		[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic],
		[Categories],
		[TaxonomyTerm],
		[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes],
		[Coverage],
		[Hours],
		[Custom_Public Comments],
		[Custom_Former Names],
		[Custom_Legal Name],
		[Custom_Facebook],
		[Custom_Instagram],
		[Custom_LinkedIn],
		[Custom_Twitter],
		[Custom_YouTube],
		[Custom_Minimum Age],
		[Custom_Maximum Age],
		[DATE_MODIFIED],
		ORG_LEVEL_1,
		ORG_DESCRIPTION,
		LOCATION_NAME,
		LOCATION_DESCRIPTION,
		SERVICE_NAME_LEVEL_1,
		SERVICE_NAME_LEVEL_2,
		DESCRIPTION,
		ORG_LOCATION_SERVICE,
		DELETION_DATE,
		SOFT_DELETION_DATE,
		[Custom_Deleted Record]
	) VALUES (
		src.[ResourceAgencyNum],
		src.LangID,
		src.[PublicName],
		src.[AlternateName],
		src.[OfficialName],
		src.[TaxonomyLevelName],
		src.[ParentAgency],
		src.[ParentAgencyNum],
		LEFT(src.[RECORD_OWNER], 3),
		src.[UniqueIDPriorSystem],
		src.[MailingAttentionName],
		src.[MailingAddress1],
		src.[MailingAddress2],
		src.[MailingCity],
		src.[MailingCommunity],
		src.[MailingStateProvince],
		src.[MailingPostalCode],
		src.[MailingCountry],
		src.[MailingAddressIsPrivate],
		src.[PhysicalAddress1],
		src.[PhysicalAddress2],
		src.[PhysicalCity],
		src.[PhysicalCounty],
		src.[PhysicalCommunity],
		src.[PhysicalStateProvince],
		src.[PhysicalPostalCode],
		src.[PhysicalCountry],
		src.[PhysicalAddressIsPrivate],
		src.[OtherAddress1],
		src.[OtherAddress2],
		src.[OtherCity],
		src.[OtherCounty],
		src.[OtherCommunity],
		src.[OtherStateProvince],
		src.[OtherPostalCode],
		src.[OtherCountry],
		src.[Latitude],
		src.[Longitude],
		src.[HoursOfOperation],
		src.[Phone1Number],
		src.[Phone1Name],
		src.[Phone1Description],
		src.[Phone1IsPrivate],
		src.[Phone1Type],
		src.[Phone2Number],
		src.[Phone2Name],
		src.[Phone2Description],
		src.[Phone2IsPrivate],
		src.[Phone2Type],
		src.[Phone3Number],
		src.[Phone3Name],
		src.[Phone3Description],
		src.[Phone3IsPrivate],
		src.[Phone3Type],
		src.[Phone4Number],
		src.[Phone4Name],
		src.[Phone4Description],
		src.[Phone4IsPrivate],
		src.[Phone4Type],
		src.[Phone5Number],
		src.[Phone5name],
		src.[Phone5Description],
		src.[Phone5IsPrivate],
		src.[Phone5Type],
		src.[PhoneFax],
		src.[PhoneFaxDescription],
		src.[PhoneFaxIsPrivate],
		src.[PhoneTTY],
		src.[PhoneTTYDescription],
		src.[PhoneTTYIsPrivate],
		src.[PhoneTollFree],
		src.[PhoneTollFreeDescription],
		src.[PhoneTollFreeIsPrivate],
		src.[PhoneNumberHotline],
		src.[PhoneNumberHotlineDescription],
		src.[PhoneNumberHotlineIsPrivate],
		src.[PhoneNumberBusinessLine],
		src.[PhoneNumberBusinessLineDescription],
		src.[PhoneNumberBusinessLineIsPrivate],
		src.[PhoneNumberOutOfArea],
		src.[PhoneNumberOutOfAreaDescription],
		src.[PhoneNumberOutOfAreaIsPrivate],
		src.[PhoneNumberAfterHours],
		src.[PhoneNumberAfterHoursDescription],
		src.[PhoneNumberAfterHoursIsPrivate],
		src.[EmailAddressMain],
		src.[WebsiteAddress],
		src.[AgencyStatus],
		src.[AgencyClassification],
		src.[CoverageArea],
		src.[CoverageAreaText],
		src.[Eligibility],
		src.[EligibilityAdult],
		src.[EligibilityChild],
		src.[EligibilityFamily],
		src.[EligibilityFemale],
		src.[EligibilityMale],
		src.[EligibilityTeen],
		src.[SeniorWorkerName],
		src.[SeniorWorkerTitle],
		src.[SeniorWorkerEmailAddress],
		src.[SeniorWorkerPhoneNumber],
		src.[SeniorWorkerIsPrivate],
		src.[MainContactName],
		src.[MainContactTitle],
		src.[MainContactEmailAddress],
		src.[MainContactPhoneNumber],
		src.[MainContactType],
		src.[MainContactIsPrivate],
		src.[LicenseAccreditation],
		src.[YearIncorporated],
		src.[AnnualBudgetTotal],
		src.[LegalStatus],
		src.[SourceOfFunds],
		src.[ExcludeFromWebsite],
		src.[ExcludeFromDirectory],
		src.[DisabilitiesAccess],
		src.[PhysicalLocationDescription],
		src.[BusServiceAccess],
		src.[PublicAccessTransportation],
		src.[PaymentMethods],
		src.[FeeStructureSource],
		src.[ApplicationProcess],
		src.[ResourceInfo],
		src.[DocumentsRequired],
		src.[LanguagesOffered],
		src.[LanguagesOfferedList],
		src.[AvailabilityNumberOfTimes],
		src.[AvailabilityFrequency],
		src.[AvailabilityPeriod],
		src.[ServiceNotAlwaysAvailability],
		src.[CapacityType],
		src.[ServiceCapacity],
		src.[NormalWaitTime],
		src.[TemporaryMessage],
		src.[TemporaryMessageAppears],
		src.[TemporaryMessageExpires],
		src.[EnteredOn],
		src.[UpdatedOn],
		src.[MadeInactiveOn],
		src.[InternalNotes],
		src.[InternalNotesForEditorsAndViewers],
		src.[HighlightedResource],
		src.[LastVerifiedOn],
		src.[LastVerifiedByName],
		src.[LastVerifiedByTitle],
		src.[LastVerifiedByPhoneNumber],
		src.[LastVerifiedByEmailAddress],
		src.[LastVerificationApprovedBy],
		src.[AvailableForDirectory],
		src.[AvailableForReferral],
		src.[AvailableForResearch],
		src.[PreferredProvider],
		src.[ConnectsToSiteNum],
		src.[ConnectsToProgramNum],
		src.[LanguageOfRecord],
		src.[CurrentWorkflowStepCode],
		src.[VolunteerOpportunities],
		src.[VolunteerDuties],
		src.[IsLinkOnly],
		src.[ProgramAgencyNamePublic],
		src.[SiteAgencyNamePublic],
		src.[Categories],
		src.[TaxonomyTerm],
		src.[TaxonomyTerms],
		src.[TaxonomyTermsNotDeactivated],
		src.[TaxonomyCodes],
		src.[Coverage],
		src.[Hours],
		src.[Custom_Public Comments],
		src.[Custom_Former Names],
		src.[Custom_Legal Name],
		src.[Custom_Facebook],
		src.[Custom_Instagram],
		src.[Custom_LinkedIn],
		src.[Custom_Twitter],
		src.[Custom_YouTube],
		src.[Custom_Minimum Age],
		src.[Custom_Maximum Age],
		GETDATE(),
		src.ORG_LEVEL_1,
		src.ORG_DESCRIPTION,
		src.LOCATION_NAME,
		src.LOCATION_DESCRIPTION,
		src.SERVICE_NAME_LEVEL_1,
		src.SERVICE_NAME_LEVEL_2,
		src.DESCRIPTION,
		'SERVICE',
		src.DELETION_DATE,
		CASE WHEN src.[Custom_Deleted Record] = 'yes' THEN GETDATE() ELSE NULL END,
		src.[Custom_Deleted Record]
	)
OPTION (ROBUST PLAN)
	;

MERGE INTO dbo.CIC_iCarolImportRollup dst
USING (
SELECT 
		(SELECT MAX(SYNC_DATE) FROM (VALUES (s.SYNC_DATE), (a.SYNC_DATE)) AS i(SYNC_DATE)) AS SYNC_DATE,
		s.[ResourceAgencyNum] AS [ResourceAgencyNum],
		s.[LangID] AS [LangID],
		s.[PublicName],
		s.[AlternateName],
		s.[OfficialName],
		s.[TaxonomyLevelName],
		s.[ParentAgency],
		s.[ParentAgencyNum],
		s.[Custom_Record Owner (controlled)] AS [RECORD_OWNER],
		LEFT(s.[UniqueIDPriorSystem], 8) AS [UniqueIDPriorSystem],
		s.[MailingAttentionName],
		s.[MailingAddress1],
		s.[MailingAddress2],
		s.[MailingCity],
		s.[MailingCommunity],
		s.[MailingStateProvince],
		s.[MailingPostalCode],
		s.[MailingCountry],
		s.[MailingAddressIsPrivate],
		s.[PhysicalAddress1],
		s.[PhysicalAddress2],
		s.[PhysicalCity],
		s.[PhysicalCounty],
		s.[PhysicalCommunity],
		s.[PhysicalStateProvince],
		s.[PhysicalPostalCode],
		s.[PhysicalCountry],
		s.[PhysicalAddressIsPrivate],
		s.[OtherAddress1],
		s.[OtherAddress2],
		s.[OtherCity],
		s.[OtherCounty],
		s.[OtherCommunity],
		s.[OtherStateProvince],
		s.[OtherPostalCode],
		NULLIF(s.[OtherCountry], '-1') AS [OtherCountry],
		CASE WHEN s.PhysicalAddressIsPrivate = 'Yes' THEN NULL ELSE NULLIF(NULLIF(s.[Latitude],'0'), '0.00000000000000') END AS [Latitude],
		CASE WHEN s.PhysicalAddressIsPrivate = 'Yes' THEN NULL ELSE NULLIF(NULLIF(s.[Longitude],'0'), '0.00000000000000') END AS [Longitude],
		s.[HoursOfOperation],
		s.[Phone1Number],
		s.[Phone1Name],
		s.[Phone1Description],
		s.[Phone1IsPrivate],
		s.[Phone1Type],
		s.[Phone2Number],
		s.[Phone2Name],
		s.[Phone2Description],
		s.[Phone2IsPrivate],
		s.[Phone2Type],
		s.[Phone3Number],
		s.[Phone3Name],
		s.[Phone3Description],
		s.[Phone3IsPrivate],
		s.[Phone3Type],
		s.[Phone4Number],
		s.[Phone4Name],
		s.[Phone4Description],
		s.[Phone4IsPrivate],
		s.[Phone4Type],
		s.[Phone5Number],
		s.[Phone5name],
		s.[Phone5Description],
		s.[Phone5IsPrivate],
		s.[Phone5Type],
		s.[PhoneFax],
		s.[PhoneFaxDescription],
		s.[PhoneFaxIsPrivate],
		s.[PhoneTTY],
		s.[PhoneTTYDescription],
		s.[PhoneTTYIsPrivate],
		s.[PhoneTollFree],
		s.[PhoneTollFreeDescription],
		s.[PhoneTollFreeIsPrivate],
		s.[PhoneNumberHotline],
		s.[PhoneNumberHotlineDescription],
		s.[PhoneNumberHotlineIsPrivate],
		s.[PhoneNumberBusinessLine],
		s.[PhoneNumberBusinessLineDescription],
		s.[PhoneNumberBusinessLineIsPrivate],
		s.[PhoneNumberOutOfArea],
		s.[PhoneNumberOutOfAreaDescription],
		s.[PhoneNumberOutOfAreaIsPrivate],
		s.[PhoneNumberAfterHours],
		s.[PhoneNumberAfterHoursDescription],
		s.[PhoneNumberAfterHoursIsPrivate],
		s.[EmailAddressMain],
		s.[WebsiteAddress],
		s.[AgencyStatus],
		s.[AgencyClassification],
		s.[CoverageArea],
		s.[CoverageAreaText],
		s.[Eligibility],
		s.[EligibilityAdult],
		s.[EligibilityChild],
		s.[EligibilityFamily],
		s.[EligibilityFemale],
		s.[EligibilityMale],
		s.[EligibilityTeen],
		s.[SeniorWorkerName],
		s.[SeniorWorkerTitle],
		s.[SeniorWorkerEmailAddress],
		s.[SeniorWorkerPhoneNumber],
		s.[SeniorWorkerIsPrivate],
		s.[MainContactName],
		s.[MainContactTitle],
		s.[MainContactEmailAddress],
		s.[MainContactPhoneNumber],
		s.[MainContactType],
		s.[MainContactIsPrivate],
		s.[LicenseAccreditation],
		s.[YearIncorporated],
		s.[AnnualBudgetTotal],
		s.[LegalStatus],
		s.[SourceOfFunds],
		s.[ExcludeFromWebsite],
		s.[ExcludeFromDirectory],
		s.[DisabilitiesAccess],
		s.[PhysicalLocationDescription],
		s.[BusServiceAccess],
		s.[PublicAccessTransportation],
		s.[PaymentMethods],
		s.[FeeStructureSource],
		s.[ApplicationProcess],
		s.[ResourceInfo],
		s.[DocumentsRequired],
		s.[LanguagesOffered],
		s.[LanguagesOfferedList],
		s.[AvailabilityNumberOfTimes],
		s.[AvailabilityFrequency],
		s.[AvailabilityPeriod],
		s.[ServiceNotAlwaysAvailability],
		s.[CapacityType],
		s.[ServiceCapacity],
		s.[NormalWaitTime],
		s.[TemporaryMessage],
		s.[TemporaryMessageAppears],
		s.[TemporaryMessageExpires],
		s.[EnteredOn],
		s.[UpdatedOn],
		s.[MadeInactiveOn],
		s.[InternalNotes],
		s.[InternalNotesForEditorsAndViewers],
		s.[HighlightedResource],
		s.[LastVerifiedOn], 
		s.[LastVerifiedByName],
		s.[LastVerifiedByTitle], 
		s.[LastVerifiedByPhoneNumber], 
		s.[LastVerifiedByEmailAddress],
		s.[LastVerificationApprovedBy],
		s.[AvailableForDirectory],
		s.[AvailableForReferral],
		s.[AvailableForResearch],
		s.[PreferredProvider],
		s.[ConnectsToSiteNum],
		s.[ConnectsToProgramNum],
		s.[LanguageOfRecord],
		s.[CurrentWorkflowStepCode],
		s.[VolunteerOpportunities],
		s.[VolunteerDuties],
		s.[IsLinkOnly],
		s.[ProgramAgencyNamePublic],
		s.[SiteAgencyNamePublic],
		s.[Categories],
		s.[TaxonomyTerm],
		s.[TaxonomyTerms],
		s.[TaxonomyTermsNotDeactivated],
		s.[TaxonomyCodes],
		s.[Coverage],
		s.[Hours],
		s.[Custom_Public Comments],
		s.[Custom_Former Names],
		s.[Custom_Legal Name],
		s.[Custom_Facebook],
		s.[Custom_Instagram],
		s.[Custom_LinkedIn],
		s.[Custom_Twitter],
		s.[Custom_YouTube],
		s.[Custom_Minimum Age],
		s.[Custom_Maximum Age],
		a.PublicName AS ORG_LEVEL_1,
		NULL AS ORG_DESCRIPTION,
		s.PublicName AS LOCATION_NAME,
		s.AgencyDescription AS LOCATION_DESCRIPTION,
		s.DELETION_DATE,
		CASE WHEN s.ResourceAgencyNum IS NULL OR 'yes' IN (s.[Custom_Deleted Record], a.[Custom_Deleted Record]) THEN 'yes' ELSE 'no' END AS [Custom_Deleted Record]
FROM dbo.CIC_iCarolImport AS s
LEFT JOIN dbo.CIC_iCarolImport a
	ON s.ParentAgencyNum=a.ResourceAgencyNum AND a.TaxonomyLevelName='Agency' AND a.LangID=s.LangID
WHERE s.TaxonomyLevelName='Site'
) AS src
ON src.ResourceAgencyNum=dst.ResourceAgencyNum AND src.LangID=dst.LangID AND src.TaxonomyLevelName = 'Site'
WHEN MATCHED AND src.SYNC_DATE > dst.DATE_MODIFIED THEN 
	UPDATE SET 
		[PublicName]=src.[PublicName],
		[AlternateName]=src.[AlternateName],
		[OfficialName]=src.[OfficialName],
		[TaxonomyLevelName]=src.[TaxonomyLevelName],
		[ParentAgency]=src.[ParentAgency],
		[ParentAgencyNum]=src.[ParentAgencyNum],
		[RECORD_OWNER]=LEFT(src.[RECORD_OWNER], 3),
		[UniqueIDPriorSystem]=src.[UniqueIDPriorSystem],
		[MailingAttentionName]=src.[MailingAttentionName],
		[MailingAddress1]=src.[MailingAddress1],
		[MailingAddress2]=src.[MailingAddress2],
		[MailingCity]=src.[MailingCity],
		[MailingCommunity]=src.[MailingCommunity],
		[MailingStateProvince]=src.[MailingStateProvince],
		[MailingPostalCode]=src.[MailingPostalCode],
		[MailingCountry]=src.[MailingCountry],
		[MailingAddressIsPrivate]=src.[MailingAddressIsPrivate],
		[PhysicalAddress1]=src.[PhysicalAddress1],
		[PhysicalAddress2]=src.[PhysicalAddress2],
		[PhysicalCity]=src.[PhysicalCity],
		[PhysicalCounty]=src.[PhysicalCounty],
		[PhysicalCommunity]=src.[PhysicalCommunity],
		[PhysicalStateProvince]=src.[PhysicalStateProvince],
		[PhysicalPostalCode]=src.[PhysicalPostalCode],
		[PhysicalCountry]=src.[PhysicalCountry],
		[PhysicalAddressIsPrivate]=src.[PhysicalAddressIsPrivate],
		[OtherAddress1]=src.[OtherAddress1],
		[OtherAddress2]=src.[OtherAddress2],
		[OtherCity]=src.[OtherCity],
		[OtherCounty]=src.[OtherCounty],
		[OtherCommunity]=src.[OtherCommunity],
		[OtherStateProvince]=src.[OtherStateProvince],
		[OtherPostalCode]=src.[OtherPostalCode],
		[OtherCountry]=src.[OtherCountry],
		[Latitude]=src.[Latitude],
		[Longitude]=src.[Longitude],
		[HoursOfOperation]=src.[HoursOfOperation],
		[Phone1Number]=src.[Phone1Number],
		[Phone1Name]=src.[Phone1Name],
		[Phone1Description]=src.[Phone1Description],
		[Phone1IsPrivate]=src.[Phone1IsPrivate],
		[Phone1Type]=src.[Phone1Type],
		[Phone2Number]=src.[Phone2Number],
		[Phone2Name]=src.[Phone2Name],
		[Phone2Description]=src.[Phone2Description],
		[Phone2IsPrivate]=src.[Phone2IsPrivate],
		[Phone2Type]=src.[Phone2Type],
		[Phone3Number]=src.[Phone3Number],
		[Phone3Name]=src.[Phone3Name],
		[Phone3Description]=src.[Phone3Description],
		[Phone3IsPrivate]=src.[Phone3IsPrivate],
		[Phone3Type]=src.[Phone3Type],
		[Phone4Number]=src.[Phone4Number],
		[Phone4Name]=src.[Phone4Name],
		[Phone4Description]=src.[Phone4Description],
		[Phone4IsPrivate]=src.[Phone4IsPrivate],
		[Phone4Type]=src.[Phone4Type],
		[Phone5Number]=src.[Phone5Number],
		[Phone5name]=src.[Phone5name],
		[Phone5Description]=src.[Phone5Description],
		[Phone5IsPrivate]=src.[Phone5IsPrivate],
		[Phone5Type]=src.[Phone5Type],
		[PhoneFax]=src.[PhoneFax],
		[PhoneFaxDescription]=src.[PhoneFaxDescription],
		[PhoneFaxIsPrivate]=src.[PhoneFaxIsPrivate],
		[PhoneTTY]=src.[PhoneTTY],
		[PhoneTTYDescription]=src.[PhoneTTYDescription],
		[PhoneTTYIsPrivate]=src.[PhoneTTYIsPrivate],
		[PhoneTollFree]=src.[PhoneTollFree],
		[PhoneTollFreeDescription]=src.[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate]=src.[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline]=src.[PhoneNumberHotline],
		[PhoneNumberHotlineDescription]=src.[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate]=src.[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine]=src.[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription]=src.[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate]=src.[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea]=src.[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription]=src.[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate]=src.[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours]=src.[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription]=src.[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate]=src.[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain]=src.[EmailAddressMain],
		[WebsiteAddress]=src.[WebsiteAddress],
		[AgencyStatus]=src.[AgencyStatus],
		[AgencyClassification]=src.[AgencyClassification],
		[CoverageArea]=src.[CoverageArea],
		[CoverageAreaText]=src.[CoverageAreaText],
		[Eligibility]=src.[Eligibility],
		[EligibilityAdult]=src.[EligibilityAdult],
		[EligibilityChild]=src.[EligibilityChild],
		[EligibilityFamily]=src.[EligibilityFamily],
		[EligibilityFemale]=src.[EligibilityFemale],
		[EligibilityMale]=src.[EligibilityMale],
		[EligibilityTeen]=src.[EligibilityTeen],
		[SeniorWorkerName]=src.[SeniorWorkerName],
		[SeniorWorkerTitle]=src.[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress]=src.[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber]=src.[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate]=src.[SeniorWorkerIsPrivate],
		[MainContactName]=src.[MainContactName],
		[MainContactTitle]=src.[MainContactTitle],
		[MainContactEmailAddress]=src.[MainContactEmailAddress],
		[MainContactPhoneNumber]=src.[MainContactPhoneNumber],
		[MainContactType]=src.[MainContactType],
		[MainContactIsPrivate]=src.[MainContactIsPrivate],
		[LicenseAccreditation]=src.[LicenseAccreditation],
		[YearIncorporated]=src.[YearIncorporated],
		[AnnualBudgetTotal]=src.[AnnualBudgetTotal],
		[LegalStatus]=src.[LegalStatus],
		[SourceOfFunds]=src.[SourceOfFunds],
		[ExcludeFromWebsite]=src.[ExcludeFromWebsite],
		[ExcludeFromDirectory]=src.[ExcludeFromDirectory],
		[DisabilitiesAccess]=src.[DisabilitiesAccess],
		[PhysicalLocationDescription]=src.[PhysicalLocationDescription],
		[BusServiceAccess]=src.[BusServiceAccess],
		[PublicAccessTransportation]=src.[PublicAccessTransportation],
		[PaymentMethods]=src.[PaymentMethods],
		[FeeStructureSource]=src.[FeeStructureSource],
		[ApplicationProcess]=src.[ApplicationProcess],
		[ResourceInfo]=src.[ResourceInfo],
		[DocumentsRequired]=src.[DocumentsRequired],
		[LanguagesOffered]=src.[LanguagesOffered],
		[LanguagesOfferedList]=src.[LanguagesOfferedList],
		[AvailabilityNumberOfTimes]=src.[AvailabilityNumberOfTimes],
		[AvailabilityFrequency]=src.[AvailabilityFrequency],
		[AvailabilityPeriod]=src.[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability]=src.[ServiceNotAlwaysAvailability],
		[CapacityType]=src.[CapacityType],
		[ServiceCapacity]=src.[ServiceCapacity],
		[NormalWaitTime]=src.[NormalWaitTime],
		[TemporaryMessage]=src.[TemporaryMessage],
		[TemporaryMessageAppears]=src.[TemporaryMessageAppears],
		[TemporaryMessageExpires]=src.[TemporaryMessageExpires],
		[EnteredOn]=src.[EnteredOn],
		[UpdatedOn]=src.[UpdatedOn],
		[MadeInactiveOn]=src.[MadeInactiveOn],
		[InternalNotes]=src.[InternalNotes],
		[InternalNotesForEditorsAndViewers]=src.[InternalNotesForEditorsAndViewers],
		[HighlightedResource]=src.[HighlightedResource],
		[LastVerifiedOn]=src.[LastVerifiedOn],
		[LastVerifiedByName]=src.[LastVerifiedByName],
		[LastVerifiedByTitle]=src.[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber]=src.[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress]=src.[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy]=src.[LastVerificationApprovedBy],
		[AvailableForDirectory]=src.[AvailableForDirectory],
		[AvailableForReferral]=src.[AvailableForReferral],
		[AvailableForResearch]=src.[AvailableForResearch],
		[PreferredProvider]=src.[PreferredProvider],
		[ConnectsToSiteNum]=src.[ConnectsToSiteNum],
		[ConnectsToProgramNum]=src.[ConnectsToProgramNum],
		[LanguageOfRecord]=src.[LanguageOfRecord],
		[CurrentWorkflowStepCode]=src.[CurrentWorkflowStepCode],
		[VolunteerOpportunities]=src.[VolunteerOpportunities],
		[VolunteerDuties]=src.[VolunteerDuties],
		[IsLinkOnly]=src.[IsLinkOnly],
		[ProgramAgencyNamePublic]=src.[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic]=src.[SiteAgencyNamePublic],
		[Categories]=src.[Categories],
		[TaxonomyTerm]=src.[TaxonomyTerm],
		[TaxonomyTerms]=src.[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated]=src.[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes]=src.[TaxonomyCodes],
		[Coverage]=src.[Coverage],
		[Hours]=src.[Hours],
		[Custom_Public Comments]=src.[Custom_Public Comments],
		[Custom_Former Names]=src.[Custom_Former Names],
		[Custom_Legal Name]=src.[Custom_Legal Name],
		[Custom_Facebook]=src.[Custom_Facebook],
		[Custom_Instagram]=src.[Custom_Instagram],
		[Custom_LinkedIn]=src.[Custom_LinkedIn],
		[Custom_Twitter]=src.[Custom_Twitter],
		[Custom_YouTube]=src.[Custom_YouTube],
		[Custom_Minimum Age]=src.[Custom_Minimum Age],
		[Custom_Maximum Age]=src.[Custom_Maximum Age],
		[dst].[DATE_MODIFIED]=GETDATE(),
		ORG_LEVEL_1=src.ORG_LEVEL_1,
		ORG_DESCRIPTION=src.ORG_DESCRIPTION,
		LOCATION_NAME=src.LOCATION_NAME,
		LOCATION_DESCRIPTION=src.LOCATION_DESCRIPTION,
		dst.ORG_LOCATION_SERVICE='SITE',
		dst.DELETION_DATE=src.DELETION_DATE,
		dst.SOFT_DELETION_DATE=CASE WHEN src.[Custom_Deleted Record] = 'yes' THEN COALESCE(dst.SOFT_DELETION_DATE,GETDATE()) ELSE NULL END,
		dst.[Custom_Deleted Record]=src.[Custom_Deleted Record]
WHEN NOT MATCHED BY TARGET AND src.TaxonomyLevelName='Site' THEN
	INSERT (
		[ResourceAgencyNum],
		[LangID],
		[PublicName],
		[AlternateName],
		[OfficialName],
		[TaxonomyLevelName],
		[ParentAgency],
		[ParentAgencyNum],
		[RECORD_OWNER],
		[UniqueIDPriorSystem],
		[MailingAttentionName],
		[MailingAddress1],
		[MailingAddress2],
		[MailingCity],
		[MailingCommunity],
		[MailingStateProvince],
		[MailingPostalCode],
		[MailingCountry],
		[MailingAddressIsPrivate],
		[PhysicalAddress1],
		[PhysicalAddress2],
		[PhysicalCity],
		[PhysicalCounty],
		[PhysicalCommunity],
		[PhysicalStateProvince],
		[PhysicalPostalCode],
		[PhysicalCountry],
		[PhysicalAddressIsPrivate],
		[OtherAddress1],
		[OtherAddress2],
		[OtherCity],
		[OtherCounty],
		[OtherCommunity],
		[OtherStateProvince],
		[OtherPostalCode],
		[OtherCountry],
		[Latitude],
		[Longitude],
		[HoursOfOperation],
		[Phone1Number],
		[Phone1Name],
		[Phone1Description],
		[Phone1IsPrivate],
		[Phone1Type],
		[Phone2Number],
		[Phone2Name],
		[Phone2Description],
		[Phone2IsPrivate],
		[Phone2Type],
		[Phone3Number],
		[Phone3Name],
		[Phone3Description],
		[Phone3IsPrivate],
		[Phone3Type],
		[Phone4Number],
		[Phone4Name],
		[Phone4Description],
		[Phone4IsPrivate],
		[Phone4Type],
		[Phone5Number],
		[Phone5name],
		[Phone5Description],
		[Phone5IsPrivate],
		[Phone5Type],
		[PhoneFax],
		[PhoneFaxDescription],
		[PhoneFaxIsPrivate],
		[PhoneTTY],
		[PhoneTTYDescription],
		[PhoneTTYIsPrivate],
		[PhoneTollFree],
		[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline],
		[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain],
		[WebsiteAddress],
		[AgencyStatus],
		[AgencyClassification],
		[CoverageArea],
		[CoverageAreaText],
		[Eligibility],
		[EligibilityAdult],
		[EligibilityChild],
		[EligibilityFamily],
		[EligibilityFemale],
		[EligibilityMale],
		[EligibilityTeen],
		[SeniorWorkerName],
		[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate],
		[MainContactName],
		[MainContactTitle],
		[MainContactEmailAddress],
		[MainContactPhoneNumber],
		[MainContactType],
		[MainContactIsPrivate],
		[LicenseAccreditation],
		[YearIncorporated],
		[AnnualBudgetTotal],
		[LegalStatus],
		[SourceOfFunds],
		[ExcludeFromWebsite],
		[ExcludeFromDirectory],
		[DisabilitiesAccess],
		[PhysicalLocationDescription],
		[BusServiceAccess],
		[PublicAccessTransportation],
		[PaymentMethods],
		[FeeStructureSource],
		[ApplicationProcess],
		[ResourceInfo],
		[DocumentsRequired],
		[LanguagesOffered],
		[LanguagesOfferedList],
		[AvailabilityNumberOfTimes],
		[AvailabilityFrequency],
		[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability],
		[CapacityType],
		[ServiceCapacity],
		[NormalWaitTime],
		[TemporaryMessage],
		[TemporaryMessageAppears],
		[TemporaryMessageExpires],
		[EnteredOn],
		[UpdatedOn],
		[MadeInactiveOn],
		[InternalNotes],
		[InternalNotesForEditorsAndViewers],
		[HighlightedResource],
		[LastVerifiedOn],
		[LastVerifiedByName],
		[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy],
		[AvailableForDirectory],
		[AvailableForReferral],
		[AvailableForResearch],
		[PreferredProvider],
		[ConnectsToSiteNum],
		[ConnectsToProgramNum],
		[LanguageOfRecord],
		[CurrentWorkflowStepCode],
		[VolunteerOpportunities],
		[VolunteerDuties],
		[IsLinkOnly],
		[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic],
		[Categories],
		[TaxonomyTerm],
		[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes],
		[Coverage],
		[Hours],
		[Custom_Public Comments],
		[Custom_Former Names],
		[Custom_Legal Name],
		[Custom_Facebook],
		[Custom_Instagram],
		[Custom_LinkedIn],
		[Custom_Twitter],
		[Custom_YouTube],
		[Custom_Minimum Age],
		[Custom_Maximum Age],
		[DATE_MODIFIED],
		ORG_LEVEL_1,
		ORG_DESCRIPTION,
		LOCATION_NAME,
		LOCATION_DESCRIPTION,
		ORG_LOCATION_SERVICE,
		DELETION_DATE,
		SOFT_DELETION_DATE,
		[Custom_Deleted Record]
	) VALUES (
		src.[ResourceAgencyNum],
		src.LangID,
		src.[PublicName],
		src.[AlternateName],
		src.[OfficialName],
		src.[TaxonomyLevelName],
		src.[ParentAgency],
		src.[ParentAgencyNum],
		LEFT(src.[RECORD_OWNER], 3),
		src.[UniqueIDPriorSystem],
		src.[MailingAttentionName],
		src.[MailingAddress1],
		src.[MailingAddress2],
		src.[MailingCity],
		src.[MailingCommunity],
		src.[MailingStateProvince],
		src.[MailingPostalCode],
		src.[MailingCountry],
		src.[MailingAddressIsPrivate],
		src.[PhysicalAddress1],
		src.[PhysicalAddress2],
		src.[PhysicalCity],
		src.[PhysicalCounty],
		src.[PhysicalCommunity],
		src.[PhysicalStateProvince],
		src.[PhysicalPostalCode],
		src.[PhysicalCountry],
		src.[PhysicalAddressIsPrivate],
		src.[OtherAddress1],
		src.[OtherAddress2],
		src.[OtherCity],
		src.[OtherCounty],
		src.[OtherCommunity],
		src.[OtherStateProvince],
		src.[OtherPostalCode],
		src.[OtherCountry],
		src.[Latitude],
		src.[Longitude],
		src.[HoursOfOperation],
		src.[Phone1Number],
		src.[Phone1Name],
		src.[Phone1Description],
		src.[Phone1IsPrivate],
		src.[Phone1Type],
		src.[Phone2Number],
		src.[Phone2Name],
		src.[Phone2Description],
		src.[Phone2IsPrivate],
		src.[Phone2Type],
		src.[Phone3Number],
		src.[Phone3Name],
		src.[Phone3Description],
		src.[Phone3IsPrivate],
		src.[Phone3Type],
		src.[Phone4Number],
		src.[Phone4Name],
		src.[Phone4Description],
		src.[Phone4IsPrivate],
		src.[Phone4Type],
		src.[Phone5Number],
		src.[Phone5name],
		src.[Phone5Description],
		src.[Phone5IsPrivate],
		src.[Phone5Type],
		src.[PhoneFax],
		src.[PhoneFaxDescription],
		src.[PhoneFaxIsPrivate],
		src.[PhoneTTY],
		src.[PhoneTTYDescription],
		src.[PhoneTTYIsPrivate],
		src.[PhoneTollFree],
		src.[PhoneTollFreeDescription],
		src.[PhoneTollFreeIsPrivate],
		src.[PhoneNumberHotline],
		src.[PhoneNumberHotlineDescription],
		src.[PhoneNumberHotlineIsPrivate],
		src.[PhoneNumberBusinessLine],
		src.[PhoneNumberBusinessLineDescription],
		src.[PhoneNumberBusinessLineIsPrivate],
		src.[PhoneNumberOutOfArea],
		src.[PhoneNumberOutOfAreaDescription],
		src.[PhoneNumberOutOfAreaIsPrivate],
		src.[PhoneNumberAfterHours],
		src.[PhoneNumberAfterHoursDescription],
		src.[PhoneNumberAfterHoursIsPrivate],
		src.[EmailAddressMain],
		src.[WebsiteAddress],
		src.[AgencyStatus],
		src.[AgencyClassification],
		src.[CoverageArea],
		src.[CoverageAreaText],
		src.[Eligibility],
		src.[EligibilityAdult],
		src.[EligibilityChild],
		src.[EligibilityFamily],
		src.[EligibilityFemale],
		src.[EligibilityMale],
		src.[EligibilityTeen],
		src.[SeniorWorkerName],
		src.[SeniorWorkerTitle],
		src.[SeniorWorkerEmailAddress],
		src.[SeniorWorkerPhoneNumber],
		src.[SeniorWorkerIsPrivate],
		src.[MainContactName],
		src.[MainContactTitle],
		src.[MainContactEmailAddress],
		src.[MainContactPhoneNumber],
		src.[MainContactType],
		src.[MainContactIsPrivate],
		src.[LicenseAccreditation],
		src.[YearIncorporated],
		src.[AnnualBudgetTotal],
		src.[LegalStatus],
		src.[SourceOfFunds],
		src.[ExcludeFromWebsite],
		src.[ExcludeFromDirectory],
		src.[DisabilitiesAccess],
		src.[PhysicalLocationDescription],
		src.[BusServiceAccess],
		src.[PublicAccessTransportation],
		src.[PaymentMethods],
		src.[FeeStructureSource],
		src.[ApplicationProcess],
		src.[ResourceInfo],
		src.[DocumentsRequired],
		src.[LanguagesOffered],
		src.[LanguagesOfferedList],
		src.[AvailabilityNumberOfTimes],
		src.[AvailabilityFrequency],
		src.[AvailabilityPeriod],
		src.[ServiceNotAlwaysAvailability],
		src.[CapacityType],
		src.[ServiceCapacity],
		src.[NormalWaitTime],
		src.[TemporaryMessage],
		src.[TemporaryMessageAppears],
		src.[TemporaryMessageExpires],
		src.[EnteredOn],
		src.[UpdatedOn],
		src.[MadeInactiveOn],
		src.[InternalNotes],
		src.[InternalNotesForEditorsAndViewers],
		src.[HighlightedResource],
		src.[LastVerifiedOn],
		src.[LastVerifiedByName],
		src.[LastVerifiedByTitle],
		src.[LastVerifiedByPhoneNumber],
		src.[LastVerifiedByEmailAddress],
		src.[LastVerificationApprovedBy],
		src.[AvailableForDirectory],
		src.[AvailableForReferral],
		src.[AvailableForResearch],
		src.[PreferredProvider],
		src.[ConnectsToSiteNum],
		src.[ConnectsToProgramNum],
		src.[LanguageOfRecord],
		src.[CurrentWorkflowStepCode],
		src.[VolunteerOpportunities],
		src.[VolunteerDuties],
		src.[IsLinkOnly],
		src.[ProgramAgencyNamePublic],
		src.[SiteAgencyNamePublic],
		src.[Categories],
		src.[TaxonomyTerm],
		src.[TaxonomyTerms],
		src.[TaxonomyTermsNotDeactivated],
		src.[TaxonomyCodes],
		src.[Coverage],
		src.[Hours],
		src.[Custom_Public Comments],
		src.[Custom_Former Names],
		src.[Custom_Legal Name],
		src.[Custom_Facebook],
		src.[Custom_Instagram],
		src.[Custom_LinkedIn],
		src.[Custom_Twitter],
		src.[Custom_YouTube],
		src.[Custom_Minimum Age],
		src.[Custom_Maximum Age],
		GETDATE(),
		src.ORG_LEVEL_1,
		src.ORG_DESCRIPTION,
		src.LOCATION_NAME,
		src.LOCATION_DESCRIPTION,
		'SITE',
		src.DELETION_DATE,
		CASE WHEN src.[Custom_Deleted Record] = 'yes' THEN GETDATE() ELSE NULL END,
		src.[Custom_Deleted Record]
	)
OPTION (ROBUST PLAN)
	;

SELECT m.MemberID, m.DefaultEmailNameCIC, m.BaseURLCIC, m.ImportNotificationEmailCIC
FROM dbo.STP_Member m WHERE m.Active=1


RETURN @Error

SET NOCOUNT OFF



GO
GRANT EXECUTE ON  [dbo].[sp_CIC_iCarolImport_Rollup] TO [cioc_login_role]
GO
