SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_GBL_NUMContractSignature_s]
	@NUM varchar(8)
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.1
	Checked by: KL
	Checked on: 18-Jan-2012
	Action: NO ACTION REQUIRED
*/

SELECT *
	FROM GBL_BT_CONTRACTSIGNATURE
WHERE NUM=@NUM
ORDER BY CASE WHEN DATE IS NULL THEN 1 ELSE 0 END, DATE

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_GBL_NUMContractSignature_s] TO [cioc_login_role]
GO
