SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[sp_CIC_iCarolExport_Prep]
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

DECLARE @DistCode NVARCHAR(20)
SET @DistCode = 'AIRSEXPORT-O211-'

DECLARE @DST_ID INT
IF @DistCode IS NOT NULL BEGIN
	SELECT @DST_ID=DST_ID FROM dbo.CIC_Distribution WHERE DistCode=@DistCode
	SET @DST_ID=ISNULL(@DST_ID,-1)
END

DECLARE @CodeMatch NVARCHAR(20)
SET @CodeMatch = REPLACE((SELECT DistCode FROM dbo.CIC_Distribution WHERE DST_ID=@DST_ID),'AIRSEXPORT-','')

IF LEN(@CodeMatch) > 2 BEGIN
	MERGE INTO dbo.CIC_BT_DST dst
	USING (SELECT DISTINCT bt.NUM
		FROM dbo.GBL_BaseTable bt
		INNER JOIN dbo.CIC_BT_PB pr
			ON pr.NUM = bt.NUM
		INNER JOIN dbo.CIC_Publication pb
			ON pr.PB_ID=pb.PB_ID
				AND pb.PubCode LIKE @CodeMatch + '%'
		WHERE bt.SOURCE_FROM_ICAROL=0
		AND NOT EXISTS(
			SELECT *
			FROM dbo.CIC_BT_PB pr2
			INNER JOIN dbo.CIC_Publication pb2
				ON pr2.PB_ID=pb2.PB_ID
					AND pb2.PubCode LIKE 'EX-' + @CodeMatch + '%'
			WHERE pr2.NUM=pr.NUM
		)
	) src
		ON dst.NUM=src.NUM AND dst.DST_ID=@DST_ID
	WHEN NOT MATCHED BY TARGET THEN
		INSERT (NUM, DST_ID) VALUES (src.NUM, @DST_ID)
	WHEN NOT MATCHED BY SOURCE AND dst.DST_ID=@DST_ID THEN
		DELETE
	;
END

UPDATE ols
	SET ols.QUEUE_FOR_EXPORT=1
FROM dbo.GBL_BT_OLS ols
INNER JOIN dbo.GBL_BaseTable bt ON bt.NUM = ols.NUM
INNER JOIN dbo.GBL_BaseTable_Description btd ON btd.NUM = bt.NUM AND btd.LangID=0 AND (btd.DELETION_DATE IS NULL OR btd.DELETION_DATE > ISNULL(ols.EXPORT_DATE,GETDATE()))
INNER JOIN dbo.CIC_BT_DST dst ON dst.NUM = bt.NUM AND dst.DST_ID=@DST_ID
WHERE ols.EXTERNAL_ID IS NOT NULL AND (GREATEST(bt.MODIFIED_DATE,btd.MODIFIED_DATE,dst.CREATED_DATE) > ols.EXPORT_DATE OR ols.EXPORT_DATE IS NULL)

DECLARE @SinceDate DATE
SELECT @SinceDate = ISNULL(MIN(EXPORT_DATE),GETDATE()) FROM dbo.GBL_BT_OLS WHERE QUEUE_FOR_EXPORT=1 AND EXTERNAL_ID IS NULL

DECLARE @CoverageAreaFieldID INT
SELECT @CoverageAreaFieldID=FieldID FROM dbo.GBL_FieldOption WHERE FieldName='AREAS_SERVED'

DECLARE @CoverageAreaChanges TABLE (
	HST_ID INT NOT NULL PRIMARY KEY,
	NUM VARCHAR(8) NOT NULL,
	LangID SMALLINT NOT NULL,
	MODIFIED_DATE SMALLDATETIME NULL
)

INSERT INTO @CoverageAreaChanges
(
    HST_ID,
    NUM,
    LangID,
    MODIFIED_DATE
)
SELECT h.HST_ID, h.NUM, h.LangID, h.MODIFIED_DATE
	FROM dbo.GBL_BaseTable_History h
WHERE FieldID=@CoverageAreaFieldID AND h.MODIFIED_DATE > @SinceDate
		AND EXISTS(SELECT * FROM dbo.GBL_BT_OLS ols WHERE ols.NUM=h.NUM AND ols.QUEUE_FOR_EXPORT=1 AND ols.EXTERNAL_ID IS NOT NULL)

INSERT INTO @CoverageAreaChanges
(
    HST_ID,
    NUM,
    LangID,
    MODIFIED_DATE
)
SELECT h.HST_ID, h.NUM, h.LangID, h.MODIFIED_DATE
	FROM dbo.GBL_BaseTable_History h
WHERE FieldID=@CoverageAreaFieldID
		AND EXISTS(SELECT * FROM dbo.GBL_BT_OLS ols WHERE ols.NUM=h.NUM AND ols.QUEUE_FOR_EXPORT=1 AND ols.EXTERNAL_ID IS NULL)

DELETE c
FROM @CoverageAreaChanges c
WHERE EXISTS(SELECT * FROM @CoverageAreaChanges c2 WHERE c2.HST_ID<>c.HST_ID AND c2.NUM=c.NUM AND c2.LangID=c.LangID AND c2.MODIFIED_DATE>c.MODIFIED_DATE)

SELECT h.NUM, h.LangID, cioc_shared.dbo.fn_SHR_GBL_DateString(h.MODIFIED_DATE) AS MODIFIED_DATE, h.MODIFIED_BY, ISNULL(h.FieldDisplay,'[NULL / MISSING]') AS AREAS_SERVED, dbo.fn_GBL_DisplayFullOrgName(h.NUM, h.LangID) AS ORG_NAME_FULL
	FROM dbo.GBL_BaseTable_History h
	INNER JOIN @CoverageAreaChanges cac ON h.HST_ID=cac.HST_ID
ORDER BY h.MODIFIED_DATE

SET NOCOUNT OFF

GO
