SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_CIC_NUMOtherAddress_l]
	@NUM varchar(8)
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.1
	Checked by: KL
	Checked on: 18-Jan-2012
	Action: NO ACTION REQUIRED
*/

SELECT ADDR_ID, CASE
	WHEN TITLE IS NOT NULL OR SITE_CODE IS NOT NULL
		THEN  '[ '
			+ CASE WHEN TITLE IS NOT NULL THEN + TITLE + CASE WHEN SITE_CODE IS NOT NULL THEN ' ; ' ELSE '' END ELSE '' END
			+ CASE WHEN SITE_CODE IS NOT NULL THEN cioc_shared.dbo.fn_SHR_STP_ObjectName('Site Code') + cioc_shared.dbo.fn_SHR_STP_ObjectName(': ') + SITE_CODE ELSE '' END
			+ ' ] '
		ELSE ''
	END + dbo.fn_GBL_FullAddress(NUM,NULL,NULL,STREET_NUMBER,STREET,STREET_TYPE,STREET_TYPE_AFTER,STREET_DIR,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,LangID,0) AS Display
FROM CIC_BT_OTHERADDRESS
WHERE NUM=@NUM AND LangID=@@LANGID
ORDER BY TITLE

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_CIC_NUMOtherAddress_l] TO [cioc_login_role]
GO
