SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_GBL_UCheck_NUM]
	@RSN int,
	@NUM varchar(8) OUTPUT,
	@EXTERNAL_ID varchar(50),
	@AgencyCode char(3)
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.5.2
	Checked by: KL
	Checked on: 20-Dec-2013
	Action: NO ACTION REQUIRED
*/

IF @NUM IS NULL AND @AgencyCode IS NOT NULL BEGIN
	SELECT @NUM = dbo.fn_GBL_LowestUnusedNUM(@AgencyCode)
END

IF @RSN IS NULL AND @EXTERNAL_ID IS NULL BEGIN
	IF EXISTS(SELECT * FROM GBL_BaseTable WHERE NUM=@NUM)
		RETURN 1
	ELSE
		RETURN 0
END ELSE IF @RSN IS NOT NULL BEGIN
	IF EXISTS(SELECT * FROM GBL_BaseTable WHERE NUM=@NUM AND RSN<>@RSN)
		RETURN 1
	ELSE
		RETURN 0
END ELSE BEGIN
	SET @NUM = NULL
	SELECT @NUM=NUM FROM GBL_BaseTable WHERE EXTERNAL_ID=@EXTERNAL_ID
	IF @NUM IS NOT NULL
		RETURN 1
	ELSE
		RETURN 0
END

SET NOCOUNT OFF

GO
GRANT EXECUTE ON  [dbo].[sp_GBL_UCheck_NUM] TO [cioc_login_role]
GO
