SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_VOL_VNUMSetTRPIDs_u]
	@VNUM varchar(10),
	@IdList varchar(max)
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.6
	Checked by: CL
	Checked on: 27-Sep-2014
	Action: TESTING REQUIRED
*/

DECLARE @tmpTRPIDs TABLE(TRP_ID int)

INSERT INTO @tmpTRPIDs SELECT DISTINCT tm.*
	FROM dbo.fn_GBL_ParseIntIDList(@IdList,',') tm
	INNER JOIN VOL_Transportation trp
		ON tm.ItemID=trp.TRP_ID

DELETE pr

	FROM VOL_OP_TRP pr
	LEFT JOIN @tmpTRPIDs tm
		ON pr.TRP_ID = tm.TRP_ID
WHERE tm.TRP_ID IS NULL AND VNUM=@VNUM

INSERT INTO VOL_OP_TRP (VNUM, TRP_ID) SELECT VNUM=@VNUM, tm.TRP_ID
	FROM @tmpTRPIDs tm
WHERE NOT EXISTS(SELECT * FROM VOL_OP_TRP pr WHERE VNUM=@VNUM AND pr.TRP_ID=tm.TRP_ID)

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_VOL_VNUMSetTRPIDs_u] TO [cioc_login_role]
GO
