SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_CIC_ProcessFb]
	@NUM varchar(8),
	@FB_ID int,
	@LangID smallint
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.8
	Checked by: CL
	Checked on: 17-Sept-2017
	Action: NO ACTION REQUIRED
	Notes: DO WE NEED TO BETTER MANAGE CASES WHERE VIEWTYPE IS NOT KNOWN, ESP IF NO ACCESS URL?
*/
IF @FB_ID IS NOT NULL AND @NUM IS NOT NULL BEGIN
	UPDATE GBL_FeedbackEntry SET NUM=@NUM WHERE FB_ID=@FB_ID AND NUM IS NULL
END

SELECT DISTINCT
		CASE WHEN fbe.FBKEY=bt.FBKEY THEN fbe.FBKEY ELSE NULL END AS FBKEY,
		fbe.SOURCE_EMAIL, fbe.AccessURL, fbe.ViewType,
		dbo.fn_CIC_RecordInView(bt.NUM,
			ISNULL(fbe.ViewType,
				ISNULL((SELECT CICViewType FROM GBL_View_DomainMap WHERE DomainName=AccessURL),
					(SELECT DefaultViewCIC FROM STP_Member WHERE MemberID=fbe.MemberID))
				),
			@LangID,0,GETDATE()) AS IN_VIEW
	FROM GBL_FeedbackEntry fbe
	INNER JOIN GBL_BaseTable bt
		ON fbe.NUM=bt.NUM
WHERE fbe.[User_ID] IS NULL
	AND fbe.SOURCE_EMAIL IS NOT NULL
	AND fbe.LangID=@LangID
	AND (@FB_ID IS NULL AND fbe.NUM=@NUM) OR (@FB_ID IS NOT NULL AND fbe.FB_ID=@FB_ID)

SET NOCOUNT OFF




GO

GRANT EXECUTE ON  [dbo].[sp_CIC_ProcessFb] TO [cioc_login_role]
GO
