SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_GBL_NUMCrossRef_s]
	@NUM varchar(8),
	@LangID smallint
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.1
	Checked by: KL
	Checked on: 18-Jan-2012
	Action: NO ACTION REQUIRED
*/

SELECT BT_AO_ID, ALT_ORG, PUBLISH
	FROM GBL_BT_ALTORG
WHERE LangID=@LangID AND NUM=@NUM

SELECT BT_FO_ID, FORMER_ORG, PUBLISH
	FROM GBL_BT_FORMERORG
WHERE LangID=@LangID AND NUM=@NUM

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_GBL_NUMCrossRef_s] TO [cioc_login_role]
GO
