SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_CIC_iCarolImport_Rollup]
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

DECLARE	@Error		INT
SET @Error = 0

MERGE INTO dbo.CIC_iCarolImportRollup dst
USING dbo.CIC_iCarolImport AS src
ON src.ResourceAgencyNum=dst.ResourceAgencyNum AND src.LangID=dst.LangID AND src.TaxonomyLevelName = 'Agency'
WHEN MATCHED AND src.SYNC_DATE > dst.DATE_MODIFIED THEN 
	UPDATE SET 
		[PublicName]=src.[PublicName],
		[AlternateName]=src.[AlternateName],
		[OfficialName]=src.[OfficialName],
		[TaxonomyLevelName]=src.[TaxonomyLevelName],
		[ParentAgency]=src.[ParentAgency],
		[ParentAgencyNum]=src.[ParentAgencyNum],
		[RECORD_OWNER]=src.[Custom_Record Owner (controlled)],
		[UniqueIDPriorSystem]=src.[UniqueIDPriorSystem],
		[MailingAttentionName]=src.[MailingAttentionName],
		[MailingAddress1]=src.[MailingAddress1],
		[MailingAddress2]=src.[MailingAddress2],
		[MailingCity]=src.[MailingCity],
		[MailingStateProvince]=src.[MailingStateProvince],
		[MailingPostalCode]=src.[MailingPostalCode],
		[MailingCountry]=src.[MailingCountry],
		[MailingAddressIsPrivate]=src.[MailingAddressIsPrivate],
		[PhysicalAddress1]=src.[PhysicalAddress1],
		[PhysicalAddress2]=src.[PhysicalAddress2],
		[PhysicalCity]=src.[PhysicalCity],
		[PhysicalCounty]=src.[PhysicalCounty],
		[PhysicalStateProvince]=src.[PhysicalStateProvince],
		[PhysicalPostalCode]=src.[PhysicalPostalCode],
		[PhysicalCountry]=src.[PhysicalCountry],
		[PhysicalAddressIsPrivate]=src.[PhysicalAddressIsPrivate],
		[OtherAddress1]=src.[OtherAddress1],
		[OtherAddress2]=src.[OtherAddress2],
		[OtherCity]=src.[OtherCity],
		[OtherCounty]=src.[OtherCounty],
		[OtherStateProvince]=src.[OtherStateProvince],
		[OtherPostalCode]=src.[OtherPostalCode],
		[OtherCountry]=src.[OtherCountry],
		[Latitude]=NULLIF(src.[Latitude],'0'),
		[Longitude]=NULLIF(src.[Longitude], '0'),
		[HoursOfOperation]=src.[HoursOfOperation],
		[Phone1Number]=src.[Phone1Number],
		[Phone1Name]=src.[Phone1Name],
		[Phone1Description]=src.[Phone1Description],
		[Phone1IsPrivate]=src.[Phone1IsPrivate],
		[Phone1Type]=src.[Phone1Type],
		[Phone2Number]=src.[Phone2Number],
		[Phone2Name]=src.[Phone2Name],
		[Phone2Description]=src.[Phone2Description],
		[Phone2IsPrivate]=src.[Phone2IsPrivate],
		[Phone2Type]=src.[Phone2Type],
		[Phone3Number]=src.[Phone3Number],
		[Phone3Name]=src.[Phone3Name],
		[Phone3Description]=src.[Phone3Description],
		[Phone3IsPrivate]=src.[Phone3IsPrivate],
		[Phone3Type]=src.[Phone3Type],
		[Phone4Number]=src.[Phone4Number],
		[Phone4Name]=src.[Phone4Name],
		[Phone4Description]=src.[Phone4Description],
		[Phone4IsPrivate]=src.[Phone4IsPrivate],
		[Phone4Type]=src.[Phone4Type],
		[Phone5Number]=src.[Phone5Number],
		[Phone5name]=src.[Phone5name],
		[Phone5Description]=src.[Phone5Description],
		[Phone5IsPrivate]=src.[Phone5IsPrivate],
		[Phone5Type]=src.[Phone5Type],
		[PhoneFax]=src.[PhoneFax],
		[PhoneFaxDescription]=src.[PhoneFaxDescription],
		[PhoneFaxIsPrivate]=src.[PhoneFaxIsPrivate],
		[PhoneTTY]=src.[PhoneTTY],
		[PhoneTTYDescription]=src.[PhoneTTYDescription],
		[PhoneTTYIsPrivate]=src.[PhoneTTYIsPrivate],
		[PhoneTollFree]=src.[PhoneTollFree],
		[PhoneTollFreeDescription]=src.[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate]=src.[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline]=src.[PhoneNumberHotline],
		[PhoneNumberHotlineDescription]=src.[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate]=src.[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine]=src.[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription]=src.[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate]=src.[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea]=src.[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription]=src.[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate]=src.[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours]=src.[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription]=src.[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate]=src.[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain]=src.[EmailAddressMain],
		[WebsiteAddress]=src.[WebsiteAddress],
		[AgencyStatus]=src.[AgencyStatus],
		[AgencyClassification]=src.[AgencyClassification],
		[CoverageArea]=src.[CoverageArea],
		[CoverageAreaText]=src.[CoverageAreaText],
		[Eligibility]=src.[Eligibility],
		[EligibilityAdult]=src.[EligibilityAdult],
		[EligibilityChild]=src.[EligibilityChild],
		[EligibilityFamily]=src.[EligibilityFamily],
		[EligibilityFemale]=src.[EligibilityFemale],
		[EligibilityMale]=src.[EligibilityMale],
		[EligibilityTeen]=src.[EligibilityTeen],
		[SeniorWorkerName]=src.[SeniorWorkerName],
		[SeniorWorkerTitle]=src.[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress]=src.[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber]=src.[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate]=src.[SeniorWorkerIsPrivate],
		[MainContactName]=src.[MainContactName],
		[MainContactTitle]=src.[MainContactTitle],
		[MainContactEmailAddress]=src.[MainContactEmailAddress],
		[MainContactPhoneNumber]=src.[MainContactPhoneNumber],
		[MainContactType]=src.[MainContactType],
		[MainContactIsPrivate]=src.[MainContactIsPrivate],
		[LicenseAccreditation]=src.[LicenseAccreditation],
		[YearIncorporated]=src.[YearIncorporated],
		[AnnualBudgetTotal]=src.[AnnualBudgetTotal],
		[LegalStatus]=src.[LegalStatus],
		[SourceOfFunds]=src.[SourceOfFunds],
		[ExcludeFromWebsite]=src.[ExcludeFromWebsite],
		[ExcludeFromDirectory]=src.[ExcludeFromDirectory],
		[DisabilitiesAccess]=src.[DisabilitiesAccess],
		[PhysicalLocationDescription]=src.[PhysicalLocationDescription],
		[BusServiceAccess]=src.[BusServiceAccess],
		[PublicAccessTransportation]=src.[PublicAccessTransportation],
		[PaymentMethods]=src.[PaymentMethods],
		[FeeStructureSource]=src.[FeeStructureSource],
		[ApplicationProcess]=src.[ApplicationProcess],
		[ResourceInfo]=src.[ResourceInfo],
		[DocumentsRequired]=src.[DocumentsRequired],
		[LanguagesOffered]=src.[LanguagesOffered],
		[LanguagesOfferedList]=src.[LanguagesOfferedList],
		[AvailabilityNumberOfTimes]=src.[AvailabilityNumberOfTimes],
		[AvailabilityFrequency]=src.[AvailabilityFrequency],
		[AvailabilityPeriod]=src.[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability]=src.[ServiceNotAlwaysAvailability],
		[CapacityType]=src.[CapacityType],
		[ServiceCapacity]=src.[ServiceCapacity],
		[NormalWaitTime]=src.[NormalWaitTime],
		[TemporaryMessage]=src.[TemporaryMessage],
		[TemporaryMessageAppears]=src.[TemporaryMessageAppears],
		[TemporaryMessageExpires]=src.[TemporaryMessageExpires],
		[EnteredOn]=src.[EnteredOn],
		[UpdatedOn]=src.[UpdatedOn],
		[MadeInactiveOn]=src.[MadeInactiveOn],
		[InternalNotes]=src.[InternalNotes],
		[InternalNotesForEditorsAndViewers]=src.[InternalNotesForEditorsAndViewers],
		[HighlightedResource]=src.[HighlightedResource],
		[LastVerifiedOn]=src.[LastVerifiedOn],
		[LastVerifiedByName]=src.[LastVerifiedByName],
		[LastVerifiedByTitle]=src.[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber]=src.[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress]=src.[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy]=src.[LastVerificationApprovedBy],
		[AvailableForDirectory]=src.[AvailableForDirectory],
		[AvailableForReferral]=src.[AvailableForReferral],
		[AvailableForResearch]=src.[AvailableForResearch],
		[PreferredProvider]=src.[PreferredProvider],
		[ConnectsToSiteNum]=src.[ConnectsToSiteNum],
		[ConnectsToProgramNum]=src.[ConnectsToProgramNum],
		[LanguageOfRecord]=src.[LanguageOfRecord],
		[CurrentWorkflowStepCode]=src.[CurrentWorkflowStepCode],
		[VolunteerOpportunities]=src.[VolunteerOpportunities],
		[VolunteerDuties]=src.[VolunteerDuties],
		[IsLinkOnly]=src.[IsLinkOnly],
		[ProgramAgencyNamePublic]=src.[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic]=src.[SiteAgencyNamePublic],
		[Categories]=src.[Categories],
		[TaxonomyTerm]=src.[TaxonomyTerm],
		[TaxonomyTerms]=src.[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated]=src.[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes]=src.[TaxonomyCodes],
		[Coverage]=src.[Coverage],
		[Hours]=src.[Hours],
		[Custom_Public Comments]=src.[Custom_Public Comments],
		[Custom_Former Names]=src.[Custom_Former Names],
		[Custom_Legal Name]=src.[Custom_Legal Name],
		[Custom_Facebook]=src.[Custom_Facebook],
		[Custom_Instagram]=src.[Custom_Instagram],
		[Custom_LinkedIn]=src.[Custom_LinkedIn],
		[Custom_Twitter]=src.[Custom_Twitter],
		[Custom_YouTube]=src.[Custom_YouTube],
		[Custom_Minimum Age]=src.[Custom_Minimum Age],
		[Custom_Maximum Age]=src.[Custom_Maximum Age],
		[dst].[DATE_MODIFIED]=GETDATE(),
		ORG_LEVEL_1=src.PublicName,
		dst.ORG_DESCRIPTION=src.AgencyDescription,
		dst.ORG_LOCATION_SERVICE='AGENCY',
		dst.DELETION_DATE=src.DELETION_DATE
WHEN NOT MATCHED BY TARGET AND src.TaxonomyLevelName='Agency' THEN
	INSERT (
		[ResourceAgencyNum],
		[LangID],
		[PublicName],
		[AlternateName],
		[OfficialName],
		[TaxonomyLevelName],
		[ParentAgency],
		[ParentAgencyNum],
		[RECORD_OWNER],
		[UniqueIDPriorSystem],
		[MailingAttentionName],
		[MailingAddress1],
		[MailingAddress2],
		[MailingCity],
		[MailingStateProvince],
		[MailingPostalCode],
		[MailingCountry],
		[MailingAddressIsPrivate],
		[PhysicalAddress1],
		[PhysicalAddress2],
		[PhysicalCity],
		[PhysicalCounty],
		[PhysicalStateProvince],
		[PhysicalPostalCode],
		[PhysicalCountry],
		[PhysicalAddressIsPrivate],
		[OtherAddress1],
		[OtherAddress2],
		[OtherCity],
		[OtherCounty],
		[OtherStateProvince],
		[OtherPostalCode],
		[OtherCountry],
		[Latitude],
		[Longitude],
		[HoursOfOperation],
		[Phone1Number],
		[Phone1Name],
		[Phone1Description],
		[Phone1IsPrivate],
		[Phone1Type],
		[Phone2Number],
		[Phone2Name],
		[Phone2Description],
		[Phone2IsPrivate],
		[Phone2Type],
		[Phone3Number],
		[Phone3Name],
		[Phone3Description],
		[Phone3IsPrivate],
		[Phone3Type],
		[Phone4Number],
		[Phone4Name],
		[Phone4Description],
		[Phone4IsPrivate],
		[Phone4Type],
		[Phone5Number],
		[Phone5name],
		[Phone5Description],
		[Phone5IsPrivate],
		[Phone5Type],
		[PhoneFax],
		[PhoneFaxDescription],
		[PhoneFaxIsPrivate],
		[PhoneTTY],
		[PhoneTTYDescription],
		[PhoneTTYIsPrivate],
		[PhoneTollFree],
		[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline],
		[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain],
		[WebsiteAddress],
		[AgencyStatus],
		[AgencyClassification],
		[CoverageArea],
		[CoverageAreaText],
		[Eligibility],
		[EligibilityAdult],
		[EligibilityChild],
		[EligibilityFamily],
		[EligibilityFemale],
		[EligibilityMale],
		[EligibilityTeen],
		[SeniorWorkerName],
		[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate],
		[MainContactName],
		[MainContactTitle],
		[MainContactEmailAddress],
		[MainContactPhoneNumber],
		[MainContactType],
		[MainContactIsPrivate],
		[LicenseAccreditation],
		[YearIncorporated],
		[AnnualBudgetTotal],
		[LegalStatus],
		[SourceOfFunds],
		[ExcludeFromWebsite],
		[ExcludeFromDirectory],
		[DisabilitiesAccess],
		[PhysicalLocationDescription],
		[BusServiceAccess],
		[PublicAccessTransportation],
		[PaymentMethods],
		[FeeStructureSource],
		[ApplicationProcess],
		[ResourceInfo],
		[DocumentsRequired],
		[LanguagesOffered],
		[LanguagesOfferedList],
		[AvailabilityNumberOfTimes],
		[AvailabilityFrequency],
		[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability],
		[CapacityType],
		[ServiceCapacity],
		[NormalWaitTime],
		[TemporaryMessage],
		[TemporaryMessageAppears],
		[TemporaryMessageExpires],
		[EnteredOn],
		[UpdatedOn],
		[MadeInactiveOn],
		[InternalNotes],
		[InternalNotesForEditorsAndViewers],
		[HighlightedResource],
		[LastVerifiedOn],
		[LastVerifiedByName],
		[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy],
		[AvailableForDirectory],
		[AvailableForReferral],
		[AvailableForResearch],
		[PreferredProvider],
		[ConnectsToSiteNum],
		[ConnectsToProgramNum],
		[LanguageOfRecord],
		[CurrentWorkflowStepCode],
		[VolunteerOpportunities],
		[VolunteerDuties],
		[IsLinkOnly],
		[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic],
		[Categories],
		[TaxonomyTerm],
		[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes],
		[Coverage],
		[Hours],
		[Custom_Public Comments],
		[Custom_Former Names],
		[Custom_Legal Name],
		[Custom_Facebook],
		[Custom_Instagram],
		[Custom_LinkedIn],
		[Custom_Twitter],
		[Custom_YouTube],
		[Custom_Minimum Age],
		[Custom_Maximum Age],
		[DATE_MODIFIED],
		ORG_LEVEL_1,
		ORG_DESCRIPTION,
		ORG_LOCATION_SERVICE,
		DELETION_DATE
	) VALUES (
		src.[ResourceAgencyNum],
		src.LangID,
		src.[PublicName],
		src.[AlternateName],
		src.[OfficialName],
		src.[TaxonomyLevelName],
		src.[ParentAgency],
		src.[ParentAgencyNum],
		src.[Custom_Record Owner (controlled)],
		src.[UniqueIDPriorSystem],
		src.[MailingAttentionName],
		src.[MailingAddress1],
		src.[MailingAddress2],
		src.[MailingCity],
		src.[MailingStateProvince],
		src.[MailingPostalCode],
		src.[MailingCountry],
		src.[MailingAddressIsPrivate],
		src.[PhysicalAddress1],
		src.[PhysicalAddress2],
		src.[PhysicalCity],
		src.[PhysicalCounty],
		src.[PhysicalStateProvince],
		src.[PhysicalPostalCode],
		src.[PhysicalCountry],
		src.[PhysicalAddressIsPrivate],
		src.[OtherAddress1],
		src.[OtherAddress2],
		src.[OtherCity],
		src.[OtherCounty],
		src.[OtherStateProvince],
		src.[OtherPostalCode],
		src.[OtherCountry],
		NULLIF(src.[Latitude],'0'),
		NULLIF(src.[Longitude],'0'),
		src.[HoursOfOperation],
		src.[Phone1Number],
		src.[Phone1Name],
		src.[Phone1Description],
		src.[Phone1IsPrivate],
		src.[Phone1Type],
		src.[Phone2Number],
		src.[Phone2Name],
		src.[Phone2Description],
		src.[Phone2IsPrivate],
		src.[Phone2Type],
		src.[Phone3Number],
		src.[Phone3Name],
		src.[Phone3Description],
		src.[Phone3IsPrivate],
		src.[Phone3Type],
		src.[Phone4Number],
		src.[Phone4Name],
		src.[Phone4Description],
		src.[Phone4IsPrivate],
		src.[Phone4Type],
		src.[Phone5Number],
		src.[Phone5name],
		src.[Phone5Description],
		src.[Phone5IsPrivate],
		src.[Phone5Type],
		src.[PhoneFax],
		src.[PhoneFaxDescription],
		src.[PhoneFaxIsPrivate],
		src.[PhoneTTY],
		src.[PhoneTTYDescription],
		src.[PhoneTTYIsPrivate],
		src.[PhoneTollFree],
		src.[PhoneTollFreeDescription],
		src.[PhoneTollFreeIsPrivate],
		src.[PhoneNumberHotline],
		src.[PhoneNumberHotlineDescription],
		src.[PhoneNumberHotlineIsPrivate],
		src.[PhoneNumberBusinessLine],
		src.[PhoneNumberBusinessLineDescription],
		src.[PhoneNumberBusinessLineIsPrivate],
		src.[PhoneNumberOutOfArea],
		src.[PhoneNumberOutOfAreaDescription],
		src.[PhoneNumberOutOfAreaIsPrivate],
		src.[PhoneNumberAfterHours],
		src.[PhoneNumberAfterHoursDescription],
		src.[PhoneNumberAfterHoursIsPrivate],
		src.[EmailAddressMain],
		src.[WebsiteAddress],
		src.[AgencyStatus],
		src.[AgencyClassification],
		src.[CoverageArea],
		src.[CoverageAreaText],
		src.[Eligibility],
		src.[EligibilityAdult],
		src.[EligibilityChild],
		src.[EligibilityFamily],
		src.[EligibilityFemale],
		src.[EligibilityMale],
		src.[EligibilityTeen],
		src.[SeniorWorkerName],
		src.[SeniorWorkerTitle],
		src.[SeniorWorkerEmailAddress],
		src.[SeniorWorkerPhoneNumber],
		src.[SeniorWorkerIsPrivate],
		src.[MainContactName],
		src.[MainContactTitle],
		src.[MainContactEmailAddress],
		src.[MainContactPhoneNumber],
		src.[MainContactType],
		src.[MainContactIsPrivate],
		src.[LicenseAccreditation],
		src.[YearIncorporated],
		src.[AnnualBudgetTotal],
		src.[LegalStatus],
		src.[SourceOfFunds],
		src.[ExcludeFromWebsite],
		src.[ExcludeFromDirectory],
		src.[DisabilitiesAccess],
		src.[PhysicalLocationDescription],
		src.[BusServiceAccess],
		src.[PublicAccessTransportation],
		src.[PaymentMethods],
		src.[FeeStructureSource],
		src.[ApplicationProcess],
		src.[ResourceInfo],
		src.[DocumentsRequired],
		src.[LanguagesOffered],
		src.[LanguagesOfferedList],
		src.[AvailabilityNumberOfTimes],
		src.[AvailabilityFrequency],
		src.[AvailabilityPeriod],
		src.[ServiceNotAlwaysAvailability],
		src.[CapacityType],
		src.[ServiceCapacity],
		src.[NormalWaitTime],
		src.[TemporaryMessage],
		src.[TemporaryMessageAppears],
		src.[TemporaryMessageExpires],
		src.[EnteredOn],
		src.[UpdatedOn],
		src.[MadeInactiveOn],
		src.[InternalNotes],
		src.[InternalNotesForEditorsAndViewers],
		src.[HighlightedResource],
		src.[LastVerifiedOn],
		src.[LastVerifiedByName],
		src.[LastVerifiedByTitle],
		src.[LastVerifiedByPhoneNumber],
		src.[LastVerifiedByEmailAddress],
		src.[LastVerificationApprovedBy],
		src.[AvailableForDirectory],
		src.[AvailableForReferral],
		src.[AvailableForResearch],
		src.[PreferredProvider],
		src.[ConnectsToSiteNum],
		src.[ConnectsToProgramNum],
		src.[LanguageOfRecord],
		src.[CurrentWorkflowStepCode],
		src.[VolunteerOpportunities],
		src.[VolunteerDuties],
		src.[IsLinkOnly],
		src.[ProgramAgencyNamePublic],
		src.[SiteAgencyNamePublic],
		src.[Categories],
		src.[TaxonomyTerm],
		src.[TaxonomyTerms],
		src.[TaxonomyTermsNotDeactivated],
		src.[TaxonomyCodes],
		src.[Coverage],
		src.[Hours],
		src.[Custom_Public Comments],
		src.[Custom_Former Names],
		src.[Custom_Legal Name],
		src.[Custom_Facebook],
		src.[Custom_Instagram],
		src.[Custom_LinkedIn],
		src.[Custom_Twitter],
		src.[Custom_YouTube],
		src.[Custom_Minimum Age],
		src.[Custom_Maximum Age],
		GETDATE(),
		src.PublicName,
		src.AgencyDescription,
		'AGENCY',
		src.DELETION_DATE
	)

	;



MERGE INTO dbo.CIC_iCarolImportRollup dst
USING (
SELECT 
		(SELECT MAX(SYNC_DATE) FROM (VALUES (pas.SYNC_DATE), (p.SYNC_DATE), (s.SYNC_DATE), (a.SYNC_DATE)) AS i(SYNC_DATE)) AS SYNC_DATE,
		COALESCE(pas.[ResourceAgencyNum], p.[ResourceAgencyNum], s.[ResourceAgencyNum], a.[ResourceAgencyNum]) AS [ResourceAgencyNum],
		COALESCE(pas.[LangID], p.[LangID], s.[LangID], a.[LangID]) AS [LangID],
		COALESCE(pas.[PublicName], p.[PublicName], s.[PublicName], a.[PublicName]) AS [PublicName],
		COALESCE(pas.[AlternateName], p.[AlternateName], s.[AlternateName], a.[AlternateName]) AS [AlternateName],
		COALESCE(pas.[OfficialName], p.[OfficialName], s.[OfficialName], a.[OfficialName]) AS [OfficialName],
		COALESCE(pas.[TaxonomyLevelName], p.[TaxonomyLevelName], s.[TaxonomyLevelName], a.[TaxonomyLevelName]) AS [TaxonomyLevelName],
		COALESCE(pas.[ParentAgency], p.[ParentAgency], s.[ParentAgency], a.[ParentAgency]) AS [ParentAgency],
		COALESCE(pas.[ParentAgencyNum], p.[ParentAgencyNum], s.[ParentAgencyNum], a.[ParentAgencyNum]) AS [ParentAgencyNum],
		COALESCE(pas.[Custom_Record Owner (controlled)], p.[Custom_Record Owner (controlled)]) AS [RECORD_OWNER],
		COALESCE(pas.[UniqueIDPriorSystem], p.[UniqueIDPriorSystem], s.[UniqueIDPriorSystem], a.[UniqueIDPriorSystem]) AS [UniqueIDPriorSystem],
		COALESCE(pas.[MailingAttentionName], p.[MailingAttentionName], s.[MailingAttentionName], a.[MailingAttentionName]) AS [MailingAttentionName],
		COALESCE(pas.[MailingAddress1], p.[MailingAddress1], s.[MailingAddress1], a.[MailingAddress1]) AS [MailingAddress1],
		COALESCE(pas.[MailingAddress2], p.[MailingAddress2], s.[MailingAddress2], a.[MailingAddress2]) AS [MailingAddress2],
		COALESCE(pas.[MailingCity], p.[MailingCity], s.[MailingCity], a.[MailingCity]) AS [MailingCity],
		COALESCE(pas.[MailingStateProvince], p.[MailingStateProvince], s.[MailingStateProvince], a.[MailingStateProvince]) AS [MailingStateProvince],
		COALESCE(pas.[MailingPostalCode], p.[MailingPostalCode], s.[MailingPostalCode], a.[MailingPostalCode]) AS [MailingPostalCode],
		COALESCE(pas.[MailingCountry], p.[MailingCountry], s.[MailingCountry], a.[MailingCountry]) AS [MailingCountry],
		COALESCE(pas.[MailingAddressIsPrivate], p.[MailingAddressIsPrivate], s.[MailingAddressIsPrivate], a.[MailingAddressIsPrivate]) AS [MailingAddressIsPrivate],
		COALESCE(pas.[PhysicalAddress1], p.[PhysicalAddress1], s.[PhysicalAddress1], a.[PhysicalAddress1]) AS [PhysicalAddress1],
		COALESCE(pas.[PhysicalAddress2], p.[PhysicalAddress2], s.[PhysicalAddress2], a.[PhysicalAddress2]) AS [PhysicalAddress2],
		COALESCE(pas.[PhysicalCity], p.[PhysicalCity], s.[PhysicalCity], a.[PhysicalCity]) AS [PhysicalCity],
		COALESCE(pas.[PhysicalCounty], p.[PhysicalCounty], s.[PhysicalCounty], a.[PhysicalCounty]) AS [PhysicalCounty],
		COALESCE(pas.[PhysicalStateProvince], p.[PhysicalStateProvince], s.[PhysicalStateProvince], a.[PhysicalStateProvince]) AS [PhysicalStateProvince],
		COALESCE(pas.[PhysicalPostalCode], p.[PhysicalPostalCode], s.[PhysicalPostalCode], a.[PhysicalPostalCode]) AS [PhysicalPostalCode],
		COALESCE(pas.[PhysicalCountry], p.[PhysicalCountry], s.[PhysicalCountry], a.[PhysicalCountry]) AS [PhysicalCountry],
		COALESCE(pas.[PhysicalAddressIsPrivate], p.[PhysicalAddressIsPrivate], s.[PhysicalAddressIsPrivate], a.[PhysicalAddressIsPrivate]) AS [PhysicalAddressIsPrivate],
		COALESCE(pas.[OtherAddress1], p.[OtherAddress1], s.[OtherAddress1], a.[OtherAddress1]) AS [OtherAddress1],
		COALESCE(pas.[OtherAddress2], p.[OtherAddress2], s.[OtherAddress2], a.[OtherAddress2]) AS [OtherAddress2],
		COALESCE(pas.[OtherCity], p.[OtherCity], s.[OtherCity], a.[OtherCity]) AS [OtherCity],
		COALESCE(pas.[OtherCounty], p.[OtherCounty], s.[OtherCounty], a.[OtherCounty]) AS [OtherCounty],
		COALESCE(pas.[OtherStateProvince], p.[OtherStateProvince], s.[OtherStateProvince], a.[OtherStateProvince]) AS [OtherStateProvince],
		COALESCE(pas.[OtherPostalCode], p.[OtherPostalCode], s.[OtherPostalCode], a.[OtherPostalCode]) AS [OtherPostalCode],
		COALESCE(pas.[OtherCountry], p.[OtherCountry], s.[OtherCountry], a.[OtherCountry]) AS [OtherCountry],
		COALESCE(NULLIF(pas.[Latitude],'0'), NULLIF(p.[Latitude],'0'), NULLIF(s.[Latitude],'0'), NULLIF(a.[Latitude],'0')) AS [Latitude],
		COALESCE(NULLIF(pas.[Longitude], '0'), NULLIF(p.[Longitude],'0'), NULLIF(s.[Longitude],'0'), NULLIF(a.[Longitude],'0')) AS [Longitude],
		COALESCE(pas.[HoursOfOperation], p.[HoursOfOperation], s.[HoursOfOperation], a.[HoursOfOperation]) AS [HoursOfOperation],
		COALESCE(pas.[Phone1Number], p.[Phone1Number], s.[Phone1Number], a.[Phone1Number]) AS [Phone1Number],
		COALESCE(pas.[Phone1Name], p.[Phone1Name], s.[Phone1Name], a.[Phone1Name]) AS [Phone1Name],
		COALESCE(pas.[Phone1Description], p.[Phone1Description], s.[Phone1Description], a.[Phone1Description]) AS [Phone1Description],
		COALESCE(pas.[Phone1IsPrivate], p.[Phone1IsPrivate], s.[Phone1IsPrivate], a.[Phone1IsPrivate]) AS [Phone1IsPrivate],
		COALESCE(pas.[Phone1Type], p.[Phone1Type], s.[Phone1Type], a.[Phone1Type]) AS [Phone1Type],
		COALESCE(pas.[Phone2Number], p.[Phone2Number], s.[Phone2Number], a.[Phone2Number]) AS [Phone2Number],
		COALESCE(pas.[Phone2Name], p.[Phone2Name], s.[Phone2Name], a.[Phone2Name]) AS [Phone2Name],
		COALESCE(pas.[Phone2Description], p.[Phone2Description], s.[Phone2Description], a.[Phone2Description]) AS [Phone2Description],
		COALESCE(pas.[Phone2IsPrivate], p.[Phone2IsPrivate], s.[Phone2IsPrivate], a.[Phone2IsPrivate]) AS [Phone2IsPrivate],
		COALESCE(pas.[Phone2Type], p.[Phone2Type], s.[Phone2Type], a.[Phone2Type]) AS [Phone2Type],
		COALESCE(pas.[Phone3Number], p.[Phone3Number], s.[Phone3Number], a.[Phone3Number]) AS [Phone3Number],
		COALESCE(pas.[Phone3Name], p.[Phone3Name], s.[Phone3Name], a.[Phone3Name]) AS [Phone3Name],
		COALESCE(pas.[Phone3Description], p.[Phone3Description], s.[Phone3Description], a.[Phone3Description]) AS [Phone3Description],
		COALESCE(pas.[Phone3IsPrivate], p.[Phone3IsPrivate], s.[Phone3IsPrivate], a.[Phone3IsPrivate]) AS [Phone3IsPrivate],
		COALESCE(pas.[Phone3Type], p.[Phone3Type], s.[Phone3Type], a.[Phone3Type]) AS [Phone3Type],
		COALESCE(pas.[Phone4Number], p.[Phone4Number], s.[Phone4Number], a.[Phone4Number]) AS [Phone4Number],
		COALESCE(pas.[Phone4Name], p.[Phone4Name], s.[Phone4Name], a.[Phone4Name]) AS [Phone4Name],
		COALESCE(pas.[Phone4Description], p.[Phone4Description], s.[Phone4Description], a.[Phone4Description]) AS [Phone4Description],
		COALESCE(pas.[Phone4IsPrivate], p.[Phone4IsPrivate], s.[Phone4IsPrivate], a.[Phone4IsPrivate]) AS [Phone4IsPrivate],
		COALESCE(pas.[Phone4Type], p.[Phone4Type], s.[Phone4Type], a.[Phone4Type]) AS [Phone4Type],
		COALESCE(pas.[Phone5Number], p.[Phone5Number], s.[Phone5Number], a.[Phone5Number]) AS [Phone5Number],
		COALESCE(pas.[Phone5name], p.[Phone5name], s.[Phone5name], a.[Phone5name]) AS [Phone5name],
		COALESCE(pas.[Phone5Description], p.[Phone5Description], s.[Phone5Description], a.[Phone5Description]) AS [Phone5Description],
		COALESCE(pas.[Phone5IsPrivate], p.[Phone5IsPrivate], s.[Phone5IsPrivate], a.[Phone5IsPrivate]) AS [Phone5IsPrivate],
		COALESCE(pas.[Phone5Type], p.[Phone5Type], s.[Phone5Type], a.[Phone5Type]) AS [Phone5Type],
		COALESCE(pas.[PhoneFax], p.[PhoneFax], s.[PhoneFax], a.[PhoneFax]) AS [PhoneFax],
		COALESCE(pas.[PhoneFaxDescription], p.[PhoneFaxDescription], s.[PhoneFaxDescription], a.[PhoneFaxDescription]) AS [PhoneFaxDescription],
		COALESCE(pas.[PhoneFaxIsPrivate], p.[PhoneFaxIsPrivate], s.[PhoneFaxIsPrivate], a.[PhoneFaxIsPrivate]) AS [PhoneFaxIsPrivate],
		COALESCE(pas.[PhoneTTY], p.[PhoneTTY], s.[PhoneTTY], a.[PhoneTTY]) AS [PhoneTTY],
		COALESCE(pas.[PhoneTTYDescription], p.[PhoneTTYDescription], s.[PhoneTTYDescription], a.[PhoneTTYDescription]) AS [PhoneTTYDescription],
		COALESCE(pas.[PhoneTTYIsPrivate], p.[PhoneTTYIsPrivate], s.[PhoneTTYIsPrivate], a.[PhoneTTYIsPrivate]) AS [PhoneTTYIsPrivate],
		COALESCE(pas.[PhoneTollFree], p.[PhoneTollFree], s.[PhoneTollFree], a.[PhoneTollFree]) AS [PhoneTollFree],
		COALESCE(pas.[PhoneTollFreeDescription], p.[PhoneTollFreeDescription], s.[PhoneTollFreeDescription], a.[PhoneTollFreeDescription]) AS [PhoneTollFreeDescription],
		COALESCE(pas.[PhoneTollFreeIsPrivate], p.[PhoneTollFreeIsPrivate], s.[PhoneTollFreeIsPrivate], a.[PhoneTollFreeIsPrivate]) AS [PhoneTollFreeIsPrivate],
		COALESCE(pas.[PhoneNumberHotline], p.[PhoneNumberHotline], s.[PhoneNumberHotline], a.[PhoneNumberHotline]) AS [PhoneNumberHotline],
		COALESCE(pas.[PhoneNumberHotlineDescription], p.[PhoneNumberHotlineDescription], s.[PhoneNumberHotlineDescription], a.[PhoneNumberHotlineDescription]) AS [PhoneNumberHotlineDescription],
		COALESCE(pas.[PhoneNumberHotlineIsPrivate], p.[PhoneNumberHotlineIsPrivate], s.[PhoneNumberHotlineIsPrivate], a.[PhoneNumberHotlineIsPrivate]) AS [PhoneNumberHotlineIsPrivate],
		COALESCE(pas.[PhoneNumberBusinessLine], p.[PhoneNumberBusinessLine], s.[PhoneNumberBusinessLine], a.[PhoneNumberBusinessLine]) AS [PhoneNumberBusinessLine],
		COALESCE(pas.[PhoneNumberBusinessLineDescription], p.[PhoneNumberBusinessLineDescription], s.[PhoneNumberBusinessLineDescription], a.[PhoneNumberBusinessLineDescription]) AS [PhoneNumberBusinessLineDescription],
		COALESCE(pas.[PhoneNumberBusinessLineIsPrivate], p.[PhoneNumberBusinessLineIsPrivate], s.[PhoneNumberBusinessLineIsPrivate], a.[PhoneNumberBusinessLineIsPrivate]) AS [PhoneNumberBusinessLineIsPrivate],
		COALESCE(pas.[PhoneNumberOutOfArea], p.[PhoneNumberOutOfArea], s.[PhoneNumberOutOfArea], a.[PhoneNumberOutOfArea]) AS [PhoneNumberOutOfArea],
		COALESCE(pas.[PhoneNumberOutOfAreaDescription], p.[PhoneNumberOutOfAreaDescription], s.[PhoneNumberOutOfAreaDescription], a.[PhoneNumberOutOfAreaDescription]) AS [PhoneNumberOutOfAreaDescription],
		COALESCE(pas.[PhoneNumberOutOfAreaIsPrivate], p.[PhoneNumberOutOfAreaIsPrivate], s.[PhoneNumberOutOfAreaIsPrivate], a.[PhoneNumberOutOfAreaIsPrivate]) AS [PhoneNumberOutOfAreaIsPrivate],
		COALESCE(pas.[PhoneNumberAfterHours], p.[PhoneNumberAfterHours], s.[PhoneNumberAfterHours], a.[PhoneNumberAfterHours]) AS [PhoneNumberAfterHours],
		COALESCE(pas.[PhoneNumberAfterHoursDescription], p.[PhoneNumberAfterHoursDescription], s.[PhoneNumberAfterHoursDescription], a.[PhoneNumberAfterHoursDescription]) AS [PhoneNumberAfterHoursDescription],
		COALESCE(pas.[PhoneNumberAfterHoursIsPrivate], p.[PhoneNumberAfterHoursIsPrivate], s.[PhoneNumberAfterHoursIsPrivate], a.[PhoneNumberAfterHoursIsPrivate]) AS [PhoneNumberAfterHoursIsPrivate],
		COALESCE(pas.[EmailAddressMain], p.[EmailAddressMain], s.[EmailAddressMain], a.[EmailAddressMain]) AS [EmailAddressMain],
		COALESCE(pas.[WebsiteAddress], p.[WebsiteAddress], s.[WebsiteAddress], a.[WebsiteAddress]) AS [WebsiteAddress],
		COALESCE(pas.[AgencyStatus], p.[AgencyStatus], s.[AgencyStatus], a.[AgencyStatus]) AS [AgencyStatus],
		COALESCE(pas.[AgencyClassification], p.[AgencyClassification], s.[AgencyClassification], a.[AgencyClassification]) AS [AgencyClassification],
		COALESCE(pas.[CoverageArea], p.[CoverageArea], s.[CoverageArea], a.[CoverageArea]) AS [CoverageArea],
		COALESCE(pas.[CoverageAreaText], p.[CoverageAreaText], s.[CoverageAreaText], a.[CoverageAreaText]) AS [CoverageAreaText],
		COALESCE(pas.[Eligibility], p.[Eligibility], s.[Eligibility], a.[Eligibility]) AS [Eligibility],
		COALESCE(pas.[EligibilityAdult], p.[EligibilityAdult], s.[EligibilityAdult], a.[EligibilityAdult]) AS [EligibilityAdult],
		COALESCE(pas.[EligibilityChild], p.[EligibilityChild], s.[EligibilityChild], a.[EligibilityChild]) AS [EligibilityChild],
		COALESCE(pas.[EligibilityFamily], p.[EligibilityFamily], s.[EligibilityFamily], a.[EligibilityFamily]) AS [EligibilityFamily],
		COALESCE(pas.[EligibilityFemale], p.[EligibilityFemale], s.[EligibilityFemale], a.[EligibilityFemale]) AS [EligibilityFemale],
		COALESCE(pas.[EligibilityMale], p.[EligibilityMale], s.[EligibilityMale], a.[EligibilityMale]) AS [EligibilityMale],
		COALESCE(pas.[EligibilityTeen], p.[EligibilityTeen], s.[EligibilityTeen], a.[EligibilityTeen]) AS [EligibilityTeen],
		COALESCE(pas.[SeniorWorkerName], p.[SeniorWorkerName], s.[SeniorWorkerName], a.[SeniorWorkerName]) AS [SeniorWorkerName],
		COALESCE(pas.[SeniorWorkerTitle], p.[SeniorWorkerTitle], s.[SeniorWorkerTitle], a.[SeniorWorkerTitle]) AS [SeniorWorkerTitle],
		COALESCE(pas.[SeniorWorkerEmailAddress], p.[SeniorWorkerEmailAddress], s.[SeniorWorkerEmailAddress], a.[SeniorWorkerEmailAddress]) AS [SeniorWorkerEmailAddress],
		COALESCE(pas.[SeniorWorkerPhoneNumber], p.[SeniorWorkerPhoneNumber], s.[SeniorWorkerPhoneNumber], a.[SeniorWorkerPhoneNumber]) AS [SeniorWorkerPhoneNumber],
		COALESCE(pas.[SeniorWorkerIsPrivate], p.[SeniorWorkerIsPrivate], s.[SeniorWorkerIsPrivate], a.[SeniorWorkerIsPrivate]) AS [SeniorWorkerIsPrivate],
		COALESCE(pas.[MainContactName], p.[MainContactName], s.[MainContactName], a.[MainContactName]) AS [MainContactName],
		COALESCE(pas.[MainContactTitle], p.[MainContactTitle], s.[MainContactTitle], a.[MainContactTitle]) AS [MainContactTitle],
		COALESCE(pas.[MainContactEmailAddress], p.[MainContactEmailAddress], s.[MainContactEmailAddress], a.[MainContactEmailAddress]) AS [MainContactEmailAddress],
		COALESCE(pas.[MainContactPhoneNumber], p.[MainContactPhoneNumber], s.[MainContactPhoneNumber], a.[MainContactPhoneNumber]) AS [MainContactPhoneNumber],
		COALESCE(pas.[MainContactType], p.[MainContactType], s.[MainContactType], a.[MainContactType]) AS [MainContactType],
		COALESCE(pas.[MainContactIsPrivate], p.[MainContactIsPrivate], s.[MainContactIsPrivate], a.[MainContactIsPrivate]) AS [MainContactIsPrivate],
		COALESCE(pas.[LicenseAccreditation], p.[LicenseAccreditation], s.[LicenseAccreditation], a.[LicenseAccreditation]) AS [LicenseAccreditation],
		COALESCE(pas.[YearIncorporated], p.[YearIncorporated], s.[YearIncorporated], a.[YearIncorporated]) AS [YearIncorporated],
		COALESCE(pas.[AnnualBudgetTotal], p.[AnnualBudgetTotal], s.[AnnualBudgetTotal], a.[AnnualBudgetTotal]) AS [AnnualBudgetTotal],
		COALESCE(pas.[LegalStatus], p.[LegalStatus], s.[LegalStatus], a.[LegalStatus]) AS [LegalStatus],
		COALESCE(pas.[SourceOfFunds], p.[SourceOfFunds], s.[SourceOfFunds], a.[SourceOfFunds]) AS [SourceOfFunds],
		COALESCE(pas.[ExcludeFromWebsite], p.[ExcludeFromWebsite], s.[ExcludeFromWebsite], a.[ExcludeFromWebsite]) AS [ExcludeFromWebsite],
		COALESCE(pas.[ExcludeFromDirectory], p.[ExcludeFromDirectory], s.[ExcludeFromDirectory], a.[ExcludeFromDirectory]) AS [ExcludeFromDirectory],
		COALESCE(pas.[DisabilitiesAccess], p.[DisabilitiesAccess], s.[DisabilitiesAccess], a.[DisabilitiesAccess]) AS [DisabilitiesAccess],
		COALESCE(pas.[PhysicalLocationDescription], p.[PhysicalLocationDescription], s.[PhysicalLocationDescription], a.[PhysicalLocationDescription]) AS [PhysicalLocationDescription],
		COALESCE(pas.[BusServiceAccess], p.[BusServiceAccess], s.[BusServiceAccess], a.[BusServiceAccess]) AS [BusServiceAccess],
		COALESCE(pas.[PublicAccessTransportation], p.[PublicAccessTransportation], s.[PublicAccessTransportation], a.[PublicAccessTransportation]) AS [PublicAccessTransportation],
		COALESCE(pas.[PaymentMethods], p.[PaymentMethods], s.[PaymentMethods], a.[PaymentMethods]) AS [PaymentMethods],
		COALESCE(pas.[FeeStructureSource], p.[FeeStructureSource], s.[FeeStructureSource], a.[FeeStructureSource]) AS [FeeStructureSource],
		COALESCE(pas.[ApplicationProcess], p.[ApplicationProcess], s.[ApplicationProcess], a.[ApplicationProcess]) AS [ApplicationProcess],
		COALESCE(pas.[ResourceInfo], p.[ResourceInfo], s.[ResourceInfo], a.[ResourceInfo]) AS [ResourceInfo],
		COALESCE(pas.[DocumentsRequired], p.[DocumentsRequired], s.[DocumentsRequired], a.[DocumentsRequired]) AS [DocumentsRequired],
		COALESCE(pas.[LanguagesOffered], p.[LanguagesOffered], s.[LanguagesOffered], a.[LanguagesOffered]) AS [LanguagesOffered],
		COALESCE(pas.[LanguagesOfferedList], p.[LanguagesOfferedList], s.[LanguagesOfferedList], a.[LanguagesOfferedList]) AS [LanguagesOfferedList],
		COALESCE(pas.[AvailabilityNumberOfTimes], p.[AvailabilityNumberOfTimes], s.[AvailabilityNumberOfTimes], a.[AvailabilityNumberOfTimes]) AS [AvailabilityNumberOfTimes],
		COALESCE(pas.[AvailabilityFrequency], p.[AvailabilityFrequency], s.[AvailabilityFrequency], a.[AvailabilityFrequency]) AS [AvailabilityFrequency],
		COALESCE(pas.[AvailabilityPeriod], p.[AvailabilityPeriod], s.[AvailabilityPeriod], a.[AvailabilityPeriod]) AS [AvailabilityPeriod],
		COALESCE(pas.[ServiceNotAlwaysAvailability], p.[ServiceNotAlwaysAvailability], s.[ServiceNotAlwaysAvailability], a.[ServiceNotAlwaysAvailability]) AS [ServiceNotAlwaysAvailability],
		COALESCE(pas.[CapacityType], p.[CapacityType], s.[CapacityType], a.[CapacityType]) AS [CapacityType],
		COALESCE(pas.[ServiceCapacity], p.[ServiceCapacity], s.[ServiceCapacity], a.[ServiceCapacity]) AS [ServiceCapacity],
		COALESCE(pas.[NormalWaitTime], p.[NormalWaitTime], s.[NormalWaitTime], a.[NormalWaitTime]) AS [NormalWaitTime],
		COALESCE(pas.[TemporaryMessage], p.[TemporaryMessage], s.[TemporaryMessage], a.[TemporaryMessage]) AS [TemporaryMessage],
		COALESCE(pas.[TemporaryMessageAppears], p.[TemporaryMessageAppears], s.[TemporaryMessageAppears], a.[TemporaryMessageAppears]) AS [TemporaryMessageAppears],
		COALESCE(pas.[TemporaryMessageExpires], p.[TemporaryMessageExpires], s.[TemporaryMessageExpires], a.[TemporaryMessageExpires]) AS [TemporaryMessageExpires],
		COALESCE(pas.[EnteredOn], p.[EnteredOn], s.[EnteredOn], a.[EnteredOn]) AS [EnteredOn],
		COALESCE(pas.[UpdatedOn], p.[UpdatedOn], s.[UpdatedOn], a.[UpdatedOn]) AS [UpdatedOn],
		COALESCE(pas.[MadeInactiveOn], p.[MadeInactiveOn], s.[MadeInactiveOn], a.[MadeInactiveOn]) AS [MadeInactiveOn],
		COALESCE(pas.[InternalNotes], p.[InternalNotes], s.[InternalNotes], a.[InternalNotes]) AS [InternalNotes],
		COALESCE(pas.[InternalNotesForEditorsAndViewers], p.[InternalNotesForEditorsAndViewers], s.[InternalNotesForEditorsAndViewers], a.[InternalNotesForEditorsAndViewers]) AS [InternalNotesForEditorsAndViewers],
		COALESCE(pas.[HighlightedResource], p.[HighlightedResource], s.[HighlightedResource], a.[HighlightedResource]) AS [HighlightedResource],
		COALESCE(pas.[LastVerifiedOn], p.[LastVerifiedOn], s.[LastVerifiedOn], a.[LastVerifiedOn]) AS [LastVerifiedOn],
		COALESCE(pas.[LastVerifiedByName], p.[LastVerifiedByName], s.[LastVerifiedByName], a.[LastVerifiedByName]) AS [LastVerifiedByName],
		COALESCE(pas.[LastVerifiedByTitle], p.[LastVerifiedByTitle], s.[LastVerifiedByTitle], a.[LastVerifiedByTitle]) AS [LastVerifiedByTitle],
		COALESCE(pas.[LastVerifiedByPhoneNumber], p.[LastVerifiedByPhoneNumber], s.[LastVerifiedByPhoneNumber], a.[LastVerifiedByPhoneNumber]) AS [LastVerifiedByPhoneNumber],
		COALESCE(pas.[LastVerifiedByEmailAddress], p.[LastVerifiedByEmailAddress], s.[LastVerifiedByEmailAddress], a.[LastVerifiedByEmailAddress]) AS [LastVerifiedByEmailAddress],
		COALESCE(pas.[LastVerificationApprovedBy], p.[LastVerificationApprovedBy], s.[LastVerificationApprovedBy], a.[LastVerificationApprovedBy]) AS [LastVerificationApprovedBy],
		COALESCE(pas.[AvailableForDirectory], p.[AvailableForDirectory], s.[AvailableForDirectory], a.[AvailableForDirectory]) AS [AvailableForDirectory],
		COALESCE(pas.[AvailableForReferral], p.[AvailableForReferral], s.[AvailableForReferral], a.[AvailableForReferral]) AS [AvailableForReferral],
		COALESCE(pas.[AvailableForResearch], p.[AvailableForResearch], s.[AvailableForResearch], a.[AvailableForResearch]) AS [AvailableForResearch],
		COALESCE(pas.[PreferredProvider], p.[PreferredProvider], s.[PreferredProvider], a.[PreferredProvider]) AS [PreferredProvider],
		COALESCE(pas.[ConnectsToSiteNum], p.[ConnectsToSiteNum], s.[ConnectsToSiteNum], a.[ConnectsToSiteNum]) AS [ConnectsToSiteNum],
		COALESCE(pas.[ConnectsToProgramNum], p.[ConnectsToProgramNum], s.[ConnectsToProgramNum], a.[ConnectsToProgramNum]) AS [ConnectsToProgramNum],
		COALESCE(pas.[LanguageOfRecord], p.[LanguageOfRecord], s.[LanguageOfRecord], a.[LanguageOfRecord]) AS [LanguageOfRecord],
		COALESCE(pas.[CurrentWorkflowStepCode], p.[CurrentWorkflowStepCode], s.[CurrentWorkflowStepCode], a.[CurrentWorkflowStepCode]) AS [CurrentWorkflowStepCode],
		COALESCE(pas.[VolunteerOpportunities], p.[VolunteerOpportunities], s.[VolunteerOpportunities], a.[VolunteerOpportunities]) AS [VolunteerOpportunities],
		COALESCE(pas.[VolunteerDuties], p.[VolunteerDuties], s.[VolunteerDuties], a.[VolunteerDuties]) AS [VolunteerDuties],
		COALESCE(pas.[IsLinkOnly], p.[IsLinkOnly], s.[IsLinkOnly], a.[IsLinkOnly]) AS [IsLinkOnly],
		COALESCE(pas.[ProgramAgencyNamePublic], p.[ProgramAgencyNamePublic], s.[ProgramAgencyNamePublic], a.[ProgramAgencyNamePublic]) AS [ProgramAgencyNamePublic],
		COALESCE(pas.[SiteAgencyNamePublic], p.[SiteAgencyNamePublic], s.[SiteAgencyNamePublic], a.[SiteAgencyNamePublic]) AS [SiteAgencyNamePublic],
		COALESCE(pas.[Categories], p.[Categories], s.[Categories], a.[Categories]) AS [Categories],
		COALESCE(pas.[TaxonomyTerm], p.[TaxonomyTerm], s.[TaxonomyTerm], a.[TaxonomyTerm]) AS [TaxonomyTerm],
		COALESCE(pas.[TaxonomyTerms], p.[TaxonomyTerms], s.[TaxonomyTerms], a.[TaxonomyTerms]) AS [TaxonomyTerms],
		COALESCE(pas.[TaxonomyTermsNotDeactivated], p.[TaxonomyTermsNotDeactivated], s.[TaxonomyTermsNotDeactivated], a.[TaxonomyTermsNotDeactivated]) AS [TaxonomyTermsNotDeactivated],
		COALESCE(pas.[TaxonomyCodes], p.[TaxonomyCodes], s.[TaxonomyCodes], a.[TaxonomyCodes]) AS [TaxonomyCodes],
		COALESCE(pas.[Coverage], p.[Coverage], s.[Coverage], a.[Coverage]) AS [Coverage],
		COALESCE(pas.[Hours], p.[Hours], s.[Hours], a.[Hours]) AS [Hours],
		COALESCE(pas.[Custom_Public Comments], p.[Custom_Public Comments], s.[Custom_Public Comments], a.[Custom_Public Comments]) AS [Custom_Public Comments],
		COALESCE(pas.[Custom_Former Names], p.[Custom_Former Names], s.[Custom_Former Names], a.[Custom_Former Names]) AS [Custom_Former Names],
		COALESCE(pas.[Custom_Legal Name], p.[Custom_Legal Name], s.[Custom_Legal Name], a.[Custom_Legal Name]) AS [Custom_Legal Name],
		COALESCE(pas.[Custom_Facebook], p.[Custom_Facebook], s.[Custom_Facebook], a.[Custom_Facebook]) AS [Custom_Facebook],
		COALESCE(pas.[Custom_Instagram], p.[Custom_Instagram], s.[Custom_Instagram], a.[Custom_Instagram]) AS [Custom_Instagram],
		COALESCE(pas.[Custom_LinkedIn], p.[Custom_LinkedIn], s.[Custom_LinkedIn], a.[Custom_LinkedIn]) AS [Custom_LinkedIn],
		COALESCE(pas.[Custom_Twitter], p.[Custom_Twitter], s.[Custom_Twitter], a.[Custom_Twitter]) AS [Custom_Twitter],
		COALESCE(pas.[Custom_YouTube], p.[Custom_YouTube], s.[Custom_YouTube], a.[Custom_YouTube]) AS [Custom_YouTube],
		COALESCE(pas.[Custom_Minimum Age], p.[Custom_Minimum Age], s.[Custom_Minimum Age], a.[Custom_Minimum Age]) AS [Custom_Minimum Age],
		COALESCE(pas.[Custom_Maximum Age], p.[Custom_Maximum Age], s.[Custom_Maximum Age], a.[Custom_Maximum Age]) AS [Custom_Maximum Age],
		a.PublicName AS ORG_LEVEL_1,
		a.AgencyDescription AS ORG_DESCRIPTION,
		s.PublicName AS LOCATION_NAME,
		s.AgencyDescription AS LOCATION_DESCRIPTION,
		COALESCE(p.PublicName, pas.PublicName) AS SERVICE_NAME_LEVEL_1,
		s.PublicName AS SERVICE_NAME_LEVEL_2,
		COALESCE(pas.AgencyDescription, p.AgencyDescription) AS DESCRIPTION,
		pas.DELETION_DATE
	FROM dbo.CIC_iCarolImport pas
	LEFT JOIN dbo.CIC_iCarolImport p
		ON p.ResourceAgencyNum=pas.ConnectsToProgramNum AND p.TaxonomyLevelName='Program' AND p.LangID=pas.LangID
	LEFT JOIN dbo.CIC_iCarolImport s
		ON s.ResourceAgencyNum=pas.ConnectsToSiteNum AND s.TaxonomyLevelName='Site' AND s.langid=pas.LangID
	LEFT JOIN dbo.CIC_iCarolImport a
		ON pas.ParentAgencyNum=a.ResourceAgencyNum AND a.TaxonomyLevelName='Agency' AND a.LangID=pas.LangID
	WHERE pas.TaxonomyLevelName='ProgramAtSite'
) AS src
ON src.ResourceAgencyNum=dst.ResourceAgencyNum AND src.LangID=dst.LangID AND src.TaxonomyLevelName = 'ProgramAtSite'
WHEN MATCHED AND src.SYNC_DATE > dst.DATE_MODIFIED THEN 
	UPDATE SET 
		[PublicName]=src.[PublicName],
		[AlternateName]=src.[AlternateName],
		[OfficialName]=src.[OfficialName],
		[TaxonomyLevelName]=src.[TaxonomyLevelName],
		[ParentAgency]=src.[ParentAgency],
		[ParentAgencyNum]=src.[ParentAgencyNum],
		[RECORD_OWNER]=src.[RECORD_OWNER],
		[UniqueIDPriorSystem]=src.[UniqueIDPriorSystem],
		[MailingAttentionName]=src.[MailingAttentionName],
		[MailingAddress1]=src.[MailingAddress1],
		[MailingAddress2]=src.[MailingAddress2],
		[MailingCity]=src.[MailingCity],
		[MailingStateProvince]=src.[MailingStateProvince],
		[MailingPostalCode]=src.[MailingPostalCode],
		[MailingCountry]=src.[MailingCountry],
		[MailingAddressIsPrivate]=src.[MailingAddressIsPrivate],
		[PhysicalAddress1]=src.[PhysicalAddress1],
		[PhysicalAddress2]=src.[PhysicalAddress2],
		[PhysicalCity]=src.[PhysicalCity],
		[PhysicalCounty]=src.[PhysicalCounty],
		[PhysicalStateProvince]=src.[PhysicalStateProvince],
		[PhysicalPostalCode]=src.[PhysicalPostalCode],
		[PhysicalCountry]=src.[PhysicalCountry],
		[PhysicalAddressIsPrivate]=src.[PhysicalAddressIsPrivate],
		[OtherAddress1]=src.[OtherAddress1],
		[OtherAddress2]=src.[OtherAddress2],
		[OtherCity]=src.[OtherCity],
		[OtherCounty]=src.[OtherCounty],
		[OtherStateProvince]=src.[OtherStateProvince],
		[OtherPostalCode]=src.[OtherPostalCode],
		[OtherCountry]=src.[OtherCountry],
		[Latitude]=src.[Latitude],
		[Longitude]=src.[Longitude],
		[HoursOfOperation]=src.[HoursOfOperation],
		[Phone1Number]=src.[Phone1Number],
		[Phone1Name]=src.[Phone1Name],
		[Phone1Description]=src.[Phone1Description],
		[Phone1IsPrivate]=src.[Phone1IsPrivate],
		[Phone1Type]=src.[Phone1Type],
		[Phone2Number]=src.[Phone2Number],
		[Phone2Name]=src.[Phone2Name],
		[Phone2Description]=src.[Phone2Description],
		[Phone2IsPrivate]=src.[Phone2IsPrivate],
		[Phone2Type]=src.[Phone2Type],
		[Phone3Number]=src.[Phone3Number],
		[Phone3Name]=src.[Phone3Name],
		[Phone3Description]=src.[Phone3Description],
		[Phone3IsPrivate]=src.[Phone3IsPrivate],
		[Phone3Type]=src.[Phone3Type],
		[Phone4Number]=src.[Phone4Number],
		[Phone4Name]=src.[Phone4Name],
		[Phone4Description]=src.[Phone4Description],
		[Phone4IsPrivate]=src.[Phone4IsPrivate],
		[Phone4Type]=src.[Phone4Type],
		[Phone5Number]=src.[Phone5Number],
		[Phone5name]=src.[Phone5name],
		[Phone5Description]=src.[Phone5Description],
		[Phone5IsPrivate]=src.[Phone5IsPrivate],
		[Phone5Type]=src.[Phone5Type],
		[PhoneFax]=src.[PhoneFax],
		[PhoneFaxDescription]=src.[PhoneFaxDescription],
		[PhoneFaxIsPrivate]=src.[PhoneFaxIsPrivate],
		[PhoneTTY]=src.[PhoneTTY],
		[PhoneTTYDescription]=src.[PhoneTTYDescription],
		[PhoneTTYIsPrivate]=src.[PhoneTTYIsPrivate],
		[PhoneTollFree]=src.[PhoneTollFree],
		[PhoneTollFreeDescription]=src.[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate]=src.[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline]=src.[PhoneNumberHotline],
		[PhoneNumberHotlineDescription]=src.[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate]=src.[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine]=src.[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription]=src.[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate]=src.[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea]=src.[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription]=src.[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate]=src.[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours]=src.[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription]=src.[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate]=src.[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain]=src.[EmailAddressMain],
		[WebsiteAddress]=src.[WebsiteAddress],
		[AgencyStatus]=src.[AgencyStatus],
		[AgencyClassification]=src.[AgencyClassification],
		[CoverageArea]=src.[CoverageArea],
		[CoverageAreaText]=src.[CoverageAreaText],
		[Eligibility]=src.[Eligibility],
		[EligibilityAdult]=src.[EligibilityAdult],
		[EligibilityChild]=src.[EligibilityChild],
		[EligibilityFamily]=src.[EligibilityFamily],
		[EligibilityFemale]=src.[EligibilityFemale],
		[EligibilityMale]=src.[EligibilityMale],
		[EligibilityTeen]=src.[EligibilityTeen],
		[SeniorWorkerName]=src.[SeniorWorkerName],
		[SeniorWorkerTitle]=src.[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress]=src.[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber]=src.[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate]=src.[SeniorWorkerIsPrivate],
		[MainContactName]=src.[MainContactName],
		[MainContactTitle]=src.[MainContactTitle],
		[MainContactEmailAddress]=src.[MainContactEmailAddress],
		[MainContactPhoneNumber]=src.[MainContactPhoneNumber],
		[MainContactType]=src.[MainContactType],
		[MainContactIsPrivate]=src.[MainContactIsPrivate],
		[LicenseAccreditation]=src.[LicenseAccreditation],
		[YearIncorporated]=src.[YearIncorporated],
		[AnnualBudgetTotal]=src.[AnnualBudgetTotal],
		[LegalStatus]=src.[LegalStatus],
		[SourceOfFunds]=src.[SourceOfFunds],
		[ExcludeFromWebsite]=src.[ExcludeFromWebsite],
		[ExcludeFromDirectory]=src.[ExcludeFromDirectory],
		[DisabilitiesAccess]=src.[DisabilitiesAccess],
		[PhysicalLocationDescription]=src.[PhysicalLocationDescription],
		[BusServiceAccess]=src.[BusServiceAccess],
		[PublicAccessTransportation]=src.[PublicAccessTransportation],
		[PaymentMethods]=src.[PaymentMethods],
		[FeeStructureSource]=src.[FeeStructureSource],
		[ApplicationProcess]=src.[ApplicationProcess],
		[ResourceInfo]=src.[ResourceInfo],
		[DocumentsRequired]=src.[DocumentsRequired],
		[LanguagesOffered]=src.[LanguagesOffered],
		[LanguagesOfferedList]=src.[LanguagesOfferedList],
		[AvailabilityNumberOfTimes]=src.[AvailabilityNumberOfTimes],
		[AvailabilityFrequency]=src.[AvailabilityFrequency],
		[AvailabilityPeriod]=src.[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability]=src.[ServiceNotAlwaysAvailability],
		[CapacityType]=src.[CapacityType],
		[ServiceCapacity]=src.[ServiceCapacity],
		[NormalWaitTime]=src.[NormalWaitTime],
		[TemporaryMessage]=src.[TemporaryMessage],
		[TemporaryMessageAppears]=src.[TemporaryMessageAppears],
		[TemporaryMessageExpires]=src.[TemporaryMessageExpires],
		[EnteredOn]=src.[EnteredOn],
		[UpdatedOn]=src.[UpdatedOn],
		[MadeInactiveOn]=src.[MadeInactiveOn],
		[InternalNotes]=src.[InternalNotes],
		[InternalNotesForEditorsAndViewers]=src.[InternalNotesForEditorsAndViewers],
		[HighlightedResource]=src.[HighlightedResource],
		[LastVerifiedOn]=src.[LastVerifiedOn],
		[LastVerifiedByName]=src.[LastVerifiedByName],
		[LastVerifiedByTitle]=src.[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber]=src.[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress]=src.[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy]=src.[LastVerificationApprovedBy],
		[AvailableForDirectory]=src.[AvailableForDirectory],
		[AvailableForReferral]=src.[AvailableForReferral],
		[AvailableForResearch]=src.[AvailableForResearch],
		[PreferredProvider]=src.[PreferredProvider],
		[ConnectsToSiteNum]=src.[ConnectsToSiteNum],
		[ConnectsToProgramNum]=src.[ConnectsToProgramNum],
		[LanguageOfRecord]=src.[LanguageOfRecord],
		[CurrentWorkflowStepCode]=src.[CurrentWorkflowStepCode],
		[VolunteerOpportunities]=src.[VolunteerOpportunities],
		[VolunteerDuties]=src.[VolunteerDuties],
		[IsLinkOnly]=src.[IsLinkOnly],
		[ProgramAgencyNamePublic]=src.[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic]=src.[SiteAgencyNamePublic],
		[Categories]=src.[Categories],
		[TaxonomyTerm]=src.[TaxonomyTerm],
		[TaxonomyTerms]=src.[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated]=src.[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes]=src.[TaxonomyCodes],
		[Coverage]=src.[Coverage],
		[Hours]=src.[Hours],
		[Custom_Public Comments]=src.[Custom_Public Comments],
		[Custom_Former Names]=src.[Custom_Former Names],
		[Custom_Legal Name]=src.[Custom_Legal Name],
		[Custom_Facebook]=src.[Custom_Facebook],
		[Custom_Instagram]=src.[Custom_Instagram],
		[Custom_LinkedIn]=src.[Custom_LinkedIn],
		[Custom_Twitter]=src.[Custom_Twitter],
		[Custom_YouTube]=src.[Custom_YouTube],
		[Custom_Minimum Age]=src.[Custom_Minimum Age],
		[Custom_Maximum Age]=src.[Custom_Maximum Age],
		[dst].[DATE_MODIFIED]=GETDATE(),
		ORG_LEVEL_1=src.ORG_LEVEL_1,
		ORG_DESCRIPTION=src.ORG_DESCRIPTION,
		LOCATION_NAME=src.LOCATION_NAME,
		LOCATION_DESCRIPTION=src.LOCATION_DESCRIPTION,
		SERVICE_NAME_LEVEL_1=src.SERVICE_NAME_LEVEL_1,
		SERVICE_NAME_LEVEL_2=src.SERVICE_NAME_LEVEL_2,
		DESCRIPTION=src.DESCRIPTION,
		dst.ORG_LOCATION_SERVICE='SERVICE',
		dst.DELETION_DATE=src.DELETION_DATE
WHEN NOT MATCHED BY TARGET AND src.TaxonomyLevelName='ProgramAtSite' THEN
	INSERT (
		[ResourceAgencyNum],
		[LangID],
		[PublicName],
		[AlternateName],
		[OfficialName],
		[TaxonomyLevelName],
		[ParentAgency],
		[ParentAgencyNum],
		[RECORD_OWNER],
		[UniqueIDPriorSystem],
		[MailingAttentionName],
		[MailingAddress1],
		[MailingAddress2],
		[MailingCity],
		[MailingStateProvince],
		[MailingPostalCode],
		[MailingCountry],
		[MailingAddressIsPrivate],
		[PhysicalAddress1],
		[PhysicalAddress2],
		[PhysicalCity],
		[PhysicalCounty],
		[PhysicalStateProvince],
		[PhysicalPostalCode],
		[PhysicalCountry],
		[PhysicalAddressIsPrivate],
		[OtherAddress1],
		[OtherAddress2],
		[OtherCity],
		[OtherCounty],
		[OtherStateProvince],
		[OtherPostalCode],
		[OtherCountry],
		[Latitude],
		[Longitude],
		[HoursOfOperation],
		[Phone1Number],
		[Phone1Name],
		[Phone1Description],
		[Phone1IsPrivate],
		[Phone1Type],
		[Phone2Number],
		[Phone2Name],
		[Phone2Description],
		[Phone2IsPrivate],
		[Phone2Type],
		[Phone3Number],
		[Phone3Name],
		[Phone3Description],
		[Phone3IsPrivate],
		[Phone3Type],
		[Phone4Number],
		[Phone4Name],
		[Phone4Description],
		[Phone4IsPrivate],
		[Phone4Type],
		[Phone5Number],
		[Phone5name],
		[Phone5Description],
		[Phone5IsPrivate],
		[Phone5Type],
		[PhoneFax],
		[PhoneFaxDescription],
		[PhoneFaxIsPrivate],
		[PhoneTTY],
		[PhoneTTYDescription],
		[PhoneTTYIsPrivate],
		[PhoneTollFree],
		[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline],
		[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain],
		[WebsiteAddress],
		[AgencyStatus],
		[AgencyClassification],
		[CoverageArea],
		[CoverageAreaText],
		[Eligibility],
		[EligibilityAdult],
		[EligibilityChild],
		[EligibilityFamily],
		[EligibilityFemale],
		[EligibilityMale],
		[EligibilityTeen],
		[SeniorWorkerName],
		[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate],
		[MainContactName],
		[MainContactTitle],
		[MainContactEmailAddress],
		[MainContactPhoneNumber],
		[MainContactType],
		[MainContactIsPrivate],
		[LicenseAccreditation],
		[YearIncorporated],
		[AnnualBudgetTotal],
		[LegalStatus],
		[SourceOfFunds],
		[ExcludeFromWebsite],
		[ExcludeFromDirectory],
		[DisabilitiesAccess],
		[PhysicalLocationDescription],
		[BusServiceAccess],
		[PublicAccessTransportation],
		[PaymentMethods],
		[FeeStructureSource],
		[ApplicationProcess],
		[ResourceInfo],
		[DocumentsRequired],
		[LanguagesOffered],
		[LanguagesOfferedList],
		[AvailabilityNumberOfTimes],
		[AvailabilityFrequency],
		[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability],
		[CapacityType],
		[ServiceCapacity],
		[NormalWaitTime],
		[TemporaryMessage],
		[TemporaryMessageAppears],
		[TemporaryMessageExpires],
		[EnteredOn],
		[UpdatedOn],
		[MadeInactiveOn],
		[InternalNotes],
		[InternalNotesForEditorsAndViewers],
		[HighlightedResource],
		[LastVerifiedOn],
		[LastVerifiedByName],
		[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy],
		[AvailableForDirectory],
		[AvailableForReferral],
		[AvailableForResearch],
		[PreferredProvider],
		[ConnectsToSiteNum],
		[ConnectsToProgramNum],
		[LanguageOfRecord],
		[CurrentWorkflowStepCode],
		[VolunteerOpportunities],
		[VolunteerDuties],
		[IsLinkOnly],
		[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic],
		[Categories],
		[TaxonomyTerm],
		[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes],
		[Coverage],
		[Hours],
		[Custom_Public Comments],
		[Custom_Former Names],
		[Custom_Legal Name],
		[Custom_Facebook],
		[Custom_Instagram],
		[Custom_LinkedIn],
		[Custom_Twitter],
		[Custom_YouTube],
		[Custom_Minimum Age],
		[Custom_Maximum Age],
		[DATE_MODIFIED],
		ORG_LEVEL_1,
		ORG_DESCRIPTION,
		LOCATION_NAME,
		LOCATION_DESCRIPTION,
		SERVICE_NAME_LEVEL_1,
		SERVICE_NAME_LEVEL_2,
		DESCRIPTION,
		ORG_LOCATION_SERVICE,
		DELETION_DATE
	) VALUES (
		src.[ResourceAgencyNum],
		src.LangID,
		src.[PublicName],
		src.[AlternateName],
		src.[OfficialName],
		src.[TaxonomyLevelName],
		src.[ParentAgency],
		src.[ParentAgencyNum],
		src.[RECORD_OWNER],
		src.[UniqueIDPriorSystem],
		src.[MailingAttentionName],
		src.[MailingAddress1],
		src.[MailingAddress2],
		src.[MailingCity],
		src.[MailingStateProvince],
		src.[MailingPostalCode],
		src.[MailingCountry],
		src.[MailingAddressIsPrivate],
		src.[PhysicalAddress1],
		src.[PhysicalAddress2],
		src.[PhysicalCity],
		src.[PhysicalCounty],
		src.[PhysicalStateProvince],
		src.[PhysicalPostalCode],
		src.[PhysicalCountry],
		src.[PhysicalAddressIsPrivate],
		src.[OtherAddress1],
		src.[OtherAddress2],
		src.[OtherCity],
		src.[OtherCounty],
		src.[OtherStateProvince],
		src.[OtherPostalCode],
		src.[OtherCountry],
		src.[Latitude],
		src.[Longitude],
		src.[HoursOfOperation],
		src.[Phone1Number],
		src.[Phone1Name],
		src.[Phone1Description],
		src.[Phone1IsPrivate],
		src.[Phone1Type],
		src.[Phone2Number],
		src.[Phone2Name],
		src.[Phone2Description],
		src.[Phone2IsPrivate],
		src.[Phone2Type],
		src.[Phone3Number],
		src.[Phone3Name],
		src.[Phone3Description],
		src.[Phone3IsPrivate],
		src.[Phone3Type],
		src.[Phone4Number],
		src.[Phone4Name],
		src.[Phone4Description],
		src.[Phone4IsPrivate],
		src.[Phone4Type],
		src.[Phone5Number],
		src.[Phone5name],
		src.[Phone5Description],
		src.[Phone5IsPrivate],
		src.[Phone5Type],
		src.[PhoneFax],
		src.[PhoneFaxDescription],
		src.[PhoneFaxIsPrivate],
		src.[PhoneTTY],
		src.[PhoneTTYDescription],
		src.[PhoneTTYIsPrivate],
		src.[PhoneTollFree],
		src.[PhoneTollFreeDescription],
		src.[PhoneTollFreeIsPrivate],
		src.[PhoneNumberHotline],
		src.[PhoneNumberHotlineDescription],
		src.[PhoneNumberHotlineIsPrivate],
		src.[PhoneNumberBusinessLine],
		src.[PhoneNumberBusinessLineDescription],
		src.[PhoneNumberBusinessLineIsPrivate],
		src.[PhoneNumberOutOfArea],
		src.[PhoneNumberOutOfAreaDescription],
		src.[PhoneNumberOutOfAreaIsPrivate],
		src.[PhoneNumberAfterHours],
		src.[PhoneNumberAfterHoursDescription],
		src.[PhoneNumberAfterHoursIsPrivate],
		src.[EmailAddressMain],
		src.[WebsiteAddress],
		src.[AgencyStatus],
		src.[AgencyClassification],
		src.[CoverageArea],
		src.[CoverageAreaText],
		src.[Eligibility],
		src.[EligibilityAdult],
		src.[EligibilityChild],
		src.[EligibilityFamily],
		src.[EligibilityFemale],
		src.[EligibilityMale],
		src.[EligibilityTeen],
		src.[SeniorWorkerName],
		src.[SeniorWorkerTitle],
		src.[SeniorWorkerEmailAddress],
		src.[SeniorWorkerPhoneNumber],
		src.[SeniorWorkerIsPrivate],
		src.[MainContactName],
		src.[MainContactTitle],
		src.[MainContactEmailAddress],
		src.[MainContactPhoneNumber],
		src.[MainContactType],
		src.[MainContactIsPrivate],
		src.[LicenseAccreditation],
		src.[YearIncorporated],
		src.[AnnualBudgetTotal],
		src.[LegalStatus],
		src.[SourceOfFunds],
		src.[ExcludeFromWebsite],
		src.[ExcludeFromDirectory],
		src.[DisabilitiesAccess],
		src.[PhysicalLocationDescription],
		src.[BusServiceAccess],
		src.[PublicAccessTransportation],
		src.[PaymentMethods],
		src.[FeeStructureSource],
		src.[ApplicationProcess],
		src.[ResourceInfo],
		src.[DocumentsRequired],
		src.[LanguagesOffered],
		src.[LanguagesOfferedList],
		src.[AvailabilityNumberOfTimes],
		src.[AvailabilityFrequency],
		src.[AvailabilityPeriod],
		src.[ServiceNotAlwaysAvailability],
		src.[CapacityType],
		src.[ServiceCapacity],
		src.[NormalWaitTime],
		src.[TemporaryMessage],
		src.[TemporaryMessageAppears],
		src.[TemporaryMessageExpires],
		src.[EnteredOn],
		src.[UpdatedOn],
		src.[MadeInactiveOn],
		src.[InternalNotes],
		src.[InternalNotesForEditorsAndViewers],
		src.[HighlightedResource],
		src.[LastVerifiedOn],
		src.[LastVerifiedByName],
		src.[LastVerifiedByTitle],
		src.[LastVerifiedByPhoneNumber],
		src.[LastVerifiedByEmailAddress],
		src.[LastVerificationApprovedBy],
		src.[AvailableForDirectory],
		src.[AvailableForReferral],
		src.[AvailableForResearch],
		src.[PreferredProvider],
		src.[ConnectsToSiteNum],
		src.[ConnectsToProgramNum],
		src.[LanguageOfRecord],
		src.[CurrentWorkflowStepCode],
		src.[VolunteerOpportunities],
		src.[VolunteerDuties],
		src.[IsLinkOnly],
		src.[ProgramAgencyNamePublic],
		src.[SiteAgencyNamePublic],
		src.[Categories],
		src.[TaxonomyTerm],
		src.[TaxonomyTerms],
		src.[TaxonomyTermsNotDeactivated],
		src.[TaxonomyCodes],
		src.[Coverage],
		src.[Hours],
		src.[Custom_Public Comments],
		src.[Custom_Former Names],
		src.[Custom_Legal Name],
		src.[Custom_Facebook],
		src.[Custom_Instagram],
		src.[Custom_LinkedIn],
		src.[Custom_Twitter],
		src.[Custom_YouTube],
		src.[Custom_Minimum Age],
		src.[Custom_Maximum Age],
		GETDATE(),
		src.ORG_LEVEL_1,
		src.ORG_DESCRIPTION,
		src.LOCATION_NAME,
		src.LOCATION_DESCRIPTION,
		src.SERVICE_NAME_LEVEL_1,
		src.SERVICE_NAME_LEVEL_2,
		src.DESCRIPTION,
		'SERVICE',
		src.DELETION_DATE
	)
OPTION (ROBUST PLAN)
	;

MERGE INTO dbo.CIC_iCarolImportRollup dst
USING (
SELECT 
		(
			SELECT MAX(SYNC_DATE)
			FROM (
				(SELECT SYNC_DATE FROM ( VALUES (s.SYNC_DATE),(a.SYNC_DATE) ) AS i(SYNC_DATE)
				UNION SELECT ISNULL(irr.DELETION_DATE, irr.DATE_MODIFIED) AS SYNC_DATE
				FROM  dbo.CIC_iCarolImportRollup irr WHERE irr.ConnectsToSiteNum=s.ResourceAgencyNum AND irr.TaxonomyLevelName='ProgramAtSite'
				)
			) AS s
		) AS SYNC_DATE,
		COALESCE(s.[ResourceAgencyNum], a.[ResourceAgencyNum]) AS [ResourceAgencyNum],
		COALESCE(s.[LangID], a.[LangID]) AS [LangID],
		COALESCE(s.[PublicName], a.[PublicName]) AS [PublicName],
		COALESCE(s.[AlternateName], a.[AlternateName]) AS [AlternateName],
		COALESCE(s.[OfficialName], a.[OfficialName]) AS [OfficialName],
		COALESCE(s.[TaxonomyLevelName], a.[TaxonomyLevelName]) AS [TaxonomyLevelName],
		COALESCE(s.[ParentAgency], a.[ParentAgency]) AS [ParentAgency],
		COALESCE(s.[ParentAgencyNum], a.[ParentAgencyNum]) AS [ParentAgencyNum],
		s.[Custom_Record Owner (controlled)] AS [RECORD_OWNER],
		COALESCE(s.[UniqueIDPriorSystem], a.[UniqueIDPriorSystem]) AS [UniqueIDPriorSystem],
		COALESCE(s.[MailingAttentionName], a.[MailingAttentionName]) AS [MailingAttentionName],
		COALESCE(s.[MailingAddress1], a.[MailingAddress1]) AS [MailingAddress1],
		COALESCE(s.[MailingAddress2], a.[MailingAddress2]) AS [MailingAddress2],
		COALESCE(s.[MailingCity], a.[MailingCity]) AS [MailingCity],
		COALESCE(s.[MailingStateProvince], a.[MailingStateProvince]) AS [MailingStateProvince],
		COALESCE(s.[MailingPostalCode], a.[MailingPostalCode]) AS [MailingPostalCode],
		COALESCE(s.[MailingCountry], a.[MailingCountry]) AS [MailingCountry],
		COALESCE(s.[MailingAddressIsPrivate], a.[MailingAddressIsPrivate]) AS [MailingAddressIsPrivate],
		COALESCE(s.[PhysicalAddress1], a.[PhysicalAddress1]) AS [PhysicalAddress1],
		COALESCE(s.[PhysicalAddress2], a.[PhysicalAddress2]) AS [PhysicalAddress2],
		COALESCE(s.[PhysicalCity], a.[PhysicalCity]) AS [PhysicalCity],
		COALESCE(s.[PhysicalCounty], a.[PhysicalCounty]) AS [PhysicalCounty],
		COALESCE(s.[PhysicalStateProvince], a.[PhysicalStateProvince]) AS [PhysicalStateProvince],
		COALESCE(s.[PhysicalPostalCode], a.[PhysicalPostalCode]) AS [PhysicalPostalCode],
		COALESCE(s.[PhysicalCountry], a.[PhysicalCountry]) AS [PhysicalCountry],
		COALESCE(s.[PhysicalAddressIsPrivate], a.[PhysicalAddressIsPrivate]) AS [PhysicalAddressIsPrivate],
		COALESCE(s.[OtherAddress1], a.[OtherAddress1]) AS [OtherAddress1],
		COALESCE(s.[OtherAddress2], a.[OtherAddress2]) AS [OtherAddress2],
		COALESCE(s.[OtherCity], a.[OtherCity]) AS [OtherCity],
		COALESCE(s.[OtherCounty], a.[OtherCounty]) AS [OtherCounty],
		COALESCE(s.[OtherStateProvince], a.[OtherStateProvince]) AS [OtherStateProvince],
		COALESCE(s.[OtherPostalCode], a.[OtherPostalCode]) AS [OtherPostalCode],
		COALESCE(s.[OtherCountry], a.[OtherCountry]) AS [OtherCountry],
		COALESCE(NULLIF(s.[Latitude], '0'),NULLIF(a.[Latitude],'0')) AS [Latitude],
		COALESCE(NULLIF(s.[Longitude],'0'), NULLIF(a.[Longitude], '0')) AS [Longitude],
		COALESCE(s.[HoursOfOperation], a.[HoursOfOperation]) AS [HoursOfOperation],
		COALESCE(s.[Phone1Number], a.[Phone1Number]) AS [Phone1Number],
		COALESCE(s.[Phone1Name], a.[Phone1Name]) AS [Phone1Name],
		COALESCE(s.[Phone1Description], a.[Phone1Description]) AS [Phone1Description],
		COALESCE(s.[Phone1IsPrivate], a.[Phone1IsPrivate]) AS [Phone1IsPrivate],
		COALESCE(s.[Phone1Type], a.[Phone1Type]) AS [Phone1Type],
		COALESCE(s.[Phone2Number], a.[Phone2Number]) AS [Phone2Number],
		COALESCE(s.[Phone2Name], a.[Phone2Name]) AS [Phone2Name],
		COALESCE(s.[Phone2Description], a.[Phone2Description]) AS [Phone2Description],
		COALESCE(s.[Phone2IsPrivate], a.[Phone2IsPrivate]) AS [Phone2IsPrivate],
		COALESCE(s.[Phone2Type], a.[Phone2Type]) AS [Phone2Type],
		COALESCE(s.[Phone3Number], a.[Phone3Number]) AS [Phone3Number],
		COALESCE(s.[Phone3Name], a.[Phone3Name]) AS [Phone3Name],
		COALESCE(s.[Phone3Description], a.[Phone3Description]) AS [Phone3Description],
		COALESCE(s.[Phone3IsPrivate], a.[Phone3IsPrivate]) AS [Phone3IsPrivate],
		COALESCE(s.[Phone3Type], a.[Phone3Type]) AS [Phone3Type],
		COALESCE(s.[Phone4Number], a.[Phone4Number]) AS [Phone4Number],
		COALESCE(s.[Phone4Name], a.[Phone4Name]) AS [Phone4Name],
		COALESCE(s.[Phone4Description], a.[Phone4Description]) AS [Phone4Description],
		COALESCE(s.[Phone4IsPrivate], a.[Phone4IsPrivate]) AS [Phone4IsPrivate],
		COALESCE(s.[Phone4Type], a.[Phone4Type]) AS [Phone4Type],
		COALESCE(s.[Phone5Number], a.[Phone5Number]) AS [Phone5Number],
		COALESCE(s.[Phone5name], a.[Phone5name]) AS [Phone5name],
		COALESCE(s.[Phone5Description], a.[Phone5Description]) AS [Phone5Description],
		COALESCE(s.[Phone5IsPrivate], a.[Phone5IsPrivate]) AS [Phone5IsPrivate],
		COALESCE(s.[Phone5Type], a.[Phone5Type]) AS [Phone5Type],
		COALESCE(s.[PhoneFax], a.[PhoneFax]) AS [PhoneFax],
		COALESCE(s.[PhoneFaxDescription], a.[PhoneFaxDescription]) AS [PhoneFaxDescription],
		COALESCE(s.[PhoneFaxIsPrivate], a.[PhoneFaxIsPrivate]) AS [PhoneFaxIsPrivate],
		COALESCE(s.[PhoneTTY], a.[PhoneTTY]) AS [PhoneTTY],
		COALESCE(s.[PhoneTTYDescription], a.[PhoneTTYDescription]) AS [PhoneTTYDescription],
		COALESCE(s.[PhoneTTYIsPrivate], a.[PhoneTTYIsPrivate]) AS [PhoneTTYIsPrivate],
		COALESCE(s.[PhoneTollFree], a.[PhoneTollFree]) AS [PhoneTollFree],
		COALESCE(s.[PhoneTollFreeDescription], a.[PhoneTollFreeDescription]) AS [PhoneTollFreeDescription],
		COALESCE(s.[PhoneTollFreeIsPrivate], a.[PhoneTollFreeIsPrivate]) AS [PhoneTollFreeIsPrivate],
		COALESCE(s.[PhoneNumberHotline], a.[PhoneNumberHotline]) AS [PhoneNumberHotline],
		COALESCE(s.[PhoneNumberHotlineDescription], a.[PhoneNumberHotlineDescription]) AS [PhoneNumberHotlineDescription],
		COALESCE(s.[PhoneNumberHotlineIsPrivate], a.[PhoneNumberHotlineIsPrivate]) AS [PhoneNumberHotlineIsPrivate],
		COALESCE(s.[PhoneNumberBusinessLine], a.[PhoneNumberBusinessLine]) AS [PhoneNumberBusinessLine],
		COALESCE(s.[PhoneNumberBusinessLineDescription], a.[PhoneNumberBusinessLineDescription]) AS [PhoneNumberBusinessLineDescription],
		COALESCE(s.[PhoneNumberBusinessLineIsPrivate], a.[PhoneNumberBusinessLineIsPrivate]) AS [PhoneNumberBusinessLineIsPrivate],
		COALESCE(s.[PhoneNumberOutOfArea], a.[PhoneNumberOutOfArea]) AS [PhoneNumberOutOfArea],
		COALESCE(s.[PhoneNumberOutOfAreaDescription], a.[PhoneNumberOutOfAreaDescription]) AS [PhoneNumberOutOfAreaDescription],
		COALESCE(s.[PhoneNumberOutOfAreaIsPrivate], a.[PhoneNumberOutOfAreaIsPrivate]) AS [PhoneNumberOutOfAreaIsPrivate],
		COALESCE(s.[PhoneNumberAfterHours], a.[PhoneNumberAfterHours]) AS [PhoneNumberAfterHours],
		COALESCE(s.[PhoneNumberAfterHoursDescription], a.[PhoneNumberAfterHoursDescription]) AS [PhoneNumberAfterHoursDescription],
		COALESCE(s.[PhoneNumberAfterHoursIsPrivate], a.[PhoneNumberAfterHoursIsPrivate]) AS [PhoneNumberAfterHoursIsPrivate],
		COALESCE(s.[EmailAddressMain], a.[EmailAddressMain]) AS [EmailAddressMain],
		COALESCE(s.[WebsiteAddress], a.[WebsiteAddress]) AS [WebsiteAddress],
		COALESCE(s.[AgencyStatus], a.[AgencyStatus]) AS [AgencyStatus],
		COALESCE(s.[AgencyClassification], a.[AgencyClassification]) AS [AgencyClassification],
		COALESCE(s.[CoverageArea], a.[CoverageArea]) AS [CoverageArea],
		COALESCE(s.[CoverageAreaText], a.[CoverageAreaText]) AS [CoverageAreaText],
		COALESCE(s.[Eligibility], a.[Eligibility]) AS [Eligibility],
		COALESCE(s.[EligibilityAdult], a.[EligibilityAdult]) AS [EligibilityAdult],
		COALESCE(s.[EligibilityChild], a.[EligibilityChild]) AS [EligibilityChild],
		COALESCE(s.[EligibilityFamily], a.[EligibilityFamily]) AS [EligibilityFamily],
		COALESCE(s.[EligibilityFemale], a.[EligibilityFemale]) AS [EligibilityFemale],
		COALESCE(s.[EligibilityMale], a.[EligibilityMale]) AS [EligibilityMale],
		COALESCE(s.[EligibilityTeen], a.[EligibilityTeen]) AS [EligibilityTeen],
		COALESCE(s.[SeniorWorkerName], a.[SeniorWorkerName]) AS [SeniorWorkerName],
		COALESCE(s.[SeniorWorkerTitle], a.[SeniorWorkerTitle]) AS [SeniorWorkerTitle],
		COALESCE(s.[SeniorWorkerEmailAddress], a.[SeniorWorkerEmailAddress]) AS [SeniorWorkerEmailAddress],
		COALESCE(s.[SeniorWorkerPhoneNumber], a.[SeniorWorkerPhoneNumber]) AS [SeniorWorkerPhoneNumber],
		COALESCE(s.[SeniorWorkerIsPrivate], a.[SeniorWorkerIsPrivate]) AS [SeniorWorkerIsPrivate],
		COALESCE(s.[MainContactName], a.[MainContactName]) AS [MainContactName],
		COALESCE(s.[MainContactTitle], a.[MainContactTitle]) AS [MainContactTitle],
		COALESCE(s.[MainContactEmailAddress], a.[MainContactEmailAddress]) AS [MainContactEmailAddress],
		COALESCE(s.[MainContactPhoneNumber], a.[MainContactPhoneNumber]) AS [MainContactPhoneNumber],
		COALESCE(s.[MainContactType], a.[MainContactType]) AS [MainContactType],
		COALESCE(s.[MainContactIsPrivate], a.[MainContactIsPrivate]) AS [MainContactIsPrivate],
		COALESCE(s.[LicenseAccreditation], a.[LicenseAccreditation]) AS [LicenseAccreditation],
		COALESCE(s.[YearIncorporated], a.[YearIncorporated]) AS [YearIncorporated],
		COALESCE(s.[AnnualBudgetTotal], a.[AnnualBudgetTotal]) AS [AnnualBudgetTotal],
		COALESCE(s.[LegalStatus], a.[LegalStatus]) AS [LegalStatus],
		COALESCE(s.[SourceOfFunds], a.[SourceOfFunds]) AS [SourceOfFunds],
		COALESCE(s.[ExcludeFromWebsite], a.[ExcludeFromWebsite]) AS [ExcludeFromWebsite],
		COALESCE(s.[ExcludeFromDirectory], a.[ExcludeFromDirectory]) AS [ExcludeFromDirectory],
		COALESCE(s.[DisabilitiesAccess], a.[DisabilitiesAccess]) AS [DisabilitiesAccess],
		COALESCE(s.[PhysicalLocationDescription], a.[PhysicalLocationDescription]) AS [PhysicalLocationDescription],
		COALESCE(s.[BusServiceAccess], a.[BusServiceAccess]) AS [BusServiceAccess],
		COALESCE(s.[PublicAccessTransportation], a.[PublicAccessTransportation]) AS [PublicAccessTransportation],
		COALESCE(s.[PaymentMethods], a.[PaymentMethods]) AS [PaymentMethods],
		COALESCE(s.[FeeStructureSource], a.[FeeStructureSource]) AS [FeeStructureSource],
		COALESCE(s.[ApplicationProcess], a.[ApplicationProcess]) AS [ApplicationProcess],
		COALESCE(s.[ResourceInfo], a.[ResourceInfo]) AS [ResourceInfo],
		COALESCE(s.[DocumentsRequired], a.[DocumentsRequired]) AS [DocumentsRequired],
		COALESCE(s.[LanguagesOffered], a.[LanguagesOffered]) AS [LanguagesOffered],
		COALESCE(s.[LanguagesOfferedList], a.[LanguagesOfferedList]) AS [LanguagesOfferedList],
		COALESCE(s.[AvailabilityNumberOfTimes], a.[AvailabilityNumberOfTimes]) AS [AvailabilityNumberOfTimes],
		COALESCE(s.[AvailabilityFrequency], a.[AvailabilityFrequency]) AS [AvailabilityFrequency],
		COALESCE(s.[AvailabilityPeriod], a.[AvailabilityPeriod]) AS [AvailabilityPeriod],
		COALESCE(s.[ServiceNotAlwaysAvailability], a.[ServiceNotAlwaysAvailability]) AS [ServiceNotAlwaysAvailability],
		COALESCE(s.[CapacityType], a.[CapacityType]) AS [CapacityType],
		COALESCE(s.[ServiceCapacity], a.[ServiceCapacity]) AS [ServiceCapacity],
		COALESCE(s.[NormalWaitTime], a.[NormalWaitTime]) AS [NormalWaitTime],
		COALESCE(s.[TemporaryMessage], a.[TemporaryMessage]) AS [TemporaryMessage],
		COALESCE(s.[TemporaryMessageAppears], a.[TemporaryMessageAppears]) AS [TemporaryMessageAppears],
		COALESCE(s.[TemporaryMessageExpires], a.[TemporaryMessageExpires]) AS [TemporaryMessageExpires],
		COALESCE(s.[EnteredOn], a.[EnteredOn]) AS [EnteredOn],
		COALESCE(s.[UpdatedOn], a.[UpdatedOn]) AS [UpdatedOn],
		COALESCE(s.[MadeInactiveOn], a.[MadeInactiveOn]) AS [MadeInactiveOn],
		COALESCE(s.[InternalNotes], a.[InternalNotes]) AS [InternalNotes],
		COALESCE(s.[InternalNotesForEditorsAndViewers], a.[InternalNotesForEditorsAndViewers]) AS [InternalNotesForEditorsAndViewers],
		COALESCE(s.[HighlightedResource], a.[HighlightedResource]) AS [HighlightedResource],
		COALESCE(s.[LastVerifiedOn], a.[LastVerifiedOn]) AS [LastVerifiedOn],
		COALESCE(s.[LastVerifiedByName], a.[LastVerifiedByName]) AS [LastVerifiedByName],
		COALESCE(s.[LastVerifiedByTitle], a.[LastVerifiedByTitle]) AS [LastVerifiedByTitle],
		COALESCE(s.[LastVerifiedByPhoneNumber], a.[LastVerifiedByPhoneNumber]) AS [LastVerifiedByPhoneNumber],
		COALESCE(s.[LastVerifiedByEmailAddress], a.[LastVerifiedByEmailAddress]) AS [LastVerifiedByEmailAddress],
		COALESCE(s.[LastVerificationApprovedBy], a.[LastVerificationApprovedBy]) AS [LastVerificationApprovedBy],
		COALESCE(s.[AvailableForDirectory], a.[AvailableForDirectory]) AS [AvailableForDirectory],
		COALESCE(s.[AvailableForReferral], a.[AvailableForReferral]) AS [AvailableForReferral],
		COALESCE(s.[AvailableForResearch], a.[AvailableForResearch]) AS [AvailableForResearch],
		COALESCE(s.[PreferredProvider], a.[PreferredProvider]) AS [PreferredProvider],
		COALESCE(s.[ConnectsToSiteNum], a.[ConnectsToSiteNum]) AS [ConnectsToSiteNum],
		COALESCE(s.[ConnectsToProgramNum], a.[ConnectsToProgramNum]) AS [ConnectsToProgramNum],
		COALESCE(s.[LanguageOfRecord], a.[LanguageOfRecord]) AS [LanguageOfRecord],
		COALESCE(s.[CurrentWorkflowStepCode], a.[CurrentWorkflowStepCode]) AS [CurrentWorkflowStepCode],
		COALESCE(s.[VolunteerOpportunities], a.[VolunteerOpportunities]) AS [VolunteerOpportunities],
		COALESCE(s.[VolunteerDuties], a.[VolunteerDuties]) AS [VolunteerDuties],
		COALESCE(s.[IsLinkOnly], a.[IsLinkOnly]) AS [IsLinkOnly],
		COALESCE(s.[ProgramAgencyNamePublic], a.[ProgramAgencyNamePublic]) AS [ProgramAgencyNamePublic],
		COALESCE(s.[SiteAgencyNamePublic], a.[SiteAgencyNamePublic]) AS [SiteAgencyNamePublic],
		COALESCE(s.[Categories], a.[Categories]) AS [Categories],
		COALESCE(s.[TaxonomyTerm], a.[TaxonomyTerm]) AS [TaxonomyTerm],
		COALESCE(s.[TaxonomyTerms], a.[TaxonomyTerms]) AS [TaxonomyTerms],
		COALESCE(s.[TaxonomyTermsNotDeactivated], a.[TaxonomyTermsNotDeactivated]) AS [TaxonomyTermsNotDeactivated],
		COALESCE(s.[TaxonomyCodes], a.[TaxonomyCodes]) AS [TaxonomyCodes],
		COALESCE(s.[Coverage], a.[Coverage]) AS [Coverage],
		COALESCE(s.[Hours], a.[Hours]) AS [Hours],
		COALESCE(s.[Custom_Public Comments], a.[Custom_Public Comments]) AS [Custom_Public Comments],
		COALESCE(s.[Custom_Former Names], a.[Custom_Former Names]) AS [Custom_Former Names],
		COALESCE(s.[Custom_Legal Name], a.[Custom_Legal Name]) AS [Custom_Legal Name],
		COALESCE(s.[Custom_Facebook], a.[Custom_Facebook]) AS [Custom_Facebook],
		COALESCE(s.[Custom_Instagram], a.[Custom_Instagram]) AS [Custom_Instagram],
		COALESCE(s.[Custom_LinkedIn], a.[Custom_LinkedIn]) AS [Custom_LinkedIn],
		COALESCE(s.[Custom_Twitter], a.[Custom_Twitter]) AS [Custom_Twitter],
		COALESCE(s.[Custom_YouTube], a.[Custom_YouTube]) AS [Custom_YouTube],
		COALESCE(s.[Custom_Minimum Age], a.[Custom_Minimum Age]) AS [Custom_Minimum Age],
		COALESCE(s.[Custom_Maximum Age], a.[Custom_Maximum Age]) AS [Custom_Maximum Age],
		a.PublicName AS ORG_LEVEL_1,
		a.AgencyDescription AS ORG_DESCRIPTION,
		s.PublicName AS LOCATION_NAME,
		s.AgencyDescription AS LOCATION_DESCRIPTION,
		s.DELETION_DATE
FROM dbo.CIC_iCarolImport AS s
LEFT JOIN dbo.CIC_iCarolImport a
	ON s.ParentAgencyNum=a.ResourceAgencyNum AND a.TaxonomyLevelName='Agency' AND a.LangID=s.LangID
WHERE s.TaxonomyLevelName='Site'
) AS src
ON src.ResourceAgencyNum=dst.ResourceAgencyNum AND src.LangID=dst.LangID AND src.TaxonomyLevelName = 'Site'
WHEN MATCHED AND src.SYNC_DATE > dst.DATE_MODIFIED THEN 
	UPDATE SET 
		[PublicName]=src.[PublicName],
		[AlternateName]=src.[AlternateName],
		[OfficialName]=src.[OfficialName],
		[TaxonomyLevelName]=src.[TaxonomyLevelName],
		[ParentAgency]=src.[ParentAgency],
		[ParentAgencyNum]=src.[ParentAgencyNum],
		[RECORD_OWNER]=src.[RECORD_OWNER],
		[UniqueIDPriorSystem]=src.[UniqueIDPriorSystem],
		[MailingAttentionName]=src.[MailingAttentionName],
		[MailingAddress1]=src.[MailingAddress1],
		[MailingAddress2]=src.[MailingAddress2],
		[MailingCity]=src.[MailingCity],
		[MailingStateProvince]=src.[MailingStateProvince],
		[MailingPostalCode]=src.[MailingPostalCode],
		[MailingCountry]=src.[MailingCountry],
		[MailingAddressIsPrivate]=src.[MailingAddressIsPrivate],
		[PhysicalAddress1]=src.[PhysicalAddress1],
		[PhysicalAddress2]=src.[PhysicalAddress2],
		[PhysicalCity]=src.[PhysicalCity],
		[PhysicalCounty]=src.[PhysicalCounty],
		[PhysicalStateProvince]=src.[PhysicalStateProvince],
		[PhysicalPostalCode]=src.[PhysicalPostalCode],
		[PhysicalCountry]=src.[PhysicalCountry],
		[PhysicalAddressIsPrivate]=src.[PhysicalAddressIsPrivate],
		[OtherAddress1]=src.[OtherAddress1],
		[OtherAddress2]=src.[OtherAddress2],
		[OtherCity]=src.[OtherCity],
		[OtherCounty]=src.[OtherCounty],
		[OtherStateProvince]=src.[OtherStateProvince],
		[OtherPostalCode]=src.[OtherPostalCode],
		[OtherCountry]=src.[OtherCountry],
		[Latitude]=src.[Latitude],
		[Longitude]=src.[Longitude],
		[HoursOfOperation]=src.[HoursOfOperation],
		[Phone1Number]=src.[Phone1Number],
		[Phone1Name]=src.[Phone1Name],
		[Phone1Description]=src.[Phone1Description],
		[Phone1IsPrivate]=src.[Phone1IsPrivate],
		[Phone1Type]=src.[Phone1Type],
		[Phone2Number]=src.[Phone2Number],
		[Phone2Name]=src.[Phone2Name],
		[Phone2Description]=src.[Phone2Description],
		[Phone2IsPrivate]=src.[Phone2IsPrivate],
		[Phone2Type]=src.[Phone2Type],
		[Phone3Number]=src.[Phone3Number],
		[Phone3Name]=src.[Phone3Name],
		[Phone3Description]=src.[Phone3Description],
		[Phone3IsPrivate]=src.[Phone3IsPrivate],
		[Phone3Type]=src.[Phone3Type],
		[Phone4Number]=src.[Phone4Number],
		[Phone4Name]=src.[Phone4Name],
		[Phone4Description]=src.[Phone4Description],
		[Phone4IsPrivate]=src.[Phone4IsPrivate],
		[Phone4Type]=src.[Phone4Type],
		[Phone5Number]=src.[Phone5Number],
		[Phone5name]=src.[Phone5name],
		[Phone5Description]=src.[Phone5Description],
		[Phone5IsPrivate]=src.[Phone5IsPrivate],
		[Phone5Type]=src.[Phone5Type],
		[PhoneFax]=src.[PhoneFax],
		[PhoneFaxDescription]=src.[PhoneFaxDescription],
		[PhoneFaxIsPrivate]=src.[PhoneFaxIsPrivate],
		[PhoneTTY]=src.[PhoneTTY],
		[PhoneTTYDescription]=src.[PhoneTTYDescription],
		[PhoneTTYIsPrivate]=src.[PhoneTTYIsPrivate],
		[PhoneTollFree]=src.[PhoneTollFree],
		[PhoneTollFreeDescription]=src.[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate]=src.[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline]=src.[PhoneNumberHotline],
		[PhoneNumberHotlineDescription]=src.[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate]=src.[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine]=src.[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription]=src.[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate]=src.[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea]=src.[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription]=src.[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate]=src.[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours]=src.[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription]=src.[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate]=src.[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain]=src.[EmailAddressMain],
		[WebsiteAddress]=src.[WebsiteAddress],
		[AgencyStatus]=src.[AgencyStatus],
		[AgencyClassification]=src.[AgencyClassification],
		[CoverageArea]=src.[CoverageArea],
		[CoverageAreaText]=src.[CoverageAreaText],
		[Eligibility]=src.[Eligibility],
		[EligibilityAdult]=src.[EligibilityAdult],
		[EligibilityChild]=src.[EligibilityChild],
		[EligibilityFamily]=src.[EligibilityFamily],
		[EligibilityFemale]=src.[EligibilityFemale],
		[EligibilityMale]=src.[EligibilityMale],
		[EligibilityTeen]=src.[EligibilityTeen],
		[SeniorWorkerName]=src.[SeniorWorkerName],
		[SeniorWorkerTitle]=src.[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress]=src.[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber]=src.[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate]=src.[SeniorWorkerIsPrivate],
		[MainContactName]=src.[MainContactName],
		[MainContactTitle]=src.[MainContactTitle],
		[MainContactEmailAddress]=src.[MainContactEmailAddress],
		[MainContactPhoneNumber]=src.[MainContactPhoneNumber],
		[MainContactType]=src.[MainContactType],
		[MainContactIsPrivate]=src.[MainContactIsPrivate],
		[LicenseAccreditation]=src.[LicenseAccreditation],
		[YearIncorporated]=src.[YearIncorporated],
		[AnnualBudgetTotal]=src.[AnnualBudgetTotal],
		[LegalStatus]=src.[LegalStatus],
		[SourceOfFunds]=src.[SourceOfFunds],
		[ExcludeFromWebsite]=src.[ExcludeFromWebsite],
		[ExcludeFromDirectory]=src.[ExcludeFromDirectory],
		[DisabilitiesAccess]=src.[DisabilitiesAccess],
		[PhysicalLocationDescription]=src.[PhysicalLocationDescription],
		[BusServiceAccess]=src.[BusServiceAccess],
		[PublicAccessTransportation]=src.[PublicAccessTransportation],
		[PaymentMethods]=src.[PaymentMethods],
		[FeeStructureSource]=src.[FeeStructureSource],
		[ApplicationProcess]=src.[ApplicationProcess],
		[ResourceInfo]=src.[ResourceInfo],
		[DocumentsRequired]=src.[DocumentsRequired],
		[LanguagesOffered]=src.[LanguagesOffered],
		[LanguagesOfferedList]=src.[LanguagesOfferedList],
		[AvailabilityNumberOfTimes]=src.[AvailabilityNumberOfTimes],
		[AvailabilityFrequency]=src.[AvailabilityFrequency],
		[AvailabilityPeriod]=src.[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability]=src.[ServiceNotAlwaysAvailability],
		[CapacityType]=src.[CapacityType],
		[ServiceCapacity]=src.[ServiceCapacity],
		[NormalWaitTime]=src.[NormalWaitTime],
		[TemporaryMessage]=src.[TemporaryMessage],
		[TemporaryMessageAppears]=src.[TemporaryMessageAppears],
		[TemporaryMessageExpires]=src.[TemporaryMessageExpires],
		[EnteredOn]=src.[EnteredOn],
		[UpdatedOn]=src.[UpdatedOn],
		[MadeInactiveOn]=src.[MadeInactiveOn],
		[InternalNotes]=src.[InternalNotes],
		[InternalNotesForEditorsAndViewers]=src.[InternalNotesForEditorsAndViewers],
		[HighlightedResource]=src.[HighlightedResource],
		[LastVerifiedOn]=src.[LastVerifiedOn],
		[LastVerifiedByName]=src.[LastVerifiedByName],
		[LastVerifiedByTitle]=src.[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber]=src.[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress]=src.[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy]=src.[LastVerificationApprovedBy],
		[AvailableForDirectory]=src.[AvailableForDirectory],
		[AvailableForReferral]=src.[AvailableForReferral],
		[AvailableForResearch]=src.[AvailableForResearch],
		[PreferredProvider]=src.[PreferredProvider],
		[ConnectsToSiteNum]=src.[ConnectsToSiteNum],
		[ConnectsToProgramNum]=src.[ConnectsToProgramNum],
		[LanguageOfRecord]=src.[LanguageOfRecord],
		[CurrentWorkflowStepCode]=src.[CurrentWorkflowStepCode],
		[VolunteerOpportunities]=src.[VolunteerOpportunities],
		[VolunteerDuties]=src.[VolunteerDuties],
		[IsLinkOnly]=src.[IsLinkOnly],
		[ProgramAgencyNamePublic]=src.[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic]=src.[SiteAgencyNamePublic],
		[Categories]=src.[Categories],
		[TaxonomyTerm]=src.[TaxonomyTerm],
		[TaxonomyTerms]=src.[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated]=src.[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes]=src.[TaxonomyCodes],
		[Coverage]=src.[Coverage],
		[Hours]=src.[Hours],
		[Custom_Public Comments]=src.[Custom_Public Comments],
		[Custom_Former Names]=src.[Custom_Former Names],
		[Custom_Legal Name]=src.[Custom_Legal Name],
		[Custom_Facebook]=src.[Custom_Facebook],
		[Custom_Instagram]=src.[Custom_Instagram],
		[Custom_LinkedIn]=src.[Custom_LinkedIn],
		[Custom_Twitter]=src.[Custom_Twitter],
		[Custom_YouTube]=src.[Custom_YouTube],
		[Custom_Minimum Age]=src.[Custom_Minimum Age],
		[Custom_Maximum Age]=src.[Custom_Maximum Age],
		[dst].[DATE_MODIFIED]=GETDATE(),
		ORG_LEVEL_1=src.ORG_LEVEL_1,
		ORG_DESCRIPTION=src.ORG_DESCRIPTION,
		LOCATION_NAME=src.LOCATION_NAME,
		LOCATION_DESCRIPTION=src.LOCATION_DESCRIPTION,
		dst.ORG_LOCATION_SERVICE='SITE',
		dst.DELETION_DATE=src.DELETION_DATE
WHEN NOT MATCHED BY TARGET AND src.TaxonomyLevelName='Site' THEN
	INSERT (
		[ResourceAgencyNum],
		[LangID],
		[PublicName],
		[AlternateName],
		[OfficialName],
		[TaxonomyLevelName],
		[ParentAgency],
		[ParentAgencyNum],
		[RECORD_OWNER],
		[UniqueIDPriorSystem],
		[MailingAttentionName],
		[MailingAddress1],
		[MailingAddress2],
		[MailingCity],
		[MailingStateProvince],
		[MailingPostalCode],
		[MailingCountry],
		[MailingAddressIsPrivate],
		[PhysicalAddress1],
		[PhysicalAddress2],
		[PhysicalCity],
		[PhysicalCounty],
		[PhysicalStateProvince],
		[PhysicalPostalCode],
		[PhysicalCountry],
		[PhysicalAddressIsPrivate],
		[OtherAddress1],
		[OtherAddress2],
		[OtherCity],
		[OtherCounty],
		[OtherStateProvince],
		[OtherPostalCode],
		[OtherCountry],
		[Latitude],
		[Longitude],
		[HoursOfOperation],
		[Phone1Number],
		[Phone1Name],
		[Phone1Description],
		[Phone1IsPrivate],
		[Phone1Type],
		[Phone2Number],
		[Phone2Name],
		[Phone2Description],
		[Phone2IsPrivate],
		[Phone2Type],
		[Phone3Number],
		[Phone3Name],
		[Phone3Description],
		[Phone3IsPrivate],
		[Phone3Type],
		[Phone4Number],
		[Phone4Name],
		[Phone4Description],
		[Phone4IsPrivate],
		[Phone4Type],
		[Phone5Number],
		[Phone5name],
		[Phone5Description],
		[Phone5IsPrivate],
		[Phone5Type],
		[PhoneFax],
		[PhoneFaxDescription],
		[PhoneFaxIsPrivate],
		[PhoneTTY],
		[PhoneTTYDescription],
		[PhoneTTYIsPrivate],
		[PhoneTollFree],
		[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline],
		[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain],
		[WebsiteAddress],
		[AgencyStatus],
		[AgencyClassification],
		[CoverageArea],
		[CoverageAreaText],
		[Eligibility],
		[EligibilityAdult],
		[EligibilityChild],
		[EligibilityFamily],
		[EligibilityFemale],
		[EligibilityMale],
		[EligibilityTeen],
		[SeniorWorkerName],
		[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate],
		[MainContactName],
		[MainContactTitle],
		[MainContactEmailAddress],
		[MainContactPhoneNumber],
		[MainContactType],
		[MainContactIsPrivate],
		[LicenseAccreditation],
		[YearIncorporated],
		[AnnualBudgetTotal],
		[LegalStatus],
		[SourceOfFunds],
		[ExcludeFromWebsite],
		[ExcludeFromDirectory],
		[DisabilitiesAccess],
		[PhysicalLocationDescription],
		[BusServiceAccess],
		[PublicAccessTransportation],
		[PaymentMethods],
		[FeeStructureSource],
		[ApplicationProcess],
		[ResourceInfo],
		[DocumentsRequired],
		[LanguagesOffered],
		[LanguagesOfferedList],
		[AvailabilityNumberOfTimes],
		[AvailabilityFrequency],
		[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability],
		[CapacityType],
		[ServiceCapacity],
		[NormalWaitTime],
		[TemporaryMessage],
		[TemporaryMessageAppears],
		[TemporaryMessageExpires],
		[EnteredOn],
		[UpdatedOn],
		[MadeInactiveOn],
		[InternalNotes],
		[InternalNotesForEditorsAndViewers],
		[HighlightedResource],
		[LastVerifiedOn],
		[LastVerifiedByName],
		[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy],
		[AvailableForDirectory],
		[AvailableForReferral],
		[AvailableForResearch],
		[PreferredProvider],
		[ConnectsToSiteNum],
		[ConnectsToProgramNum],
		[LanguageOfRecord],
		[CurrentWorkflowStepCode],
		[VolunteerOpportunities],
		[VolunteerDuties],
		[IsLinkOnly],
		[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic],
		[Categories],
		[TaxonomyTerm],
		[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes],
		[Coverage],
		[Hours],
		[Custom_Public Comments],
		[Custom_Former Names],
		[Custom_Legal Name],
		[Custom_Facebook],
		[Custom_Instagram],
		[Custom_LinkedIn],
		[Custom_Twitter],
		[Custom_YouTube],
		[Custom_Minimum Age],
		[Custom_Maximum Age],
		[DATE_MODIFIED],
		ORG_LEVEL_1,
		ORG_DESCRIPTION,
		LOCATION_NAME,
		LOCATION_DESCRIPTION,
		ORG_LOCATION_SERVICE,
		DELETION_DATE
	) VALUES (
		src.[ResourceAgencyNum],
		src.LangID,
		src.[PublicName],
		src.[AlternateName],
		src.[OfficialName],
		src.[TaxonomyLevelName],
		src.[ParentAgency],
		src.[ParentAgencyNum],
		src.[RECORD_OWNER],
		src.[UniqueIDPriorSystem],
		src.[MailingAttentionName],
		src.[MailingAddress1],
		src.[MailingAddress2],
		src.[MailingCity],
		src.[MailingStateProvince],
		src.[MailingPostalCode],
		src.[MailingCountry],
		src.[MailingAddressIsPrivate],
		src.[PhysicalAddress1],
		src.[PhysicalAddress2],
		src.[PhysicalCity],
		src.[PhysicalCounty],
		src.[PhysicalStateProvince],
		src.[PhysicalPostalCode],
		src.[PhysicalCountry],
		src.[PhysicalAddressIsPrivate],
		src.[OtherAddress1],
		src.[OtherAddress2],
		src.[OtherCity],
		src.[OtherCounty],
		src.[OtherStateProvince],
		src.[OtherPostalCode],
		src.[OtherCountry],
		src.[Latitude],
		src.[Longitude],
		src.[HoursOfOperation],
		src.[Phone1Number],
		src.[Phone1Name],
		src.[Phone1Description],
		src.[Phone1IsPrivate],
		src.[Phone1Type],
		src.[Phone2Number],
		src.[Phone2Name],
		src.[Phone2Description],
		src.[Phone2IsPrivate],
		src.[Phone2Type],
		src.[Phone3Number],
		src.[Phone3Name],
		src.[Phone3Description],
		src.[Phone3IsPrivate],
		src.[Phone3Type],
		src.[Phone4Number],
		src.[Phone4Name],
		src.[Phone4Description],
		src.[Phone4IsPrivate],
		src.[Phone4Type],
		src.[Phone5Number],
		src.[Phone5name],
		src.[Phone5Description],
		src.[Phone5IsPrivate],
		src.[Phone5Type],
		src.[PhoneFax],
		src.[PhoneFaxDescription],
		src.[PhoneFaxIsPrivate],
		src.[PhoneTTY],
		src.[PhoneTTYDescription],
		src.[PhoneTTYIsPrivate],
		src.[PhoneTollFree],
		src.[PhoneTollFreeDescription],
		src.[PhoneTollFreeIsPrivate],
		src.[PhoneNumberHotline],
		src.[PhoneNumberHotlineDescription],
		src.[PhoneNumberHotlineIsPrivate],
		src.[PhoneNumberBusinessLine],
		src.[PhoneNumberBusinessLineDescription],
		src.[PhoneNumberBusinessLineIsPrivate],
		src.[PhoneNumberOutOfArea],
		src.[PhoneNumberOutOfAreaDescription],
		src.[PhoneNumberOutOfAreaIsPrivate],
		src.[PhoneNumberAfterHours],
		src.[PhoneNumberAfterHoursDescription],
		src.[PhoneNumberAfterHoursIsPrivate],
		src.[EmailAddressMain],
		src.[WebsiteAddress],
		src.[AgencyStatus],
		src.[AgencyClassification],
		src.[CoverageArea],
		src.[CoverageAreaText],
		src.[Eligibility],
		src.[EligibilityAdult],
		src.[EligibilityChild],
		src.[EligibilityFamily],
		src.[EligibilityFemale],
		src.[EligibilityMale],
		src.[EligibilityTeen],
		src.[SeniorWorkerName],
		src.[SeniorWorkerTitle],
		src.[SeniorWorkerEmailAddress],
		src.[SeniorWorkerPhoneNumber],
		src.[SeniorWorkerIsPrivate],
		src.[MainContactName],
		src.[MainContactTitle],
		src.[MainContactEmailAddress],
		src.[MainContactPhoneNumber],
		src.[MainContactType],
		src.[MainContactIsPrivate],
		src.[LicenseAccreditation],
		src.[YearIncorporated],
		src.[AnnualBudgetTotal],
		src.[LegalStatus],
		src.[SourceOfFunds],
		src.[ExcludeFromWebsite],
		src.[ExcludeFromDirectory],
		src.[DisabilitiesAccess],
		src.[PhysicalLocationDescription],
		src.[BusServiceAccess],
		src.[PublicAccessTransportation],
		src.[PaymentMethods],
		src.[FeeStructureSource],
		src.[ApplicationProcess],
		src.[ResourceInfo],
		src.[DocumentsRequired],
		src.[LanguagesOffered],
		src.[LanguagesOfferedList],
		src.[AvailabilityNumberOfTimes],
		src.[AvailabilityFrequency],
		src.[AvailabilityPeriod],
		src.[ServiceNotAlwaysAvailability],
		src.[CapacityType],
		src.[ServiceCapacity],
		src.[NormalWaitTime],
		src.[TemporaryMessage],
		src.[TemporaryMessageAppears],
		src.[TemporaryMessageExpires],
		src.[EnteredOn],
		src.[UpdatedOn],
		src.[MadeInactiveOn],
		src.[InternalNotes],
		src.[InternalNotesForEditorsAndViewers],
		src.[HighlightedResource],
		src.[LastVerifiedOn],
		src.[LastVerifiedByName],
		src.[LastVerifiedByTitle],
		src.[LastVerifiedByPhoneNumber],
		src.[LastVerifiedByEmailAddress],
		src.[LastVerificationApprovedBy],
		src.[AvailableForDirectory],
		src.[AvailableForReferral],
		src.[AvailableForResearch],
		src.[PreferredProvider],
		src.[ConnectsToSiteNum],
		src.[ConnectsToProgramNum],
		src.[LanguageOfRecord],
		src.[CurrentWorkflowStepCode],
		src.[VolunteerOpportunities],
		src.[VolunteerDuties],
		src.[IsLinkOnly],
		src.[ProgramAgencyNamePublic],
		src.[SiteAgencyNamePublic],
		src.[Categories],
		src.[TaxonomyTerm],
		src.[TaxonomyTerms],
		src.[TaxonomyTermsNotDeactivated],
		src.[TaxonomyCodes],
		src.[Coverage],
		src.[Hours],
		src.[Custom_Public Comments],
		src.[Custom_Former Names],
		src.[Custom_Legal Name],
		src.[Custom_Facebook],
		src.[Custom_Instagram],
		src.[Custom_LinkedIn],
		src.[Custom_Twitter],
		src.[Custom_YouTube],
		src.[Custom_Minimum Age],
		src.[Custom_Maximum Age],
		GETDATE(),
		src.ORG_LEVEL_1,
		src.ORG_DESCRIPTION,
		src.LOCATION_NAME,
		src.LOCATION_DESCRIPTION,
		'SITE',
		src.DELETION_DATE
	)
OPTION (ROBUST PLAN)
	;

SELECT m.MemberID, m.DefaultEmailNameCIC, m.BaseURLCIC
FROM dbo.STP_Member m


RETURN @Error

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_CIC_iCarolImport_Rollup] TO [cioc_login_role]
GO
