SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_CIC_iCarolImport_Incremental]
	@SYNC_DATE SMALLDATETIME,
	@source_file nvarchar(MAX) 
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

DECLARE	@Error		INT
SET @Error = 0

IF OBJECT_ID('tempdb.dbo.#source', 'U') IS NOT NULL
  DROP TABLE #source; 

CREATE TABLE #source (
	[ResourceAgencyNum] [NVARCHAR](50) COLLATE Latin1_General_100_CI_AI NOT NULL PRIMARY KEY,
	[ImportDate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ImportStatus] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Refresh] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PublicName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AlternateName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OfficialName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TaxonomyLevelName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ParentAgency] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ParentAgencyNum] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[RecordOwner] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[UniqueIDPriorSystem] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingAttentionName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingAddress1] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingAddress2] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingCity] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingStateProvince] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingPostalCode] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingCountry] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingAddressIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalAddress1] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalAddress2] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalCity] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalCounty] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalStateProvince] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalPostalCode] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalCountry] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalAddressIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherAddress1] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherAddress2] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherCity] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherCounty] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherStateProvince] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherPostalCode] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherCountry] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Latitude] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Longitude] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[HoursOfOperation] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone1Number] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone1Name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone1Description] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone1IsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone1Type] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone2Number] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone2Name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone2Description] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone2IsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone2Type] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone3Number] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone3Name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone3Description] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone3IsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone3Type] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone4Number] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone4Name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone4Description] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone4IsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone4Type] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone5Number] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone5name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone5Description] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone5IsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Phone5Type] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneFax] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneFaxDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneFaxIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTTY] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTTYDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTTYIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTollFree] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTollFreeDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneTollFreeIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberHotline] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberHotlineDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberHotlineIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberBusinessLine] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberBusinessLineDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberBusinessLineIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberOutOfArea] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberOutOfAreaDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberOutOfAreaIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberAfterHours] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberAfterHoursDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhoneNumberAfterHoursIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EmailAddressMain] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[WebsiteAddress] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AgencyStatus] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AgencyClassification] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AgencyDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SearchHints] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[CoverageArea] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[CoverageAreaText] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Eligibility] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityAdult] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityChild] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityFamily] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityFemale] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityMale] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EligibilityTeen] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SeniorWorkerName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SeniorWorkerTitle] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SeniorWorkerEmailAddress] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SeniorWorkerPhoneNumber] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SeniorWorkerIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactTitle] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactEmailAddress] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactPhoneNumber] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactType] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MainContactIsPrivate] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LicenseAccreditation] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[IRSStatus] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[FEIN] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[YearIncorporated] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AnnualBudgetTotal] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LegalStatus] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SourceOfFunds] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ExcludeFromWebsite] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ExcludeFromDirectory] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[DisabilitiesAccess] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PhysicalLocationDescription] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[BusServiceAccess] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PublicAccessTransportation] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PaymentMethods] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[FeeStructureSource] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ApplicationProcess] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ResourceInfo] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[DocumentsRequired] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LanguagesOffered] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LanguagesOfferedList] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailabilityNumberOfTimes] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailabilityFrequency] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailabilityPeriod] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ServiceNotAlwaysAvailability] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[CapacityType] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ServiceCapacity] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[NormalWaitTime] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TemporaryMessage] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TemporaryMessageAppears] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TemporaryMessageExpires] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[EnteredOn] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[UpdatedOn] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[MadeInactiveOn] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[InternalNotes] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[InternalNotesForEditorsAndViewers] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[HighlightedResource] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerifiedOn] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerifiedByName] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerifiedByTitle] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerifiedByPhoneNumber] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerifiedByEmailAddress] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LastVerificationApprovedBy] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailableForDirectory] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailableForReferral] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[AvailableForResearch] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[PreferredProvider] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ConnectsToSiteNum] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ConnectsToProgramNum] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[LanguageOfRecord] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[CurrentWorkflowStepCode] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[VolunteerOpportunities] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[VolunteerDuties] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[IsLinkOnly] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[ProgramAgencyNamePublic] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[SiteAgencyNamePublic] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Categories] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TaxonomyTerm] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TaxonomyTerms] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TaxonomyTermsNotDeactivated] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[TaxonomyCodes] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Coverage] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Hours] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Public Comments] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Former Names] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Headings] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Legal Name] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Pub Codes] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Record Owner (controlled)] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_SINV] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_iCarol-managed record] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Facebook] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Instagram] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_LinkedIn] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Twitter] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_YouTube] [NVARCHAR](MAX) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Minimum Age] [NVARCHAR](255) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Maximum Age] [NVARCHAR](255) COLLATE Latin1_General_100_CI_AI NULL,
	[Custom_Deleted Record] [nvarchar](10) COLLATE Latin1_General_100_CI_AI NULL,
	[MailingCommunity] [NVARCHAR](500) COLLATE Latin1_General_100_CI_AI NULL,
	[OtherCommunity] [NVARCHAR](500) COLLATE Latin1_General_100_CI_AI NULL,
    [PhysicalCommunity] [NVARCHAR](500) COLLATE Latin1_General_100_CI_AI NULL


)

DECLARE @sql VARCHAR(MAX)
SET @sql = 'BULK INSERT #source FROM ''' + @source_file + '''WITH (CODEPAGE=''65001'',DATAFILETYPE=''Char'',  FIELDTERMINATOR=''' + CHAR(3) + ''', ROWTERMINATOR=''' + CHAR(4) + ''', FIRSTROW=1)'
EXEC (@sql)

MERGE INTO dbo.CIC_iCarolImport dst
USING #source AS src
ON dst.ResourceAgencyNum=src.ResourceAgencyNum AND dst.LangID=@@LANGID
WHEN MATCHED THEN
	UPDATE SET 
		[SYNC_DATE]=@SYNC_DATE,
		dst.DELETION_DATE=NULL,
		[ImportDate]=src.[ImportDate],
		[ImportStatus]=src.[ImportStatus],
		[Refresh]=src.[Refresh],
		[PublicName]=src.[PublicName],
		[AlternateName]=src.[AlternateName],
		[OfficialName]=src.[OfficialName],
		[TaxonomyLevelName]=src.[TaxonomyLevelName],
		[ParentAgency]=src.[ParentAgency],
		[ParentAgencyNum]=src.[ParentAgencyNum],
		[RecordOwner]=src.[RecordOwner],
		[UniqueIDPriorSystem]=src.[UniqueIDPriorSystem],
		[MailingAttentionName]=src.[MailingAttentionName],
		[MailingAddress1]=src.[MailingAddress1],
		[MailingAddress2]=src.[MailingAddress2],
		[MailingCity]=src.[MailingCity],
		[MailingStateProvince]=src.[MailingStateProvince],
		[MailingPostalCode]=src.[MailingPostalCode],
		[MailingCountry]=src.[MailingCountry],
		[MailingAddressIsPrivate]=src.[MailingAddressIsPrivate],
		[PhysicalAddress1]=src.[PhysicalAddress1],
		[PhysicalAddress2]=src.[PhysicalAddress2],
		[PhysicalCity]=src.[PhysicalCity],
		[PhysicalCounty]=src.[PhysicalCounty],
		[PhysicalStateProvince]=src.[PhysicalStateProvince],
		[PhysicalPostalCode]=src.[PhysicalPostalCode],
		[PhysicalCountry]=src.[PhysicalCountry],
		[PhysicalAddressIsPrivate]=src.[PhysicalAddressIsPrivate],
		[OtherAddress1]=src.[OtherAddress1],
		[OtherAddress2]=src.[OtherAddress2],
		[OtherCity]=src.[OtherCity],
		[OtherCounty]=src.[OtherCounty],
		[OtherStateProvince]=src.[OtherStateProvince],
		[OtherPostalCode]=src.[OtherPostalCode],
		[OtherCountry]=src.[OtherCountry],
		[Latitude]=src.[Latitude],
		[Longitude]=src.[Longitude],
		[HoursOfOperation]=src.[HoursOfOperation],
		[Phone1Number]=src.[Phone1Number],
		[Phone1Name]=src.[Phone1Name],
		[Phone1Description]=src.[Phone1Description],
		[Phone1IsPrivate]=src.[Phone1IsPrivate],
		[Phone1Type]=src.[Phone1Type],
		[Phone2Number]=src.[Phone2Number],
		[Phone2Name]=src.[Phone2Name],
		[Phone2Description]=src.[Phone2Description],
		[Phone2IsPrivate]=src.[Phone2IsPrivate],
		[Phone2Type]=src.[Phone2Type],
		[Phone3Number]=src.[Phone3Number],
		[Phone3Name]=src.[Phone3Name],
		[Phone3Description]=src.[Phone3Description],
		[Phone3IsPrivate]=src.[Phone3IsPrivate],
		[Phone3Type]=src.[Phone3Type],
		[Phone4Number]=src.[Phone4Number],
		[Phone4Name]=src.[Phone4Name],
		[Phone4Description]=src.[Phone4Description],
		[Phone4IsPrivate]=src.[Phone4IsPrivate],
		[Phone4Type]=src.[Phone4Type],
		[Phone5Number]=src.[Phone5Number],
		[Phone5name]=src.[Phone5name],
		[Phone5Description]=src.[Phone5Description],
		[Phone5IsPrivate]=src.[Phone5IsPrivate],
		[Phone5Type]=src.[Phone5Type],
		[PhoneFax]=src.[PhoneFax],
		[PhoneFaxDescription]=src.[PhoneFaxDescription],
		[PhoneFaxIsPrivate]=src.[PhoneFaxIsPrivate],
		[PhoneTTY]=src.[PhoneTTY],
		[PhoneTTYDescription]=src.[PhoneTTYDescription],
		[PhoneTTYIsPrivate]=src.[PhoneTTYIsPrivate],
		[PhoneTollFree]=src.[PhoneTollFree],
		[PhoneTollFreeDescription]=src.[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate]=src.[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline]=src.[PhoneNumberHotline],
		[PhoneNumberHotlineDescription]=src.[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate]=src.[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine]=src.[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription]=src.[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate]=src.[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea]=src.[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription]=src.[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate]=src.[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours]=src.[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription]=src.[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate]=src.[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain]=src.[EmailAddressMain],
		[WebsiteAddress]=src.[WebsiteAddress],
		[AgencyStatus]=src.[AgencyStatus],
		[AgencyClassification]=src.[AgencyClassification],
		[AgencyDescription]=src.[AgencyDescription],
		[SearchHints]=src.[SearchHints],
		[CoverageArea]=src.[CoverageArea],
		[CoverageAreaText]=src.[CoverageAreaText],
		[Eligibility]=src.[Eligibility],
		[EligibilityAdult]=src.[EligibilityAdult],
		[EligibilityChild]=src.[EligibilityChild],
		[EligibilityFamily]=src.[EligibilityFamily],
		[EligibilityFemale]=src.[EligibilityFemale],
		[EligibilityMale]=src.[EligibilityMale],
		[EligibilityTeen]=src.[EligibilityTeen],
		[SeniorWorkerName]=src.[SeniorWorkerName],
		[SeniorWorkerTitle]=src.[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress]=src.[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber]=src.[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate]=src.[SeniorWorkerIsPrivate],
		[MainContactName]=src.[MainContactName],
		[MainContactTitle]=src.[MainContactTitle],
		[MainContactEmailAddress]=src.[MainContactEmailAddress],
		[MainContactPhoneNumber]=src.[MainContactPhoneNumber],
		[MainContactType]=src.[MainContactType],
		[MainContactIsPrivate]=src.[MainContactIsPrivate],
		[LicenseAccreditation]=src.[LicenseAccreditation],
		[IRSStatus]=src.[IRSStatus],
		[FEIN]=src.[FEIN],
		[YearIncorporated]=src.[YearIncorporated],
		[AnnualBudgetTotal]=src.[AnnualBudgetTotal],
		[LegalStatus]=src.[LegalStatus],
		[SourceOfFunds]=src.[SourceOfFunds],
		[ExcludeFromWebsite]=src.[ExcludeFromWebsite],
		[ExcludeFromDirectory]=src.[ExcludeFromDirectory],
		[DisabilitiesAccess]=src.[DisabilitiesAccess],
		[PhysicalLocationDescription]=src.[PhysicalLocationDescription],
		[BusServiceAccess]=src.[BusServiceAccess],
		[PublicAccessTransportation]=src.[PublicAccessTransportation],
		[PaymentMethods]=src.[PaymentMethods],
		[FeeStructureSource]=src.[FeeStructureSource],
		[ApplicationProcess]=src.[ApplicationProcess],
		[ResourceInfo]=src.[ResourceInfo],
		[DocumentsRequired]=src.[DocumentsRequired],
		[LanguagesOffered]=src.[LanguagesOffered],
		[LanguagesOfferedList]=src.[LanguagesOfferedList],
		[AvailabilityNumberOfTimes]=src.[AvailabilityNumberOfTimes],
		[AvailabilityFrequency]=src.[AvailabilityFrequency],
		[AvailabilityPeriod]=src.[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability]=src.[ServiceNotAlwaysAvailability],
		[CapacityType]=src.[CapacityType],
		[ServiceCapacity]=src.[ServiceCapacity],
		[NormalWaitTime]=src.[NormalWaitTime],
		[TemporaryMessage]=src.[TemporaryMessage],
		[TemporaryMessageAppears]=src.[TemporaryMessageAppears],
		[TemporaryMessageExpires]=src.[TemporaryMessageExpires],
		[EnteredOn]=src.[EnteredOn],
		[UpdatedOn]=src.[UpdatedOn],
		[MadeInactiveOn]=src.[MadeInactiveOn],
		[InternalNotes]=src.[InternalNotes],
		[InternalNotesForEditorsAndViewers]=src.[InternalNotesForEditorsAndViewers],
		[HighlightedResource]=src.[HighlightedResource],
		[LastVerifiedOn]=src.[LastVerifiedOn],
		[LastVerifiedByName]=src.[LastVerifiedByName],
		[LastVerifiedByTitle]=src.[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber]=src.[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress]=src.[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy]=src.[LastVerificationApprovedBy],
		[AvailableForDirectory]=src.[AvailableForDirectory],
		[AvailableForReferral]=src.[AvailableForReferral],
		[AvailableForResearch]=src.[AvailableForResearch],
		[PreferredProvider]=src.[PreferredProvider],
		[ConnectsToSiteNum]=src.[ConnectsToSiteNum],
		[ConnectsToProgramNum]=src.[ConnectsToProgramNum],
		[LanguageOfRecord]=src.[LanguageOfRecord],
		[CurrentWorkflowStepCode]=src.[CurrentWorkflowStepCode],
		[VolunteerOpportunities]=src.[VolunteerOpportunities],
		[VolunteerDuties]=src.[VolunteerDuties],
		[IsLinkOnly]=src.[IsLinkOnly],
		[ProgramAgencyNamePublic]=src.[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic]=src.[SiteAgencyNamePublic],
		[Categories]=src.[Categories],
		[TaxonomyTerm]=src.[TaxonomyTerm],
		[TaxonomyTerms]=src.[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated]=src.[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes]=src.[TaxonomyCodes],
		[Coverage]=src.[Coverage],
		[Hours]=src.[Hours],
		[Custom_Public Comments]=src.[Custom_Public Comments],
		[Custom_Former Names]=src.[Custom_Former Names],
		[Custom_Headings]=src.[Custom_Headings],
		[Custom_Legal Name]=src.[Custom_Legal Name],
		[Custom_Pub Codes]=src.[Custom_Pub Codes],
		[Custom_Record Owner (controlled)]=src.[Custom_Record Owner (controlled)],
		[Custom_SINV]=src.[Custom_SINV],
		[Custom_iCarol-managed record]=src.[Custom_iCarol-managed record],
		[Custom_Facebook]=src.[Custom_Facebook],
		[Custom_Instagram]=src.[Custom_Instagram],
		[Custom_LinkedIn]=src.[Custom_LinkedIn],
		[Custom_Twitter]=src.[Custom_Twitter],
		[Custom_YouTube]=src.[Custom_YouTube],
		[Custom_Minimum Age]=src.[Custom_Minimum Age],
		[Custom_Maximum Age]=src.[Custom_Maximum Age],
		[Custom_Deleted Record]=src.[Custom_Deleted Record],
		[MailingCommunity]=src.[MailingCommunity],
		[OtherCommunity]=src.[OtherCommunity],
		[PhysicalCommunity]=src.[PhysicalCommunity]

WHEN NOT MATCHED BY TARGET THEN
	INSERT (
		[ResourceAgencyNum],
		[LangID],
		[SYNC_DATE],
		DELETION_DATE,
		[ImportDate],
		[ImportStatus],
		[Refresh],
		[PublicName],
		[AlternateName],
		[OfficialName],
		[TaxonomyLevelName],
		[ParentAgency],
		[ParentAgencyNum],
		[RecordOwner],
		[UniqueIDPriorSystem],
		[MailingAttentionName],
		[MailingAddress1],
		[MailingAddress2],
		[MailingCity],
		[MailingStateProvince],
		[MailingPostalCode],
		[MailingCountry],
		[MailingAddressIsPrivate],
		[PhysicalAddress1],
		[PhysicalAddress2],
		[PhysicalCity],
		[PhysicalCounty],
		[PhysicalStateProvince],
		[PhysicalPostalCode],
		[PhysicalCountry],
		[PhysicalAddressIsPrivate],
		[OtherAddress1],
		[OtherAddress2],
		[OtherCity],
		[OtherCounty],
		[OtherStateProvince],
		[OtherPostalCode],
		[OtherCountry],
		[Latitude],
		[Longitude],
		[HoursOfOperation],
		[Phone1Number],
		[Phone1Name],
		[Phone1Description],
		[Phone1IsPrivate],
		[Phone1Type],
		[Phone2Number],
		[Phone2Name],
		[Phone2Description],
		[Phone2IsPrivate],
		[Phone2Type],
		[Phone3Number],
		[Phone3Name],
		[Phone3Description],
		[Phone3IsPrivate],
		[Phone3Type],
		[Phone4Number],
		[Phone4Name],
		[Phone4Description],
		[Phone4IsPrivate],
		[Phone4Type],
		[Phone5Number],
		[Phone5name],
		[Phone5Description],
		[Phone5IsPrivate],
		[Phone5Type],
		[PhoneFax],
		[PhoneFaxDescription],
		[PhoneFaxIsPrivate],
		[PhoneTTY],
		[PhoneTTYDescription],
		[PhoneTTYIsPrivate],
		[PhoneTollFree],
		[PhoneTollFreeDescription],
		[PhoneTollFreeIsPrivate],
		[PhoneNumberHotline],
		[PhoneNumberHotlineDescription],
		[PhoneNumberHotlineIsPrivate],
		[PhoneNumberBusinessLine],
		[PhoneNumberBusinessLineDescription],
		[PhoneNumberBusinessLineIsPrivate],
		[PhoneNumberOutOfArea],
		[PhoneNumberOutOfAreaDescription],
		[PhoneNumberOutOfAreaIsPrivate],
		[PhoneNumberAfterHours],
		[PhoneNumberAfterHoursDescription],
		[PhoneNumberAfterHoursIsPrivate],
		[EmailAddressMain],
		[WebsiteAddress],
		[AgencyStatus],
		[AgencyClassification],
		[AgencyDescription],
		[SearchHints],
		[CoverageArea],
		[CoverageAreaText],
		[Eligibility],
		[EligibilityAdult],
		[EligibilityChild],
		[EligibilityFamily],
		[EligibilityFemale],
		[EligibilityMale],
		[EligibilityTeen],
		[SeniorWorkerName],
		[SeniorWorkerTitle],
		[SeniorWorkerEmailAddress],
		[SeniorWorkerPhoneNumber],
		[SeniorWorkerIsPrivate],
		[MainContactName],
		[MainContactTitle],
		[MainContactEmailAddress],
		[MainContactPhoneNumber],
		[MainContactType],
		[MainContactIsPrivate],
		[LicenseAccreditation],
		[IRSStatus],
		[FEIN],
		[YearIncorporated],
		[AnnualBudgetTotal],
		[LegalStatus],
		[SourceOfFunds],
		[ExcludeFromWebsite],
		[ExcludeFromDirectory],
		[DisabilitiesAccess],
		[PhysicalLocationDescription],
		[BusServiceAccess],
		[PublicAccessTransportation],
		[PaymentMethods],
		[FeeStructureSource],
		[ApplicationProcess],
		[ResourceInfo],
		[DocumentsRequired],
		[LanguagesOffered],
		[LanguagesOfferedList],
		[AvailabilityNumberOfTimes],
		[AvailabilityFrequency],
		[AvailabilityPeriod],
		[ServiceNotAlwaysAvailability],
		[CapacityType],
		[ServiceCapacity],
		[NormalWaitTime],
		[TemporaryMessage],
		[TemporaryMessageAppears],
		[TemporaryMessageExpires],
		[EnteredOn],
		[UpdatedOn],
		[MadeInactiveOn],
		[InternalNotes],
		[InternalNotesForEditorsAndViewers],
		[HighlightedResource],
		[LastVerifiedOn],
		[LastVerifiedByName],
		[LastVerifiedByTitle],
		[LastVerifiedByPhoneNumber],
		[LastVerifiedByEmailAddress],
		[LastVerificationApprovedBy],
		[AvailableForDirectory],
		[AvailableForReferral],
		[AvailableForResearch],
		[PreferredProvider],
		[ConnectsToSiteNum],
		[ConnectsToProgramNum],
		[LanguageOfRecord],
		[CurrentWorkflowStepCode],
		[VolunteerOpportunities],
		[VolunteerDuties],
		[IsLinkOnly],
		[ProgramAgencyNamePublic],
		[SiteAgencyNamePublic],
		[Categories],
		[TaxonomyTerm],
		[TaxonomyTerms],
		[TaxonomyTermsNotDeactivated],
		[TaxonomyCodes],
		[Coverage],
		[Hours],
		[Custom_Public Comments],
		[Custom_Former Names],
		[Custom_Headings],
		[Custom_Legal Name],
		[Custom_Pub Codes],
		[Custom_Record Owner (controlled)],
		[Custom_SINV],
		[Custom_iCarol-managed record],
		[Custom_Facebook],
		[Custom_Instagram],
		[Custom_LinkedIn],
		[Custom_Twitter],
		[Custom_YouTube],
		[Custom_Minimum Age],
		[Custom_Maximum Age],
		[Custom_Deleted Record],
		[MailingCommunity],
		[OtherCommunity],
		[PhysicalCommunity]
	) VALUES (
		src.[ResourceAgencyNum],
		@@LANGID,
		@SYNC_DATE,
		NULL,
		src.[ImportDate],
		src.[ImportStatus],
		src.[Refresh],
		src.[PublicName],
		src.[AlternateName],
		src.[OfficialName],
		src.[TaxonomyLevelName],
		src.[ParentAgency],
		src.[ParentAgencyNum],
		src.[RecordOwner],
		src.[UniqueIDPriorSystem],
		src.[MailingAttentionName],
		src.[MailingAddress1],
		src.[MailingAddress2],
		src.[MailingCity],
		src.[MailingStateProvince],
		src.[MailingPostalCode],
		src.[MailingCountry],
		src.[MailingAddressIsPrivate],
		src.[PhysicalAddress1],
		src.[PhysicalAddress2],
		src.[PhysicalCity],
		src.[PhysicalCounty],
		src.[PhysicalStateProvince],
		src.[PhysicalPostalCode],
		src.[PhysicalCountry],
		src.[PhysicalAddressIsPrivate],
		src.[OtherAddress1],
		src.[OtherAddress2],
		src.[OtherCity],
		src.[OtherCounty],
		src.[OtherStateProvince],
		src.[OtherPostalCode],
		src.[OtherCountry],
		src.[Latitude],
		src.[Longitude],
		src.[HoursOfOperation],
		src.[Phone1Number],
		src.[Phone1Name],
		src.[Phone1Description],
		src.[Phone1IsPrivate],
		src.[Phone1Type],
		src.[Phone2Number],
		src.[Phone2Name],
		src.[Phone2Description],
		src.[Phone2IsPrivate],
		src.[Phone2Type],
		src.[Phone3Number],
		src.[Phone3Name],
		src.[Phone3Description],
		src.[Phone3IsPrivate],
		src.[Phone3Type],
		src.[Phone4Number],
		src.[Phone4Name],
		src.[Phone4Description],
		src.[Phone4IsPrivate],
		src.[Phone4Type],
		src.[Phone5Number],
		src.[Phone5name],
		src.[Phone5Description],
		src.[Phone5IsPrivate],
		src.[Phone5Type],
		src.[PhoneFax],
		src.[PhoneFaxDescription],
		src.[PhoneFaxIsPrivate],
		src.[PhoneTTY],
		src.[PhoneTTYDescription],
		src.[PhoneTTYIsPrivate],
		src.[PhoneTollFree],
		src.[PhoneTollFreeDescription],
		src.[PhoneTollFreeIsPrivate],
		src.[PhoneNumberHotline],
		src.[PhoneNumberHotlineDescription],
		src.[PhoneNumberHotlineIsPrivate],
		src.[PhoneNumberBusinessLine],
		src.[PhoneNumberBusinessLineDescription],
		src.[PhoneNumberBusinessLineIsPrivate],
		src.[PhoneNumberOutOfArea],
		src.[PhoneNumberOutOfAreaDescription],
		src.[PhoneNumberOutOfAreaIsPrivate],
		src.[PhoneNumberAfterHours],
		src.[PhoneNumberAfterHoursDescription],
		src.[PhoneNumberAfterHoursIsPrivate],
		src.[EmailAddressMain],
		src.[WebsiteAddress],
		src.[AgencyStatus],
		src.[AgencyClassification],
		src.[AgencyDescription],
		src.[SearchHints],
		src.[CoverageArea],
		src.[CoverageAreaText],
		src.[Eligibility],
		src.[EligibilityAdult],
		src.[EligibilityChild],
		src.[EligibilityFamily],
		src.[EligibilityFemale],
		src.[EligibilityMale],
		src.[EligibilityTeen],
		src.[SeniorWorkerName],
		src.[SeniorWorkerTitle],
		src.[SeniorWorkerEmailAddress],
		src.[SeniorWorkerPhoneNumber],
		src.[SeniorWorkerIsPrivate],
		src.[MainContactName],
		src.[MainContactTitle],
		src.[MainContactEmailAddress],
		src.[MainContactPhoneNumber],
		src.[MainContactType],
		src.[MainContactIsPrivate],
		src.[LicenseAccreditation],
		src.[IRSStatus],
		src.[FEIN],
		src.[YearIncorporated],
		src.[AnnualBudgetTotal],
		src.[LegalStatus],
		src.[SourceOfFunds],
		src.[ExcludeFromWebsite],
		src.[ExcludeFromDirectory],
		src.[DisabilitiesAccess],
		src.[PhysicalLocationDescription],
		src.[BusServiceAccess],
		src.[PublicAccessTransportation],
		src.[PaymentMethods],
		src.[FeeStructureSource],
		src.[ApplicationProcess],
		src.[ResourceInfo],
		src.[DocumentsRequired],
		src.[LanguagesOffered],
		src.[LanguagesOfferedList],
		src.[AvailabilityNumberOfTimes],
		src.[AvailabilityFrequency],
		src.[AvailabilityPeriod],
		src.[ServiceNotAlwaysAvailability],
		src.[CapacityType],
		src.[ServiceCapacity],
		src.[NormalWaitTime],
		src.[TemporaryMessage],
		src.[TemporaryMessageAppears],
		src.[TemporaryMessageExpires],
		src.[EnteredOn],
		src.[UpdatedOn],
		src.[MadeInactiveOn],
		src.[InternalNotes],
		src.[InternalNotesForEditorsAndViewers],
		src.[HighlightedResource],
		src.[LastVerifiedOn],
		src.[LastVerifiedByName],
		src.[LastVerifiedByTitle],
		src.[LastVerifiedByPhoneNumber],
		src.[LastVerifiedByEmailAddress],
		src.[LastVerificationApprovedBy],
		src.[AvailableForDirectory],
		src.[AvailableForReferral],
		src.[AvailableForResearch],
		src.[PreferredProvider],
		src.[ConnectsToSiteNum],
		src.[ConnectsToProgramNum],
		src.[LanguageOfRecord],
		src.[CurrentWorkflowStepCode],
		src.[VolunteerOpportunities],
		src.[VolunteerDuties],
		src.[IsLinkOnly],
		src.[ProgramAgencyNamePublic],
		src.[SiteAgencyNamePublic],
		src.[Categories],
		src.[TaxonomyTerm],
		src.[TaxonomyTerms],
		src.[TaxonomyTermsNotDeactivated],
		src.[TaxonomyCodes],
		src.[Coverage],
		src.[Hours],
		src.[Custom_Public Comments],
		src.[Custom_Former Names],
		src.[Custom_Headings],
		src.[Custom_Legal Name],
		src.[Custom_Pub Codes],
		src.[Custom_Record Owner (controlled)],
		src.[Custom_SINV],
		src.[Custom_iCarol-managed record],
		src.[Custom_Facebook],
		src.[Custom_Instagram],
		src.[Custom_LinkedIn],
		src.[Custom_Twitter],
		src.[Custom_YouTube],
		src.[Custom_Minimum Age],
		src.[Custom_Maximum Age],
		src.[Custom_Deleted Record],
		src.[MailingCommunity],
		src.[OtherCommunity],
		src.[PhysicalCommunity]
	)

	;

RETURN @Error

SET NOCOUNT OFF

GO
GRANT EXECUTE ON  [dbo].[sp_CIC_iCarolImport_Incremental] TO [cioc_login_role]
GO
GRANT EXECUTE ON  [dbo].[sp_CIC_iCarolImport_Incremental] TO [cioc_maintenance_role]
GO
