SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_VOL_VNUMSetTRNIDs_u]
	@VNUM varchar(10),
	@IdList varchar(max)
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.6
	Checked by: CL
	Checked on: 27-Sep-2014
	Action: TESTING REQUIRED
*/

DECLARE @tmpTRNIDs TABLE(TRN_ID int)

INSERT INTO @tmpTRNIDs SELECT DISTINCT tm.*
	FROM dbo.fn_GBL_ParseIntIDList(@IdList,',') tm
	INNER JOIN VOL_Training trn
		ON tm.ItemID = trn.TRN_ID

DELETE pr
	FROM VOL_OP_TRN pr
	LEFT JOIN @tmpTRNIDs tm
		ON pr.TRN_ID = tm.TRN_ID
WHERE tm.TRN_ID IS NULL AND VNUM=@VNUM

INSERT INTO VOL_OP_TRN (VNUM, TRN_ID) SELECT VNUM=@VNUM, tm.TRN_ID
	FROM @tmpTRNIDs tm
WHERE NOT EXISTS(SELECT * FROM VOL_OP_TRN pr WHERE VNUM=@VNUM AND pr.TRN_ID=tm.TRN_ID)

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_VOL_VNUMSetTRNIDs_u] TO [cioc_login_role]
GO
