SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[sp_CIC_NUMSetCMIDs_u]
	@NUM varchar(8),
	@IdList varchar(max)
WITH EXECUTE AS CALLER
AS
SET NOCOUNT ON

/*
	Checked for Release: 3.1
	Checked by: KL
	Checked on: 06-Apr-2012
	Action: NO ACTION REQUIRED
	Notes: For future, incoporate MERGE statement
*/

DECLARE @tmpCMIDs TABLE(
	CM_ID int NOT NULL PRIMARY KEY
)

INSERT INTO @tmpCMIDs SELECT DISTINCT tm.*
	FROM dbo.fn_GBL_ParseIntIDList(@IdList,',') tm
	INNER JOIN GBL_Community cm
		ON tm.ItemID=cm.CM_ID

DELETE pr
	FROM CIC_BT_CM pr
	LEFT JOIN @tmpCMIDs tm
		ON pr.CM_ID = tm.CM_ID
WHERE tm.CM_ID IS NULL AND NUM=@NUM

INSERT INTO CIC_BT_CM (NUM, CM_ID) SELECT NUM=@NUM, tm.CM_ID
	FROM @tmpCMIDs tm
WHERE NOT EXISTS(SELECT * FROM CIC_BT_CM pr WHERE NUM=@NUM AND pr.CM_ID=tm.CM_ID)

SET NOCOUNT OFF


GO
GRANT EXECUTE ON  [dbo].[sp_CIC_NUMSetCMIDs_u] TO [cioc_login_role]
GO
