CREATE TABLE [dbo].[GBL_BT_FORMERORG]
(
[BT_FO_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[LangID] [smallint] NOT NULL CONSTRAINT [DF_GBL_BT_FORMERORG_EQUIVALENT] DEFAULT ((0)),
[FORMER_ORG] [nvarchar] (255) COLLATE Latin1_General_100_CS_AS NOT NULL,
[DATE_OF_CHANGE] [nvarchar] (20) COLLATE Latin1_General_100_CI_AI NULL,
[PUBLISH] [bit] NOT NULL CONSTRAINT [DF_GBL_BT_FORMERORG_PUBLISH] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_GBL_BT_FORMERORG_iud] ON [dbo].[GBL_BT_FORMERORG]
FOR INSERT, UPDATE, DELETE AS

SET NOCOUNT ON

UPDATE btd
	SET	CMP_FormerOrg = dbo.fn_GBL_NUMToFormerOrg(btd.NUM,btd.LangID),
		CMP_CrossRef = dbo.fn_GBL_NUMToCrossRef(btd.NUM,btd.LangID)
	FROM GBL_BaseTable_Description btd
	WHERE EXISTS(SELECT * FROM Inserted i WHERE i.NUM=btd.NUM AND i.LangID=btd.LangID)
		OR EXISTS(SELECT * FROM Deleted d WHERE d.NUM=btd.NUM AND d.LangID=btd.LangID)

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[GBL_BT_FORMERORG] ADD CONSTRAINT [PK_GBL_BT_FORMERORG] PRIMARY KEY CLUSTERED  ([BT_FO_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GBL_BT_FORMERORG_UniquePair] ON [dbo].[GBL_BT_FORMERORG] ([NUM], [FORMER_ORG], [LangID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GBL_BT_FORMERORG] ADD CONSTRAINT [FK_GBL_BT_FORMERORG_GBL_BaseTable_Description] FOREIGN KEY ([NUM], [LangID]) REFERENCES [dbo].[GBL_BaseTable_Description] ([NUM], [LangID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[GBL_BT_FORMERORG] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[GBL_BT_FORMERORG] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[GBL_BT_FORMERORG] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[GBL_BT_FORMERORG] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[GBL_BT_FORMERORG] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[GBL_BT_FORMERORG] TO [cioc_vol_search_role]
GO
CREATE FULLTEXT INDEX ON [dbo].[GBL_BT_FORMERORG] KEY INDEX [PK_GBL_BT_FORMERORG] ON [GBLRecord] WITH STOPLIST [CIOC_DEFAULT_STOPLIST]
GO
ALTER FULLTEXT INDEX ON [dbo].[GBL_BT_FORMERORG] ADD ([FORMER_ORG] LANGUAGE 1033)
GO
