CREATE TABLE [dbo].[CIC_BT_BR]
(
[BT_BR_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[BR_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_BR] ADD CONSTRAINT [PK_CIC_BT_BR] PRIMARY KEY CLUSTERED  ([BT_BR_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_BR_UniquePair] ON [dbo].[CIC_BT_BR] ([NUM], [BR_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_BR] ADD CONSTRAINT [FK_CIC_BT_BR_CIC_BusRoute] FOREIGN KEY ([BR_ID]) REFERENCES [dbo].[CIC_BusRoute] ([BR_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_BR] ADD CONSTRAINT [FK_CIC_BT_BR_CIC_BT_BR] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_BR] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_BR] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_BR] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_BR] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_BR] TO [cioc_login_role]
GO
