CREATE TABLE [dbo].[VOL_OP_CL]
(
[OP_CL_ID] [int] NOT NULL IDENTITY(1, 1),
[VNUM] [varchar] (10) COLLATE Latin1_General_100_CI_AI NOT NULL,
[CL_ID] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[VOL_OP_CL] ADD 
CONSTRAINT [PK_VOL_OP_CL] PRIMARY KEY CLUSTERED  ([OP_CL_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_OP_CL] ADD CONSTRAINT [IX_VOL_OP_CL_UniquePair] UNIQUE NONCLUSTERED  ([VNUM], [CL_ID]) ON [PRIMARY]

GO

ALTER TABLE [dbo].[VOL_OP_CL] ADD CONSTRAINT [FK_VOL_OP_CL_VOL_CommitmentLength] FOREIGN KEY ([CL_ID]) REFERENCES [dbo].[VOL_CommitmentLength] ([CL_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_OP_CL] WITH NOCHECK ADD CONSTRAINT [FK_VOL_OP_CL_VOL_Opportunity] FOREIGN KEY ([VNUM]) REFERENCES [dbo].[VOL_Opportunity] ([VNUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_OP_CL] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[VOL_OP_CL] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_OP_CL] TO [cioc_vol_search_role]
GO
