CREATE TABLE [dbo].[TAX_U_TM_RC]
(
[TM_RC_ID] [int] NOT NULL IDENTITY(1, 1),
[Code] [varchar] (21) COLLATE Latin1_General_100_CI_AI NOT NULL,
[RC_ID] [int] NOT NULL,
[Authorized] [bit] NOT NULL CONSTRAINT [DF_TAX_U_TM_RC_Authorized] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_U_TM_RC] ADD CONSTRAINT [PK_TAX_U_TM_RC] PRIMARY KEY CLUSTERED ([TM_RC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_U_TM_RC] ADD CONSTRAINT [IX_TAX_U_TM_RC_UniquePair] UNIQUE NONCLUSTERED ([Code], [RC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_U_TM_RC] WITH NOCHECK ADD CONSTRAINT [FK_TAX_U_TM_RC_TAX_U_RelatedConcept] FOREIGN KEY ([RC_ID]) REFERENCES [dbo].[TAX_U_RelatedConcept] ([RC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TAX_U_TM_RC] WITH NOCHECK ADD CONSTRAINT [FK_TAX_U_TM_RC_TAX_U_Term] FOREIGN KEY ([Code]) REFERENCES [dbo].[TAX_U_Term] ([Code]) ON DELETE CASCADE ON UPDATE CASCADE
GO
