CREATE TABLE [dbo].[VOL_OP_IL]
(
[OP_IL_ID] [int] NOT NULL IDENTITY(1, 1),
[VNUM] [varchar] (10) COLLATE Latin1_General_100_CI_AI NOT NULL,
[IL_ID] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[VOL_OP_IL] ADD 
CONSTRAINT [PK_VOL_OP_IL] PRIMARY KEY CLUSTERED  ([OP_IL_ID]) ON [PRIMARY]
CREATE UNIQUE NONCLUSTERED INDEX [IX_VOL_OP_IL_UniquePair] ON [dbo].[VOL_OP_IL] ([VNUM], [IL_ID]) ON [PRIMARY]

GO

ALTER TABLE [dbo].[VOL_OP_IL] ADD CONSTRAINT [FK_VOL_OP_IL_VOL_InteractionLevel] FOREIGN KEY ([IL_ID]) REFERENCES [dbo].[VOL_InteractionLevel] ([IL_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_OP_IL] WITH NOCHECK ADD CONSTRAINT [FK_VOL_OP_IL_VOL_Opportunity] FOREIGN KEY ([VNUM]) REFERENCES [dbo].[VOL_Opportunity] ([VNUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_OP_IL] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[VOL_OP_IL] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_OP_IL] TO [cioc_vol_search_role]
GO
