CREATE TABLE [dbo].[VOL_OP_CM]
(
[OP_CM_ID] [int] NOT NULL IDENTITY(1, 1),
[VNUM] [varchar] (10) COLLATE Latin1_General_100_CI_AI NOT NULL,
[CM_ID] [int] NOT NULL,
[NUM_NEEDED] [smallint] NULL
) ON [PRIMARY]
CREATE NONCLUSTERED INDEX [IX_VOL_OP_CM_CMIDVNUMInclNUMNEEDED] ON [dbo].[VOL_OP_CM] ([CM_ID], [VNUM]) INCLUDE ([NUM_NEEDED]) ON [PRIMARY]

ALTER TABLE [dbo].[VOL_OP_CM] ADD 
CONSTRAINT [PK_VOL_OP_CM] PRIMARY KEY CLUSTERED  ([OP_CM_ID]) ON [PRIMARY]
CREATE UNIQUE NONCLUSTERED INDEX [IX_VOL_OP_CM_UniquePair] ON [dbo].[VOL_OP_CM] ([VNUM], [CM_ID]) ON [PRIMARY]

ALTER TABLE [dbo].[VOL_OP_CM] ADD
CONSTRAINT [CK_VOL_OP_CM_NUM_NEEDED] CHECK (([NUM_NEEDED]>(0) OR [NUM_NEEDED] IS NULL))
GO

ALTER TABLE [dbo].[VOL_OP_CM] ADD CONSTRAINT [FK_VOL_OP_CM_GBL_Community] FOREIGN KEY ([CM_ID]) REFERENCES [dbo].[GBL_Community] ([CM_ID]) ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_OP_CM] WITH NOCHECK ADD CONSTRAINT [FK_VOL_OP_CM_VOL_Opportunity] FOREIGN KEY ([VNUM]) REFERENCES [dbo].[VOL_Opportunity] ([VNUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_OP_CM] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[VOL_OP_CM] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[VOL_OP_CM] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[VOL_OP_CM] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_OP_CM] TO [cioc_vol_search_role]
GO
