CREATE TABLE [dbo].[CCR_BT_TOC]
(
[BT_TOC_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[TOC_ID] [int] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CCR_BT_TOC_SRCH] ON [dbo].[CCR_BT_TOC]
FOR INSERT, UPDATE, DELETE AS

SET NOCOUNT ON

UPDATE btd
		SET SRCH_Anywhere_U = 1
	FROM GBL_BaseTable_Description btd
	WHERE	btd.SRCH_Anywhere_U <> 1
		AND (EXISTS(SELECT * FROM Inserted i WHERE btd.NUM = i.NUM)
		OR EXISTS(SELECT * FROM Deleted d WHERE btd.NUM = d.NUM))

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[CCR_BT_TOC] ADD CONSTRAINT [PK_CCR_BT_TOC] PRIMARY KEY CLUSTERED  ([BT_TOC_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CCR_BT_TOC_UniquePair] ON [dbo].[CCR_BT_TOC] ([NUM], [TOC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCR_BT_TOC] ADD CONSTRAINT [FK_CCR_BT_TOC_CCR_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CCR_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CCR_BT_TOC] WITH NOCHECK ADD CONSTRAINT [FK_CCR_CG_TOC_CCR_TypeOfCare] FOREIGN KEY ([TOC_ID]) REFERENCES [dbo].[CCR_TypeOfCare] ([TOC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CCR_BT_TOC] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CCR_BT_TOC] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CCR_BT_TOC] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CCR_BT_TOC] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CCR_BT_TOC] TO [cioc_login_role]
GO
