CREATE TABLE [dbo].[VOL_OP_AC]
(
[OP_AC_ID] [int] NOT NULL IDENTITY(1, 1),
[VNUM] [varchar] (10) COLLATE Latin1_General_100_CI_AI NOT NULL,
[AC_ID] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[VOL_OP_AC] ADD 
CONSTRAINT [PK_VOL_OP_AC] PRIMARY KEY CLUSTERED  ([OP_AC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_OP_AC] ADD CONSTRAINT [IX_VOL_OP_AC_UniquePair] UNIQUE NONCLUSTERED  ([VNUM], [AC_ID]) ON [PRIMARY]

GO

ALTER TABLE [dbo].[VOL_OP_AC] ADD CONSTRAINT [FK_VOL_OP_AC_GBL_Accessibility] FOREIGN KEY ([AC_ID]) REFERENCES [dbo].[GBL_Accessibility] ([AC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_OP_AC] WITH NOCHECK ADD CONSTRAINT [FK_VOL_OP_AC_VOL_Opportunity] FOREIGN KEY ([VNUM]) REFERENCES [dbo].[VOL_Opportunity] ([VNUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_OP_AC] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[VOL_OP_AC] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_OP_AC] TO [cioc_vol_search_role]
GO
