CREATE TABLE [dbo].[CIC_BT_OTHERADDRESS]
(
[ADDR_ID] [int] NOT NULL IDENTITY(1, 1),
[GUID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_CIC_BT_OTHERADDRESS_GUID] DEFAULT (newid()),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[LangID] [smallint] NOT NULL,
[TITLE] [nvarchar] (100) COLLATE Latin1_General_100_CI_AI NULL,
[SITE_CODE] [varchar] (100) COLLATE Latin1_General_100_CI_AI NULL,
[CARE_OF] [nvarchar] (100) COLLATE Latin1_General_100_CI_AI NULL,
[BOX_TYPE] [nvarchar] (20) COLLATE Latin1_General_100_CI_AI NULL,
[PO_BOX] [nvarchar] (20) COLLATE Latin1_General_100_CI_AI NULL,
[BUILDING] [nvarchar] (150) COLLATE Latin1_General_100_CI_AI NULL,
[STREET_NUMBER] [nvarchar] (30) COLLATE Latin1_General_100_CI_AI NULL,
[STREET] [nvarchar] (150) COLLATE Latin1_General_100_CI_AI NULL,
[STREET_TYPE] [nvarchar] (20) COLLATE Latin1_General_100_CI_AI NULL,
[STREET_TYPE_AFTER] [bit] NULL,
[STREET_DIR] [varchar] (2) COLLATE Latin1_General_100_CI_AI NULL,
[SUFFIX] [nvarchar] (150) COLLATE Latin1_General_100_CI_AI NULL,
[CITY] [nvarchar] (100) COLLATE Latin1_General_100_CI_AI NULL,
[PROVINCE] [varchar] (2) COLLATE Latin1_General_100_CI_AI NULL,
[COUNTRY] [nvarchar] (60) COLLATE Latin1_General_100_CI_AI NULL,
[POSTAL_CODE] [varchar] (20) COLLATE Latin1_General_100_CI_AI NULL,
[MAP_LINK] [int] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CIC_BT_OTHERADDRESS_d] ON [dbo].[CIC_BT_OTHERADDRESS] 
FOR DELETE  AS

SET NOCOUNT ON

UPDATE cbt
	SET	MAIN_ADDRESS_ADDRID = NULL
	FROM CIC_BaseTable cbt
	INNER JOIN Deleted d ON d.ADDR_ID=cbt.MAIN_ADDRESS_ADDRID

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[CIC_BT_OTHERADDRESS] ADD CONSTRAINT [PK_CIC_BT_OTHERADDRESS] PRIMARY KEY CLUSTERED  ([ADDR_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_OTHERADDRESS] ADD CONSTRAINT [FK_CIC_BT_OTHERADDRESS_STP_Language] FOREIGN KEY ([LangID]) REFERENCES [dbo].[STP_Language] ([LangID])
GO
ALTER TABLE [dbo].[CIC_BT_OTHERADDRESS] ADD CONSTRAINT [FK_CIC_BT_OTHERADDRESS_GBL_MappingSystem] FOREIGN KEY ([MAP_LINK]) REFERENCES [dbo].[GBL_MappingSystem] ([MAP_ID]) ON DELETE SET NULL ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_OTHERADDRESS] ADD CONSTRAINT [FK_CIC_BT_OTHERADDRESS_CIC_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_OTHERADDRESS] ADD CONSTRAINT [FK_CIC_BT_OTHERADDRESS_GBL_StreetDir] FOREIGN KEY ([STREET_DIR]) REFERENCES [dbo].[GBL_StreetDir] ([Dir])
GO
GRANT SELECT ON  [dbo].[CIC_BT_OTHERADDRESS] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_OTHERADDRESS] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_OTHERADDRESS] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_OTHERADDRESS] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_OTHERADDRESS] TO [cioc_login_role]
GO
