CREATE TABLE [dbo].[CIC_BT_VUT_TP]
(
[BT_VUT_TP_ID] [int] NOT NULL IDENTITY(1, 1),
[BT_VUT_ID] [int] NOT NULL,
[VTP_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_VUT_TP] ADD CONSTRAINT [PK_CIC_BT_VUT_TP] PRIMARY KEY CLUSTERED  ([BT_VUT_TP_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_VUT_TP] ON [dbo].[CIC_BT_VUT_TP] ([BT_VUT_ID], [VTP_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_VUT_TP] ADD CONSTRAINT [FK_CIC_BT_VUT_TP_CIC_BT_VUT] FOREIGN KEY ([BT_VUT_ID]) REFERENCES [dbo].[CIC_BT_VUT] ([BT_VUT_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_VUT_TP] ADD CONSTRAINT [FK_CIC_BT_VUT_TP_CIC_Vacancy_TargetPop] FOREIGN KEY ([VTP_ID]) REFERENCES [dbo].[CIC_Vacancy_TargetPop] ([VTP_ID]) ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_VUT_TP] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_VUT_TP] TO [cioc_login_role]
GO
