CREATE TABLE [dbo].[CIC_BT_FD]
(
[BT_FD_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[FD_ID] [int] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CIC_BT_FD_iud] ON [dbo].[CIC_BT_FD] 
FOR INSERT, UPDATE, DELETE AS

SET NOCOUNT ON

UPDATE cbtd
	SET	CMP_Funding = dbo.fn_CIC_NUMToFunding(cbtd.NUM,cbtd.FUNDING_NOTES,cbtd.LangID)
	FROM CIC_BaseTable_Description cbtd
	WHERE EXISTS(SELECT * FROM Inserted i WHERE i.NUM=cbtd.NUM)
		OR EXISTS(SELECT * FROM Deleted d WHERE d.NUM=cbtd.NUM)

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[CIC_BT_FD] ADD CONSTRAINT [PK_BT_FD] PRIMARY KEY CLUSTERED  ([BT_FD_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CIC_BT_FD_FDID] ON [dbo].[CIC_BT_FD] ([FD_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_FD_UniquePair] ON [dbo].[CIC_BT_FD] ([NUM], [FD_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_FD] ADD CONSTRAINT [FK_CIC_BT_FD_CIC_Funding] FOREIGN KEY ([FD_ID]) REFERENCES [dbo].[CIC_Funding] ([FD_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_FD] ADD CONSTRAINT [FK_CIC_BT_FD_CIC_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_FD] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_FD] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_FD] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_FD] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_FD] TO [cioc_login_role]
GO
