CREATE TABLE [dbo].[CIC_BT_EXTRA_RADIO]
(
[BT_EXDT_ID] [int] NOT NULL IDENTITY(1, 1),
[FieldName] [varchar] (100) COLLATE Latin1_General_100_CI_AI NOT NULL,
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[Value] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_EXTRA_RADIO] ADD CONSTRAINT [PK_CIC_BT_EXTRA_RADIO] PRIMARY KEY CLUSTERED  ([BT_EXDT_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_EXTRA_RADIO_UniqueField] ON [dbo].[CIC_BT_EXTRA_RADIO] ([FieldName], [NUM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_EXTRA_RADIO] ADD CONSTRAINT [FK_CIC_BT_EXTRA_RADIO_GBL_FieldOption] FOREIGN KEY ([FieldName]) REFERENCES [dbo].[GBL_FieldOption] ([FieldName]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_EXTRA_RADIO] ADD CONSTRAINT [FK_CIC_BT_EXTRA_RADIO_CIC_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_EXTRA_RADIO] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_EXTRA_RADIO] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_EXTRA_RADIO] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_EXTRA_RADIO] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_EXTRA_RADIO] TO [cioc_login_role]
GO
