CREATE TABLE [dbo].[CCR_BaseTable]
(
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[CREATED_DATE] [smalldatetime] NULL CONSTRAINT [DF_CCR_BaseTable_CREATED_DATE] DEFAULT (getdate()),
[CREATED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[MODIFIED_DATE] [smalldatetime] NULL CONSTRAINT [DF_CCR_BaseTable_MODIFIED_DATE] DEFAULT (getdate()),
[MODIFIED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[LICENSE_NUMBER] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[LICENSE_RENEWAL] [smalldatetime] NULL,
[LC_INFANT] [smallint] NULL,
[LC_TODDLER] [smallint] NULL,
[LC_PRESCHOOL] [smallint] NULL,
[LC_KINDERGARTEN] [smallint] NULL,
[LC_SCHOOLAGE] [smallint] NULL,
[LC_TOTAL] [smallint] NULL,
[SPACE_AVAILABLE] [bit] NULL,
[SPACE_AVAILABLE_DATE] [smalldatetime] NULL,
[SUBSIDY] [bit] NULL,
[TYPE_OF_PROGRAM] [int] NULL,
[SUBSIDY_NAMED_PROGRAM] [bit] NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CCR_BaseTable_iu] ON [dbo].[CCR_BaseTable]
FOR INSERT, UPDATE AS

SET NOCOUNT ON

IF UPDATE (MODIFIED_DATE) BEGIN
	IF EXISTS(SELECT * FROM GBL_BaseTable_Description btd INNER JOIN Inserted i ON btd.NUM=i.NUM WHERE btd.MODIFIED_DATE < i.MODIFIED_DATE) BEGIN
		UPDATE btd
			SET	MODIFIED_DATE=i.MODIFIED_DATE,
				MODIFIED_BY=i.MODIFIED_BY
		FROM GBL_BaseTable_Description btd
		INNER JOIN Inserted i
			ON btd.NUM=i.NUM
		WHERE btd.MODIFIED_DATE < i.MODIFIED_DATE
	END
END

SET NOCOUNT OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CCR_BaseTable_SRCH] ON [dbo].[CCR_BaseTable]
FOR INSERT, UPDATE AS

SET NOCOUNT ON

IF UPDATE (TYPE_OF_PROGRAM) BEGIN
	UPDATE btd
		SET SRCH_Anywhere_U = 1
	FROM GBL_BaseTable_Description btd
	INNER JOIN Inserted i
		ON btd.NUM=i.NUM
	WHERE btd.SRCH_Anywhere_U <> 1
END

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[CCR_BaseTable] ADD CONSTRAINT [PK_CCR_BaseTable] PRIMARY KEY CLUSTERED ([NUM]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CCR_BaseTable_NUM] ON [dbo].[CCR_BaseTable] ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CCR_BaseTable_SPACE_AVAILABLE] ON [dbo].[CCR_BaseTable] ([SPACE_AVAILABLE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CCR_BaseTable_SUBSIDY] ON [dbo].[CCR_BaseTable] ([SUBSIDY]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CCR_BaseTable_TYPE_OF_PROGRAM] ON [dbo].[CCR_BaseTable] ([TYPE_OF_PROGRAM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCR_BaseTable] ADD CONSTRAINT [FK_CCR_BaseTable_CCR_TypeOfProgram] FOREIGN KEY ([TYPE_OF_PROGRAM]) REFERENCES [dbo].[CCR_TypeOfProgram] ([TOP_ID]) ON DELETE SET NULL ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CCR_BaseTable] ADD CONSTRAINT [FK_CCR_BaseTable_GBL_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[GBL_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CCR_BaseTable] TO [cioc_cic_search_role]
GO
GRANT DELETE ON  [dbo].[CCR_BaseTable] TO [cioc_login_role]
GO
GRANT INSERT ON  [dbo].[CCR_BaseTable] TO [cioc_login_role]
GO
GRANT SELECT ON  [dbo].[CCR_BaseTable] TO [cioc_login_role]
GO
GRANT UPDATE ON  [dbo].[CCR_BaseTable] TO [cioc_login_role]
GO
