CREATE TABLE [dbo].[TAX_TM_RC]
(
[TM_RC_ID] [int] NOT NULL IDENTITY(1, 1),
[CREATED_DATE] [smalldatetime] NULL CONSTRAINT [DF_TAX_TM_RC_CREATED_DATE] DEFAULT (getdate()),
[CREATED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[MODIFIED_DATE] [smalldatetime] NULL CONSTRAINT [DF_TAX_TM_RC_MODIFIED_DATE] DEFAULT (getdate()),
[MODIFIED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[Code] [varchar] (21) COLLATE Latin1_General_100_CI_AI NOT NULL,
[RC_ID] [int] NOT NULL,
[Authorized] [bit] NOT NULL CONSTRAINT [DF_TAX_TM_RC_Authorized] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_TM_RC] ADD CONSTRAINT [PK_TAX_TM_RC] PRIMARY KEY CLUSTERED  ([TM_RC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_TM_RC] ADD CONSTRAINT [IX_TAX_TM_RC_UniquePair] UNIQUE NONCLUSTERED  ([Code], [RC_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_TAX_TM_RC_RCIDCode] ON [dbo].[TAX_TM_RC] ([RC_ID], [Code]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_TM_RC] WITH NOCHECK ADD CONSTRAINT [FK_TAX_TM_RC_TAX_Term] FOREIGN KEY ([Code]) REFERENCES [dbo].[TAX_Term] ([Code]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TAX_TM_RC] WITH NOCHECK ADD CONSTRAINT [FK_TAX_TM_RC_TAX_RelatedConcept] FOREIGN KEY ([RC_ID]) REFERENCES [dbo].[TAX_RelatedConcept] ([RC_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[TAX_TM_RC] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[TAX_TM_RC] TO [cioc_login_role]
GO
