CREATE TABLE [dbo].[CIC_BT_NC]
(
[BT_NAICS_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[Code] [varchar] (6) COLLATE Latin1_General_100_CI_AI NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CIC_BT_NC_iud] ON [dbo].[CIC_BT_NC] 
FOR INSERT, UPDATE, DELETE  AS

SET NOCOUNT ON

UPDATE cbtd
	SET	CMP_NAICS = dbo.fn_CIC_NUMToNAICS(cbtd.NUM,cbtd.LangID)
	FROM CIC_BaseTable_Description cbtd
	WHERE EXISTS(SELECT * FROM Inserted i WHERE i.NUM=cbtd.NUM)
		OR EXISTS(SELECT * FROM Deleted d WHERE d.NUM=cbtd.NUM)

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[CIC_BT_NC] ADD CONSTRAINT [PK_BUS_BT_NAICS] PRIMARY KEY CLUSTERED  ([BT_NAICS_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_NC_UniquePair] ON [dbo].[CIC_BT_NC] ([NUM], [Code]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_NC] WITH NOCHECK ADD CONSTRAINT [FK_CIC_BT_NAICS_NAICS] FOREIGN KEY ([Code]) REFERENCES [dbo].[NAICS] ([Code]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_NC] ADD CONSTRAINT [FK_CIC_BT_NC_CIC_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_NC] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_NC] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_NC] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_NC] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_NC] TO [cioc_login_role]
GO
