CREATE TABLE [dbo].[VOL_OP_TRP]
(
[OP_TRP_ID] [int] NOT NULL IDENTITY(1, 1),
[VNUM] [varchar] (10) COLLATE Latin1_General_100_CI_AI NOT NULL,
[TRP_ID] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[VOL_OP_TRP] ADD 
CONSTRAINT [PK_VOL_OP_TRP] PRIMARY KEY CLUSTERED  ([OP_TRP_ID]) ON [PRIMARY]
CREATE UNIQUE NONCLUSTERED INDEX [IX_VOL_OP_TRP_UniquePair] ON [dbo].[VOL_OP_TRP] ([VNUM], [TRP_ID]) ON [PRIMARY]

GO

ALTER TABLE [dbo].[VOL_OP_TRP] WITH NOCHECK ADD CONSTRAINT [FK_VOL_OP_TRP_VOL_Opportunity] FOREIGN KEY ([VNUM]) REFERENCES [dbo].[VOL_Opportunity] ([VNUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_OP_TRP] ADD CONSTRAINT [FK_VOL_OP_TRP_VOL_Transportation] FOREIGN KEY ([TRP_ID]) REFERENCES [dbo].[VOL_Transportation] ([TRP_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_OP_TRP] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[VOL_OP_TRP] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_OP_TRP] TO [cioc_vol_search_role]
GO
