CREATE TABLE [dbo].[GBL_BT_CONTRACTSIGNATURE]
(
[CTS_ID] [int] NOT NULL IDENTITY(1, 1),
[GUID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_GBL_BT_CONTRACTSIGNATURE_GUID] DEFAULT (newid()),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[SIGSTATUS] [int] NOT NULL,
[SIGNATORY] [nvarchar] (255) COLLATE Latin1_General_100_CI_AI NULL,
[NOTES] [nvarchar] (255) COLLATE Latin1_General_100_CI_AI NULL,
[DATE] [smalldatetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GBL_BT_CONTRACTSIGNATURE] ADD CONSTRAINT [PK_GBL_BT_CONTRACTSIGNATURE] PRIMARY KEY CLUSTERED  ([CTS_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GBL_BT_CONTRACTSIGNATURE] ADD CONSTRAINT [FK_GBL_BT_CONTRACTSIGNATURE_GBL_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[GBL_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[GBL_BT_CONTRACTSIGNATURE] ADD CONSTRAINT [FK_GBL_BT_CONTRACTSIGNATURE_GBL_SignatureStatus] FOREIGN KEY ([SIGSTATUS]) REFERENCES [dbo].[GBL_SignatureStatus] ([SIG_ID])
GO
GRANT SELECT ON  [dbo].[GBL_BT_CONTRACTSIGNATURE] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[GBL_BT_CONTRACTSIGNATURE] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[GBL_BT_CONTRACTSIGNATURE] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[GBL_BT_CONTRACTSIGNATURE] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[GBL_BT_CONTRACTSIGNATURE] TO [cioc_login_role]
GO
