CREATE TABLE [dbo].[VOL_Profile_CM]
(
[Profile_CM_ID] [int] NOT NULL IDENTITY(1, 1),
[ProfileID] [uniqueidentifier] NOT NULL,
[CM_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_Profile_CM] ADD CONSTRAINT [PK_VOL_Profile_CM] PRIMARY KEY CLUSTERED  ([Profile_CM_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_VOL_Profile_CM_UniquePair] ON [dbo].[VOL_Profile_CM] ([ProfileID], [CM_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_Profile_CM] ADD CONSTRAINT [FK_VOL_Profile_CM_GBL_Community] FOREIGN KEY ([CM_ID]) REFERENCES [dbo].[GBL_Community] ([CM_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_Profile_CM] ADD CONSTRAINT [FK_VOL_Profile_CM_VOL_Profile] FOREIGN KEY ([ProfileID]) REFERENCES [dbo].[VOL_Profile] ([ProfileID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_Profile_CM] TO [cioc_login_role]
GO
