CREATE TABLE [dbo].[TAX_U_Facet]
(
[FC_ID] [int] NOT NULL IDENTITY(1, 1),
[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_TAX_U_Facet_CREATED_DATE] DEFAULT (getdate()),
[CREATED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_TAX_U_Facet_MODIFIED_DATE] DEFAULT (getdate()),
[MODIFIED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[Facet_en] [nvarchar] (255) COLLATE Latin1_General_100_CI_AI NOT NULL,
[Facet_fr] [nvarchar] (255) COLLATE Latin1_General_100_CI_AI NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_U_Facet] ADD CONSTRAINT [PK_TAX_U_Facet] PRIMARY KEY CLUSTERED ([FC_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_U_Facet] ADD CONSTRAINT [IX_TAX_U_Facet] UNIQUE NONCLUSTERED ([Facet_en]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_TAX_U_Facet_fr] ON [dbo].[TAX_U_Facet] ([Facet_fr]) WHERE ([Facet_fr] IS NOT NULL) ON [PRIMARY]
GO
