CREATE TABLE [dbo].[VOL_OP_AI]
(
[OP_AI_ID] [int] NOT NULL IDENTITY(1, 1),
[VNUM] [varchar] (10) COLLATE Latin1_General_100_CI_AI NOT NULL,
[AI_ID] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[VOL_OP_AI] ADD 
CONSTRAINT [PK_VOL_OP_AI] PRIMARY KEY CLUSTERED  ([OP_AI_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_OP_AI] ADD CONSTRAINT [IX_VOL_OP_AI_UniquePair] UNIQUE NONCLUSTERED  ([VNUM], [AI_ID]) ON [PRIMARY]

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_VOL_OP_AI_iud] ON [dbo].[VOL_OP_AI]
FOR INSERT, UPDATE, DELETE AS

BEGIN

SET NOCOUNT ON

UPDATE vod
	SET	CMP_Interests = dbo.fn_VOL_VNUMToInterest(vod.VNUM, vod.LangID)
	FROM VOL_Opportunity_Description vod
	WHERE EXISTS(SELECT * FROM Inserted i WHERE i.VNUM=vod.VNUM)
		OR EXISTS(SELECT * FROM Deleted d WHERE d.VNUM=vod.VNUM)

SET NOCOUNT OFF

END
GO

ALTER TABLE [dbo].[VOL_OP_AI] WITH NOCHECK ADD CONSTRAINT [FK_VOL_OP_AI_VOL_Interest] FOREIGN KEY ([AI_ID]) REFERENCES [dbo].[VOL_Interest] ([AI_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_OP_AI] WITH NOCHECK ADD CONSTRAINT [FK_VOL_OP_AI_VOL_Opportunity] FOREIGN KEY ([VNUM]) REFERENCES [dbo].[VOL_Opportunity] ([VNUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_OP_AI] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[VOL_OP_AI] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[VOL_OP_AI] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[VOL_OP_AI] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_OP_AI] TO [cioc_vol_search_role]
GO
