CREATE TABLE [dbo].[CIC_BT_SL]
(
[BT_SL_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[SL_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_SL] ADD CONSTRAINT [PK_CIC_BT_SL] PRIMARY KEY CLUSTERED  ([BT_SL_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_SL_UniquePair] ON [dbo].[CIC_BT_SL] ([NUM], [SL_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CIC_BT_SL_SLID] ON [dbo].[CIC_BT_SL] ([SL_ID]) ON [PRIMARY]
GO
CREATE STATISTICS [_dta_stat_327672215_1_2_3] ON [dbo].[CIC_BT_SL] ([BT_SL_ID], [NUM], [SL_ID])
GO
ALTER TABLE [dbo].[CIC_BT_SL] ADD CONSTRAINT [FK_CIC_BT_SL_CIC_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_SL] ADD CONSTRAINT [FK_CIC_BT_SL_CIC_ServiceLevel] FOREIGN KEY ([SL_ID]) REFERENCES [dbo].[CIC_ServiceLevel] ([SL_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_SL] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_SL] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_SL] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_SL] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_SL] TO [cioc_login_role]
GO
