CREATE TABLE [dbo].[VOL_OP_EXTRA_TEXT]
(
[OP_EXT_ID] [int] NOT NULL IDENTITY(1, 1),
[FieldName] [varchar] (100) COLLATE Latin1_General_100_CI_AI NOT NULL,
[VNUM] [varchar] (10) COLLATE Latin1_General_100_CI_AI NOT NULL,
[LangID] [smallint] NOT NULL,
[Value] [nvarchar] (max) COLLATE Latin1_General_100_CI_AI NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[tr_VOL_OP_EXTRA_TEXT_SRCH] ON [dbo].[VOL_OP_EXTRA_TEXT]
FOR INSERT, UPDATE, DELETE AS

SET NOCOUNT ON

UPDATE btd
	SET SRCH_Anywhere_U = 1
FROM VOL_Opportunity_Description btd
WHERE btd.SRCH_Anywhere_U <> 1
	AND EXISTS(SELECT * FROM Inserted i
		INNER JOIN VOL_FieldOption fo
			ON fo.FieldName=i.FieldName AND fo.FullTextIndex=1
		WHERE btd.VNUM=i.VNUM AND btd.LangID=i.LangID)

SET NOCOUNT OFF

GO
ALTER TABLE [dbo].[VOL_OP_EXTRA_TEXT] ADD CONSTRAINT [PK_VOL_OP_EXTRA_TEXT] PRIMARY KEY CLUSTERED  ([OP_EXT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_OP_EXTRA_TEXT] ADD CONSTRAINT [FK_VOL_OP_EXTRA_TEXT_VOL_FieldOption] FOREIGN KEY ([FieldName]) REFERENCES [dbo].[VOL_FieldOption] ([FieldName]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_OP_EXTRA_TEXT] ADD CONSTRAINT [FK_VOL_OP_EXTRA_TEXT_VOL_Opportunity_Description] FOREIGN KEY ([VNUM], [LangID]) REFERENCES [dbo].[VOL_Opportunity_Description] ([VNUM], [LangID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_OP_EXTRA_TEXT] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[VOL_OP_EXTRA_TEXT] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[VOL_OP_EXTRA_TEXT] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[VOL_OP_EXTRA_TEXT] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_OP_EXTRA_TEXT] TO [cioc_vol_search_role]
GO
