CREATE TABLE [dbo].[CCR_BT_SCH]
(
[BT_SCH_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[SCH_ID] [int] NOT NULL,
[Escort] [bit] NOT NULL CONSTRAINT [DF_CCR_BT_SCH_Escort] DEFAULT ((0)),
[InArea] [bit] NOT NULL CONSTRAINT [DF_CCR_BT_SCH_InArea] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CCR_BT_SCH_iu] ON [dbo].[CCR_BT_SCH]
FOR INSERT, UPDATE AS

SET NOCOUNT ON

IF UPDATE(InArea) OR UPDATE(Escort) BEGIN
	DELETE pr
	FROM CCR_BT_SCH pr
	INNER JOIN Inserted i
		ON pr.BT_SCH_ID = i.BT_SCH_ID
	WHERE pr.Escort=0 AND pr.InArea=0
END

IF UPDATE(InArea) BEGIN
	UPDATE prn
		SET prn.InAreaNotes = NULL
	FROM CCR_BT_SCH_Notes prn
	INNER JOIN CCR_BT_SCH pr
		ON prn.BT_SCH_ID=pr.BT_SCH_ID
	INNER JOIN Inserted i
		ON pr.BT_SCH_ID = i.BT_SCH_ID
	WHERE pr.InArea=0
END

IF UPDATE(Escort) BEGIN
	UPDATE prn
		SET prn.EscortNotes = NULL
	FROM CCR_BT_SCH_Notes prn
	INNER JOIN CCR_BT_SCH pr
		ON prn.BT_SCH_ID=pr.BT_SCH_ID
	INNER JOIN Inserted i
		ON pr.BT_SCH_ID = i.BT_SCH_ID
	WHERE pr.Escort=0
END

SET NOCOUNT OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CCR_BT_SCH_SRCH] ON [dbo].[CCR_BT_SCH]
FOR INSERT, UPDATE, DELETE AS

SET NOCOUNT ON

UPDATE btd
		SET SRCH_Anywhere_U = 1
	FROM GBL_BaseTable_Description btd
	WHERE	btd.SRCH_Anywhere_U <> 1
		AND (EXISTS(SELECT * FROM Inserted i WHERE btd.NUM = i.NUM)
		OR EXISTS(SELECT * FROM Deleted d WHERE btd.NUM = d.NUM))

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[CCR_BT_SCH] ADD CONSTRAINT [PK_CCR_BT_SCH] PRIMARY KEY CLUSTERED  ([BT_SCH_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CCR_BT_SCH_UniquePair] ON [dbo].[CCR_BT_SCH] ([NUM], [SCH_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CCR_BT_SCH] ADD CONSTRAINT [FK_CCR_BT_SCH_CCR_BT_SCH] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CCR_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CCR_BT_SCH] WITH NOCHECK ADD CONSTRAINT [FK_CCR_CG_SCH_CCR_School] FOREIGN KEY ([SCH_ID]) REFERENCES [dbo].[CCR_School] ([SCH_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CCR_BT_SCH] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CCR_BT_SCH] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CCR_BT_SCH] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CCR_BT_SCH] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CCR_BT_SCH] TO [cioc_login_role]
GO
