CREATE TABLE [dbo].[GBL_BT_OLS]
(
[BT_OLS_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[OLS_ID] [int] NOT NULL,
[EXTERNAL_ID] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[QUEUE_FOR_EXPORT] [bit] NOT NULL CONSTRAINT [DF_GBL_BT_OLS_QUEUE_FOR_EXPORT] DEFAULT ((0))
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_GBL_BT_OLS_iud] ON [dbo].[GBL_BT_OLS] 
FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON

/*
	Checked for Release: 3.5.2
	Checked by: KL
	Checked on: 25-Mar-2015
	Action: NO ACTION REQUIRED
*/

DECLARE @SiteOLSID int
SELECT @SiteOLSID=OLS_ID FROM dbo.GBL_OrgLocationService WHERE Code='SITE'

IF EXISTS(SELECT * FROM Inserted i) OR EXISTS(SELECT * FROM Deleted d) BEGIN

;
WITH LocationName (NUM,LangID,LOCATION_NAME) AS (
	SELECT btd.NUM, btd.LangID, CASE
				WHEN EXISTS(SELECT * FROM GBL_BT_OLS pr WHERE pr.NUM=btd.NUM AND pr.OLS_ID=@SiteOLSID)
					THEN btd.LOCATION_NAME
				WHEN (SELECT COUNT(*) FROM GBL_BT_LOCATION_SERVICE WHERE SERVICE_NUM=btd.NUM)=1
					THEN (SELECT TOP 1 LOCATION_NAME FROM GBL_BaseTable_Description lbtd INNER JOIN GBL_BT_LOCATION_SERVICE ls ON ls.LOCATION_NUM=lbtd.NUM AND ls.SERVICE_NUM=btd.NUM ORDER BY CASE WHEN LangID=btd.LangID THEN 0 ELSE 1 END, LangID)
				ELSE
					NULL
				END AS LOCATION_NAME_X
	FROM GBL_BaseTable_Description btd
	LEFT JOIN Inserted i
		ON i.NUM=btd.NUM AND i.OLS_ID=@SiteOLSID
	LEFT JOIN Deleted d
		ON d.NUM=btd.NUM AND d.OLS_ID=@SiteOLSID
	WHERE (i.NUM IS NOT NULL OR d.NUM IS NOT NULL)
)
UPDATE btd
	SET LOCATION_NAME = ln.LOCATION_NAME
FROM GBL_BaseTable_Description btd
INNER JOIN LocationName ln
	ON btd.NUM=ln.NUM AND btd.LangID=ln.LangID
WHERE (ln.LOCATION_NAME IS NULL AND btd.LOCATION_NAME IS NOT NULL)
	OR (ln.LOCATION_NAME IS NOT NULL AND btd.LOCATION_NAME IS NULL)
	OR (ln.LOCATION_NAME <> btd.LOCATION_NAME)

END

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[GBL_BT_OLS] ADD CONSTRAINT [PK_GBL_BT_OLS] PRIMARY KEY CLUSTERED ([BT_OLS_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GBL_BT_OLS_UniquePair] ON [dbo].[GBL_BT_OLS] ([NUM], [OLS_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GBL_BT_OLS_OLSIDNUM] ON [dbo].[GBL_BT_OLS] ([OLS_ID], [NUM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GBL_BT_OLS] ADD CONSTRAINT [FK_GBL_BT_OLS_GBL_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[GBL_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[GBL_BT_OLS] ADD CONSTRAINT [FK_GBL_BT_OLS_GBL_OrgLocationService] FOREIGN KEY ([OLS_ID]) REFERENCES [dbo].[GBL_OrgLocationService] ([OLS_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[GBL_BT_OLS] TO [cioc_cic_search_role]
GO
GRANT DELETE ON  [dbo].[GBL_BT_OLS] TO [cioc_login_role]
GO
GRANT INSERT ON  [dbo].[GBL_BT_OLS] TO [cioc_login_role]
GO
GRANT SELECT ON  [dbo].[GBL_BT_OLS] TO [cioc_login_role]
GO
GRANT UPDATE ON  [dbo].[GBL_BT_OLS] TO [cioc_login_role]
GO
GRANT SELECT ON  [dbo].[GBL_BT_OLS] TO [cioc_vol_search_role]
GO
