CREATE TABLE [dbo].[CIC_BT_PB_GH]
(
[BT_PB_GH_ID] [int] NOT NULL IDENTITY(1, 1),
[CREATED_DATE] [smalldatetime] NULL CONSTRAINT [DF_CIC_BT_PB_GH_CREATED_DATE] DEFAULT (getdate()),
[CREATED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[MODIFIED_DATE] [smalldatetime] NULL CONSTRAINT [DF_CIC_BT_PB_GH_MODIFIED_DATE] DEFAULT (getdate()),
[MODIFIED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[BT_PB_ID] [int] NULL,
[GH_ID] [int] NOT NULL,
[NUM_Cache] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_PB_GH] ADD CONSTRAINT [IX_CIC_BT_PB_GH_UniquePair] UNIQUE NONCLUSTERED  ([BT_PB_ID], [GH_ID]) ON [PRIMARY]

GO
ALTER TABLE [dbo].[CIC_BT_PB_GH] ADD CONSTRAINT [PK_BT_PB_GH] PRIMARY KEY CLUSTERED  ([BT_PB_GH_ID]) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_CIC_BT_PB_GH_GHID] ON [dbo].[CIC_BT_PB_GH] ([GH_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_PB_GH_NUM_Cache] ON [dbo].[CIC_BT_PB_GH] ([NUM_Cache], [GH_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_PB_GH] ADD CONSTRAINT [FK_BT_PB_GH_BT_PB] FOREIGN KEY ([BT_PB_ID]) REFERENCES [dbo].[CIC_BT_PB] ([BT_PB_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_PB_GH] ADD CONSTRAINT [FK_CIC_BT_PB_GH_CIC_GeneralHeading] FOREIGN KEY ([GH_ID]) REFERENCES [dbo].[CIC_GeneralHeading] ([GH_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_PB_GH] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_PB_GH] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_PB_GH] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_PB_GH] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_PB_GH] TO [cioc_login_role]
GO
