CREATE TABLE [dbo].[VOL_OP_SSN]
(
[OP_SSN_ID] [int] NOT NULL IDENTITY(1, 1),
[VNUM] [varchar] (10) COLLATE Latin1_General_100_CI_AI NOT NULL,
[SSN_ID] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[VOL_OP_SSN] ADD 
CONSTRAINT [PK_VOL_OP_SSN] PRIMARY KEY CLUSTERED  ([OP_SSN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_OP_SSN] ADD CONSTRAINT [IX_VOL_OP_SSN_UniquePair] UNIQUE NONCLUSTERED  ([VNUM], [SSN_ID]) ON [PRIMARY]

GO

ALTER TABLE [dbo].[VOL_OP_SSN] WITH NOCHECK ADD CONSTRAINT [FK_VOL_OP_SSN_VOL_Opportunity] FOREIGN KEY ([VNUM]) REFERENCES [dbo].[VOL_Opportunity] ([VNUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_OP_SSN] ADD CONSTRAINT [FK_VOL_OP_SSN_VOL_Seasons] FOREIGN KEY ([SSN_ID]) REFERENCES [dbo].[VOL_Seasons] ([SSN_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_OP_SSN] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[VOL_OP_SSN] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_OP_SSN] TO [cioc_vol_search_role]
GO
