CREATE TABLE [dbo].[CIC_BT_EXTRA_TEXT]
(
[BT_EXT_ID] [int] NOT NULL IDENTITY(1, 1),
[FieldName] [varchar] (100) COLLATE Latin1_General_100_CI_AI NOT NULL,
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[LangID] [smallint] NOT NULL,
[Value] [nvarchar] (max) COLLATE Latin1_General_100_CI_AI NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_EXTRA_TEXT_UniqueField] ON [dbo].[CIC_BT_EXTRA_TEXT] ([NUM], [FieldName], [LangID]) ON [PRIMARY]

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CIC_BT_EXTRA_TEXT_SRCH] ON [dbo].[CIC_BT_EXTRA_TEXT]
FOR INSERT, UPDATE, DELETE AS

SET NOCOUNT ON

UPDATE btd
	SET SRCH_Anywhere_U = 1
FROM GBL_BaseTable_Description btd
WHERE btd.SRCH_Anywhere_U <> 1
	AND EXISTS(SELECT * FROM Inserted i
		INNER JOIN GBL_FieldOption fo
			ON fo.FieldName=i.FieldName AND fo.FullTextIndex=1
		WHERE btd.NUM=i.NUM AND btd.LangID=i.LangID)

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[CIC_BT_EXTRA_TEXT] ADD CONSTRAINT [PK_CIC_BT_EXTRA_TEXT] PRIMARY KEY CLUSTERED  ([BT_EXT_ID]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[CIC_BT_EXTRA_TEXT] ADD CONSTRAINT [FK_CIC_BT_EXTRA_TEXT_GBL_FieldOption] FOREIGN KEY ([FieldName]) REFERENCES [dbo].[GBL_FieldOption] ([FieldName]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_EXTRA_TEXT] ADD CONSTRAINT [FK_CIC_BT_EXTRA_TEXT_CIC_BaseTable_Description] FOREIGN KEY ([NUM], [LangID]) REFERENCES [dbo].[CIC_BaseTable_Description] ([NUM], [LangID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_EXTRA_TEXT] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_EXTRA_TEXT] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_EXTRA_TEXT] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_EXTRA_TEXT] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_EXTRA_TEXT] TO [cioc_login_role]
GO
