CREATE TABLE [dbo].[CIC_BaseTable]
(
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[CREATED_DATE] [smalldatetime] NULL CONSTRAINT [DF_CIC_BaseTable_CREATED_DATE] DEFAULT (getdate()),
[CREATED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[MODIFIED_DATE] [smalldatetime] NULL CONSTRAINT [DF_CIC_BaseTable_MODIFIED_DATE] DEFAULT (getdate()),
[MODIFIED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[TAX_MODIFIED_DATE] [smalldatetime] NULL CONSTRAINT [DF_CIC_BaseTable_TAX_MODIFIED_DATE] DEFAULT (getdate()),
[TAX_MODIFIED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[ACCREDITED] [int] NULL,
[CERTIFIED] [int] NULL,
[CORP_REG_NO] [varchar] (100) COLLATE Latin1_General_100_CI_AI NULL,
[CURRENCY_USED] [int] NULL,
[DD_CODE] [varchar] (max) COLLATE Latin1_General_100_CI_AI NULL,
[EMPLOYEES_FT] [int] NULL,
[EMPLOYEES_PT] [int] NULL,
[EMPLOYEES_TOTAL] [int] NULL,
[EMPLOYEES_RANGE] [int] NULL,
[FEE_ASSISTANCE_AVAILABLE] [bit] NULL CONSTRAINT [DF_CIC_BaseTable_FEE_ASSISTANCE_AVAILABLE] DEFAULT ((0)),
[FISCAL_YEAR_END] [int] NULL,
[MAIN_ADDRESS_SITE] [bit] NOT NULL CONSTRAINT [DF_CIC_BaseTable_MAIN_ADDRESS_SITE] DEFAULT ((0)),
[MAIN_ADDRESS_MAIL] [bit] NOT NULL CONSTRAINT [DF_CIC_BaseTable_MAIN_ADDRESS_MAIL] DEFAULT ((0)),
[MAIN_ADDRESS_ADDRID] [int] NULL,
[MAIN_ADDRESS_BADDRID] [int] NULL,
[MIN_AGE] [decimal] (5, 2) NULL,
[MAX_AGE] [decimal] (5, 2) NULL,
[OCG_NO] [varchar] (100) COLLATE Latin1_General_100_CI_AI NULL,
[PAYMENT_TERMS] [int] NULL,
[PREF_CURRENCY] [int] NULL,
[PREF_PAYMENT_METHOD] [int] NULL,
[QUALITY] [int] NULL,
[RECORD_TYPE] [int] NULL,
[TAX_REG_NO] [varchar] (100) COLLATE Latin1_General_100_CI_AI NULL,
[WARD] [int] NULL,
[WCB_NO] [varchar] (100) COLLATE Latin1_General_100_CI_AI NULL,
[SRCH_PubTax_U] [bit] NOT NULL CONSTRAINT [DF_CIC_BaseTable_SRCH_PubTax_U] DEFAULT ((0))
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CIC_BaseTable_CMP] ON [dbo].[CIC_BaseTable]
FOR INSERT, UPDATE AS

SET NOCOUNT ON

IF UPDATE(FEE_ASSISTANCE_AVAILABLE) BEGIN
	UPDATE cbtd
		SET	CMP_Fees = dbo.fn_CIC_NUMToFeeType(cbtd.NUM,cbtd.FEE_NOTES,cbt.FEE_ASSISTANCE_AVAILABLE,cbtd.FEE_ASSISTANCE_FOR,cbtd.FEE_ASSISTANCE_FROM,cbtd.LangID)
	FROM CIC_BaseTable cbt
	INNER JOIN CIC_BaseTable_Description cbtd
		ON cbt.NUM=cbtd.NUM
	INNER JOIN Inserted i
		ON cbt.NUM = i.NUM
END

SET NOCOUNT OFF
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CIC_BaseTable_iu] ON [dbo].[CIC_BaseTable]
FOR INSERT, UPDATE AS

SET NOCOUNT ON

IF UPDATE (MODIFIED_DATE) BEGIN
	UPDATE btd
		SET	MODIFIED_DATE=i.MODIFIED_DATE,
			MODIFIED_BY=i.MODIFIED_BY
	FROM GBL_BaseTable_Description btd
	INNER JOIN Inserted i
		ON btd.NUM=i.NUM
	WHERE btd.MODIFIED_DATE < i.MODIFIED_DATE
END

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [PK_CIC_BaseTable] PRIMARY KEY CLUSTERED  ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CIC_BaseTable_NUM] ON [dbo].[CIC_BaseTable] ([NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CIC_BaseTable_RECORDTYPE] ON [dbo].[CIC_BaseTable] ([RECORD_TYPE]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CIC_BaseTable_TAXMODIFIEDDATENUM] ON [dbo].[CIC_BaseTable] ([TAX_MODIFIED_DATE], [NUM]) ON [PRIMARY]
GO
CREATE STATISTICS [_dta_stat_1486628339_29_1] ON [dbo].[CIC_BaseTable] ([QUALITY], [NUM])
GO
CREATE STATISTICS [_dta_stat_1486628339_30_1_29] ON [dbo].[CIC_BaseTable] ([RECORD_TYPE], [NUM], [QUALITY])
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_CIC_Accreditation] FOREIGN KEY ([ACCREDITED]) REFERENCES [dbo].[CIC_Accreditation] ([ACR_ID]) ON DELETE SET NULL ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BaseTable] WITH NOCHECK ADD CONSTRAINT [FK_CIC_BaseTable_CIC_BT_OTHERADDRESS] FOREIGN KEY ([MAIN_ADDRESS_ADDRID]) REFERENCES [dbo].[CIC_BT_OTHERADDRESS] ([ADDR_ID]) NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_CIC_Certification] FOREIGN KEY ([CERTIFIED]) REFERENCES [dbo].[CIC_Certification] ([CRT_ID]) ON DELETE SET NULL ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_CIC_EmployeeRange] FOREIGN KEY ([EMPLOYEES_RANGE]) REFERENCES [dbo].[CIC_EmployeeRange] ([ER_ID]) ON DELETE SET NULL ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_CIC_FiscalYearEnd] FOREIGN KEY ([FISCAL_YEAR_END]) REFERENCES [dbo].[CIC_FiscalYearEnd] ([FYE_ID]) ON DELETE SET NULL ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_CIC_Quality] FOREIGN KEY ([QUALITY]) REFERENCES [dbo].[CIC_Quality] ([RQ_ID]) ON DELETE SET NULL ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_CIC_RecordType] FOREIGN KEY ([RECORD_TYPE]) REFERENCES [dbo].[CIC_RecordType] ([RT_ID]) ON DELETE SET NULL ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_CIC_Ward] FOREIGN KEY ([WARD]) REFERENCES [dbo].[CIC_Ward] ([WD_ID]) ON DELETE SET NULL
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_GBL_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[GBL_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_GBL_BT_BILLINGADDRESS] FOREIGN KEY ([MAIN_ADDRESS_BADDRID]) REFERENCES [dbo].[GBL_BT_BILLINGADDRESS] ([BADDR_ID])
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_GBL_Currency] FOREIGN KEY ([PREF_CURRENCY]) REFERENCES [dbo].[GBL_Currency] ([CUR_ID])
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_GBL_PaymentMethod] FOREIGN KEY ([PREF_PAYMENT_METHOD]) REFERENCES [dbo].[GBL_PaymentMethod] ([PAY_ID]) ON DELETE SET NULL ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BaseTable] ADD CONSTRAINT [FK_CIC_BaseTable_GBL_PaymentTerms] FOREIGN KEY ([PAYMENT_TERMS]) REFERENCES [dbo].[GBL_PaymentTerms] ([PYT_ID]) ON DELETE SET NULL
GO
ALTER TABLE [dbo].[CIC_BaseTable] NOCHECK CONSTRAINT [FK_CIC_BaseTable_CIC_BT_OTHERADDRESS]
GO
GRANT SELECT ON  [dbo].[CIC_BaseTable] TO [cioc_cic_search_role]
GO
GRANT DELETE ON  [dbo].[CIC_BaseTable] TO [cioc_login_role]
GO
GRANT INSERT ON  [dbo].[CIC_BaseTable] TO [cioc_login_role]
GO
GRANT SELECT ON  [dbo].[CIC_BaseTable] TO [cioc_login_role]
GO
GRANT UPDATE ON  [dbo].[CIC_BaseTable] TO [cioc_login_role]
GO
