CREATE TABLE [dbo].[TAX_U_SeeAlso]
(
[SA_ID] [int] NOT NULL IDENTITY(1, 1),
[CREATED_DATE] [datetime] NOT NULL CONSTRAINT [DF_TAX_U_SeeAlso_CREATED_DATE] DEFAULT (getdate()),
[CREATED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[MODIFIED_DATE] [datetime] NOT NULL CONSTRAINT [DF_TAX_U_SeeAlso_MODIFIED_DATE] DEFAULT (getdate()),
[MODIFIED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NULL,
[Code] [varchar] (21) COLLATE Latin1_General_100_CI_AI NOT NULL,
[SA_Code] [varchar] (21) COLLATE Latin1_General_100_CI_AI NOT NULL,
[Authorized] [bit] NOT NULL CONSTRAINT [DF_TAX_U_SeeAlso_Authorized] DEFAULT ((0))
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_U_SeeAlso] WITH NOCHECK ADD CONSTRAINT [CK_TAX_U_SeeAlso_SelfReference] CHECK (([Code]<>[SA_Code]))
GO
ALTER TABLE [dbo].[TAX_U_SeeAlso] ADD CONSTRAINT [PK_TAX_U_SeeAlso] PRIMARY KEY CLUSTERED ([SA_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TAX_U_SeeAlso] WITH NOCHECK ADD CONSTRAINT [FK_TAX_U_SeeAlso_TAX_U_Term] FOREIGN KEY ([Code]) REFERENCES [dbo].[TAX_U_Term] ([Code]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[TAX_U_SeeAlso] WITH NOCHECK ADD CONSTRAINT [FK_TAX_U_SeeAlso_TAX_U_Term_SeeAlso] FOREIGN KEY ([SA_Code]) REFERENCES [dbo].[TAX_U_Term] ([Code])
GO
