CREATE TABLE [dbo].[GBL_BT_MAP]
(
[BT_MAP_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[MAP_ID] [int] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_GBL_BT_MAP_iud] ON [dbo].[GBL_BT_MAP]
FOR INSERT, UPDATE, DELETE AS

SET NOCOUNT ON

UPDATE btd
	SET CMP_SiteAddressWeb = dbo.fn_GBL_FullAddress(bt.NUM,bt.RSN,btd.SITE_BUILDING,btd.SITE_STREET_NUMBER,btd.SITE_STREET,btd.SITE_STREET_TYPE,btd.SITE_STREET_TYPE_AFTER,btd.SITE_STREET_DIR,btd.SITE_SUFFIX,btd.SITE_CITY,btd.SITE_PROVINCE,btd.SITE_COUNTRY,bt.SITE_POSTAL_CODE,NULL,NULL,NULL,bt.LATITUDE,bt.LONGITUDE,btd.LangID,1)
	FROM GBL_BaseTable_Description btd
	INNER JOIN GBL_BaseTable bt
		ON btd.NUM=bt.NUM
WHERE EXISTS(SELECT * FROM Inserted i WHERE i.NUM=btd.NUM)
	OR EXISTS(SELECT * FROM Deleted d WHERE d.NUM=btd.NUM)

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[GBL_BT_MAP] ADD CONSTRAINT [PK_GBL_BT_MAP] PRIMARY KEY CLUSTERED  ([BT_MAP_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_GBL_BT_MAP_UniquePair] ON [dbo].[GBL_BT_MAP] ([NUM], [MAP_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GBL_BT_MAP] WITH NOCHECK ADD CONSTRAINT [FK_GBL_BT_MAP_GBL_MappingSystem] FOREIGN KEY ([MAP_ID]) REFERENCES [dbo].[GBL_MappingSystem] ([MAP_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[GBL_BT_MAP] ADD CONSTRAINT [FK_GBL_BT_MAP_GBL_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[GBL_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[GBL_BT_MAP] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[GBL_BT_MAP] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[GBL_BT_MAP] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[GBL_BT_MAP] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[GBL_BT_MAP] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[GBL_BT_MAP] TO [cioc_vol_search_role]
GO
