CREATE TABLE [dbo].[VOL_OP_EXTRA_RADIO]
(
[OP_EXDT_ID] [int] NOT NULL IDENTITY(1, 1),
[FieldName] [varchar] (100) COLLATE Latin1_General_100_CI_AI NOT NULL,
[VNUM] [varchar] (10) COLLATE Latin1_General_100_CI_AI NOT NULL,
[Value] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_OP_EXTRA_RADIO] ADD CONSTRAINT [PK_VOL_OP_EXTRA_RADIO] PRIMARY KEY CLUSTERED  ([OP_EXDT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_OP_EXTRA_RADIO] ADD CONSTRAINT [FK_VOL_OP_EXTRA_RADIO_VOL_FieldOption] FOREIGN KEY ([FieldName]) REFERENCES [dbo].[VOL_FieldOption] ([FieldName]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_OP_EXTRA_RADIO] ADD CONSTRAINT [FK_VOL_OP_EXTRA_RADIO_VOL_Opportunity] FOREIGN KEY ([VNUM]) REFERENCES [dbo].[VOL_Opportunity] ([VNUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_OP_EXTRA_RADIO] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[VOL_OP_EXTRA_RADIO] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[VOL_OP_EXTRA_RADIO] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[VOL_OP_EXTRA_RADIO] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_OP_EXTRA_RADIO] TO [cioc_vol_search_role]
GO
