CREATE TABLE [dbo].[CIC_BT_EXTRA_EMAIL]
(
[BT_EXT_ID] [int] NOT NULL IDENTITY(1, 1),
[FieldName] [varchar] (100) COLLATE Latin1_General_100_CI_AI NOT NULL,
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[LangID] [smallint] NOT NULL,
[Value] [nvarchar] (60) COLLATE Latin1_General_100_CI_AI NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[CIC_BT_EXTRA_EMAIL] ADD
CONSTRAINT [FK_CIC_BT_EXTRA_EMAIL_CIC_BaseTable_Description] FOREIGN KEY ([NUM], [LangID]) REFERENCES [dbo].[CIC_BaseTable_Description] ([NUM], [LangID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_EXTRA_EMAIL] ADD CONSTRAINT [PK_CIC_BT_EXTRA_EMAIL] PRIMARY KEY CLUSTERED  ([BT_EXT_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_EXTRA_EMAIL_UniqueField] ON [dbo].[CIC_BT_EXTRA_EMAIL] ([FieldName], [NUM], [LangID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_EXTRA_EMAIL] ADD CONSTRAINT [FK_CIC_BT_EXTRA_EMAIL_GBL_FieldOption] FOREIGN KEY ([FieldName]) REFERENCES [dbo].[GBL_FieldOption] ([FieldName]) ON DELETE CASCADE ON UPDATE CASCADE
GO

GRANT SELECT ON  [dbo].[CIC_BT_EXTRA_EMAIL] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_EXTRA_EMAIL] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_EXTRA_EMAIL] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_EXTRA_EMAIL] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_EXTRA_EMAIL] TO [cioc_login_role]
GO
