CREATE TABLE [dbo].[CIC_BT_DST]
(
[BT_DST_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[DST_ID] [int] NOT NULL,
[CREATED_DATE] [smalldatetime] NULL CONSTRAINT [DF_CIC_BT_DST_CREATED_DATE] DEFAULT (getdate())
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_DST] ADD CONSTRAINT [PK_BT_DST] PRIMARY KEY CLUSTERED  ([BT_DST_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_DST_UniquePair] ON [dbo].[CIC_BT_DST] ([NUM], [DST_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_DST] ADD CONSTRAINT [FK_CIC_BT_DST_CIC_Distribution] FOREIGN KEY ([DST_ID]) REFERENCES [dbo].[CIC_Distribution] ([DST_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_DST] ADD CONSTRAINT [FK_CIC_BT_DST_CIC_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_DST] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_DST] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_DST] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_DST] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_DST] TO [cioc_login_role]
GO
