CREATE TABLE [dbo].[VOL_OP_SK]
(
[OP_SK_ID] [int] NOT NULL IDENTITY(1, 1),
[VNUM] [varchar] (10) COLLATE Latin1_General_100_CI_AI NOT NULL,
[SK_ID] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[VOL_OP_SK] ADD 
CONSTRAINT [PK_VOL_OP_SK] PRIMARY KEY CLUSTERED  ([OP_SK_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_OP_SK] ADD CONSTRAINT [IX_VOL_OP_SK_UniquePair] UNIQUE NONCLUSTERED  ([VNUM], [SK_ID]) ON [PRIMARY]

GO

ALTER TABLE [dbo].[VOL_OP_SK] WITH NOCHECK ADD CONSTRAINT [FK_VOL_OP_SK_VOL_Opportunity] FOREIGN KEY ([VNUM]) REFERENCES [dbo].[VOL_Opportunity] ([VNUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_OP_SK] ADD CONSTRAINT [FK_VOL_OP_SK_VOL_Skill] FOREIGN KEY ([SK_ID]) REFERENCES [dbo].[VOL_Skill] ([SK_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_OP_SK] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[VOL_OP_SK] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_OP_SK] TO [cioc_vol_search_role]
GO
