CREATE TABLE [dbo].[CIC_BT_SBJ]
(
[BT_SBJ_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[Subj_ID] [int] NOT NULL
) ON [PRIMARY]
GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CIC_BT_SBJ_iud] ON [dbo].[CIC_BT_SBJ] 
FOR INSERT, UPDATE, DELETE AS

SET NOCOUNT ON

IF EXISTS(SELECT * FROM Inserted i INNER JOIN GBL_BaseTable_Description btd ON btd.NUM = i.NUM
	WHERE NOT EXISTS(SELECT * FROM dbo.CIC_BaseTable_Description cbtd WHERE cbtd.NUM=btd.NUM AND cbtd.LangID=btd.LangID)) BEGIN
	INSERT INTO CIC_BaseTable_Description (NUM, LangID)
	SELECT DISTINCT btd.NUM, btd.LangID
		FROM GBL_BaseTable_Description btd
		INNER JOIN Inserted i
			ON i.NUM = btd.NUM
	WHERE NOT EXISTS(SELECT * FROM dbo.CIC_BaseTable_Description cbtd WHERE cbtd.NUM=btd.NUM AND cbtd.LangID=btd.LangID)
END

UPDATE cbtd
	SET SRCH_Subjects_U = 1
	FROM CIC_BaseTable_Description cbtd
	WHERE (EXISTS(SELECT * FROM Inserted i WHERE i.NUM=cbtd.NUM)
		OR EXISTS(SELECT * FROM Deleted d WHERE d.NUM=cbtd.NUM))

SET NOCOUNT OFF
GO

ALTER TABLE [dbo].[CIC_BT_SBJ] ADD CONSTRAINT [PK_CIC_BT_SBJ] PRIMARY KEY CLUSTERED  ([BT_SBJ_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_SBJ_UniquePair] ON [dbo].[CIC_BT_SBJ] ([NUM], [Subj_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CIC_BT_SBJ_SubjID] ON [dbo].[CIC_BT_SBJ] ([Subj_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CIC_BT_SBJ_IncludeBTSBJIDNUM] ON [dbo].[CIC_BT_SBJ] ([Subj_ID]) INCLUDE ([BT_SBJ_ID], [NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CIC_BT_SBJ_SubjIDBTSBJIDNUM] ON [dbo].[CIC_BT_SBJ] ([Subj_ID], [BT_SBJ_ID], [NUM]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CIC_BT_SBJ_SubjIDNUM] ON [dbo].[CIC_BT_SBJ] ([Subj_ID], [NUM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_SBJ] ADD CONSTRAINT [FK_CIC_BT_SBJ_CIC_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_SBJ] ADD CONSTRAINT [FK_CIC_BT_SBJ_THS_Subject] FOREIGN KEY ([Subj_ID]) REFERENCES [dbo].[THS_Subject] ([Subj_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_SBJ] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_SBJ] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_SBJ] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_SBJ] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_SBJ] TO [cioc_login_role]
GO
