CREATE TABLE [dbo].[VOL_AI_IG]
(
[AI_IG_ID] [int] NOT NULL IDENTITY(1, 1),
[AI_ID] [int] NOT NULL,
[IG_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_AI_IG] ADD CONSTRAINT [PK_VOL_AI_IG] PRIMARY KEY CLUSTERED  ([AI_IG_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_AI_IG] ADD CONSTRAINT [IX_VOL_AI_IG_UniquePair] UNIQUE NONCLUSTERED  ([AI_ID], [IG_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VOL_AI_IG] WITH NOCHECK ADD CONSTRAINT [FK_VOL_AI_IG_VOL_Interest] FOREIGN KEY ([AI_ID]) REFERENCES [dbo].[VOL_Interest] ([AI_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[VOL_AI_IG] WITH NOCHECK ADD CONSTRAINT [FK_VOL_AI_IG_VOL_InterestGroup] FOREIGN KEY ([IG_ID]) REFERENCES [dbo].[VOL_InterestGroup] ([IG_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[VOL_AI_IG] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[VOL_AI_IG] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[VOL_AI_IG] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[VOL_AI_IG] TO [cioc_vol_search_role]
GO
