CREATE TABLE [dbo].[CIC_BT_ACT]
(
[BT_ACT_ID] [int] NOT NULL IDENTITY(1, 1),
[GUID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_CIC_BT_ACT_GUID] DEFAULT (newid()),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[LegacyID] [int] NULL,
[MODIFIED_DATE] [smalldatetime] NULL,
[ASTAT_ID] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_ACT] ADD CONSTRAINT [PK_CIC_BT_ACT] PRIMARY KEY CLUSTERED  ([BT_ACT_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_CIC_BT_ACT_NUMBTACTIDASTATID] ON [dbo].[CIC_BT_ACT] ([NUM], [BT_ACT_ID], [ASTAT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_ACT] ADD CONSTRAINT [FK_CIC_BT_ACT_CIC_Activity_Status] FOREIGN KEY ([ASTAT_ID]) REFERENCES [dbo].[CIC_Activity_Status] ([ASTAT_ID])
GO
ALTER TABLE [dbo].[CIC_BT_ACT] ADD CONSTRAINT [FK_CIC_BT_ACT_CIC_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_ACT] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_ACT] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_ACT] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_ACT] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_ACT] TO [cioc_login_role]
GO
