CREATE TABLE [dbo].[GBL_BT_LOCATION_SERVICE]
(
[LOCATION_NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[SERVICE_NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL
) ON [PRIMARY]


CREATE UNIQUE NONCLUSTERED INDEX [IX_GBL_BT_LOCATION_SERVICE_SERVICENUMLOCATIONNUM] ON [dbo].[GBL_BT_LOCATION_SERVICE] ([SERVICE_NUM], [LOCATION_NUM]) ON [PRIMARY]

GO

SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[tr_GBL_BT_LOCATION_SERVICE_iud] ON [dbo].[GBL_BT_LOCATION_SERVICE] 
FOR INSERT, UPDATE, DELETE AS
SET NOCOUNT ON

/*
	Checked for Release: 3.6.2
	Checked by: KL
	Checked on: 26-Mar-2015
	Action: NO ACTION REQUIRED
*/

IF EXISTS(SELECT * FROM Inserted i) OR EXISTS(SELECT * FROM Deleted d) BEGIN
;
WITH LocationName (NUM,LangID,LOCATION_NAME) AS (
	SELECT btd.NUM, btd.LangID, CASE
		WHEN EXISTS(SELECT * FROM GBL_BT_OLS pr INNER JOIN GBL_OrgLocationService ols ON pr.OLS_ID=ols.OLS_ID AND ols.Code='SITE' WHERE pr.NUM=btd.NUM)
			THEN btd.LOCATION_NAME
		WHEN (SELECT COUNT(*) FROM GBL_BT_LOCATION_SERVICE WHERE SERVICE_NUM=btd.NUM)=1
			THEN (SELECT TOP 1 LOCATION_NAME FROM GBL_BaseTable_Description lbtd INNER JOIN GBL_BT_LOCATION_SERVICE ls ON ls.LOCATION_NUM=lbtd.NUM AND ls.SERVICE_NUM=btd.NUM ORDER BY CASE WHEN LangID=btd.LangID THEN 0 ELSE 1 END, LangID)
		ELSE
			NULL
		END AS LOCATION_NAME_X
	FROM GBL_BaseTable_Description btd
	INNER JOIN (
			SELECT SERVICE_NUM FROM Inserted i
			UNION SELECT SERVICE_NUM FROM Deleted
	) o
		ON o.SERVICE_NUM=btd.NUM
)
UPDATE btd
	SET LOCATION_NAME = ln.LOCATION_NAME
FROM GBL_BaseTable_Description btd
INNER JOIN LocationName ln
	ON btd.NUM=ln.NUM AND btd.LangID=ln.LangID
WHERE (ln.LOCATION_NAME IS NULL AND btd.LOCATION_NAME IS NOT NULL)
	OR (ln.LOCATION_NAME IS NOT NULL AND btd.LOCATION_NAME IS NULL)
	OR (ln.LOCATION_NAME <> btd.LOCATION_NAME)

END

SET NOCOUNT OFF

GO


ALTER TABLE [dbo].[GBL_BT_LOCATION_SERVICE] ADD CONSTRAINT [PK_GBL_BT_LOCATION_SERVICE] PRIMARY KEY CLUSTERED  ([LOCATION_NUM], [SERVICE_NUM]) ON [PRIMARY]
GO

ALTER TABLE [dbo].[GBL_BT_LOCATION_SERVICE] ADD CONSTRAINT [FK_GBL_BT_LOCATION_SERVICE_GBL_BaseTable_LOCATION] FOREIGN KEY ([LOCATION_NUM]) REFERENCES [dbo].[GBL_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[GBL_BT_LOCATION_SERVICE] WITH NOCHECK ADD CONSTRAINT [FK_GBL_BT_LOCATION_SERVICE_GBL_BaseTable_SERVICE] FOREIGN KEY ([SERVICE_NUM]) REFERENCES [dbo].[GBL_BaseTable] ([NUM]) NOT FOR REPLICATION
GO
ALTER TABLE [dbo].[GBL_BT_LOCATION_SERVICE] NOCHECK CONSTRAINT [FK_GBL_BT_LOCATION_SERVICE_GBL_BaseTable_SERVICE]
GO
GRANT SELECT ON  [dbo].[GBL_BT_LOCATION_SERVICE] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[GBL_BT_LOCATION_SERVICE] TO [cioc_login_role]
GRANT SELECT ON  [dbo].[GBL_BT_LOCATION_SERVICE] TO [cioc_vol_search_role]
GO
