CREATE TABLE [dbo].[GBL_Display_Fld]
(
[DD_FLD_ID] [int] NOT NULL IDENTITY(1, 1),
[DD_ID] [int] NOT NULL,
[FieldID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GBL_Display_Fld] ADD CONSTRAINT [PK_GBL_Users_Display_Fld] PRIMARY KEY CLUSTERED  ([DD_FLD_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GBL_Display_Fld] ADD CONSTRAINT [IX_GBL_Users_Display_Fld_UniquePair] UNIQUE NONCLUSTERED  ([DD_ID], [FieldID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GBL_Display_Fld] WITH NOCHECK ADD CONSTRAINT [FK_GBL_Display_Fld_GBL_Display] FOREIGN KEY ([DD_ID]) REFERENCES [dbo].[GBL_Display] ([DD_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[GBL_Display_Fld] WITH NOCHECK ADD CONSTRAINT [FK_GBL_Users_Display_Fld_GBL_FieldOption] FOREIGN KEY ([FieldID]) REFERENCES [dbo].[GBL_FieldOption] ([FieldID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
