CREATE TABLE [dbo].[GBL_BT_BILLINGADDRESS]
(
[BADDR_ID] [int] NOT NULL IDENTITY(1, 1),
[GUID] [uniqueidentifier] NOT NULL CONSTRAINT [DF_GBL_BT_BILLINGADDRESS_GUID] DEFAULT (newid()),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[LangID] [smallint] NOT NULL,
[ADDRTYPE] [int] NOT NULL,
[PRIORITY] [tinyint] NOT NULL CONSTRAINT [DF_GBL_BT_BILLINGADDRESS_PRIORITY] DEFAULT ((0)),
[SITE_CODE] [varchar] (100) COLLATE Latin1_General_100_CI_AI NULL,
[LINE_1] [nvarchar] (200) COLLATE Latin1_General_100_CI_AI NULL,
[LINE_2] [nvarchar] (200) COLLATE Latin1_General_100_CI_AI NULL,
[LINE_3] [nvarchar] (200) COLLATE Latin1_General_100_CI_AI NULL,
[LINE_4] [nvarchar] (200) COLLATE Latin1_General_100_CI_AI NULL,
[CITY] [nvarchar] (100) COLLATE Latin1_General_100_CI_AI NULL,
[PROVINCE] [varchar] (2) COLLATE Latin1_General_100_CI_AI NULL,
[COUNTRY] [nvarchar] (60) COLLATE Latin1_General_100_CI_AI NULL,
[POSTAL_CODE] [varchar] (20) COLLATE Latin1_General_100_CI_AI NULL,
[CAS_CONFIRMATION_DATE] [smalldatetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GBL_BT_BILLINGADDRESS] ADD CONSTRAINT [PK_GBL_BT_BILLINGADDRESS] PRIMARY KEY CLUSTERED  ([BADDR_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_GBL_BT_BILLINGADDRESS_NUM] ON [dbo].[GBL_BT_BILLINGADDRESS] ([NUM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GBL_BT_BILLINGADDRESS] ADD CONSTRAINT [FK_GBL_BT_BILLINGADDRESS_GBL_BillingAddressType] FOREIGN KEY ([ADDRTYPE]) REFERENCES [dbo].[GBL_BillingAddressType] ([AddressTypeID])
GO
ALTER TABLE [dbo].[GBL_BT_BILLINGADDRESS] ADD CONSTRAINT [FK_GBL_BT_BILLINGADDRESS_GBL_BaseTable_Description] FOREIGN KEY ([NUM], [LangID]) REFERENCES [dbo].[GBL_BaseTable_Description] ([NUM], [LangID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[GBL_BT_BILLINGADDRESS] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[GBL_BT_BILLINGADDRESS] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[GBL_BT_BILLINGADDRESS] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[GBL_BT_BILLINGADDRESS] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[GBL_BT_BILLINGADDRESS] TO [cioc_login_role]
GO
