CREATE TABLE [dbo].[CIC_BT_LN_LND]
(
[BT_LN_ID] [int] NOT NULL,
[LND_ID] [int] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE TRIGGER [dbo].[tr_CIC_BT_LN_LND_iud] ON [dbo].[CIC_BT_LN_LND] 
FOR INSERT, UPDATE, DELETE AS

SET NOCOUNT ON

UPDATE pr
	SET	LN_ID=LN_ID
	FROM CIC_BT_LN pr
	WHERE EXISTS(SELECT * FROM Inserted i WHERE i.BT_LN_ID=pr.BT_LN_ID)
		OR EXISTS(SELECT * FROM Deleted d WHERE d.BT_LN_ID=pr.BT_LN_ID)

SET NOCOUNT OFF

GO

ALTER TABLE [dbo].[CIC_BT_LN_LND] ADD CONSTRAINT [PK_CIC_BT_LN_LND] PRIMARY KEY CLUSTERED  ([LND_ID], [BT_LN_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_LN_LND] ADD CONSTRAINT [FK_CIC_BT_LN_LND_CIC_BT_LN] FOREIGN KEY ([BT_LN_ID]) REFERENCES [dbo].[CIC_BT_LN] ([BT_LN_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_LN_LND] ADD CONSTRAINT [FK_CIC_BT_LN_LND_GBL_Language_Details] FOREIGN KEY ([LND_ID]) REFERENCES [dbo].[GBL_Language_Details] ([LND_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_LN_LND] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_LN_LND] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_LN_LND] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_LN_LND] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_LN_LND] TO [cioc_login_role]
GO
