CREATE TABLE [dbo].[CIC_BT_VUT_History]
(
[BT_VUT_HIST_ID] [bigint] NOT NULL IDENTITY(1, 1),
[BT_VUT_ID] [int] NOT NULL,
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[BT_VUT_GUID] [uniqueidentifier] NOT NULL,
[VacancyChange] [smallint] NOT NULL,
[VacancyFinal] [smallint] NOT NULL,
[MODIFIED_DATE] [datetime2] (0) NOT NULL,
[MODIFIED_BY] [varchar] (50) COLLATE Latin1_General_100_CI_AI NOT NULL,
[ServiceTitle] [nvarchar] (100) COLLATE Latin1_General_100_CI_AI NOT NULL,
[MemberID] [int] NOT NULL
) ON [PRIMARY]
ALTER TABLE [dbo].[CIC_BT_VUT_History] ADD 
CONSTRAINT [PK_CIC_BT_VUT_History] PRIMARY KEY CLUSTERED  ([BT_VUT_HIST_ID]) ON [PRIMARY]
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_VUT_History] ON [dbo].[CIC_BT_VUT_History] ([BT_VUT_ID], [MODIFIED_DATE] DESC, [BT_VUT_HIST_ID] DESC) ON [PRIMARY]

ALTER TABLE [dbo].[CIC_BT_VUT_History] WITH NOCHECK ADD
CONSTRAINT [FK_CIC_BT_VUT_History_CIC_BT_VUT] FOREIGN KEY ([BT_VUT_ID], [BT_VUT_GUID], [NUM]) REFERENCES [dbo].[CIC_BT_VUT] ([BT_VUT_ID], [GUID], [NUM]) ON UPDATE CASCADE
ALTER TABLE [dbo].[CIC_BT_VUT_History] NOCHECK CONSTRAINT [FK_CIC_BT_VUT_History_CIC_BT_VUT]
ALTER TABLE [dbo].[CIC_BT_VUT_History] ADD
CONSTRAINT [FK_CIC_BT_VUT_History_STP_Member] FOREIGN KEY ([MemberID]) REFERENCES [dbo].[STP_Member] ([MemberID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
