CREATE TABLE [dbo].[CIC_BT_MT]
(
[BT_MT_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[MT_ID] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_MT] ADD CONSTRAINT [PK_BUS_BT_MT] PRIMARY KEY CLUSTERED  ([BT_MT_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_MT_UniquePair] ON [dbo].[CIC_BT_MT] ([NUM], [MT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_MT] WITH NOCHECK ADD CONSTRAINT [FK_CIC_BT_MT_CIC_MembershipType] FOREIGN KEY ([MT_ID]) REFERENCES [dbo].[CIC_MembershipType] ([MT_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_MT] ADD CONSTRAINT [FK_CIC_BT_MT_CIC_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_MT] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_MT] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_MT] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_MT] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_MT] TO [cioc_login_role]
GO
