CREATE TABLE [dbo].[CIC_BT_FT]
(
[BT_FT_ID] [int] NOT NULL IDENTITY(1, 1),
[NUM] [varchar] (8) COLLATE Latin1_General_100_CI_AI NOT NULL,
[FT_ID] [int] NOT NULL
) ON [PRIMARY]
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE TRIGGER [dbo].[tr_CIC_BT_FT_iud] ON [dbo].[CIC_BT_FT] 
FOR INSERT, UPDATE, DELETE AS

SET NOCOUNT ON

UPDATE cbtd
	SET	CMP_Fees = dbo.fn_CIC_NUMToFeeType(cbtd.NUM,cbtd.FEE_NOTES,cbt.FEE_ASSISTANCE_AVAILABLE,cbtd.FEE_ASSISTANCE_FOR,cbtd.FEE_ASSISTANCE_FROM,cbtd.LangID)
	FROM CIC_BaseTable cbt
	INNER JOIN CIC_BaseTable_Description cbtd
		ON cbt.NUM=cbtd.NUM
	WHERE EXISTS(SELECT * FROM Inserted i WHERE i.NUM=cbtd.NUM)
		OR EXISTS(SELECT * FROM Deleted d WHERE d.NUM=cbtd.NUM)

SET NOCOUNT OFF
GO
ALTER TABLE [dbo].[CIC_BT_FT] ADD CONSTRAINT [PK_CIC_BT_FT] PRIMARY KEY CLUSTERED  ([BT_FT_ID]) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX [IX_CIC_BT_FT_UniquePair] ON [dbo].[CIC_BT_FT] ([NUM], [FT_ID]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CIC_BT_FT] ADD CONSTRAINT [FK_CIC_BT_FT_CIC_FeeType] FOREIGN KEY ([FT_ID]) REFERENCES [dbo].[CIC_FeeType] ([FT_ID]) ON DELETE CASCADE ON UPDATE CASCADE
GO
ALTER TABLE [dbo].[CIC_BT_FT] ADD CONSTRAINT [FK_CIC_BT_FT_CIC_BaseTable] FOREIGN KEY ([NUM]) REFERENCES [dbo].[CIC_BaseTable] ([NUM]) ON DELETE CASCADE ON UPDATE CASCADE
GO
GRANT SELECT ON  [dbo].[CIC_BT_FT] TO [cioc_cic_search_role]
GRANT SELECT ON  [dbo].[CIC_BT_FT] TO [cioc_login_role]
GRANT INSERT ON  [dbo].[CIC_BT_FT] TO [cioc_login_role]
GRANT DELETE ON  [dbo].[CIC_BT_FT] TO [cioc_login_role]
GRANT UPDATE ON  [dbo].[CIC_BT_FT] TO [cioc_login_role]
GO
