
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE VIEW [dbo].[XML_EXPORT_V2] AS

/*
	Checked for Release: 3.6
	Checked by: KL
	Checked on: 27-Sep-2014
	Action: TESTING REQUIRED
*/

SELECT
	mem.MemberID AS USE_MEMBER_ID,
	bt.MemberID,
	bt.RSN,
	bt.NUM,
	RECORD_OWNER,
	ORG_LEVEL_1,
	ORG_LEVEL_2,
	ORG_LEVEL_3,
	ORG_LEVEL_4,
	ORG_LEVEL_5,
	LOCATION_NAME,
	SERVICE_NAME_LEVEL_1,
	SERVICE_NAME_LEVEL_2,
	CMP_Accessibility AS ACCESSIBILITY,
	dbo.fn_CIC_DisplayCertification(ACCREDITED,btd.LangID) AS ACCREDITED,
	dbo.fn_CIC_NUMToActivity(bt.NUM,cbtd.ACTIVITY_NOTES) AS ACTIVITY_INFO,
	AFTER_HRS_PHONE,
	CMP_AltOrg AS ALT_ORG,
	[APPLICATION],
	CMP_AreasServed AS AREAS_SERVED,
	BEST_TIME_TO_CALL,
	dbo.fn_GBL_NUMToBillingAddress(bt.NUM) AS BILLING_ADDRESSES,
	BOUNDARIES,
	dbo.fn_CIC_NUMToBusRoutes(bt.NUM) AS BUS_ROUTES,
	cioc_shared.dbo.fn_SHR_CCR_FullLicenseInfo(LICENSE_NUMBER, LICENSE_RENEWAL, LC_TOTAL, LC_INFANT, LC_TODDLER, LC_PRESCHOOL, LC_KINDERGARTEN, LC_SCHOOLAGE, LC_NOTES) AS CC_LICENSE_INFO,
	dbo.fn_CIC_DisplayCertification(CERTIFIED,btd.LangID) AS CERTIFIED,
	COLLECTED_BY,
	COLLECTED_DATE,
	COMMENTS,
	(SELECT CMP_Name FROM GBL_Contact c WHERE GblContactType='CONTACT_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_NAME_1,
	(SELECT TITLE FROM GBL_Contact c WHERE GblContactType='CONTACT_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_TITLE_1,
	(SELECT ORG FROM GBL_Contact c WHERE GblContactType='CONTACT_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_ORG_1,
	(SELECT CMP_PhoneFull FROM GBL_Contact c WHERE GblContactType='CONTACT_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_PHONE_1,
	(SELECT FAX FROM GBL_Contact c WHERE GblContactType='CONTACT_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_FAX_1,
	(SELECT EMAIL FROM GBL_Contact c WHERE GblContactType='CONTACT_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_EMAIL_1,
	(SELECT CMP_Name FROM GBL_Contact c WHERE GblContactType='CONTACT_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_NAME_2,
	(SELECT TITLE FROM GBL_Contact c WHERE GblContactType='CONTACT_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_TITLE_2,
	(SELECT ORG FROM GBL_Contact c WHERE GblContactType='CONTACT_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_ORG_2,
	(SELECT CMP_PhoneFull FROM GBL_Contact c WHERE GblContactType='CONTACT_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_PHONE_2,
	(SELECT FAX FROM GBL_Contact c WHERE GblContactType='CONTACT_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_FAX_2,
	(SELECT EMAIL FROM GBL_Contact c WHERE GblContactType='CONTACT_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS CONTACT_EMAIL_2,
	dbo.fn_GBL_NUMToContractSignature(bt.NUM) AS CONTRACT_SIGNATURE,
	CORP_REG_NO,
	bt.CREATED_BY,
	bt.CREATED_DATE,
	CRISIS_PHONE,
	CMP_CrossRef AS CROSS_REF,
	DATES,
	DD_CODE,
	DELETED_BY,
	DELETION_DATE,
	[DESCRIPTION],
	dbo.fn_CIC_NUMToDistribution(mem.MemberID,bt.NUM) AS DISTRIBUTION,
	E_MAIL,
	ELECTIONS,
	cioc_shared.dbo.fn_SHR_CIC_FullEligibility(MIN_AGE, MAX_AGE, ELIGIBILITY_NOTES) AS ELIGIBILITY,
	EMAIL_UPDATE_DATE,
	dbo.fn_CIC_FullEmployees(EMPLOYEES_FT,EMPLOYEES_PT,EMPLOYEES_TOTAL) AS EMPLOYEES,
	dbo.fn_CIC_FullEmployeesRange(EMPLOYEES_RANGE) AS EMPLOYEES_RANGE,
	ESTABLISHED,
	(SELECT CMP_Name FROM GBL_Contact c WHERE GblContactType='EXEC_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_NAME_1,
	(SELECT TITLE FROM GBL_Contact c WHERE GblContactType='EXEC_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_TITLE_1,
	(SELECT ORG FROM GBL_Contact c WHERE GblContactType='EXEC_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_ORG_1,
	(SELECT CMP_PhoneFull FROM GBL_Contact c WHERE GblContactType='EXEC_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_PHONE_1,
	(SELECT FAX FROM GBL_Contact c WHERE GblContactType='EXEC_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_FAX_1,
	(SELECT EMAIL FROM GBL_Contact c WHERE GblContactType='EXEC_1' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_EMAIL_1,
	(SELECT CMP_Name FROM GBL_Contact c WHERE GblContactType='EXEC_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_NAME_2,
	(SELECT TITLE FROM GBL_Contact c WHERE GblContactType='EXEC_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_TITLE_2,
	(SELECT ORG FROM GBL_Contact c WHERE GblContactType='EXEC_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_ORG_2,
	(SELECT CMP_PhoneFull FROM GBL_Contact c WHERE GblContactType='EXEC_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_PHONE_2,
	(SELECT FAX FROM GBL_Contact c WHERE GblContactType='EXEC_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_FAX_2,
	(SELECT EMAIL FROM GBL_Contact c WHERE GblContactType='EXEC_2' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXEC_EMAIL_2,
	EXTERNAL_ID,
	(SELECT CMP_Name FROM GBL_Contact c WHERE GblContactType='EXTRA_CONTACT_A' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXTRA_CONTACT_NAME_A,
	(SELECT TITLE FROM GBL_Contact c WHERE GblContactType='EXTRA_CONTACT_A' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXTRA_CONTACT_TITLE_A,
	(SELECT ORG FROM GBL_Contact c WHERE GblContactType='EXTRA_CONTACT_A' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXTRA_CONTACT_ORG_A,
	(SELECT CMP_PhoneFull FROM GBL_Contact c WHERE GblContactType='EXTRA_CONTACT_A' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXTRA_CONTACT_PHONE_A,
	(SELECT FAX FROM GBL_Contact c WHERE GblContactType='EXTRA_CONTACT_A' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXTRA_CONTACT_FAX_A,
	(SELECT EMAIL FROM GBL_Contact c WHERE GblContactType='EXTRA_CONTACT_A' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS EXTRA_CONTACT_EMAIL_A,
	FAX,
	CMP_Fees AS FEES,
	dbo.fn_CIC_DisplayFiscalYearEnd(FISCAL_YEAR_END,btd.LangID) AS FISCAL_YEAR_END,
	CMP_FormerOrg AS FORMER_ORG,
	CMP_Funding AS FUNDING,
	GEOCODE_NOTES,
	HOURS,
	IMPORT_DATE,
	dbo.fn_GBL_NUMToRecordNote('INTERNAL_MEMO',bt.NUM,btd.LangID) AS INTERNAL_MEMO,
	INTERSECTION,
	CMP_Languages AS LANGUAGES,
	LATITUDE,
	LEGAL_ORG,
	dbo.fn_CIC_NUMToLocalTerms(mem.MemberID,bt.NUM,btd.LangID) AS LOCAL_SUBJECTS,
	dbo.fn_GBL_DisplayCommunity(bt.LOCATED_IN_CM,btd.LangID) AS LOCATED_IN_CM,
	LOCATION_DESCRIPTION,
	dbo.fn_GBL_NUMToLocationServices(bt.NUM,bt.ORG_NUM,NULL,1) AS LOCATION_SERVICES,
	LOGO_ADDRESS,
	LONGITUDE,
	CMP_MailAddress AS MAIL_ADDRESS,
	MAIL_CARE_OF, MAIL_BOX_TYPE, MAIL_PO_BOX, MAIL_BUILDING, MAIL_STREET_NUMBER, MAIL_STREET, MAIL_STREET_TYPE, ISNULL(ISNULL(MAIL_STREET_TYPE_AFTER, (SELECT TOP 1 st.AfterName FROM GBL_StreetType st WHERE st.LangID=btd.LangID AND st.StreetType COLLATE Latin1_General_100_CI_AI=MAIL_STREET_TYPE)), CASE WHEN btd.LangID=2 THEN 0 ELSE 1 END) AS MAIL_STREET_TYPE_AFTER, MAIL_STREET_DIR, MAIL_SUFFIX, MAIL_CITY, MAIL_PROVINCE, MAIL_COUNTRY, MAIL_POSTAL_CODE,
	MAP_PIN,
	MEETINGS,
	dbo.fn_CIC_NUMToMembershipType(bt.NUM,cbtd.MEMBERSHIP_NOTES) AS MEMBERSHIP,
	bt.MODIFIED_BY,
	bt.MODIFIED_DATE,
	dbo.fn_CIC_NUMToNAICS(bt.NUM,btd.LangID) AS NAICS,
	NO_UPDATE_EMAIL,
	NON_PUBLIC,
	OCG_NO,
	OFFICE_PHONE,
	ORG_DESCRIPTION,
	dbo.fn_GBL_NUMToOrgLocationService(bt.NUM) AS ORG_LOCATION_SERVICE,
	ORG_NUM,
	dbo.fn_CIC_NUMToOtherAddress(bt.NUM) AS OTHER_ADDRESSES,
	dbo.fn_GBL_DisplayPaymentTerms(cbt.PAYMENT_TERMS,btd.LangID) AS PAYMENT_TERMS,
	dbo.fn_GBL_DisplayCurrency(cbt.PREF_CURRENCY,0) AS PREF_CURRENCY,
	dbo.fn_GBL_DisplayPaymentMethod(cbt.PREF_PAYMENT_METHOD,btd.LangID) AS PREF_PAYMENT_METHOD,
	PRINT_MATERIAL,
	PUBLIC_COMMENTS,
	dbo.fn_CIC_NUMToPublication(mem.MemberID,bt.NUM) AS PUBLICATION,
	QUALITY,
	RECORD_TYPE,
	RESOURCES,
	dbo.fn_CCR_NUMToSchoolEscort(bt.NUM,btd.LangID) AS SCHOOL_ESCORT,
	dbo.fn_CCR_NUMToSchoolsInArea(bt.NUM,SCHOOLS_IN_AREA_NOTES,btd.LangID) AS SCHOOLS_IN_AREA,
	dbo.fn_CIC_NUMToServiceLevel_Export(bt.NUM) AS SERVICE_LEVEL,
	CMP_SiteAddress AS SITE_ADDRESS,
	SITE_BUILDING, SITE_STREET_NUMBER, SITE_STREET, SITE_STREET_TYPE, ISNULL(ISNULL(SITE_STREET_TYPE_AFTER, (SELECT TOP 1 st.AfterName FROM GBL_StreetType st WHERE st.LangID=btd.LangID AND st.StreetType COLLATE Latin1_General_100_CI_AI=SITE_STREET_TYPE)), CASE WHEN btd.LangID=2 THEN 0 ELSE 1 END) AS SITE_STREET_TYPE_AFTER, SITE_STREET_DIR, SITE_SUFFIX, SITE_CITY, SITE_PROVINCE, SITE_COUNTRY, SITE_POSTAL_CODE,
	SITE_LOCATION,
	dbo.fn_GBL_NUMToSocialMedia(bt.NUM) AS SOCIAL_MEDIA,
	SORT_AS,
	SOURCE_NAME, SOURCE_TITLE, SOURCE_ORG, SOURCE_PHONE, SOURCE_FAX, SOURCE_EMAIL, SOURCE_POSTAL_CODE, SOURCE_PROVINCE, SOURCE_CITY, SOURCE_ADDRESS, SOURCE_BUILDING,
	SOURCE_DB,
	dbo.fn_CCR_FullSpaceAvailable(SPACE_AVAILABLE, SPACE_AVAILABLE_NOTES, SPACE_AVAILABLE_DATE) AS SPACE_AVAILABLE,
	dbo.fn_CIC_NUMToAuthorizedTerms(bt.NUM,btd.LangID) AS SUBJECTS,
	CAST(SUBSIDY AS tinyint) AS SUBSIDY,
	SUP_DESCRIPTION,
	TAX_MODIFIED_BY,
	TAX_MODIFIED_DATE,
	TAX_REG_NO,
	dbo.fn_CIC_NUMToTaxTerms(bt.NUM,btd.LangID) AS TAXONOMY,
	TDD_PHONE,
	TOLL_FREE_PHONE,
	TRANSPORTATION,
	dbo.fn_CCR_NUMToTypeOfCare(bt.NUM,TYPE_OF_CARE_NOTES,btd.LangID) AS TYPE_OF_CARE,
	dbo.fn_CCR_DisplayTypeOfProgram(TYPE_OF_PROGRAM,btd.LangID) AS TYPE_OF_PROGRAM,
	UPDATE_DATE,
	UPDATE_EMAIL,
	UPDATE_HISTORY,
	UPDATE_SCHEDULE,
	UPDATED_BY,
	dbo.fn_CIC_NUMToVacancy(bt.NUM,cbtd.VACANCY_NOTES,0) AS VACANCY_INFO,
	(SELECT CMP_Name FROM GBL_Contact c WHERE GblContactType='VOLCONTACT' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS VOLCONTACT_NAME,
	(SELECT TITLE FROM GBL_Contact c WHERE GblContactType='VOLCONTACT' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS VOLCONTACT_TITLE,
	(SELECT ORG FROM GBL_Contact c WHERE GblContactType='VOLCONTACT' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS VOLCONTACT_ORG,
	(SELECT CMP_PhoneFull FROM GBL_Contact c WHERE GblContactType='VOLCONTACT' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS VOLCONTACT_PHONE,
	(SELECT FAX FROM GBL_Contact c WHERE GblContactType='VOLCONTACT' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS VOLCONTACT_FAX,
	(SELECT EMAIL FROM GBL_Contact c WHERE GblContactType='VOLCONTACT' AND GblNUM=bt.NUM AND c.LangID=btd.LangID) AS VOLCONTACT_EMAIL,
	WARD,
	WCB_NO,
	WWW_ADDRESS
FROM STP_Member mem, GBL_BaseTable bt
	INNER JOIN GBL_BaseTable_Description btd
		ON bt.NUM=btd.NUM
	LEFT JOIN CIC_BaseTable cbt
		ON bt.NUM=cbt.NUM
	LEFT JOIN CIC_BaseTable_Description cbtd
		ON cbt.NUM=cbtd.NUM AND cbtd.LangID=btd.LangID
	LEFT JOIN CCR_BaseTable ccbt
		ON bt.NUM=ccbt.NUM
	LEFT JOIN CCR_BaseTable_Description ccbtd
		ON ccbt.NUM=ccbtd.NUM AND ccbtd.LangID=btd.LangID
WHERE btd.LangID=@@LANGID








GO


GRANT SELECT ON  [dbo].[XML_EXPORT_V2] TO [cioc_login_role]
GO
